UnityToolbox: Saveable Class Reference
Saveable Class Reference abstract
The base implementation for all gameobjects that should be saved. It is able to serialize the transform and parent data with the SaveGameManager. Requires a PrefabManager and aIDManager, if the objects are not initially found in the scene.
Public Member Functions
void Save ()
Defines all data to be serialized by the SaveGameManager.
void Load ()
Loads all data, deserialized by the SaveGameManager.
void OnValidate ()
Public Attributes
int PrefabID = -1
Protected Member Functions
abstract void LoadData (GameData data)
Is called after the base data is loaded in Load. Allows additional data to be deserialized.
abstract List< GameData > SaveData ()
Is called on Save. Allows the definition of all additional GameData to be serialized.
abstract void OnObjectDeleted ()
A method called on deletion, that is that the object is removed from the save game and destroyed. It is not called when destroyed but saved.
Protected Attributes
bool _removeFromSaveOnDelete
Properties
string ID [get, set]
A unique ID.
bool InEditor [get]
Whether the gameobject is found in the scene initally. Or created dynamically.
Private Member Functions
void Awake ()
void OnDestroy ()
Private Attributes
string _id = ""
bool _inEditor
Member Function Documentation
Awake()
void Saveable.Awake () private
References _id, _inEditor, and IDManager.GetUniqueID().
Load()
void Saveable.Load ()
References ID, LoadData(), ParentData.ParentID, TransformData.Position, TransformData.Rotation, TransformData.Scale, VectorData.x, VectorData.y, and VectorData.z.
Referenced by SaveGameManager.LoadSaved().
LoadData()
abstract void Saveable.LoadData (GameData data) protected pure virtual
Parameters
data A GameData implementation, which holds data to load.
Implemented in Item.
Referenced by Load().
OnDestroy()
void Saveable.OnDestroy () private
References _removeFromSaveOnDelete, ID, OnObjectDeleted(), and Save().
OnObjectDeleted()
abstract void Saveable.OnObjectDeleted () protected pure virtual
Implemented in Item.
Referenced by OnDestroy().
OnValidate()
void Saveable.OnValidate ()
References _id, _inEditor, and IDManager.GetUniqueID().
Save()
void Saveable.Save ()
References ID, InEditor, PrefabID, and SaveData().
Referenced by OnDestroy().
SaveData()
abstract List< GameData > Saveable.SaveData () protected pure virtual
Returns
Implemented in Item.
Referenced by Save().
Member Data Documentation
_id
string Saveable._id = "" private
Referenced by Awake(), and OnValidate().
_inEditor
bool Saveable._inEditor private
Referenced by Awake(), and OnValidate().
_removeFromSaveOnDelete
bool Saveable._removeFromSaveOnDelete protected
Referenced by OnDestroy().
PrefabID
int Saveable.PrefabID = -1
Referenced by PrefabManager.GetPrefabForID(), and Save().
Property Documentation
ID
string Saveable.ID get set
Referenced by Load(), SaveGameManager.LoadSaved(), OnDestroy(), Save(), and IDManager.SceneChanged().
InEditor
bool Saveable.InEditor get
Referenced by Save().