UnityToolbox: Item.Management.ItemDefinitionDrawer Class Reference
Item.Management.ItemDefinitionDrawer Class Reference
This class enables a selection field for the ItemDefinition within the inspector.
Public Member Functions
override float GetPropertyHeight (SerializedProperty property, GUIContent label)
override void OnGUI (Rect position, SerializedProperty property, GUIContent label)
void ItemDefinitionSelected (ItemDefinition itemDefinition)
Private Attributes
ItemDefinitionSelectionWindow _window
SerializedProperty _property
Member Function Documentation
GetPropertyHeight()
override float Item.Management.ItemDefinitionDrawer.GetPropertyHeight (SerializedProperty property, GUIContent label)
ItemDefinitionSelected()
void Item.Management.ItemDefinitionDrawer.ItemDefinitionSelected (ItemDefinition itemDefinition)
References Item.Management.ItemDefinitionDrawer._property, Item.Management.ItemDefinitionDrawer._window, and Item.Management.ItemDefinitionDrawer.ItemDefinitionSelected().
Referenced by Item.Management.ItemDefinitionDrawer.ItemDefinitionSelected(), and Item.Management.ItemDefinitionDrawer.OnGUI().
OnGUI()
override void Item.Management.ItemDefinitionDrawer.OnGUI (Rect position, SerializedProperty property, GUIContent label)
References Item.Management.ItemDefinitionDrawer._property, Item.Management.ItemDefinitionDrawer._window, Item.ItemDefinition.DEVIDER, Item.Management.ItemDefinitionDrawer.ItemDefinitionSelected(), Item.Management.ItemScope.Name, Item.ItemDefinition.Name, Item.Management.ItemDefinitionSelectionWindow.Open(), and Item.ItemDefinition.Scope.
Member Data Documentation
_property
SerializedProperty Item.Management.ItemDefinitionDrawer._property private
Referenced by Item.Management.ItemDefinitionDrawer.ItemDefinitionSelected(), and Item.Management.ItemDefinitionDrawer.OnGUI().
_window
ItemDefinitionSelectionWindow Item.Management.ItemDefinitionDrawer._window private
Referenced by Item.Management.ItemDefinitionDrawer.ItemDefinitionSelected(), and Item.Management.ItemDefinitionDrawer.OnGUI().