UnityToolbox: LocalisationManagerWindow Class Reference
LocalisationManagerWindow Class Reference
Public Member Functions
void OnAfterAssemblyReload ()
Static Public Member Functions
static void Open ()
Private Member Functions
void InitializeWindow ()
void Awake ()
void OnGUI ()
void DisplaySettingsTab ()
void DisplayScopesTab ()
void DisplayLanguagesTab ()
void DisplayIDsTab ()
void DrawLineHorizontal ()
void UpdateStatus (string status)
void OnEnable ()
void OnDisable ()
bool IsPathValid (string path)
Static Private Member Functions
static void DisplayWindow ()
Private Attributes
int _selectedTab = 0
string _assetPathInProject
string _status
Vector2 _scrollPosScope
string _scopeName
Vector2 _scrollPosLanguage
string _languageName
string _languageShortName
Vector2 _scrollPosID
string _IDName
int _selectedScope
Dictionary< LocalisationLanguage, string > _newLocalisations
int _selectedLanguage
string _searchIDString
int _selectedSearch
bool _foldoutAdd
bool _foldoutSearch
Static Private Attributes
const int IDS = 0
const int LANGUAGES = 1
const int SCOPES = 2
const int SETTINGS = 3
Member Function Documentation
Awake()
void LocalisationManagerWindow.Awake () private
References InitializeWindow().
DisplayIDsTab()
void LocalisationManagerWindow.DisplayIDsTab () private
References _foldoutAdd, _foldoutSearch, _IDName, _newLocalisations, _scrollPosID, _searchIDString, _selectedLanguage, _selectedScope, _selectedSearch, Localizer.AddLocalisation(), LocalisationID.DEVIDER, DrawLineHorizontal(), Localizer.Instance, Localizer.LocalisationData, Localizer.LocalisationLanguages, Localizer.LocalisationScopes, LocalisationLanguage.Name, LocalisationEditIDWindow.Open(), Localizer.RemoveLocalisation(), UpdateStatus(), and Localizer.WriteData().
Referenced by OnGUI().
DisplayLanguagesTab()
void LocalisationManagerWindow.DisplayLanguagesTab () private
References _languageName, _languageShortName, _scrollPosLanguage, Localizer.AddLanguage(), DrawLineHorizontal(), Localizer.Instance, Localizer.LocalisationLanguages, LocalisationLanguage.Name, LocalisationEditLanguageWindow.Open(), Localizer.RemoveLanguage(), LocalisationLanguage.ShortName, UpdateStatus(), and Localizer.WriteData().
Referenced by OnGUI().
DisplayScopesTab()
void LocalisationManagerWindow.DisplayScopesTab () private
References _scopeName, _scrollPosScope, Localizer.AddScope(), Localizer.DefaultScope, DrawLineHorizontal(), LocalisationScope.Equals(), Localizer.Instance, Localizer.LocalisationScopes, LocalisationScope.Name, LocalisationEditScopeWindow.Open(), Localizer.RemoveScope(), UpdateStatus(), and Localizer.WriteData().
Referenced by OnGUI().
DisplaySettingsTab()
void LocalisationManagerWindow.DisplaySettingsTab () private
References _assetPathInProject, DrawLineHorizontal(), Localizer.Initialize(), Localizer.Instance, Localizer.IsInitialized, ResourcesUtil.TrySetValidPath(), and UpdateStatus().
Referenced by OnGUI().
DisplayWindow()
static void LocalisationManagerWindow.DisplayWindow () static private
DrawLineHorizontal()
void LocalisationManagerWindow.DrawLineHorizontal () private
Referenced by DisplayIDsTab(), DisplayLanguagesTab(), DisplayScopesTab(), DisplaySettingsTab(), and OnGUI().
InitializeWindow()
void LocalisationManagerWindow.InitializeWindow () private
References _assetPathInProject, _newLocalisations, _scrollPosID, _scrollPosLanguage, _scrollPosScope, _searchIDString, _status, ResourcesUtil.GetProjectPath(), Localizer.Initialize(), and Localizer.Instance.
Referenced by Awake(), and OnAfterAssemblyReload().
IsPathValid()
bool LocalisationManagerWindow.IsPathValid (string path) private
OnAfterAssemblyReload()
void LocalisationManagerWindow.OnAfterAssemblyReload ()
References InitializeWindow().
Referenced by OnDisable(), and OnEnable().
OnDisable()
void LocalisationManagerWindow.OnDisable () private
References OnAfterAssemblyReload().
OnEnable()
void LocalisationManagerWindow.OnEnable () private
References OnAfterAssemblyReload().
OnGUI()
void LocalisationManagerWindow.OnGUI () private
References _selectedTab, _status, DisplayIDsTab(), DisplayLanguagesTab(), DisplayScopesTab(), DisplaySettingsTab(), DrawLineHorizontal(), IDS, Localizer.Instance, Localizer.IsInitialized, LANGUAGES, SCOPES, and SETTINGS.
Open()
static void LocalisationManagerWindow.Open () static
UpdateStatus()
void LocalisationManagerWindow.UpdateStatus (string status) private
References _status.
Referenced by DisplayIDsTab(), DisplayLanguagesTab(), DisplayScopesTab(), and DisplaySettingsTab().
Member Data Documentation
_assetPathInProject
string LocalisationManagerWindow._assetPathInProject private
Referenced by DisplaySettingsTab(), and InitializeWindow().
_foldoutAdd
bool LocalisationManagerWindow._foldoutAdd private
Referenced by DisplayIDsTab().
_foldoutSearch
bool LocalisationManagerWindow._foldoutSearch private
Referenced by DisplayIDsTab().
_IDName
string LocalisationManagerWindow._IDName private
Referenced by DisplayIDsTab().
_languageName
string LocalisationManagerWindow._languageName private
Referenced by DisplayLanguagesTab().
_languageShortName
string LocalisationManagerWindow._languageShortName private
Referenced by DisplayLanguagesTab().
_newLocalisations
Dictionary<LocalisationLanguage, string> LocalisationManagerWindow._newLocalisations private
Referenced by DisplayIDsTab(), and InitializeWindow().
_scopeName
string LocalisationManagerWindow._scopeName private
Referenced by DisplayScopesTab().
_scrollPosID
Vector2 LocalisationManagerWindow._scrollPosID private
Referenced by DisplayIDsTab(), and InitializeWindow().
_scrollPosLanguage
Vector2 LocalisationManagerWindow._scrollPosLanguage private
Referenced by DisplayLanguagesTab(), and InitializeWindow().
_scrollPosScope
Vector2 LocalisationManagerWindow._scrollPosScope private
Referenced by DisplayScopesTab(), and InitializeWindow().
_searchIDString
string LocalisationManagerWindow._searchIDString private
Referenced by DisplayIDsTab(), and InitializeWindow().
_selectedLanguage
int LocalisationManagerWindow._selectedLanguage private
Referenced by DisplayIDsTab().
_selectedScope
int LocalisationManagerWindow._selectedScope private
Referenced by DisplayIDsTab().
_selectedSearch
int LocalisationManagerWindow._selectedSearch private
Referenced by DisplayIDsTab().
_selectedTab
int LocalisationManagerWindow._selectedTab = 0 private
Referenced by OnGUI().
_status
string LocalisationManagerWindow._status private
Referenced by InitializeWindow(), OnGUI(), and UpdateStatus().
IDS
const int LocalisationManagerWindow.IDS = 0 static private
Referenced by OnGUI().
LANGUAGES
const int LocalisationManagerWindow.LANGUAGES = 1 static private
Referenced by OnGUI().
SCOPES
const int LocalisationManagerWindow.SCOPES = 2 static private
Referenced by OnGUI().
SETTINGS
const int LocalisationManagerWindow.SETTINGS = 3 static private
Referenced by OnGUI().