UnityToolbox Documentation: TerrainDecoration Class Reference
TerrainDecoration Class Reference
A script which places decoration on a generated terrain.
Public Member Functions
void DeleteObjects ()
Deletes all spawned objects.
void PlaceObjects ()
Places all defined objects.
Private Member Functions
bool CheckPositionType (int x, int y)
void RotationPlacementForChildren (GameObject parent, float heightOffset, bool widthPlacement)
void RotationPlacementForChildrenRecursiv (GameObject parent, float heightOffset, bool widthPlacement)
void CheckForAnchorsRecursiv (Transform parent)
Private Attributes
float _pctForNone
TerrainDecorationPositionType _positionType
bool _raycastPlacement
LayerMask _groundMask
List< TerrainDecorationInformation > _objectsToPlace
TerrainGenerator _terrainGenerator
List< GameObject > _spawnedObjects
List< TerrainDecorationInformation > _weightedObjects
Member Function Documentation
CheckForAnchorsRecursiv()
void TerrainDecoration.CheckForAnchorsRecursiv (Transform parent) private
References CheckForAnchorsRecursiv().
Referenced by CheckForAnchorsRecursiv(), and PlaceObjects().
CheckPositionType()
bool TerrainDecoration.CheckPositionType (int x, int y) private
References _positionType, _terrainGenerator, and TerrainGenerator.GeneratedGrid.
Referenced by PlaceObjects().
DeleteObjects()
void TerrainDecoration.DeleteObjects ()
References _spawnedObjects.
Referenced by TerrainGenerateAll.DeleteAllDecoration(), and TerrainDecorationEditor.OnInspectorGUI().
PlaceObjects()
void TerrainDecoration.PlaceObjects ()
References _objectsToPlace, _pctForNone, _raycastPlacement, _spawnedObjects, _terrainGenerator, _weightedObjects, CheckForAnchorsRecursiv(), CheckPositionType(), TerrainDecorationInformation.Clone(), TerrainGenerator.GeneratedGrid, TerrainGenerator.GeneratedMesh, TerrainDecorationInformation.HeightOffset, TerrainDecorationInformation.Object, TerrainDecorationChildInfo.RelativeToParent, RotationPlacementForChildren(), TerrainDecorationInformation.Weight, and TerrainDecorationInformation.WidthPlacement.
Referenced by TerrainGenerateAll.GenerateAll(), TerrainDecorationEditor.OnInspectorGUI(), and TerrainGenerateAll.WaitNextFrame().
RotationPlacementForChildren()
void TerrainDecoration.RotationPlacementForChildren (GameObject parent, float heightOffset, bool widthPlacement) private
References _groundMask, _spawnedObjects, and RotationPlacementForChildrenRecursiv().
Referenced by PlaceObjects().
RotationPlacementForChildrenRecursiv()
void TerrainDecoration.RotationPlacementForChildrenRecursiv (GameObject parent, float heightOffset, bool widthPlacement) private
References _groundMask, _spawnedObjects, TerrainDecorationChildInfo.RelativeToParent, and RotationPlacementForChildrenRecursiv().
Referenced by RotationPlacementForChildren(), and RotationPlacementForChildrenRecursiv().
Member Data Documentation
_groundMask
LayerMask TerrainDecoration._groundMask private
Referenced by RotationPlacementForChildren(), and RotationPlacementForChildrenRecursiv().
_objectsToPlace
List<TerrainDecorationInformation> TerrainDecoration._objectsToPlace private
Referenced by PlaceObjects().
_pctForNone
float TerrainDecoration._pctForNone private
Referenced by PlaceObjects().
_positionType
TerrainDecorationPositionType TerrainDecoration._positionType private
Referenced by CheckPositionType().
_raycastPlacement
bool TerrainDecoration._raycastPlacement private
Referenced by PlaceObjects().
_spawnedObjects
List<GameObject> TerrainDecoration._spawnedObjects private
Referenced by DeleteObjects(), PlaceObjects(), RotationPlacementForChildren(), and RotationPlacementForChildrenRecursiv().
_terrainGenerator
TerrainGenerator TerrainDecoration._terrainGenerator private
Referenced by CheckPositionType(), and PlaceObjects().
_weightedObjects
List<TerrainDecorationInformation> TerrainDecoration._weightedObjects private
Referenced by PlaceObjects().