UnityToolbox: LocalizedText Class Reference
LocalizedText Class Reference
This script is placed on a Text component and swaps out the localisation in editor and runtime.
Public Member Functions
void OnValidate ()
Private Member Functions
void Start ()
void OnDestroy ()
void UpdateText (int atIndex)
void UpdateText (LocalisationLanguage language)
Private Attributes
LocalisationID _localisationID
string _displayedString
List< LocalisationLanguage > _allLanguages
List< string > _allLanguagesString
int _selectedLanuage
Text _textToDisplay
string _languagePref
Member Function Documentation
OnDestroy()
void LocalizedText.OnDestroy () private
References UpdateText().
OnValidate()
void LocalizedText.OnValidate ()
References _allLanguages, _allLanguagesString, _selectedLanuage, ProjectPrefs.GetString(), Localizer.Initialize(), Localizer.Instance, Localizer.IsInitialized, Localizer.LocalisationLanguages, and UpdateText().
Start()
void LocalizedText.Start () private
References _allLanguages, _languagePref, ProjectPrefs.GetString(), Localizer.Initialize(), Localizer.Instance, Localizer.IsInitialized, PlayerPrefKeys.LANGUAGE, Localizer.LocalisationLanguages, and UpdateText().
UpdateText() [1/2]
void LocalizedText.UpdateText (int atIndex) private
References _allLanguages, _displayedString, _localisationID, _textToDisplay, Localizer.Instance, and Localizer.LocalisationData.
Referenced by OnDestroy(), OnValidate(), and Start().
UpdateText() [2/2]
void LocalizedText.UpdateText (LocalisationLanguage language) private
References _displayedString, _localisationID, _textToDisplay, Localizer.Instance, and Localizer.LocalisationData.
Member Data Documentation
_allLanguages
List<LocalisationLanguage> LocalizedText._allLanguages private
Referenced by OnValidate(), Start(), and UpdateText().
_allLanguagesString
List<string> LocalizedText._allLanguagesString private
Referenced by OnValidate().
_displayedString
string LocalizedText._displayedString private
Referenced by UpdateText().
_languagePref
string LocalizedText._languagePref private
Referenced by Start().
_localisationID
LocalisationID LocalizedText._localisationID private
Referenced by UpdateText().
_selectedLanuage
int LocalizedText._selectedLanuage private
Referenced by OnValidate().
_textToDisplay
Text LocalizedText._textToDisplay private
Referenced by UpdateText().