UnityToolbox: DialogGraphView Class Reference
DialogGraphView Class Reference
The dialog graph used within a window.
Public Member Functions
DialogGraphView ()
void AddNode (DialogNode node)
Adds a new DialogNode to the graph and draws it.
override List< Port > GetCompatiblePorts (Port startPort, NodeAdapter nodeAdapter)
Properties
HashSet< int > IDS [get]
Private Member Functions
DialogNode CreateNode (Vector2 position)
void AddGrid ()
void AddStyle ()
void AddManipulators ()
IManipulator CreateNodeManipulator ()
IManipulator CreateGroupManipulator ()
Group CreateGroup (string title, Vector2 localMousePosition)
string GetPathOfStyle ()
GraphViewChange OnGraphChange (GraphViewChange change)
Private Attributes
HashSet< int > _ids
Constructor & Destructor Documentation
DialogGraphView()
DialogGraphView.DialogGraphView ()
References _ids, AddGrid(), AddManipulators(), AddStyle(), and OnGraphChange().
Member Function Documentation
AddGrid()
void DialogGraphView.AddGrid () private
Referenced by DialogGraphView().
AddManipulators()
void DialogGraphView.AddManipulators () private
References CreateGroupManipulator(), and CreateNodeManipulator().
Referenced by DialogGraphView().
AddNode()
void DialogGraphView.AddNode (DialogNode node)
Parameters
node
References _ids, DialogNode.Draw(), and DialogNode.ID.
Referenced by DialogGraphWindow.UpdateData().
AddStyle()
void DialogGraphView.AddStyle () private
References GetPathOfStyle().
Referenced by DialogGraphView().
CreateGroup()
Group DialogGraphView.CreateGroup (string title, Vector2 localMousePosition) private
Referenced by CreateGroupManipulator().
CreateGroupManipulator()
IManipulator DialogGraphView.CreateGroupManipulator () private
References CreateGroup().
Referenced by AddManipulators().
CreateNode()
DialogNode DialogGraphView.CreateNode (Vector2 position) private
References _ids, and DialogNode.Draw().
Referenced by CreateNodeManipulator().
CreateNodeManipulator()
IManipulator DialogGraphView.CreateNodeManipulator () private
References CreateNode().
Referenced by AddManipulators().
GetCompatiblePorts()
override List< Port > DialogGraphView.GetCompatiblePorts (Port startPort, NodeAdapter nodeAdapter)
GetPathOfStyle()
string DialogGraphView.GetPathOfStyle () private
References ProjectPrefs.GetString().
Referenced by AddStyle().
OnGraphChange()
GraphViewChange DialogGraphView.OnGraphChange (GraphViewChange change) private
Referenced by DialogGraphView().
Member Data Documentation
_ids
HashSet<int> DialogGraphView._ids private
Referenced by AddNode(), CreateNode(), and DialogGraphView().
Property Documentation
IDS
HashSet<int> DialogGraphView.IDS get