UnityToolbox: ItemDefinitionEditWindow Class Reference
ItemDefinitionEditWindow Class Reference
Public Member Functions
void OnGUI ()
new void Close ()
Static Public Member Functions
static void Open (ItemDefinition currentItemDefinition)
Properties
ItemDefinition CurrentItemDefinition [set]
Private Member Functions
void Awake ()
void Init (ItemDefinition value)
void DrawLine ()
void DrawCreationFields ()
void DrawAddDefinedItem ()
void ItemDefinitionEdited (ItemDefinition oldItemDefinition, ItemDefinition newItemDefinition)
void ScopeEdited (ItemScope oldScope, ItemScope newScope)
void UpdateStatus (string status)
Private Attributes
ItemDefinition _currentItemDefinition
Vector2 _scrollPosCreation
Type _type
List< bool > _selectionBoolValues
List< string > _selectionStringValues
List< float > _selectionFloatValues
List< int > _selectionIntValues
List< FieldInfo > _selectionFields
string _newItemDefinitionName
int _newSelectedScope
Texture2D _newItemDefinitionIcon
GameObject _newItemDefinitionPrefab
int _newMaxStackCount
string _status
Member Function Documentation
Awake()
void ItemDefinitionEditWindow.Awake () private
References ItemDefinitionEdited(), ScopeEdited(), and UpdateStatus().
Close()
new void ItemDefinitionEditWindow.Close ()
References ItemDefinitionEdited(), and ScopeEdited().
Referenced by DrawAddDefinedItem(), ItemDefinitionEdited(), and ScopeEdited().
DrawAddDefinedItem()
void ItemDefinitionEditWindow.DrawAddDefinedItem () private
References _currentItemDefinition, _newItemDefinitionIcon, _newItemDefinitionName, _newItemDefinitionPrefab, _newMaxStackCount, _newSelectedScope, _selectionBoolValues, _selectionFields, _selectionFloatValues, _selectionIntValues, _selectionStringValues, _type, Close(), Itemizer.EditItemDefinition(), Itemizer.Instance, Itemizer.ItemScopes, UpdateStatus(), and Itemizer.WriteData().
Referenced by OnGUI().
DrawCreationFields()
void ItemDefinitionEditWindow.DrawCreationFields () private
References _newItemDefinitionIcon, _newItemDefinitionName, _newItemDefinitionPrefab, _newMaxStackCount, _newSelectedScope, _scrollPosCreation, _selectionBoolValues, _selectionFields, _selectionFloatValues, _selectionIntValues, _selectionStringValues, _type, ItemDefinition.DEVIDER, Itemizer.Instance, and Itemizer.ItemScopes.
Referenced by OnGUI().
DrawLine()
void ItemDefinitionEditWindow.DrawLine () private
Referenced by OnGUI().
Init()
void ItemDefinitionEditWindow.Init (ItemDefinition value) private
References _currentItemDefinition, _newItemDefinitionIcon, _newItemDefinitionName, _newItemDefinitionPrefab, _newMaxStackCount, _newSelectedScope, _selectionBoolValues, _selectionFields, _selectionFloatValues, _selectionIntValues, _selectionStringValues, _type, ItemScope.Equals(), ItemDefinition.IconPath, Itemizer.Instance, Itemizer.ItemScopes, ItemDefinition.MaxStackCount, ItemDefinition.Name, and ItemDefinition.PrefabPath.
ItemDefinitionEdited()
void ItemDefinitionEditWindow.ItemDefinitionEdited (ItemDefinition oldItemDefinition, ItemDefinition newItemDefinition) private
References Close().
Referenced by Awake(), and Close().
OnGUI()
void ItemDefinitionEditWindow.OnGUI ()
References _status, DrawAddDefinedItem(), DrawCreationFields(), and DrawLine().
Open()
static void ItemDefinitionEditWindow.Open (ItemDefinition currentItemDefinition) static
Referenced by ItemManagerWindow.DrawListItems(), and ItemDefinitionSelectionWindow.OnGUI().
ScopeEdited()
void ItemDefinitionEditWindow.ScopeEdited (ItemScope oldScope, ItemScope newScope) private
References Close().
Referenced by Awake(), and Close().
UpdateStatus()
void ItemDefinitionEditWindow.UpdateStatus (string status) private
References _status.
Referenced by Awake(), and DrawAddDefinedItem().
Member Data Documentation
_currentItemDefinition
ItemDefinition ItemDefinitionEditWindow._currentItemDefinition private
Referenced by DrawAddDefinedItem(), and Init().
_newItemDefinitionIcon
Texture2D ItemDefinitionEditWindow._newItemDefinitionIcon private
Referenced by DrawAddDefinedItem(), DrawCreationFields(), and Init().
_newItemDefinitionName
string ItemDefinitionEditWindow._newItemDefinitionName private
Referenced by DrawAddDefinedItem(), DrawCreationFields(), and Init().
_newItemDefinitionPrefab
GameObject ItemDefinitionEditWindow._newItemDefinitionPrefab private
Referenced by DrawAddDefinedItem(), DrawCreationFields(), and Init().
_newMaxStackCount
int ItemDefinitionEditWindow._newMaxStackCount private
Referenced by DrawAddDefinedItem(), DrawCreationFields(), and Init().
_newSelectedScope
int ItemDefinitionEditWindow._newSelectedScope private
Referenced by DrawAddDefinedItem(), DrawCreationFields(), and Init().
_scrollPosCreation
Vector2 ItemDefinitionEditWindow._scrollPosCreation private
Referenced by DrawCreationFields().
_selectionBoolValues
List<bool> ItemDefinitionEditWindow._selectionBoolValues private
Referenced by DrawAddDefinedItem(), DrawCreationFields(), and Init().
_selectionFields
List<FieldInfo> ItemDefinitionEditWindow._selectionFields private
Referenced by DrawAddDefinedItem(), DrawCreationFields(), and Init().
_selectionFloatValues
List<float> ItemDefinitionEditWindow._selectionFloatValues private
Referenced by DrawAddDefinedItem(), DrawCreationFields(), and Init().
_selectionIntValues
List<int> ItemDefinitionEditWindow._selectionIntValues private
Referenced by DrawAddDefinedItem(), DrawCreationFields(), and Init().
_selectionStringValues
List<string> ItemDefinitionEditWindow._selectionStringValues private
Referenced by DrawAddDefinedItem(), DrawCreationFields(), and Init().
_status
string ItemDefinitionEditWindow._status private
Referenced by OnGUI(), and UpdateStatus().
_type
Type ItemDefinitionEditWindow._type private
Referenced by DrawAddDefinedItem(), DrawCreationFields(), and Init().
Property Documentation
CurrentItemDefinition
ItemDefinition ItemDefinitionEditWindow.CurrentItemDefinition set