UnityToolbox Documentation: LanguageSetting Class Reference
LanguageSetting Class Reference
A script which displays the language settings. Requires the UIEventManager and the SettingsManager. LanguageSettingButton is required to change its value.
Private Member Functions
void Start ()
void OnDestroy ()
void NextLanguage ()
void PreviousLanguage ()
Private Attributes
HashSet< LocalisationLanguage > _localisationLanguages
int _currentLanguage
Text _displayText
string _languagePref
Member Function Documentation
NextLanguage()
void LanguageSetting.NextLanguage () private
References _currentLanguage, _languagePref, and _localisationLanguages.
Referenced by OnDestroy(), and Start().
OnDestroy()
void LanguageSetting.OnDestroy () private
References NextLanguage(), and PreviousLanguage().
PreviousLanguage()
void LanguageSetting.PreviousLanguage () private
References _currentLanguage, _languagePref, and _localisationLanguages.
Referenced by OnDestroy(), and Start().
Start()
void LanguageSetting.Start () private
References _currentLanguage, _displayText, _languagePref, _localisationLanguages, ProjectPrefs.GetString(), Localizer.Initialize(), Localizer.Instance, Localizer.IsInitialized, PlayerPrefKeys.LANGUAGE, Localizer.LocalisationLanguages, NextLanguage(), and PreviousLanguage().
Member Data Documentation
_currentLanguage
int LanguageSetting._currentLanguage private
Referenced by NextLanguage(), PreviousLanguage(), and Start().
_displayText
Text LanguageSetting._displayText private
Referenced by Start().
_languagePref
string LanguageSetting._languagePref private
Referenced by NextLanguage(), PreviousLanguage(), and Start().
_localisationLanguages
HashSet<LocalisationLanguage> LanguageSetting._localisationLanguages private
Referenced by NextLanguage(), PreviousLanguage(), and Start().