UnityToolbox: LocalisationEditLanguageWindow Class Reference
LocalisationEditLanguageWindow Class Reference
Public Member Functions
void OnGUI ()
Static Public Member Functions
static void Open (LocalisationLanguage language)
Properties
LocalisationLanguage Language [set]
Private Member Functions
void Awake ()
void LanguageEdited (LocalisationLanguage language)
Private Attributes
LocalisationLanguage _language
string _newLanguageName
string _newLanguageShort
string _status
Member Function Documentation
Awake()
void LocalisationEditLanguageWindow.Awake () private
References LanguageEdited().
LanguageEdited()
void LocalisationEditLanguageWindow.LanguageEdited (LocalisationLanguage language) private
References _language, LocalisationLanguage.Equals(), and LanguageEdited().
Referenced by Awake(), LanguageEdited(), and OnGUI().
OnGUI()
void LocalisationEditLanguageWindow.OnGUI ()
References _language, _newLanguageName, _newLanguageShort, _status, Localizer.EditLanguage(), Localizer.Instance, LanguageEdited(), and Localizer.WriteData().
Open()
static void LocalisationEditLanguageWindow.Open (LocalisationLanguage language) static
Referenced by LocalisationManagerWindow.DisplayLanguagesTab().
Member Data Documentation
_language
LocalisationLanguage LocalisationEditLanguageWindow._language private
Referenced by LanguageEdited(), and OnGUI().
_newLanguageName
string LocalisationEditLanguageWindow._newLanguageName private
Referenced by OnGUI().
_newLanguageShort
string LocalisationEditLanguageWindow._newLanguageShort private
Referenced by OnGUI().
_status
string LocalisationEditLanguageWindow._status private
Referenced by OnGUI().
Property Documentation
Language
LocalisationLanguage LocalisationEditLanguageWindow.Language set