UnityToolbox: UnityToolbox.Item.Management.Itemizer Class Reference
UnityToolbox.Item.Management.Itemizer Class Reference
The core of the item managment system. It takes care of the (de)serialization and changes to all data.
Public Member Functions
bool Initialize ()
Tries to initialize the Itemizer.
ItemDefinition AddItemDefinition (ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, string iconGUID, string prefabGUID)
Creates a new item definition and adds it to the mangement.
T AddInheritedItemDefinition< T > (ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, string iconGUID, string prefabGUID, HashSet< ItemField > itemFields)
Creates a new item inheriting ItemDefinition and adds it to the mangement.
void RemoveItemDefinition (ItemDefinition itemDefinition)
Removes an ItemDefinition from the mangement.
void EditInheritedItemDefinition< T > (ItemDefinition itemDefinition, ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, string iconGUID, string prefabGUID, HashSet< ItemField > itemFields)
Edits a given item inheriting ItemDefinition and replaces the old within the mangement.
void EditItemDefinition (ItemDefinition itemDefinition, ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, string iconGUID, string prefabGUID)
Edits a given ItemDefinition and replaces the old within the mangement.
ItemScope AddItemScope (string name)
Adds a new ItemScope by a given unique name.
void RemoveItemScope (ItemScope scope)
Removes a given ItemScope. Replaces the given scope used for the ItemDefinition with the DefaultScope.
void EditItemScope (ItemScope scope, string name)
Edits a given ItemScope and replaces the old.
List< Type > GetAllInheritedItemDefinitionTypes ()
Checks the assembly for all classes inheriting ItemDefinition.
void WriteData ()
Writes all data to the set resources folder.
void ItemScopeEdited (ItemScope oldScope, ItemScope newScope)
Invokes the OnItemScopeEdited action.
void ItemDefinitionEdited (ItemDefinition oldItemDefinition, ItemDefinition newItemDefinition)
Invokes the OnItemDefinitionEdited action.
Properties
static Itemizer Instance [get]
The singleton instance of the Itemizer.
bool Initialized [get]
Is the itemizer initialized? If not, it cannot be used.
HashSet< ItemDefinition > ItemDefinitions [get]
All defined items.
HashSet< ItemDefinition > FaultyItemDefinitions [get]
All defined items which are faulty.
HashSet< ItemScope > ItemScopes [get]
All defined item scopes.
ItemScope DefaultScope [get]
The defaulte scope, set by default and is the replacement for deleted scopes.
Events
Action< ItemScope, ItemScope > OnItemScopeEdited
Action< ItemDefinition, ItemDefinition > OnItemDefinitionEdited
Private Member Functions
Itemizer ()
Usage forbidden as the Itemizer.Instance should be used.
void InternalRemoveItemDefinition (ItemDefinition itemDefinition)
void CheckInitialized ()
void ReadData ()
void ReadItemData ()
void ReadItemScopes ()
Private Attributes
bool _initialized
string FILENAMEITEMS = "ItemData.txt"
string FILENAMESCOPES = "ItemScopeData.txt"
HashSet< ItemDefinition > _itemDefinitions
HashSet< ItemDefinition > _faultyItemDefinitions
HashSet< ItemScope > _itemScopes
ItemScope _defaultScope
Static Private Attributes
static Itemizer _instance
Constructor & Destructor Documentation
Itemizer()
UnityToolbox.Item.Management.Itemizer.Itemizer () private
Member Function Documentation
AddInheritedItemDefinition< T >()
T UnityToolbox.Item.Management.Itemizer.AddInheritedItemDefinition< T > (ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, string iconGUID, string prefabGUID, HashSet< ItemField > itemFields)
Template Parameters
T A type which inherits ItemDefinition.
Parameters
scope The scope of the definition."/></param> <param name="name">The name of the definition. Has to be unique in combination with the scope.</param> <param name="maxStackCount">How high this item can be stacked.</param> <param name="resourceIconPath">The path to where the icon can be found. Has to be a resources path.</param> <param name="resourcePrefabPath">The path to where the prefab can be found. Has to be a resources path.</param> <param name="itemFields">All additional field values defined for type <typeparamref name="T"/>.</param> <returns>The created <see cref="ItemDefinition"/>.</returns> <exception cref="ItemDefinitionException">
Type Constraints
T : ItemDefinition
References UnityToolbox.Item.Management.Itemizer._itemDefinitions, UnityToolbox.Item.Management.Itemizer._itemScopes, UnityToolbox.Item.Management.Itemizer.CheckInitialized(), UnityToolbox.Item.Management.ItemField.FieldName, UnityToolbox.Item.Management.ItemField.FieldType, and UnityToolbox.Item.Management.ItemField.GetValue().
Referenced by UnityToolbox.Item.Management.Itemizer.EditInheritedItemDefinition< T >().
AddItemDefinition()
ItemDefinition UnityToolbox.Item.Management.Itemizer.AddItemDefinition (ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, string iconGUID, string prefabGUID)
Parameters
scope The scope of the definition."/></param> <param name="name">The name of the definition. Has to be unique in combination with the scope.</param> <param name="maxStackCount">How high this item can be stacked.</param> <param name="resourceIconPath">The path to where the icon can be found. Has to be a resources path.</param> <param name="resourcePrefabPath">The path to where the prefab can be found. Has to be a resources path.</param> <returns>The created <see cref="ItemDefinition"/>.</returns> <exception cref="ItemDefinitionException">
References UnityToolbox.Item.Management.Itemizer._itemDefinitions, UnityToolbox.Item.Management.Itemizer._itemScopes, UnityToolbox.Item.Management.Itemizer.CheckInitialized(), and UnityToolbox.Item.ItemDefinition.GetQualifiedName().
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.Itemizer.EditItemDefinition(), UnityToolbox.Item.Management.Itemizer.EditItemScope(), and UnityToolbox.Item.Management.Itemizer.RemoveItemScope().
AddItemScope()
ItemScope UnityToolbox.Item.Management.Itemizer.AddItemScope (string name)
Parameters
name The unique name of the scope to create.
Returns
The created ItemScope.
Exceptions
ItemDefinitionException
References UnityToolbox.Item.Management.Itemizer._itemScopes, and UnityToolbox.Item.Management.Itemizer.CheckInitialized().
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DisplayScopesTab(), and UnityToolbox.Item.Management.Itemizer.EditItemScope().
CheckInitialized()
void UnityToolbox.Item.Management.Itemizer.CheckInitialized () private
References UnityToolbox.Item.Management.Itemizer._initialized, and UnityToolbox.Item.Management.Itemizer.Initialize().
Referenced by UnityToolbox.Item.Management.Itemizer.AddInheritedItemDefinition< T >(), UnityToolbox.Item.Management.Itemizer.AddItemDefinition(), UnityToolbox.Item.Management.Itemizer.AddItemScope(), UnityToolbox.Item.Management.Itemizer.EditItemScope(), UnityToolbox.Item.Management.Itemizer.InternalRemoveItemDefinition(), UnityToolbox.Item.Management.Itemizer.RemoveItemDefinition(), and UnityToolbox.Item.Management.Itemizer.RemoveItemScope().
EditInheritedItemDefinition< T >()
void UnityToolbox.Item.Management.Itemizer.EditInheritedItemDefinition< T > (ItemDefinition itemDefinition, ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, string iconGUID, string prefabGUID, HashSet< ItemField > itemFields)
Template Parameters
T A type which inherits ItemDefinition.
Parameters
itemDefinition The ItemDefinition to be edited.
scope The new scope of the definition."/></param> <param name="name">The new name of the definition. Has to be unique in combination with the scope.</param> <param name="maxStackCount">How high this item can be stacked.</param> <param name="resourceIconPath">The new path to where the icon can be found. Has to be a resources path.</param> <param name="resourcePrefabPath">The new path to where the prefab can be found. Has to be a resources path.</param> <param name="itemFields">All additional new field values defined for type <typeparamref name="T"/>.</param> <returns>The created <see cref="ItemDefinition"/>.</returns> <exception cref="ItemDefinitionException">
Type Constraints
T : ItemDefinition
References UnityToolbox.Item.Management.Itemizer._faultyItemDefinitions, UnityToolbox.Item.Management.Itemizer._itemDefinitions, UnityToolbox.Item.Management.Itemizer.AddInheritedItemDefinition< T >(), UnityToolbox.Item.Management.Itemizer.InternalRemoveItemDefinition(), and UnityToolbox.Item.Management.Itemizer.ItemDefinitionEdited().
EditItemDefinition()
void UnityToolbox.Item.Management.Itemizer.EditItemDefinition (ItemDefinition itemDefinition, ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, string iconGUID, string prefabGUID)
Parameters
itemDefinition The ItemDefinition to be edited.
scope The new scope of the definition."/></param> <param name="name">The new name of the definition. Has to be unique in combination with the scope.</param> <param name="maxStackCount">How high this item can be stacked.</param> <param name="resourceIconPath">The new path to where the icon can be found. Has to be a resources path.</param> <param name="resourcePrefabPath">The new path to where the prefab can be found. Has to be a resources path.</param> <returns>The created <see cref="ItemDefinition"/>.</returns> <exception cref="ItemDefinitionException">
References UnityToolbox.Item.Management.Itemizer._faultyItemDefinitions, UnityToolbox.Item.Management.Itemizer._itemDefinitions, UnityToolbox.Item.Management.Itemizer.AddItemDefinition(), UnityToolbox.Item.Management.Itemizer.InternalRemoveItemDefinition(), and UnityToolbox.Item.Management.Itemizer.ItemDefinitionEdited().
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), and UnityToolbox.Item.Management.ItemManagerWindow.FixFaultyItemsByGUID().
EditItemScope()
void UnityToolbox.Item.Management.Itemizer.EditItemScope (ItemScope scope, string name)
Parameters
scope The ItemScope to edit.
name The new unique name of the scope.
Exceptions
ItemDefinitionException
References UnityToolbox.Item.Management.Itemizer._defaultScope, UnityToolbox.Item.Management.Itemizer._itemDefinitions, UnityToolbox.Item.Management.Itemizer._itemScopes, UnityToolbox.Item.Management.Itemizer.AddItemDefinition(), UnityToolbox.Item.Management.Itemizer.AddItemScope(), UnityToolbox.Item.Management.Itemizer.CheckInitialized(), UnityToolbox.Item.Management.ItemScope.Equals(), UnityToolbox.Item.ItemDefinition.IconGUID, UnityToolbox.Item.ItemDefinition.IconPath, UnityToolbox.Item.Management.Itemizer.InternalRemoveItemDefinition(), UnityToolbox.Item.Management.Itemizer.ItemScopeEdited(), UnityToolbox.Item.ItemDefinition.MaxStackCount, UnityToolbox.Item.Management.ItemScope.Name, UnityToolbox.Item.ItemDefinition.Name, UnityToolbox.Item.ItemDefinition.PrefabGUID, and UnityToolbox.Item.ItemDefinition.PrefabPath.
Referenced by UnityToolbox.Item.Management.ItemScopeEditWindow.OnGUI().
GetAllInheritedItemDefinitionTypes()
List< Type > UnityToolbox.Item.Management.Itemizer.GetAllInheritedItemDefinitionTypes ()
Returns
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.Awake(), UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.Awake(), UnityToolbox.Item.Management.ItemManagerWindow.DisplaySettingsTab(), and UnityToolbox.Item.Management.ItemManagerWindow.InitializeWindow().
Initialize()
bool UnityToolbox.Item.Management.Itemizer.Initialize ()
Returns
Whether initializing was successful.
References UnityToolbox.Item.Management.Itemizer._defaultScope, UnityToolbox.Item.Management.Itemizer._initialized, UnityToolbox.Item.Management.Itemizer._itemDefinitions, UnityToolbox.Item.Management.Itemizer._itemScopes, ProjectPrefs.GetString(), ResourcesUtil.IsFullPathValid(), and UnityToolbox.Item.Management.Itemizer.ReadData().
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.Awake(), UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.Awake(), UnityToolbox.Item.ItemManager.Awake(), UnityToolbox.Item.Management.Itemizer.CheckInitialized(), UnityToolbox.Item.Management.ItemManagerWindow.DisplaySettingsTab(), and UnityToolbox.Item.Management.ItemManagerWindow.InitializeWindow().
InternalRemoveItemDefinition()
void UnityToolbox.Item.Management.Itemizer.InternalRemoveItemDefinition (ItemDefinition itemDefinition) private
References UnityToolbox.Item.Management.Itemizer._itemDefinitions, UnityToolbox.Item.Management.Itemizer.CheckInitialized(), and UnityToolbox.Item.ItemDefinition.GetQualifiedName().
Referenced by UnityToolbox.Item.Management.Itemizer.EditInheritedItemDefinition< T >(), UnityToolbox.Item.Management.Itemizer.EditItemDefinition(), UnityToolbox.Item.Management.Itemizer.EditItemScope(), and UnityToolbox.Item.Management.Itemizer.RemoveItemScope().
ItemDefinitionEdited()
void UnityToolbox.Item.Management.Itemizer.ItemDefinitionEdited (ItemDefinition oldItemDefinition, ItemDefinition newItemDefinition)
Parameters
oldItemDefinition
newItemDefinition
References UnityToolbox.Item.Management.Itemizer.OnItemDefinitionEdited.
Referenced by UnityToolbox.Item.Management.Itemizer.EditInheritedItemDefinition< T >(), UnityToolbox.Item.Management.Itemizer.EditItemDefinition(), and UnityToolbox.Item.Management.Itemizer.RemoveItemDefinition().
ItemScopeEdited()
void UnityToolbox.Item.Management.Itemizer.ItemScopeEdited (ItemScope oldScope, ItemScope newScope)
Parameters
oldScope
newScope
References UnityToolbox.Item.Management.Itemizer.OnItemScopeEdited.
Referenced by UnityToolbox.Item.Management.Itemizer.EditItemScope(), and UnityToolbox.Item.Management.Itemizer.RemoveItemScope().
ReadData()
void UnityToolbox.Item.Management.Itemizer.ReadData () private
References UnityToolbox.Item.Management.Itemizer.ReadItemData(), and UnityToolbox.Item.Management.Itemizer.ReadItemScopes().
Referenced by UnityToolbox.Item.Management.Itemizer.Initialize().
ReadItemData()
void UnityToolbox.Item.Management.Itemizer.ReadItemData () private
References UnityToolbox.Item.Management.Itemizer._faultyItemDefinitions, UnityToolbox.Item.Management.Itemizer._itemDefinitions, UnityToolbox.Item.ItemDefinition.Deserialize(), and UnityToolbox.Item.Management.Itemizer.FILENAMEITEMS.
Referenced by UnityToolbox.Item.Management.Itemizer.ReadData().
ReadItemScopes()
void UnityToolbox.Item.Management.Itemizer.ReadItemScopes () private
References UnityToolbox.Item.Management.Itemizer._itemScopes, and UnityToolbox.Item.Management.Itemizer.FILENAMESCOPES.
Referenced by UnityToolbox.Item.Management.Itemizer.ReadData().
RemoveItemDefinition()
void UnityToolbox.Item.Management.Itemizer.RemoveItemDefinition (ItemDefinition itemDefinition)
Parameters
itemDefinition The ItemDefinition to be removed.
Exceptions
ItemDefinitionException
References UnityToolbox.Item.Management.Itemizer._faultyItemDefinitions, UnityToolbox.Item.Management.Itemizer._itemDefinitions, UnityToolbox.Item.Management.Itemizer.CheckInitialized(), UnityToolbox.Item.ItemDefinition.GetQualifiedName(), and UnityToolbox.Item.Management.Itemizer.ItemDefinitionEdited().
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DrawListItems(), UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DrawListItems(), and UnityToolbox.Item.Management.ItemManagerWindow.DrawListItems().
RemoveItemScope()
void UnityToolbox.Item.Management.Itemizer.RemoveItemScope (ItemScope scope)
Parameters
scope The ItemScope to remove.
Exceptions
ItemDefinitionException
References UnityToolbox.Item.Management.Itemizer._defaultScope, UnityToolbox.Item.Management.Itemizer._itemDefinitions, UnityToolbox.Item.Management.Itemizer._itemScopes, UnityToolbox.Item.Management.Itemizer.AddItemDefinition(), UnityToolbox.Item.Management.Itemizer.CheckInitialized(), UnityToolbox.Item.Management.ItemScope.Equals(), UnityToolbox.Item.ItemDefinition.IconGUID, UnityToolbox.Item.ItemDefinition.IconPath, UnityToolbox.Item.Management.Itemizer.InternalRemoveItemDefinition(), UnityToolbox.Item.Management.Itemizer.ItemScopeEdited(), UnityToolbox.Item.ItemDefinition.MaxStackCount, UnityToolbox.Item.Management.ItemScope.Name, UnityToolbox.Item.ItemDefinition.Name, UnityToolbox.Item.ItemDefinition.PrefabGUID, and UnityToolbox.Item.ItemDefinition.PrefabPath.
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DrawListScopes().
WriteData()
void UnityToolbox.Item.Management.Itemizer.WriteData ()
References UnityToolbox.Item.Management.Itemizer._itemDefinitions, UnityToolbox.Item.Management.Itemizer._itemScopes, UnityToolbox.Item.Management.Itemizer.FILENAMEITEMS, UnityToolbox.Item.Management.Itemizer.FILENAMESCOPES, and ResourcesUtil.WriteFile().
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DisplayScopesTab(), UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemManagerWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DrawListItems(), UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DrawListItems(), UnityToolbox.Item.Management.ItemManagerWindow.DrawListItems(), UnityToolbox.Item.Management.ItemManagerWindow.DrawListScopes(), UnityToolbox.Item.Management.ItemManagerWindow.FixFaultyItemsByGUID(), and UnityToolbox.Item.Management.ItemScopeEditWindow.OnGUI().
Member Data Documentation
_defaultScope
ItemScope UnityToolbox.Item.Management.Itemizer._defaultScope private
Referenced by UnityToolbox.Item.Management.Itemizer.EditItemScope(), UnityToolbox.Item.Management.Itemizer.Initialize(), and UnityToolbox.Item.Management.Itemizer.RemoveItemScope().
_faultyItemDefinitions
HashSet<ItemDefinition> UnityToolbox.Item.Management.Itemizer._faultyItemDefinitions private
Referenced by UnityToolbox.Item.Management.Itemizer.EditInheritedItemDefinition< T >(), UnityToolbox.Item.Management.Itemizer.EditItemDefinition(), UnityToolbox.Item.Management.Itemizer.ReadItemData(), and UnityToolbox.Item.Management.Itemizer.RemoveItemDefinition().
_initialized
bool UnityToolbox.Item.Management.Itemizer._initialized private
Referenced by UnityToolbox.Item.Management.Itemizer.CheckInitialized(), and UnityToolbox.Item.Management.Itemizer.Initialize().
_instance
Itemizer UnityToolbox.Item.Management.Itemizer._instance static private
_itemDefinitions
HashSet<ItemDefinition> UnityToolbox.Item.Management.Itemizer._itemDefinitions private
Referenced by UnityToolbox.Item.Management.Itemizer.AddInheritedItemDefinition< T >(), UnityToolbox.Item.Management.Itemizer.AddItemDefinition(), UnityToolbox.Item.Management.Itemizer.EditInheritedItemDefinition< T >(), UnityToolbox.Item.Management.Itemizer.EditItemDefinition(), UnityToolbox.Item.Management.Itemizer.EditItemScope(), UnityToolbox.Item.Management.Itemizer.Initialize(), UnityToolbox.Item.Management.Itemizer.InternalRemoveItemDefinition(), UnityToolbox.Item.Management.Itemizer.ReadItemData(), UnityToolbox.Item.Management.Itemizer.RemoveItemDefinition(), UnityToolbox.Item.Management.Itemizer.RemoveItemScope(), and UnityToolbox.Item.Management.Itemizer.WriteData().
_itemScopes
HashSet<ItemScope> UnityToolbox.Item.Management.Itemizer._itemScopes private
Referenced by UnityToolbox.Item.Management.Itemizer.AddInheritedItemDefinition< T >(), UnityToolbox.Item.Management.Itemizer.AddItemDefinition(), UnityToolbox.Item.Management.Itemizer.AddItemScope(), UnityToolbox.Item.Management.Itemizer.EditItemScope(), UnityToolbox.Item.Management.Itemizer.Initialize(), UnityToolbox.Item.Management.Itemizer.ReadItemScopes(), UnityToolbox.Item.Management.Itemizer.RemoveItemScope(), and UnityToolbox.Item.Management.Itemizer.WriteData().
FILENAMEITEMS
string UnityToolbox.Item.Management.Itemizer.FILENAMEITEMS = "ItemData.txt" private
Referenced by UnityToolbox.Item.Management.Itemizer.ReadItemData(), and UnityToolbox.Item.Management.Itemizer.WriteData().
FILENAMESCOPES
string UnityToolbox.Item.Management.Itemizer.FILENAMESCOPES = "ItemScopeData.txt" private
Referenced by UnityToolbox.Item.Management.Itemizer.ReadItemScopes(), and UnityToolbox.Item.Management.Itemizer.WriteData().
Property Documentation
DefaultScope
ItemScope UnityToolbox.Item.Management.Itemizer.DefaultScope get
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DrawListScopes().
FaultyItemDefinitions
HashSet<ItemDefinition> UnityToolbox.Item.Management.Itemizer.FaultyItemDefinitions get
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DrawListItems(), UnityToolbox.Item.Management.ItemManagerWindow.FixFaultyItemsByGUID(), UnityToolbox.Item.Management.ItemDefinitionErrorWindow.OnGUI(), UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.OnGUI(), and UnityToolbox.Item.Management.ItemManagerWindow.OnGUI().
Initialized
bool UnityToolbox.Item.Management.Itemizer.Initialized get
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.Awake(), UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.Awake(), UnityToolbox.Item.Management.ItemManagerWindow.InitializeWindow(), UnityToolbox.Item.Management.ItemManagerWindow.OnGUI(), and UnityToolbox.Item.ItemManager.SpawnItemInstance().
Instance
Itemizer UnityToolbox.Item.Management.Itemizer.Instance static get
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.Awake(), UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.Awake(), UnityToolbox.Item.ItemManager.Awake(), UnityToolbox.Item.Management.ItemManagerWindow.DisplayScopesTab(), UnityToolbox.Item.Management.ItemManagerWindow.DisplaySettingsTab(), UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemManagerWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), UnityToolbox.Item.Management.ItemManagerWindow.DrawCreationFields(), UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DrawListItems(), UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DrawListItems(), UnityToolbox.Item.Management.ItemManagerWindow.DrawListItems(), UnityToolbox.Item.Management.ItemManagerWindow.DrawListScopes(), UnityToolbox.Item.Management.ItemManagerWindow.FixFaultyItemsByGUID(), UnityToolbox.Item.Management.ItemDefinitionEditWindow.Init(), UnityToolbox.Item.Management.ItemManagerWindow.InitializeWindow(), UnityToolbox.Item.Management.ItemDefinitionErrorWindow.OnGUI(), UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.OnGUI(), UnityToolbox.Item.Management.ItemManagerWindow.OnGUI(), UnityToolbox.Item.Management.ItemScopeEditWindow.OnGUI(), and UnityToolbox.Item.ItemManager.SpawnItemInstance().
ItemDefinitions
HashSet<ItemDefinition> UnityToolbox.Item.Management.Itemizer.ItemDefinitions get
Referenced by UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DrawListItems(), UnityToolbox.Item.Management.ItemManagerWindow.DrawListItems(), and UnityToolbox.Item.ItemManager.SpawnItemInstance().
ItemScopes
HashSet<ItemScope> UnityToolbox.Item.Management.Itemizer.ItemScopes get
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemManagerWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), UnityToolbox.Item.Management.ItemManagerWindow.DrawCreationFields(), UnityToolbox.Item.Management.ItemManagerWindow.DrawListScopes(), and UnityToolbox.Item.Management.ItemDefinitionEditWindow.Init().
Event Documentation
OnItemDefinitionEdited
Action<ItemDefinition, ItemDefinition> UnityToolbox.Item.Management.Itemizer.OnItemDefinitionEdited
Referenced by UnityToolbox.Item.Management.Itemizer.ItemDefinitionEdited().
OnItemScopeEdited
Action<ItemScope, ItemScope> UnityToolbox.Item.Management.Itemizer.OnItemScopeEdited
Referenced by UnityToolbox.Item.Management.Itemizer.ItemScopeEdited().