UnityToolbox: AudioMixer Class Reference
AudioMixer Class Reference
A audio mixer which plays audio clips and with optional defined volume settings. See AudioVolumeSetter.
Public Member Functions
void PlayRandomSource ()
Plays a random sound from the defined list.
void FadePause ()
void FadeResume ()
Properties
bool IsPassive [get, set]
bool IsPlaying [get]
Private Member Functions
void Start ()
void Update ()
void FadeEnd ()
IEnumerator FadeIn (float value)
IEnumerator FadeOutPause ()
IEnumerator FadeOut ()
Private Attributes
bool _isPassive
bool _isPlaying
bool _fadeIn
bool _fadeOut
float _minDelayBetweenSounds
float _maxDelayBetweenSounds
List< AudioMixerItem > _items
bool _internalPause
float _totalProbability
List< Coroutine > _coroutines
float _timer
AudioSource _audioSource
Member Function Documentation
FadeEnd()
void AudioMixer.FadeEnd () private
References _audioSource, _coroutines, _fadeOut, and FadeOut().
Referenced by Update().
FadeIn()
IEnumerator AudioMixer.FadeIn (float value) private
References _audioSource.
Referenced by FadeResume().
FadeOut()
IEnumerator AudioMixer.FadeOut () private
References _audioSource.
Referenced by FadeEnd().
FadeOutPause()
IEnumerator AudioMixer.FadeOutPause () private
References _audioSource.
Referenced by FadePause().
FadePause()
void AudioMixer.FadePause ()
References _coroutines, _internalPause, and FadeOutPause().
FadeResume()
void AudioMixer.FadeResume ()
References _coroutines, _internalPause, FadeIn(), PlayerPrefKeys.GetPrefereceKey(), and PlayerPrefKeys.MUSIC_VOLUME.
Referenced by PlayRandomSource().
PlayRandomSource()
void AudioMixer.PlayRandomSource ()
References _audioSource, _fadeIn, _internalPause, _isPlaying, _items, _totalProbability, FadeResume(), and AudioMixerItem.Source.
Referenced by GotoMenuButton.OnPointerClick(), ToggleMenuButton.OnPointerClick(), MenuWheelNavButton.OnPointerClick(), RebindButton.OnPointerClick(), ResetButton.OnPointerClick(), GotoSceneButton.OnPointerDown(), QuitButton.OnPointerDown(), ResetSavegameButton.OnPointerDown(), ShowOnHover.OnPointerEnter(), SwapOnHover.OnPointerEnter(), TintImageOnHover.OnPointerEnter(), TintTextOnHover.OnPointerEnter(), RebindButton.SetKeyToControl(), Update(), and SliderSetting.UpdateValues().
Start()
void AudioMixer.Start () private
References _audioSource, _coroutines, _items, _totalProbability, AudioMixerItem.CountedProbability, and AudioMixerItem.Probability.
Update()
void AudioMixer.Update () private
References _audioSource, _internalPause, _isPassive, _isPlaying, _maxDelayBetweenSounds, _minDelayBetweenSounds, _timer, FadeEnd(), and PlayRandomSource().
Member Data Documentation
_audioSource
AudioSource AudioMixer._audioSource private
Referenced by FadeEnd(), FadeIn(), FadeOut(), FadeOutPause(), PlayRandomSource(), Start(), and Update().
_coroutines
List<Coroutine> AudioMixer._coroutines private
Referenced by FadeEnd(), FadePause(), FadeResume(), and Start().
_fadeIn
bool AudioMixer._fadeIn private
Referenced by PlayRandomSource().
_fadeOut
bool AudioMixer._fadeOut private
Referenced by FadeEnd().
_internalPause
bool AudioMixer._internalPause private
Referenced by FadePause(), FadeResume(), PlayRandomSource(), and Update().
_isPassive
bool AudioMixer._isPassive private
Referenced by Update().
_isPlaying
bool AudioMixer._isPlaying private
Referenced by PlayRandomSource(), and Update().
_items
List<AudioMixerItem> AudioMixer._items private
Referenced by PlayRandomSource(), and Start().
_maxDelayBetweenSounds
float AudioMixer._maxDelayBetweenSounds private
Referenced by Update().
_minDelayBetweenSounds
float AudioMixer._minDelayBetweenSounds private
Referenced by Update().
_timer
float AudioMixer._timer private
Referenced by Update().
_totalProbability
float AudioMixer._totalProbability private
Referenced by PlayRandomSource(), and Start().
Property Documentation
IsPassive
bool AudioMixer.IsPassive get set
IsPlaying
bool AudioMixer.IsPlaying get