UnityToolbox: Module Class Reference
Module Class Reference
The base of a module. Required if you want anything to be called from the ModuleManager.
Public Member Functions
virtual void Awake ()
Private Member Functions
IEnumerator WaitTillMasterSceneLoaded ()
void OnDestroy ()
Member Function Documentation
Awake()
virtual void Module.Awake () virtual
Reimplemented in InventoryManager, IDManager, SaveGameManager, PlayerPrefKeys, DialogManager, and LocalisationManager.
References ModuleManager.IsLoaded(), and WaitTillMasterSceneLoaded().
OnDestroy()
void Module.OnDestroy () private
WaitTillMasterSceneLoaded()
IEnumerator Module.WaitTillMasterSceneLoaded () private
References ModuleManager.IsLoaded().
Referenced by Awake().