UnityToolbox Documentation: HeldInventory Class Reference
HeldInventory Class Reference
Public Member Functions
override bool AddItem (Item item, int count)
override void RemoveItem (Item item, int count)
override void UpdateItem (Item old, Item updated)
override void RemoveItem (Item item)
abstract bool AddItem (Item item, int count)
abstract void RemoveItem (Item item, int count)
abstract void RemoveItem (Item item)
abstract void UpdateItem (Item old, Item updated)
Properties
Item ItemHeld [get]
int Count [get]
Properties inherited from InventoryBase
string ID [get]
Private Attributes
Item _itemHeld
int _count
Member Function Documentation
AddItem()
override bool HeldInventory.AddItem (Item item, int count) virtual
Implements InventoryBase.
References _count, _itemHeld, and Item.Equals().
Referenced by HeldInventoryManager.ManageInventorys(), and UpdateItem().
RemoveItem() [1/2]
override void HeldInventory.RemoveItem (Item item) virtual
Implements InventoryBase.
References _count, and _itemHeld.
RemoveItem() [2/2]
override void HeldInventory.RemoveItem (Item item, int count) virtual
Implements InventoryBase.
References _count, _itemHeld, Item.Equals(), and Item.Inventory.
Referenced by HeldInventoryManager.ManageInventorys(), HeldInventoryManager.Update(), and UpdateItem().
UpdateItem()
override void HeldInventory.UpdateItem (Item old, Item updated) virtual
Implements InventoryBase.
References _itemHeld, AddItem(), Item.Equals(), and RemoveItem().
Member Data Documentation
_count
int HeldInventory._count private
Referenced by AddItem(), and RemoveItem().
_itemHeld
Item HeldInventory._itemHeld private
Referenced by AddItem(), RemoveItem(), and UpdateItem().
Property Documentation
Count
int HeldInventory.Count get
Referenced by HeldInventoryManager.ManageInventorys(), and HeldInventoryManager.Update().
ItemHeld
Item HeldInventory.ItemHeld get
Referenced by HeldInventoryManager.ManageInventorys(), and HeldInventoryManager.Update().