UnityToolbox: GamestateGraphPathSelectionWindow Class Reference
GamestateGraphPathSelectionWindow Class Reference
Static Public Member Functions
static void Open (GamestateGraphWindow graph)
Properties
GamestateGraphWindow Graph [set]
Private Member Functions
void OnEnable ()
void OnGUI ()
void DisplaySetting ()
Private Attributes
string _assetPathInProject
string _status
GamestateGraphWindow _graph
Member Function Documentation
DisplaySetting()
void GamestateGraphPathSelectionWindow.DisplaySetting () private
References _assetPathInProject, _graph, _status, ResourcesUtil.TrySetValidPath(), and GamestateGraphWindow.UpdateData().
Referenced by OnGUI().
OnEnable()
void GamestateGraphPathSelectionWindow.OnEnable () private
References _assetPathInProject, and ProjectPrefs.GetString().
OnGUI()
void GamestateGraphPathSelectionWindow.OnGUI () private
References DisplaySetting().
Open()
static void GamestateGraphPathSelectionWindow.Open (GamestateGraphWindow graph) static
Referenced by GamestateGraphWindow.OnEnable().
Member Data Documentation
_assetPathInProject
string GamestateGraphPathSelectionWindow._assetPathInProject private
Referenced by DisplaySetting(), and OnEnable().
_graph
GamestateGraphWindow GamestateGraphPathSelectionWindow._graph private
Referenced by DisplaySetting().
_status
string GamestateGraphPathSelectionWindow._status private
Referenced by DisplaySetting().
Property Documentation
Graph
GamestateGraphWindow GamestateGraphPathSelectionWindow.Graph set