UnityToolbox Documentation: Localizer Class Reference
Localizer Class Reference
The heart of the localisation system. Every localisation, its serialisation and editing is managed here.
Public Member Functions
bool AddLocalisation (LocalisationID localisationID, Dictionary< LocalisationLanguage, string > localisations)
Adds a new localisation to the system.
bool AddScope (string scopeName)
Adds a new LocalisationScope to the system.
bool AddLanguage (string languageName, string languageShortName)
Adds a new LocalisationLanguage to the system.
void RemoveLanguage (LocalisationLanguage language)
Removes a LocalisationLanguage from the system.
void RemoveScope (LocalisationScope scope)
Removes a LocalisationScope from the system.
void RemoveLocalisation (LocalisationID localisationID)
Removes a localisation, that is a LocalisationID with all its content, from the system.
bool EditLocalisationID (LocalisationID oldID, LocalisationID newID)
Edits an existing LocalisationID by replacing the IDs, but keeping its content.
bool EditScope (LocalisationScope oldScope, string newScopeName)
Replaces a LocalisationScope with a new one for all available data.
bool EditLanguage (LocalisationLanguage oldLanguage, string newLanguageName, string newLanguageShortName)
Replaces a LocalisationLanguage with a new one for all available data.
bool EditLocalisation (LocalisationID localisationID, Dictionary< LocalisationLanguage, string > localisations)
Edits a given localisation found by the LocalisationID by replacing the current content with localisations .
void WriteData ()
Writes the data to disk. For this to work, a valid path within the project must be setup.
void Initialize ()
Initializes the Localizer. This is required due to its dependency on a valid path.
Public Attributes
Action< LocalisationScope > ScopeEdited
Action< LocalisationLanguage > LanguageEdited
Action< LocalisationID > LocalisationIDEdited
Properties
string AssetPathInProject [set]
static Localizer Instance [get]
Dictionary< LocalisationID, Dictionary< LocalisationLanguage, string > > LocalisationData [get]
HashSet< LocalisationLanguage > LocalisationLanguages [get]
HashSet< LocalisationScope > LocalisationScopes [get]
LocalisationScope DefaultScope [get]
bool IsInitialized [get]
Private Member Functions
void OnScopeEdited (LocalisationScope oldScope)
Callback for when a LocalisationScope is edited or removed.
void OnLanguageEdited (LocalisationLanguage oldLanguage)
Callback for when a LocalisationLanguage is edited or removed.
void OnLocalisationEdited (LocalisationID oldLocalisationID)
Callback for when a LocalisationID is edited or removed.
Private Attributes
string _assetPathInProject
Dictionary< LocalisationID, Dictionary< LocalisationLanguage, string > > _localisationData
HashSet< LocalisationLanguage > _localisationLanguages
HashSet< LocalisationScope > _localisationScopes
LocalisationScope _defaultScope
readonly string _dataPath = "/LocalisationData.dat"
readonly string _languagesDataPath = "/LocalisationLanguages.dat"
readonly string _scopesDataPath = "/LocalisationScopes.dat"
bool _isInitialized
JsonSerializerSettings _settings
Static Private Attributes
static Localizer _instance
Member Function Documentation
AddLanguage()
bool Localizer.AddLanguage (string languageName, string languageShortName)
Parameters
languageName
languageShortName
Returns
References _isInitialized, _localisationLanguages, and Initialize().
Referenced by LocalisationManagerWindow.DisplayLanguagesTab().
AddLocalisation()
bool Localizer.AddLocalisation (LocalisationID localisationID, Dictionary< LocalisationLanguage, string > localisations)
Parameters
localisationID
localisations
Returns
References _isInitialized, _localisationData, _localisationLanguages, Initialize(), and LocalisationLanguage.Name.
Referenced by LocalisationManagerWindow.DisplayIDsTab().
AddScope()
bool Localizer.AddScope (string scopeName)
Parameters
scopeName
Returns
References _defaultScope, _isInitialized, _localisationScopes, LocalisationScope.Equals(), and Initialize().
Referenced by LocalisationManagerWindow.DisplayScopesTab().
EditLanguage()
bool Localizer.EditLanguage (LocalisationLanguage oldLanguage, string newLanguageName, string newLanguageShortName)
Parameters
oldLanguage
newLanguageName
newLanguageShortName
Returns
References _isInitialized, _localisationData, _localisationLanguages, Initialize(), and OnLanguageEdited().
Referenced by LocalisationEditLanguageWindow.OnGUI().
EditLocalisation()
bool Localizer.EditLocalisation (LocalisationID localisationID, Dictionary< LocalisationLanguage, string > localisations)
Parameters
localisationID
localisations
Returns
References _isInitialized, _localisationData, _localisationLanguages, Initialize(), LocalisationLanguage.Name, and OnLocalisationEdited().
Referenced by LocalisationEditIDWindow.OnGUI().
EditLocalisationID()
bool Localizer.EditLocalisationID (LocalisationID oldID, LocalisationID newID)
Parameters
oldID
newID
Returns
References _isInitialized, _localisationData, Initialize(), and OnLocalisationEdited().
Referenced by LocalisationEditIDWindow.OnGUI().
EditScope()
bool Localizer.EditScope (LocalisationScope oldScope, string newScopeName)
Parameters
oldScope
newScopeName
Returns
References _defaultScope, _isInitialized, _localisationData, _localisationScopes, LocalisationScope.Equals(), Initialize(), LocalisationScope.Name, and OnScopeEdited().
Referenced by LocalisationEditScopeWindow.OnGUI().
Initialize()
void Localizer.Initialize ()
References _assetPathInProject, _dataPath, _defaultScope, _isInitialized, _languagesDataPath, _localisationData, _localisationLanguages, _localisationScopes, _scopesDataPath, and _settings.
Referenced by AddLanguage(), AddLocalisation(), AddScope(), LocalisationManagerWindow.DisplaySettingsTab(), EditLanguage(), EditLocalisation(), EditLocalisationID(), EditScope(), LocalisationManagerWindow.InitializeWindow(), LocalisationSelectionWindow.InitializeWindow(), LocalizedText.OnValidate(), RemoveLanguage(), RemoveLocalisation(), RemoveScope(), LanguageSetting.Start(), LocalizedText.Start(), and WriteData().
OnLanguageEdited()
void Localizer.OnLanguageEdited (LocalisationLanguage oldLanguage) private
Parameters
oldLanguage
References LanguageEdited.
Referenced by EditLanguage(), and RemoveLanguage().
OnLocalisationEdited()
void Localizer.OnLocalisationEdited (LocalisationID oldLocalisationID) private
Parameters
oldLocalisationID
References LocalisationIDEdited.
Referenced by EditLocalisation(), EditLocalisationID(), and RemoveLocalisation().
OnScopeEdited()
void Localizer.OnScopeEdited (LocalisationScope oldScope) private
Parameters
oldScope
References ScopeEdited.
Referenced by EditScope(), and RemoveScope().
RemoveLanguage()
void Localizer.RemoveLanguage (LocalisationLanguage language)
Parameters
language
References _isInitialized, _localisationData, _localisationLanguages, Initialize(), and OnLanguageEdited().
Referenced by LocalisationManagerWindow.DisplayLanguagesTab().
RemoveLocalisation()
void Localizer.RemoveLocalisation (LocalisationID localisationID)
Parameters
localisationID
References _isInitialized, _localisationData, Initialize(), and OnLocalisationEdited().
Referenced by LocalisationManagerWindow.DisplayIDsTab(), and LocalisationSelectionWindow.OnGUI().
RemoveScope()
void Localizer.RemoveScope (LocalisationScope scope)
Parameters
scope
References _defaultScope, _isInitialized, _localisationData, _localisationScopes, LocalisationScope.Equals(), Initialize(), LocalisationScope.Name, and OnScopeEdited().
Referenced by LocalisationManagerWindow.DisplayScopesTab().
WriteData()
void Localizer.WriteData ()
References _assetPathInProject, _dataPath, _isInitialized, _languagesDataPath, _localisationData, _localisationLanguages, _localisationScopes, _scopesDataPath, _settings, and Initialize().
Referenced by LocalisationManagerWindow.DisplayIDsTab(), LocalisationManagerWindow.DisplayLanguagesTab(), LocalisationManagerWindow.DisplayScopesTab(), LocalisationEditIDWindow.OnGUI(), LocalisationEditLanguageWindow.OnGUI(), LocalisationEditScopeWindow.OnGUI(), and LocalisationSelectionWindow.OnGUI().
Member Data Documentation
_assetPathInProject
string Localizer._assetPathInProject private
Referenced by Initialize(), and WriteData().
_dataPath
readonly string Localizer._dataPath = "/LocalisationData.dat" private
Referenced by Initialize(), and WriteData().
_defaultScope
LocalisationScope Localizer._defaultScope private
Referenced by AddScope(), EditScope(), Initialize(), and RemoveScope().
_instance
Localizer Localizer._instance static private
_isInitialized
bool Localizer._isInitialized private
Referenced by AddLanguage(), AddLocalisation(), AddScope(), EditLanguage(), EditLocalisation(), EditLocalisationID(), EditScope(), Initialize(), RemoveLanguage(), RemoveLocalisation(), RemoveScope(), and WriteData().
_languagesDataPath
readonly string Localizer._languagesDataPath = "/LocalisationLanguages.dat" private
Referenced by Initialize(), and WriteData().
_localisationData
Dictionary<LocalisationID, Dictionary<LocalisationLanguage, string> > Localizer._localisationData private
Referenced by AddLocalisation(), EditLanguage(), EditLocalisation(), EditLocalisationID(), EditScope(), Initialize(), RemoveLanguage(), RemoveLocalisation(), RemoveScope(), and WriteData().
_localisationLanguages
HashSet<LocalisationLanguage> Localizer._localisationLanguages private
Referenced by AddLanguage(), AddLocalisation(), EditLanguage(), EditLocalisation(), Initialize(), RemoveLanguage(), and WriteData().
_localisationScopes
HashSet<LocalisationScope> Localizer._localisationScopes private
Referenced by AddScope(), EditScope(), Initialize(), RemoveScope(), and WriteData().
_scopesDataPath
readonly string Localizer._scopesDataPath = "/LocalisationScopes.dat" private
Referenced by Initialize(), and WriteData().
_settings
JsonSerializerSettings Localizer._settings private
Referenced by Initialize(), and WriteData().
LanguageEdited
Action<LocalisationLanguage> Localizer.LanguageEdited
Referenced by OnLanguageEdited().
LocalisationIDEdited
Action<LocalisationID> Localizer.LocalisationIDEdited
Referenced by OnLocalisationEdited().
ScopeEdited
Action<LocalisationScope> Localizer.ScopeEdited
Referenced by OnScopeEdited().
Property Documentation
AssetPathInProject
string Localizer.AssetPathInProject set
DefaultScope
LocalisationScope Localizer.DefaultScope get
Referenced by LocalisationManagerWindow.DisplayScopesTab().
Instance
Localizer Localizer.Instance static get
Referenced by LocalisationManagerWindow.DisplayIDsTab(), LocalisationManagerWindow.DisplayLanguagesTab(), LocalisationManagerWindow.DisplayScopesTab(), LocalisationManagerWindow.DisplaySettingsTab(), LocalisationManagerWindow.InitializeWindow(), LocalisationSelectionWindow.InitializeWindow(), LocalisationEditIDWindow.OnGUI(), LocalisationEditLanguageWindow.OnGUI(), LocalisationEditScopeWindow.OnGUI(), LocalisationManagerWindow.OnGUI(), LocalisationSelectionWindow.OnGUI(), LocalizedText.OnValidate(), LanguageSetting.Start(), LocalizedText.Start(), and LocalizedText.UpdateText().
IsInitialized
bool Localizer.IsInitialized get
Referenced by LocalisationManagerWindow.DisplaySettingsTab(), LocalisationManagerWindow.OnGUI(), LocalizedText.OnValidate(), LanguageSetting.Start(), and LocalizedText.Start().
LocalisationData
Dictionary<LocalisationID, Dictionary<LocalisationLanguage, string> > Localizer.LocalisationData get
Referenced by LocalisationManagerWindow.DisplayIDsTab(), LocalisationSelectionWindow.OnGUI(), and LocalizedText.UpdateText().
LocalisationLanguages
HashSet<LocalisationLanguage> Localizer.LocalisationLanguages get
Referenced by LocalisationManagerWindow.DisplayIDsTab(), LocalisationManagerWindow.DisplayLanguagesTab(), LocalisationEditIDWindow.OnGUI(), LocalisationSelectionWindow.OnGUI(), LocalizedText.OnValidate(), LanguageSetting.Start(), and LocalizedText.Start().
LocalisationScopes
HashSet<LocalisationScope> Localizer.LocalisationScopes get
Referenced by LocalisationManagerWindow.DisplayIDsTab(), LocalisationManagerWindow.DisplayScopesTab(), and LocalisationEditIDWindow.OnGUI().