UnityToolbox: DisplayDialog Class Reference
DisplayDialog Class Reference
Displays all relevant data on a canvas as soon as a dialog is triggered. Requires DialogManager and UIEventManager to work.
Public Member Functions
void UpdateDialog (DialogNodeData currentNode)
Updates the UI elements to the information given by the currentNode .
Private Member Functions
void Awake ()
void OnDestroy ()
void OnValidate ()
Private Attributes
Text _title
Text _description
Image _spriteToShow
List< Text > _options
int _menuType
List< string > MenuTypes
Member Function Documentation
Awake()
void DisplayDialog.Awake () private
References UpdateDialog().
OnDestroy()
void DisplayDialog.OnDestroy () private
References UpdateDialog().
OnValidate()
void DisplayDialog.OnValidate () private
References MenuTypes, and MenuManager.MenuTypesForEditor.
UpdateDialog()
void DisplayDialog.UpdateDialog (DialogNodeData currentNode)
Parameters
currentNode
References _description, _menuType, _options, _spriteToShow, _title, DialogNodeData.Avatar, DialogNodeData.Options, DialogNodeData.Text, and DialogNodeData.Title.
Referenced by Awake(), and OnDestroy().
Member Data Documentation
_description
Text DisplayDialog._description private
Referenced by UpdateDialog().
_menuType
int DisplayDialog._menuType private
Referenced by UpdateDialog().
_options
List<Text> DisplayDialog._options private
Referenced by UpdateDialog().
_spriteToShow
Image DisplayDialog._spriteToShow private
Referenced by UpdateDialog().
_title
Text DisplayDialog._title private
Referenced by UpdateDialog().
MenuTypes
List<string> DisplayDialog.MenuTypes private
Referenced by OnValidate().