UnityToolbox: TriggerDetection Class Reference
TriggerDetection Class Reference abstract
This script is used for interactions with objects with optional tooltips.
Public Member Functions
void Start ()
void Update ()
abstract void OnInteraction (GameObject foundObject)
Execute whatever should happen when the trigger found a valid object to interact with.
Protected Attributes
string _tooltip
string _appendedTooltip
string _interactActionName
PlayerInput _input
bool _tooltipEnabled
Whether the tooltip module should be used to display text.
bool _isBinding
Member Function Documentation
OnInteraction()
abstract void TriggerDetection.OnInteraction (GameObject foundObject) pure virtual
Parameters
foundObject The trigger data.
Referenced by Update().
Start()
void TriggerDetection.Start ()
References _isBinding, and _tooltipEnabled.
Update()
void TriggerDetection.Update ()
References _appendedTooltip, _input, _interactActionName, _isBinding, _tooltip, _tooltipEnabled, SettingsManager.CurrentValueOfControl(), ColliderInfo.GetAllCollisions2D(), and OnInteraction().
Member Data Documentation
_appendedTooltip
string TriggerDetection._appendedTooltip protected
Referenced by Update().
_input
PlayerInput TriggerDetection._input protected
Referenced by Update().
_interactActionName
string TriggerDetection._interactActionName protected
Referenced by Update().
_isBinding
bool TriggerDetection._isBinding protected
Referenced by Start(), and Update().
_tooltip
string TriggerDetection._tooltip protected
Referenced by Update().
_tooltipEnabled
bool TriggerDetection._tooltipEnabled protected
Referenced by Start(), and Update().