UnityToolbox: GamestateGraphWindow Class Reference
GamestateGraphWindow Class Reference
Public Member Functions
void UpdateData ()
Static Public Member Functions
static void Open ()
Private Member Functions
void AddGraphView ()
void WriteData ()
void OnAfterAssemblyReload ()
void OnDestroy ()
void OnEnable ()
void OnDisable ()
Private Attributes
GamestateGraphView _graphView
Static Private Attributes
const string FILENAME = "GamestateData.txt"
Member Function Documentation
AddGraphView()
void GamestateGraphWindow.AddGraphView () private
References _graphView.
Referenced by OnEnable().
OnAfterAssemblyReload()
void GamestateGraphWindow.OnAfterAssemblyReload () private
References UpdateData().
Referenced by OnDisable(), and OnEnable().
OnDestroy()
void GamestateGraphWindow.OnDestroy () private
References WriteData().
OnDisable()
void GamestateGraphWindow.OnDisable () private
References OnAfterAssemblyReload().
OnEnable()
void GamestateGraphWindow.OnEnable () private
References AddGraphView(), FILENAME, ProjectPrefs.GetString(), OnAfterAssemblyReload(), GamestateGraphPathSelectionWindow.Open(), and UpdateData().
Referenced by Open().
Open()
static void GamestateGraphWindow.Open () static
References OnEnable().
UpdateData()
void GamestateGraphWindow.UpdateData ()
References _graphView, GamestateGraphView.AddNode(), FILENAME, and GamestateNode.InputPort.
Referenced by GamestateGraphPathSelectionWindow.DisplaySetting(), OnAfterAssemblyReload(), and OnEnable().
WriteData()
void GamestateGraphWindow.WriteData () private
References _graphView, FILENAME, GamestateNode.GamestateName, ResourcesUtil.GetLocalPath(), GamestateNode.ID, GamestateNode.InputIDs, GamestateNode.OutputIDs, GamestateNode.UpdateValues(), and ResourcesUtil.WriteFile().
Referenced by OnDestroy().
Member Data Documentation
_graphView
GamestateGraphView GamestateGraphWindow._graphView private
Referenced by AddGraphView(), UpdateData(), and WriteData().
FILENAME
const string GamestateGraphWindow.FILENAME = "GamestateData.txt" static private
Referenced by OnEnable(), UpdateData(), and WriteData().