UnityToolbox: Item.Management.ItemScope Class Reference
Item.Management.ItemScope Class Reference
The scope which is used to indentify and serialize item data.
Public Member Functions
override bool Equals (object obj)
Overriden to disregard the reference and check for an equal name.
override int GetHashCode ()
Overriden to disregard the reference and check for an equal name.
Public Attributes
string Name
Member Function Documentation
Equals()
override bool Item.Management.ItemScope.Equals (object obj)
Parameters
obj
Returns
References Item.Management.ItemScope.Name.
Referenced by Item.Management.ItemManagerWindow.DrawListScopes(), Item.Management.Itemizer.EditItemScope(), Item.Management.ItemDefinitionEditWindow.Init(), Item.Management.Itemizer.RemoveItemScope(), and Item.Management.ItemScopeEditWindow.ScopeEdited().
GetHashCode()
override int Item.Management.ItemScope.GetHashCode ()
Returns
References Item.Management.ItemScope.Name.
Member Data Documentation
Name
string Item.Management.ItemScope.Name
Referenced by Item.Management.ItemManagerWindow.DrawListScopes(), Item.Management.Itemizer.EditItemScope(), Item.Management.ItemScope.Equals(), Item.Management.ItemScope.GetHashCode(), Item.Management.ItemDefinitionDrawer.OnGUI(), and Item.Management.Itemizer.RemoveItemScope().