UnityToolbox: RebindButton Class Reference
RebindButton Class Reference
A script which is placed on a UI element and acts as a button. It will rebind key controls. It requires the UIEventManager and the SettingsManager, as well information about the ActionName and the Control (e.g. "Character Move" & "left"). The control can be left empty if no information is necessary. (e.g. "Character Jump" & "")
Public Member Functions
void Awake ()
void OnGUI ()
void OnPointerClick (PointerEventData eventData)
Private Member Functions
void Start ()
void SetKeyToControl (string key, string keyOrMouseCode)
IEnumerator ResetText ()
IEnumerator SetEvent ()
string ReturnKeyCode (string path)
Private Attributes
AudioMixer _clickSounds
AudioMixer _errorSounds
string _control
string _actionName
string _keyPress
bool _isKeyboard
bool _isSetting
string _alternateText
Text _textChild
bool _otherIsSetting
SettingsManager _manager
bool _isEnabled
Member Function Documentation
Awake()
void RebindButton.Awake ()
References _isEnabled.
OnGUI()
void RebindButton.OnGUI ()
References _actionName, _alternateText, _control, _isKeyboard, _keyPress, _manager, SettingsManager.CurrentValueOfControl(), and ReturnKeyCode().
OnPointerClick()
void RebindButton.OnPointerClick (PointerEventData eventData)
References _clickSounds, _isEnabled, _isSetting, _otherIsSetting, AudioMixer.PlayRandomSource(), and SetEvent().
ResetText()
IEnumerator RebindButton.ResetText () private
References _alternateText.
Referenced by SetKeyToControl().
ReturnKeyCode()
string RebindButton.ReturnKeyCode (string path) private
Referenced by OnGUI().
SetEvent()
IEnumerator RebindButton.SetEvent () private
References _isKeyboard, _isSetting, _keyPress, and SetKeyToControl().
Referenced by OnPointerClick().
SetKeyToControl()
void RebindButton.SetKeyToControl (string key, string keyOrMouseCode) private
References _actionName, _alternateText, _control, _errorSounds, _manager, AudioMixer.PlayRandomSource(), ResetText(), and SettingsManager.SetKey().
Referenced by SetEvent().
Start()
void RebindButton.Start () private
References _alternateText, _manager, _otherIsSetting, and _textChild.
Member Data Documentation
_actionName
string RebindButton._actionName private
Referenced by OnGUI(), and SetKeyToControl().
_alternateText
string RebindButton._alternateText private
Referenced by OnGUI(), ResetText(), SetKeyToControl(), and Start().
_clickSounds
AudioMixer RebindButton._clickSounds private
Referenced by OnPointerClick().
_control
string RebindButton._control private
Referenced by OnGUI(), and SetKeyToControl().
_errorSounds
AudioMixer RebindButton._errorSounds private
Referenced by SetKeyToControl().
_isEnabled
bool RebindButton._isEnabled private
Referenced by Awake(), and OnPointerClick().
_isKeyboard
bool RebindButton._isKeyboard private
Referenced by OnGUI(), and SetEvent().
_isSetting
bool RebindButton._isSetting private
Referenced by OnPointerClick(), and SetEvent().
_keyPress
string RebindButton._keyPress private
Referenced by OnGUI(), and SetEvent().
_manager
SettingsManager RebindButton._manager private
Referenced by OnGUI(), SetKeyToControl(), and Start().
_otherIsSetting
bool RebindButton._otherIsSetting private
Referenced by OnPointerClick(), and Start().
_textChild
Text RebindButton._textChild private
Referenced by Start().