UnityToolbox: Item.Management.ItemScopeEditWindow Class Reference
Item.Management.ItemScopeEditWindow Class Reference
Public Member Functions
void OnGUI ()
Static Public Member Functions
static void Open (ItemScope scope)
Properties
ItemScope Scope [set]
Private Member Functions
void Awake ()
void ScopeEdited (ItemScope scope, ItemScope newScope)
void DrawLineHorizontal ()
void UpdateStatus (string status)
Private Attributes
ItemScope _scope
string _newScopeName
string _status
Member Function Documentation
Awake()
void Item.Management.ItemScopeEditWindow.Awake () private
References Item.Management.ItemScopeEditWindow.ScopeEdited(), and Item.Management.ItemScopeEditWindow.UpdateStatus().
DrawLineHorizontal()
void Item.Management.ItemScopeEditWindow.DrawLineHorizontal () private
Referenced by Item.Management.ItemScopeEditWindow.OnGUI().
OnGUI()
void Item.Management.ItemScopeEditWindow.OnGUI ()
References Item.Management.ItemScopeEditWindow._newScopeName, Item.Management.ItemScopeEditWindow._scope, Item.Management.ItemScopeEditWindow._status, Item.Management.ItemScopeEditWindow.DrawLineHorizontal(), Item.Management.Itemizer.EditItemScope(), Item.Management.Itemizer.Instance, Item.Management.ItemScopeEditWindow.ScopeEdited(), Item.Management.ItemScopeEditWindow.UpdateStatus(), and Item.Management.Itemizer.WriteData().
Open()
static void Item.Management.ItemScopeEditWindow.Open (ItemScope scope) static
Referenced by Item.Management.ItemManagerWindow.DrawListScopes().
ScopeEdited()
void Item.Management.ItemScopeEditWindow.ScopeEdited (ItemScope scope, ItemScope newScope) private
References Item.Management.ItemScopeEditWindow._scope, Item.Management.ItemScope.Equals(), and Item.Management.ItemScopeEditWindow.ScopeEdited().
Referenced by Item.Management.ItemScopeEditWindow.Awake(), Item.Management.ItemScopeEditWindow.OnGUI(), and Item.Management.ItemScopeEditWindow.ScopeEdited().
UpdateStatus()
void Item.Management.ItemScopeEditWindow.UpdateStatus (string status) private
References Item.Management.ItemScopeEditWindow._status.
Referenced by Item.Management.ItemScopeEditWindow.Awake(), and Item.Management.ItemScopeEditWindow.OnGUI().
Member Data Documentation
_newScopeName
string Item.Management.ItemScopeEditWindow._newScopeName private
Referenced by Item.Management.ItemScopeEditWindow.OnGUI().
_scope
ItemScope Item.Management.ItemScopeEditWindow._scope private
Referenced by Item.Management.ItemScopeEditWindow.OnGUI(), and Item.Management.ItemScopeEditWindow.ScopeEdited().
_status
string Item.Management.ItemScopeEditWindow._status private
Referenced by Item.Management.ItemScopeEditWindow.OnGUI(), and Item.Management.ItemScopeEditWindow.UpdateStatus().
Property Documentation
Scope
ItemScope Item.Management.ItemScopeEditWindow.Scope set