UnityToolbox: Item.Management.Itemizer Class Reference
Item.Management.Itemizer Class Reference
The core of the item managment system. It takes care of the (de)serialization and changes to all data.
Public Member Functions
bool Initialize ()
Tries to initialize the Itemizer.
ItemDefinition AddItemDefinition (ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath)
Creates a new item definition and adds it to the mangement.
T AddInheritedItemDefinition< T > (ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, HashSet< ItemField > itemFields)
Creates a new item inheriting ItemDefinition and adds it to the mangement.
void RemoveItemDefinition (ItemDefinition itemDefinition)
Removes an ItemDefinition from the mangement.
void EditInheritedItemDefinition< T > (ItemDefinition itemDefinition, ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, HashSet< ItemField > itemFields)
Edits a given item inheriting ItemDefinition and replaces the old within the mangement.
void EditItemDefinition (ItemDefinition itemDefinition, ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath)
Edits a given ItemDefinition and replaces the old within the mangement.
ItemScope AddItemScope (string name)
Adds a new ItemScope by a given unique name.
void RemoveItemScope (ItemScope scope)
Removes a given ItemScope. Replaces the given scope used for the ItemDefinition with the DefaultScope.
void EditItemScope (ItemScope scope, string name)
Edits a given ItemScope and replaces the old.
List< Type > GetAllInheritedItemDefinitionTypes ()
Checks the assembly for all classes inheriting ItemDefinition.
void WriteData ()
Writes all data to the set resources folder.
void ItemScopeEdited (ItemScope oldScope, ItemScope newScope)
Invokes the OnItemScopeEdited action.
void ItemDefinitionEdited (ItemDefinition oldItemDefinition, ItemDefinition newItemDefinition)
Invokes the OnItemDefinitionEdited action.
Properties
static Itemizer Instance [get]
The singleton instance of the Itemizer.
bool Initialized [get]
Is the itemizer initialized? If not, it cannot be used.
HashSet< ItemDefinition > ItemDefinitions [get]
All defined items.
HashSet< ItemScope > ItemScopes [get]
All defined item scopes.
ItemScope DefaultScope [get]
The defaulte scope, set by default and is the replacement for deleted scopes.
Events
Action< ItemScope, ItemScope > OnItemScopeEdited
Action< ItemDefinition, ItemDefinition > OnItemDefinitionEdited
Private Member Functions
Itemizer ()
Usage forbidden as the Itemizer.Instance should be used.
void InternalRemoveItemDefinition (ItemDefinition itemDefinition)
void CheckInitialized ()
void ReadDataLocally ()
HashSet< ItemDefinition > ReadItemData ()
HashSet< ItemScope > ReadItemScopes ()
Private Attributes
bool _initialized
string FILENAMEITEMS = "ItemData.txt"
string FILENAMESCOPES = "ItemScopeData.txt"
HashSet< ItemDefinition > _itemDefinitions
HashSet< ItemScope > _itemScopes
ItemScope _defaultScope
Static Private Attributes
static Itemizer _instance
Constructor & Destructor Documentation
Itemizer()
Item.Management.Itemizer.Itemizer () private
Member Function Documentation
AddInheritedItemDefinition< T >()
T Item.Management.Itemizer.AddInheritedItemDefinition< T > (ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, HashSet< ItemField > itemFields)
Template Parameters
T A type which inherits ItemDefinition.
Parameters
scope The scope of the definition."/></param> <param name="name">The name of the definition. Has to be unique in combination with the scope.</param> <param name="maxStackCount">How high this item can be stacked.</param> <param name="resourceIconPath">The path to where the icon can be found. Has to be a resources path.</param> <param name="resourcePrefabPath">The path to where the prefab can be found. Has to be a resources path.</param> <param name="itemFields">All additional field values defined for type <typeparamref name="T"/>.</param> <returns>The created <see cref="ItemDefinition"/>.</returns> <exception cref="ArgumentException">
Type Constraints
T : ItemDefinition
References Item.Management.Itemizer._itemDefinitions, Item.Management.Itemizer._itemScopes, Item.Management.Itemizer.CheckInitialized(), Item.Management.ItemField.FieldName, Item.Management.ItemField.FieldType, and Item.Management.ItemField.GetValue().
Referenced by Item.Management.Itemizer.EditInheritedItemDefinition< T >().
AddItemDefinition()
ItemDefinition Item.Management.Itemizer.AddItemDefinition (ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath)
Parameters
scope The scope of the definition."/></param> <param name="name">The name of the definition. Has to be unique in combination with the scope.</param> <param name="maxStackCount">How high this item can be stacked.</param> <param name="resourceIconPath">The path to where the icon can be found. Has to be a resources path.</param> <param name="resourcePrefabPath">The path to where the prefab can be found. Has to be a resources path.</param> <returns>The created <see cref="ItemDefinition"/>.</returns> <exception cref="ArgumentException">
References Item.Management.Itemizer._itemDefinitions, Item.Management.Itemizer._itemScopes, Item.Management.Itemizer.CheckInitialized(), and Item.ItemDefinition.GetQualifiedName().
Referenced by Item.Management.ItemManagerWindow.DrawAddDefinedItem(), Item.Management.Itemizer.EditItemDefinition(), Item.Management.Itemizer.EditItemScope(), and Item.Management.Itemizer.RemoveItemScope().
AddItemScope()
ItemScope Item.Management.Itemizer.AddItemScope (string name)
Parameters
name The unique name of the scope to create.
Returns
The created ItemScope.
Exceptions
ArgumentException
References Item.Management.Itemizer._itemScopes, and Item.Management.Itemizer.CheckInitialized().
Referenced by Item.Management.ItemManagerWindow.DisplayScopesTab(), and Item.Management.Itemizer.EditItemScope().
CheckInitialized()
void Item.Management.Itemizer.CheckInitialized () private
References Item.Management.Itemizer._initialized, and Item.Management.Itemizer.Initialize().
Referenced by Item.Management.Itemizer.AddInheritedItemDefinition< T >(), Item.Management.Itemizer.AddItemDefinition(), Item.Management.Itemizer.AddItemScope(), Item.Management.Itemizer.EditItemScope(), Item.Management.Itemizer.InternalRemoveItemDefinition(), Item.Management.Itemizer.RemoveItemDefinition(), and Item.Management.Itemizer.RemoveItemScope().
EditInheritedItemDefinition< T >()
void Item.Management.Itemizer.EditInheritedItemDefinition< T > (ItemDefinition itemDefinition, ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, HashSet< ItemField > itemFields)
Template Parameters
T A type which inherits ItemDefinition.
Parameters
itemDefinition The ItemDefinition to be edited.
scope The new scope of the definition."/></param> <param name="name">The new name of the definition. Has to be unique in combination with the scope.</param> <param name="maxStackCount">How high this item can be stacked.</param> <param name="resourceIconPath">The new path to where the icon can be found. Has to be a resources path.</param> <param name="resourcePrefabPath">The new path to where the prefab can be found. Has to be a resources path.</param> <param name="itemFields">All additional new field values defined for type <typeparamref name="T"/>.</param> <returns>The created <see cref="ItemDefinition"/>.</returns> <exception cref="ArgumentException">
Type Constraints
T : ItemDefinition
References Item.Management.Itemizer._itemDefinitions, Item.Management.Itemizer.AddInheritedItemDefinition< T >(), Item.Management.Itemizer.InternalRemoveItemDefinition(), and Item.Management.Itemizer.ItemDefinitionEdited().
EditItemDefinition()
void Item.Management.Itemizer.EditItemDefinition (ItemDefinition itemDefinition, ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath)
Parameters
itemDefinition The ItemDefinition to be edited.
scope The new scope of the definition."/></param> <param name="name">The new name of the definition. Has to be unique in combination with the scope.</param> <param name="maxStackCount">How high this item can be stacked.</param> <param name="resourceIconPath">The new path to where the icon can be found. Has to be a resources path.</param> <param name="resourcePrefabPath">The new path to where the prefab can be found. Has to be a resources path.</param> <returns>The created <see cref="ItemDefinition"/>.</returns> <exception cref="ArgumentException">
References Item.Management.Itemizer._itemDefinitions, Item.Management.Itemizer.AddItemDefinition(), Item.Management.Itemizer.InternalRemoveItemDefinition(), and Item.Management.Itemizer.ItemDefinitionEdited().
Referenced by Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem().
EditItemScope()
void Item.Management.Itemizer.EditItemScope (ItemScope scope, string name)
Parameters
scope The ItemScope to edit.
name The new unique name of the scope.
Exceptions
ArgumentException
References Item.Management.Itemizer._defaultScope, Item.Management.Itemizer._itemDefinitions, Item.Management.Itemizer._itemScopes, Item.Management.Itemizer.AddItemDefinition(), Item.Management.Itemizer.AddItemScope(), Item.Management.Itemizer.CheckInitialized(), Item.Management.ItemScope.Equals(), Item.ItemDefinition.IconPath, Item.Management.Itemizer.InternalRemoveItemDefinition(), Item.Management.Itemizer.ItemScopeEdited(), Item.ItemDefinition.MaxStackCount, Item.Management.ItemScope.Name, Item.ItemDefinition.Name, and Item.ItemDefinition.PrefabPath.
Referenced by Item.Management.ItemScopeEditWindow.OnGUI().
GetAllInheritedItemDefinitionTypes()
List< Type > Item.Management.Itemizer.GetAllInheritedItemDefinitionTypes ()
Returns
Referenced by Item.Management.ItemManagerWindow.DisplaySettingsTab(), and Item.Management.ItemManagerWindow.InitializeWindow().
Initialize()
bool Item.Management.Itemizer.Initialize ()
Returns
Whether initializing was successful.
References Item.Management.Itemizer._defaultScope, Item.Management.Itemizer._initialized, Item.Management.Itemizer._itemDefinitions, Item.Management.Itemizer._itemScopes, ProjectPrefs.GetString(), and Item.Management.Itemizer.ReadDataLocally().
Referenced by Item.Management.ItemDefinitionSelectionWindow.Awake(), Item.Management.Itemizer.CheckInitialized(), and Item.Management.ItemManagerWindow.DisplaySettingsTab().
InternalRemoveItemDefinition()
void Item.Management.Itemizer.InternalRemoveItemDefinition (ItemDefinition itemDefinition) private
References Item.Management.Itemizer._itemDefinitions, Item.Management.Itemizer.CheckInitialized(), and Item.ItemDefinition.GetQualifiedName().
Referenced by Item.Management.Itemizer.EditInheritedItemDefinition< T >(), Item.Management.Itemizer.EditItemDefinition(), Item.Management.Itemizer.EditItemScope(), and Item.Management.Itemizer.RemoveItemScope().
ItemDefinitionEdited()
void Item.Management.Itemizer.ItemDefinitionEdited (ItemDefinition oldItemDefinition, ItemDefinition newItemDefinition)
Parameters
oldItemDefinition
newItemDefinition
References Item.Management.Itemizer.OnItemDefinitionEdited.
Referenced by Item.Management.Itemizer.EditInheritedItemDefinition< T >(), Item.Management.Itemizer.EditItemDefinition(), and Item.Management.Itemizer.RemoveItemDefinition().
ItemScopeEdited()
void Item.Management.Itemizer.ItemScopeEdited (ItemScope oldScope, ItemScope newScope)
Parameters
oldScope
newScope
References Item.Management.Itemizer.OnItemScopeEdited.
Referenced by Item.Management.Itemizer.EditItemScope(), and Item.Management.Itemizer.RemoveItemScope().
ReadDataLocally()
void Item.Management.Itemizer.ReadDataLocally () private
References Item.Management.Itemizer._instance, Item.Management.Itemizer._itemDefinitions, Item.Management.Itemizer._itemScopes, Item.Management.Itemizer.ReadItemData(), and Item.Management.Itemizer.ReadItemScopes().
Referenced by Item.Management.Itemizer.Initialize().
ReadItemData()
HashSet< ItemDefinition > Item.Management.Itemizer.ReadItemData () private
References Item.ItemDefinition.Deserialize(), and Item.Management.Itemizer.FILENAMEITEMS.
Referenced by Item.Management.Itemizer.ReadDataLocally().
ReadItemScopes()
HashSet< ItemScope > Item.Management.Itemizer.ReadItemScopes () private
References Item.Management.Itemizer.FILENAMESCOPES.
Referenced by Item.Management.Itemizer.ReadDataLocally().
RemoveItemDefinition()
void Item.Management.Itemizer.RemoveItemDefinition (ItemDefinition itemDefinition)
Parameters
itemDefinition The ItemDefinition to be removed.
Exceptions
ArgumentException
References Item.Management.Itemizer._itemDefinitions, Item.Management.Itemizer.CheckInitialized(), Item.ItemDefinition.GetQualifiedName(), and Item.Management.Itemizer.ItemDefinitionEdited().
Referenced by Item.Management.ItemManagerWindow.DrawListItems(), and Item.Management.ItemDefinitionSelectionWindow.OnGUI().
RemoveItemScope()
void Item.Management.Itemizer.RemoveItemScope (ItemScope scope)
Parameters
scope The ItemScope to remove.
Exceptions
ArgumentException
References Item.Management.Itemizer._defaultScope, Item.Management.Itemizer._itemDefinitions, Item.Management.Itemizer._itemScopes, Item.Management.Itemizer.AddItemDefinition(), Item.Management.Itemizer.CheckInitialized(), Item.Management.ItemScope.Equals(), Item.ItemDefinition.IconPath, Item.Management.Itemizer.InternalRemoveItemDefinition(), Item.Management.Itemizer.ItemScopeEdited(), Item.ItemDefinition.MaxStackCount, Item.Management.ItemScope.Name, Item.ItemDefinition.Name, and Item.ItemDefinition.PrefabPath.
Referenced by Item.Management.ItemManagerWindow.DrawListScopes().
WriteData()
void Item.Management.Itemizer.WriteData ()
References Item.Management.Itemizer._itemDefinitions, Item.Management.Itemizer._itemScopes, Item.Management.Itemizer.FILENAMEITEMS, Item.Management.Itemizer.FILENAMESCOPES, and ResourcesUtil.WriteFile().
Referenced by Item.Management.ItemManagerWindow.DisplayScopesTab(), Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), Item.Management.ItemManagerWindow.DrawAddDefinedItem(), Item.Management.ItemManagerWindow.DrawListItems(), Item.Management.ItemManagerWindow.DrawListScopes(), Item.Management.ItemDefinitionSelectionWindow.OnGUI(), and Item.Management.ItemScopeEditWindow.OnGUI().
Member Data Documentation
_defaultScope
ItemScope Item.Management.Itemizer._defaultScope private
Referenced by Item.Management.Itemizer.EditItemScope(), Item.Management.Itemizer.Initialize(), and Item.Management.Itemizer.RemoveItemScope().
_initialized
bool Item.Management.Itemizer._initialized private
Referenced by Item.Management.Itemizer.CheckInitialized(), and Item.Management.Itemizer.Initialize().
_instance
Itemizer Item.Management.Itemizer._instance static private
Referenced by Item.Management.Itemizer.ReadDataLocally().
_itemDefinitions
HashSet<ItemDefinition> Item.Management.Itemizer._itemDefinitions private
Referenced by Item.Management.Itemizer.AddInheritedItemDefinition< T >(), Item.Management.Itemizer.AddItemDefinition(), Item.Management.Itemizer.EditInheritedItemDefinition< T >(), Item.Management.Itemizer.EditItemDefinition(), Item.Management.Itemizer.EditItemScope(), Item.Management.Itemizer.Initialize(), Item.Management.Itemizer.InternalRemoveItemDefinition(), Item.Management.Itemizer.ReadDataLocally(), Item.Management.Itemizer.RemoveItemDefinition(), Item.Management.Itemizer.RemoveItemScope(), and Item.Management.Itemizer.WriteData().
_itemScopes
HashSet<ItemScope> Item.Management.Itemizer._itemScopes private
Referenced by Item.Management.Itemizer.AddInheritedItemDefinition< T >(), Item.Management.Itemizer.AddItemDefinition(), Item.Management.Itemizer.AddItemScope(), Item.Management.Itemizer.EditItemScope(), Item.Management.Itemizer.Initialize(), Item.Management.Itemizer.ReadDataLocally(), Item.Management.Itemizer.RemoveItemScope(), and Item.Management.Itemizer.WriteData().
FILENAMEITEMS
string Item.Management.Itemizer.FILENAMEITEMS = "ItemData.txt" private
Referenced by Item.Management.Itemizer.ReadItemData(), and Item.Management.Itemizer.WriteData().
FILENAMESCOPES
string Item.Management.Itemizer.FILENAMESCOPES = "ItemScopeData.txt" private
Referenced by Item.Management.Itemizer.ReadItemScopes(), and Item.Management.Itemizer.WriteData().
Property Documentation
DefaultScope
ItemScope Item.Management.Itemizer.DefaultScope get
Referenced by Item.Management.ItemManagerWindow.DrawListScopes().
Initialized
bool Item.Management.Itemizer.Initialized get
Referenced by Item.Management.ItemManagerWindow.InitializeWindow(), Item.Management.ItemManagerWindow.OnGUI(), and Item.ItemManager.SpawnItemInstance().
Instance
Itemizer Item.Management.Itemizer.Instance static get
Referenced by Item.Management.ItemDefinitionSelectionWindow.Awake(), Item.Management.ItemManagerWindow.DisplayScopesTab(), Item.Management.ItemManagerWindow.DisplaySettingsTab(), Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), Item.Management.ItemManagerWindow.DrawAddDefinedItem(), Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), Item.Management.ItemManagerWindow.DrawCreationFields(), Item.Management.ItemManagerWindow.DrawListItems(), Item.Management.ItemManagerWindow.DrawListScopes(), Item.Management.ItemDefinitionEditWindow.Init(), Item.Management.ItemManagerWindow.InitializeWindow(), Item.Management.ItemDefinitionSelectionWindow.OnGUI(), Item.Management.ItemManagerWindow.OnGUI(), Item.Management.ItemScopeEditWindow.OnGUI(), and Item.ItemManager.SpawnItemInstance().
ItemDefinitions
HashSet<ItemDefinition> Item.Management.Itemizer.ItemDefinitions get
Referenced by Item.Management.ItemManagerWindow.DrawListItems(), Item.Management.ItemDefinitionSelectionWindow.OnGUI(), and Item.ItemManager.SpawnItemInstance().
ItemScopes
HashSet<ItemScope> Item.Management.Itemizer.ItemScopes get
Referenced by Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), Item.Management.ItemManagerWindow.DrawAddDefinedItem(), Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), Item.Management.ItemManagerWindow.DrawCreationFields(), Item.Management.ItemManagerWindow.DrawListScopes(), and Item.Management.ItemDefinitionEditWindow.Init().
Event Documentation
OnItemDefinitionEdited
Action<ItemDefinition, ItemDefinition> Item.Management.Itemizer.OnItemDefinitionEdited
Referenced by Item.Management.Itemizer.ItemDefinitionEdited().
OnItemScopeEdited
Action<ItemScope, ItemScope> Item.Management.Itemizer.OnItemScopeEdited
Referenced by Item.Management.Itemizer.ItemScopeEdited().