UnityToolbox: UnityToolbox.Item.Management.ItemScopeEditWindow Class Reference
UnityToolbox.Item.Management.ItemScopeEditWindow Class Reference
Public Member Functions
void OnGUI ()
Static Public Member Functions
static void Open (ItemScope scope)
Properties
ItemScope Scope [set]
Private Member Functions
void Awake ()
void ScopeEdited (ItemScope scope, ItemScope newScope)
void DrawLineHorizontal ()
void UpdateStatus (string status)
Private Attributes
ItemScope _scope
string _newScopeName
string _status
Member Function Documentation
Awake()
void UnityToolbox.Item.Management.ItemScopeEditWindow.Awake () private
References UnityToolbox.Item.Management.ItemScopeEditWindow.ScopeEdited(), and UnityToolbox.Item.Management.ItemScopeEditWindow.UpdateStatus().
DrawLineHorizontal()
void UnityToolbox.Item.Management.ItemScopeEditWindow.DrawLineHorizontal () private
Referenced by UnityToolbox.Item.Management.ItemScopeEditWindow.OnGUI().
OnGUI()
void UnityToolbox.Item.Management.ItemScopeEditWindow.OnGUI ()
References UnityToolbox.Item.Management.ItemScopeEditWindow._newScopeName, UnityToolbox.Item.Management.ItemScopeEditWindow._scope, UnityToolbox.Item.Management.ItemScopeEditWindow._status, UnityToolbox.Item.Management.ItemScopeEditWindow.DrawLineHorizontal(), UnityToolbox.Item.Management.Itemizer.EditItemScope(), UnityToolbox.Item.Management.Itemizer.Instance, UnityToolbox.Item.Management.ItemScopeEditWindow.ScopeEdited(), UnityToolbox.Item.Management.ItemScopeEditWindow.UpdateStatus(), and UnityToolbox.Item.Management.Itemizer.WriteData().
Open()
static void UnityToolbox.Item.Management.ItemScopeEditWindow.Open (ItemScope scope) static
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DrawListScopes().
ScopeEdited()
void UnityToolbox.Item.Management.ItemScopeEditWindow.ScopeEdited (ItemScope scope, ItemScope newScope) private
References UnityToolbox.Item.Management.ItemScopeEditWindow._scope, UnityToolbox.Item.Management.ItemScope.Equals(), and UnityToolbox.Item.Management.ItemScopeEditWindow.ScopeEdited().
Referenced by UnityToolbox.Item.Management.ItemScopeEditWindow.Awake(), UnityToolbox.Item.Management.ItemScopeEditWindow.OnGUI(), and UnityToolbox.Item.Management.ItemScopeEditWindow.ScopeEdited().
UpdateStatus()
void UnityToolbox.Item.Management.ItemScopeEditWindow.UpdateStatus (string status) private
References UnityToolbox.Item.Management.ItemScopeEditWindow._status.
Referenced by UnityToolbox.Item.Management.ItemScopeEditWindow.Awake(), and UnityToolbox.Item.Management.ItemScopeEditWindow.OnGUI().
Member Data Documentation
_newScopeName
string UnityToolbox.Item.Management.ItemScopeEditWindow._newScopeName private
Referenced by UnityToolbox.Item.Management.ItemScopeEditWindow.OnGUI().
_scope
ItemScope UnityToolbox.Item.Management.ItemScopeEditWindow._scope private
Referenced by UnityToolbox.Item.Management.ItemScopeEditWindow.OnGUI(), and UnityToolbox.Item.Management.ItemScopeEditWindow.ScopeEdited().
_status
string UnityToolbox.Item.Management.ItemScopeEditWindow._status private
Referenced by UnityToolbox.Item.Management.ItemScopeEditWindow.OnGUI(), and UnityToolbox.Item.Management.ItemScopeEditWindow.UpdateStatus().
Property Documentation
Scope
ItemScope UnityToolbox.Item.Management.ItemScopeEditWindow.Scope set