UnityToolbox: Itemizer Class Reference
Itemizer Class Reference
The core of the item managment system. It takes care of the (de)serialization and changes to all data.
Public Member Functions
void Initialize ()
ItemDefinition AddItemDefinition (ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath)
T AddInheritedItemDefinition< T > (ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, HashSet< ItemField > itemFields)
void RemoveItemDefinition (ItemDefinition itemDefinition)
void EditInheritedItemDefinition< T > (ItemDefinition itemDefinition, ItemScope scope, string name, int maxStackCount, string iconPath, string prefabPath, HashSet< ItemField > itemFields)
void EditItemDefinition (ItemDefinition itemDefinition, ItemScope scope, string name, int maxStackCount, string iconPath, string prefabPath)
ItemScope AddItemScope (string name)
void RemoveItemScope (ItemScope scope)
void EditItemScope (ItemScope scope, string name)
List< Type > GetAllInheritedItemDefinitionTypes ()
void WriteData ()
Writes all data to the set resources folder.
void ItemScopeEdited (ItemScope oldScope, ItemScope newScope)
void ItemDefinitionEdited (ItemDefinition oldItemDefinition, ItemDefinition newItemDefinition)
Properties
static Itemizer Instance [get]
bool Initialized [get]
HashSet< ItemDefinition > ItemDefinitions [get]
All defined items.
HashSet< ItemScope > ItemScopes [get]
All defined item scopes.
ItemScope DefaultScope [get]
Events
Action< ItemScope, ItemScope > OnItemScopeEdited
Action< ItemDefinition, ItemDefinition > OnItemDefinitionEdited
Private Member Functions
void InternalRemoveItemDefinition (ItemDefinition itemDefinition)
void CheckInitialized ()
void ReadDataLocally ()
HashSet< ItemDefinition > ReadItemData ()
HashSet< ItemScope > ReadItemScopes ()
Private Attributes
bool _initialized
string FILENAMEITEMS = "ItemData.txt"
string FILENAMESCOPES = "ItemScopeData.txt"
HashSet< ItemDefinition > _itemDefinitions
HashSet< ItemScope > _itemScopes
ItemScope _defaultScope
Static Private Attributes
static Itemizer _instance
Member Function Documentation
AddInheritedItemDefinition< T >()
T Itemizer.AddInheritedItemDefinition< T > (ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, HashSet< ItemField > itemFields)
Type Constraints
T : ItemDefinition
References _itemDefinitions, _itemScopes, CheckInitialized(), ItemField.FieldName, ItemField.FieldType, and ItemField.GetValue().
Referenced by EditInheritedItemDefinition< T >().
AddItemDefinition()
ItemDefinition Itemizer.AddItemDefinition (ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath)
References _itemDefinitions, _itemScopes, CheckInitialized(), and ItemDefinition.GetQualifiedName().
Referenced by ItemManagerWindow.DrawAddDefinedItem(), EditItemDefinition(), EditItemScope(), and RemoveItemScope().
AddItemScope()
ItemScope Itemizer.AddItemScope (string name)
References _itemScopes, and CheckInitialized().
Referenced by ItemManagerWindow.DisplayScopesTab(), and EditItemScope().
CheckInitialized()
void Itemizer.CheckInitialized () private
References _initialized, and Initialize().
Referenced by AddInheritedItemDefinition< T >(), AddItemDefinition(), AddItemScope(), EditItemScope(), InternalRemoveItemDefinition(), RemoveItemDefinition(), and RemoveItemScope().
EditInheritedItemDefinition< T >()
void Itemizer.EditInheritedItemDefinition< T > (ItemDefinition itemDefinition, ItemScope scope, string name, int maxStackCount, string iconPath, string prefabPath, HashSet< ItemField > itemFields)
Type Constraints
T : ItemDefinition
References _itemDefinitions, AddInheritedItemDefinition< T >(), InternalRemoveItemDefinition(), and ItemDefinitionEdited().
EditItemDefinition()
void Itemizer.EditItemDefinition (ItemDefinition itemDefinition, ItemScope scope, string name, int maxStackCount, string iconPath, string prefabPath)
References _itemDefinitions, AddItemDefinition(), InternalRemoveItemDefinition(), and ItemDefinitionEdited().
Referenced by ItemDefinitionEditWindow.DrawAddDefinedItem().
EditItemScope()
void Itemizer.EditItemScope (ItemScope scope, string name)
References _defaultScope, _itemDefinitions, _itemScopes, AddItemDefinition(), AddItemScope(), CheckInitialized(), ItemScope.Equals(), ItemDefinition.IconPath, InternalRemoveItemDefinition(), ItemScopeEdited(), ItemDefinition.MaxStackCount, ItemDefinition.Name, ItemScope.Name, and ItemDefinition.PrefabPath.
Referenced by ItemScopeEditWindow.OnGUI().
GetAllInheritedItemDefinitionTypes()
List< Type > Itemizer.GetAllInheritedItemDefinitionTypes ()
Referenced by ItemManagerWindow.DisplaySettingsTab(), and ItemManagerWindow.InitializeWindow().
Initialize()
void Itemizer.Initialize ()
References _defaultScope, _initialized, _itemDefinitions, _itemScopes, ProjectPrefs.GetString(), and ReadDataLocally().
Referenced by ItemDefinitionSelectionWindow.Awake(), CheckInitialized(), and ItemManagerWindow.DisplaySettingsTab().
InternalRemoveItemDefinition()
void Itemizer.InternalRemoveItemDefinition (ItemDefinition itemDefinition) private
References _itemDefinitions, CheckInitialized(), and ItemDefinition.GetQualifiedName().
Referenced by EditInheritedItemDefinition< T >(), EditItemDefinition(), EditItemScope(), and RemoveItemScope().
ItemDefinitionEdited()
void Itemizer.ItemDefinitionEdited (ItemDefinition oldItemDefinition, ItemDefinition newItemDefinition)
References OnItemDefinitionEdited.
Referenced by EditInheritedItemDefinition< T >(), EditItemDefinition(), and RemoveItemDefinition().
ItemScopeEdited()
void Itemizer.ItemScopeEdited (ItemScope oldScope, ItemScope newScope)
References OnItemScopeEdited.
Referenced by EditItemScope(), and RemoveItemScope().
ReadDataLocally()
void Itemizer.ReadDataLocally () private
References _instance, _itemDefinitions, _itemScopes, ReadItemData(), and ReadItemScopes().
Referenced by Initialize().
ReadItemData()
HashSet< ItemDefinition > Itemizer.ReadItemData () private
References ItemDefinition.Deserialize(), and FILENAMEITEMS.
Referenced by ReadDataLocally().
ReadItemScopes()
HashSet< ItemScope > Itemizer.ReadItemScopes () private
References FILENAMESCOPES.
Referenced by ReadDataLocally().
RemoveItemDefinition()
void Itemizer.RemoveItemDefinition (ItemDefinition itemDefinition)
References _itemDefinitions, CheckInitialized(), ItemDefinition.GetQualifiedName(), and ItemDefinitionEdited().
Referenced by ItemManagerWindow.DrawListItems(), and ItemDefinitionSelectionWindow.OnGUI().
RemoveItemScope()
void Itemizer.RemoveItemScope (ItemScope scope)
References _defaultScope, _itemDefinitions, _itemScopes, AddItemDefinition(), CheckInitialized(), ItemScope.Equals(), ItemDefinition.IconPath, InternalRemoveItemDefinition(), ItemScopeEdited(), ItemDefinition.MaxStackCount, ItemDefinition.Name, ItemScope.Name, and ItemDefinition.PrefabPath.
Referenced by ItemManagerWindow.DrawListScopes().
WriteData()
void Itemizer.WriteData ()
References _itemDefinitions, _itemScopes, FILENAMEITEMS, FILENAMESCOPES, and ResourcesUtil.WriteFile().
Referenced by ItemManagerWindow.DisplayScopesTab(), ItemDefinitionEditWindow.DrawAddDefinedItem(), ItemManagerWindow.DrawAddDefinedItem(), ItemManagerWindow.DrawListItems(), ItemManagerWindow.DrawListScopes(), ItemDefinitionSelectionWindow.OnGUI(), and ItemScopeEditWindow.OnGUI().
Member Data Documentation
_defaultScope
ItemScope Itemizer._defaultScope private
Referenced by EditItemScope(), Initialize(), and RemoveItemScope().
_initialized
bool Itemizer._initialized private
Referenced by CheckInitialized(), and Initialize().
_instance
Itemizer Itemizer._instance static private
Referenced by ReadDataLocally().
_itemDefinitions
HashSet<ItemDefinition> Itemizer._itemDefinitions private
Referenced by AddInheritedItemDefinition< T >(), AddItemDefinition(), EditInheritedItemDefinition< T >(), EditItemDefinition(), EditItemScope(), Initialize(), InternalRemoveItemDefinition(), ReadDataLocally(), RemoveItemDefinition(), RemoveItemScope(), and WriteData().
_itemScopes
HashSet<ItemScope> Itemizer._itemScopes private
Referenced by AddInheritedItemDefinition< T >(), AddItemDefinition(), AddItemScope(), EditItemScope(), Initialize(), ReadDataLocally(), RemoveItemScope(), and WriteData().
FILENAMEITEMS
string Itemizer.FILENAMEITEMS = "ItemData.txt" private
Referenced by ReadItemData(), and WriteData().
FILENAMESCOPES
string Itemizer.FILENAMESCOPES = "ItemScopeData.txt" private
Referenced by ReadItemScopes(), and WriteData().
Property Documentation
DefaultScope
ItemScope Itemizer.DefaultScope get
Referenced by ItemManagerWindow.DrawListScopes().
Initialized
bool Itemizer.Initialized get
Referenced by ItemManagerWindow.InitializeWindow(), ItemManagerWindow.OnGUI(), and ItemManager.SpawnItemInstance().
Instance
Itemizer Itemizer.Instance static get
Referenced by ItemDefinitionSelectionWindow.Awake(), ItemManagerWindow.DisplayScopesTab(), ItemManagerWindow.DisplaySettingsTab(), ItemDefinitionEditWindow.DrawAddDefinedItem(), ItemManagerWindow.DrawAddDefinedItem(), ItemDefinitionEditWindow.DrawCreationFields(), ItemManagerWindow.DrawCreationFields(), ItemManagerWindow.DrawListItems(), ItemManagerWindow.DrawListScopes(), ItemDefinitionEditWindow.Init(), ItemManagerWindow.InitializeWindow(), ItemDefinitionSelectionWindow.OnGUI(), ItemManagerWindow.OnGUI(), ItemScopeEditWindow.OnGUI(), and ItemManager.SpawnItemInstance().
ItemDefinitions
HashSet<ItemDefinition> Itemizer.ItemDefinitions get
Referenced by ItemManagerWindow.DrawListItems(), ItemDefinitionSelectionWindow.OnGUI(), and ItemManager.SpawnItemInstance().
ItemScopes
HashSet<ItemScope> Itemizer.ItemScopes get
Referenced by ItemDefinitionEditWindow.DrawAddDefinedItem(), ItemManagerWindow.DrawAddDefinedItem(), ItemDefinitionEditWindow.DrawCreationFields(), ItemManagerWindow.DrawCreationFields(), ItemManagerWindow.DrawListScopes(), and ItemDefinitionEditWindow.Init().
Event Documentation
OnItemDefinitionEdited
Action<ItemDefinition, ItemDefinition> Itemizer.OnItemDefinitionEdited
Referenced by ItemDefinitionEdited().
OnItemScopeEdited
Action<ItemScope, ItemScope> Itemizer.OnItemScopeEdited
Referenced by ItemScopeEdited().