UnityToolbox: UnityToolbox.Item.Management.ItemDefinitionSelectionWindow Class Reference
UnityToolbox.Item.Management.ItemDefinitionSelectionWindow Class Reference
Static Public Member Functions
static ItemDefinitionSelectionWindow Open ()
Events
Action< ItemDefinition > OnItemDefinitionSelected
Private Member Functions
void Awake ()
void OnGUI ()
void DisplayItemsTab ()
void DrawListItems ()
void SetupListsForItemType (Type type)
void DrawLineHorizontal ()
void UpdateStatus (string status)
Private Attributes
Vector2 _scrollPos
string _searchString
bool _foldoutSearch
string _status
int _selectedSearch
List< Type > _itemDefinitionTypes
List< bool > _selectionBoolValues
List< float > _selectionFloatValues
List< int > _selectionIntValues
List< string > _selectionStringValues
List< FieldInfo > _selectionFields
ItemDefinitionErrorWindow _errorWindow
Member Function Documentation
Awake()
void UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.Awake () private
References UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._itemDefinitionTypes, UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._searchString, UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._selectedSearch, UnityToolbox.Item.Management.Itemizer.GetAllInheritedItemDefinitionTypes(), UnityToolbox.Item.Management.Itemizer.Initialize(), UnityToolbox.Item.Management.Itemizer.Initialized, UnityToolbox.Item.Management.Itemizer.Instance, UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.SetupListsForItemType(), and UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.UpdateStatus().
DisplayItemsTab()
void UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DisplayItemsTab () private
References UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._foldoutSearch, UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._itemDefinitionTypes, UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._searchString, UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._selectedSearch, UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._status, UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DrawLineHorizontal(), and UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DrawListItems().
Referenced by UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.OnGUI().
DrawLineHorizontal()
void UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DrawLineHorizontal () private
Referenced by UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DisplayItemsTab(), and UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DrawListItems().
DrawListItems()
void UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DrawListItems () private
References UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._itemDefinitionTypes, UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._scrollPos, UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._searchString, UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._selectedSearch, UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DrawLineHorizontal(), UnityToolbox.Item.ItemDefinition.GetQualifiedName(), UnityToolbox.Item.Management.Itemizer.Instance, UnityToolbox.Item.Management.Itemizer.ItemDefinitions, UnityToolbox.Item.ItemDefinition.Name, UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.OnItemDefinitionSelected, UnityToolbox.Item.Management.ItemDefinitionEditWindow.Open(), UnityToolbox.Item.Management.Itemizer.RemoveItemDefinition(), UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.UpdateStatus(), and UnityToolbox.Item.Management.Itemizer.WriteData().
Referenced by UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DisplayItemsTab().
OnGUI()
void UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.OnGUI () private
References UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._errorWindow, UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DisplayItemsTab(), UnityToolbox.Item.Management.Itemizer.FaultyItemDefinitions, UnityToolbox.Item.Management.Itemizer.Instance, UnityToolbox.Item.Management.ItemDefinitionErrorWindow.Open(), and UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.UpdateStatus().
Open()
static ItemDefinitionSelectionWindow UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.Open () static
Referenced by UnityToolbox.Item.Management.ItemDefinitionDrawer.OnGUI().
SetupListsForItemType()
void UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.SetupListsForItemType (Type type) private
References UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._selectionBoolValues, UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._selectionFields, UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._selectionFloatValues, UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._selectionIntValues, and UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._selectionStringValues.
Referenced by UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.Awake().
UpdateStatus()
void UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.UpdateStatus (string status) private
References UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._status.
Referenced by UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.Awake(), UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DrawListItems(), and UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.OnGUI().
Member Data Documentation
_errorWindow
ItemDefinitionErrorWindow UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._errorWindow private
Referenced by UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.OnGUI().
_foldoutSearch
bool UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._foldoutSearch private
Referenced by UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DisplayItemsTab().
_itemDefinitionTypes
List<Type> UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._itemDefinitionTypes private
Referenced by UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.Awake(), UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DisplayItemsTab(), and UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DrawListItems().
_scrollPos
Vector2 UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._scrollPos private
Referenced by UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DrawListItems().
_searchString
string UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._searchString private
Referenced by UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.Awake(), UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DisplayItemsTab(), and UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DrawListItems().
_selectedSearch
int UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._selectedSearch private
Referenced by UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.Awake(), UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DisplayItemsTab(), and UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DrawListItems().
_selectionBoolValues
List<bool> UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._selectionBoolValues private
Referenced by UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.SetupListsForItemType().
_selectionFields
List<FieldInfo> UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._selectionFields private
Referenced by UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.SetupListsForItemType().
_selectionFloatValues
List<float> UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._selectionFloatValues private
Referenced by UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.SetupListsForItemType().
_selectionIntValues
List<int> UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._selectionIntValues private
Referenced by UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.SetupListsForItemType().
_selectionStringValues
List<string> UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._selectionStringValues private
Referenced by UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.SetupListsForItemType().
_status
string UnityToolbox.Item.Management.ItemDefinitionSelectionWindow._status private
Referenced by UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DisplayItemsTab(), and UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.UpdateStatus().
Event Documentation
OnItemDefinitionSelected
Action<ItemDefinition> UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.OnItemDefinitionSelected
Referenced by UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DrawListItems().