UnityToolbox Documentation: SaveGameManager Class Reference
SaveGameManager Class Reference
A manager, which is takes care of the (de)serialisation of GameObjects and CompletionData. Requires a PrefabManager and IDManager for objects that are not present initially.
Public Member Functions
override void Awake ()
bool GetCompletionInfo (string ID)
Trys to find completion infos with an ID. Similar to gamestates but not necessarily linear.
void SetCompletionInfo (string ID, bool isCompleted)
Sets completion info.
List< GameData > GetGameDataForID (string ID)
Trys to find GameData for an ID.
void SetDataToSave (GameData data, string ID, bool writeImmediate)
Sets data to be seralized.
void RemoveDataFromSave (string ID)
Removes an object from the serialisation data.
void ResetAll ()
Resets all save game data and permanetly removes every data to be serialized.
virtual void Awake ()
Public Attributes
Action< string, bool > OnCompletionInfoChanged
Private Member Functions
IEnumerator Load ()
void LoadAllIntoScene ()
void LoadSaved ()
void SpawnSaved ()
void WriteData ()
void ReadData ()
void ReadSpawnData ()
void ReadCompletionData ()
void OnDestroy ()
byte[] Encrypt (string plainText, byte[] key, byte[] iv)
string Decrypt (byte[] cypherText, byte[] key, byte[] iv)
Private Attributes
string _pathToUse
readonly string _dataPath = "/SaveGameData.dat"
readonly string _spawnDataPath = "/SaveGameObjects.dat"
readonly string _completionDataPath = "/SaveGameCompletion.dat"
Dictionary< string, List< GameData > > _data
Dictionary< string, ResourceData > _spawnData
HashSet< string > _spawnedIDs
CompletionData _completionInfo
JsonSerializerSettings _settings
Member Function Documentation
Awake()
override void SaveGameManager.Awake () virtual
Reimplemented from Module.
References _completionInfo, _data, _pathToUse, _settings, _spawnData, _spawnedIDs, Load(), ReadCompletionData(), ReadData(), and ReadSpawnData().
Decrypt()
string SaveGameManager.Decrypt (byte[] cypherText, byte[] key, byte[] iv) private
Encrypt()
byte[] SaveGameManager.Encrypt (string plainText, byte[] key, byte[] iv) private
GetCompletionInfo()
bool SaveGameManager.GetCompletionInfo (string ID)
Parameters
ID The ID of the completion info.
Returns
Whether the the completion info is set or not.
References _completionInfo, and CompletionData.IDToCompletion.
GetGameDataForID()
List< GameData > SaveGameManager.GetGameDataForID (string ID)
Parameters
ID The ID of the Saveable.
Returns
References _data.
Load()
IEnumerator SaveGameManager.Load () private
References _spawnedIDs, IDManager.GetSceneNameOfID(), and LoadAllIntoScene().
Referenced by Awake().
LoadAllIntoScene()
void SaveGameManager.LoadAllIntoScene () private
References LoadSaved(), and SpawnSaved().
Referenced by Load().
LoadSaved()
void SaveGameManager.LoadSaved () private
References _data, IDManager.GetSceneNameOfID(), Saveable.ID, and Saveable.Load().
Referenced by LoadAllIntoScene().
OnDestroy()
void SaveGameManager.OnDestroy () private
References WriteData().
ReadCompletionData()
void SaveGameManager.ReadCompletionData () private
References _completionDataPath, _completionInfo, _pathToUse, and _settings.
Referenced by Awake().
ReadData()
void SaveGameManager.ReadData () private
References _data, _dataPath, _pathToUse, and _settings.
Referenced by Awake().
ReadSpawnData()
void SaveGameManager.ReadSpawnData () private
References _pathToUse, _settings, _spawnData, and _spawnDataPath.
Referenced by Awake().
RemoveDataFromSave()
void SaveGameManager.RemoveDataFromSave (string ID)
Parameters
ID The ID of the Saveable to be removed.
References _data, and _spawnData.
ResetAll()
void SaveGameManager.ResetAll ()
References _completionInfo, _data, and _spawnData.
SetCompletionInfo()
void SaveGameManager.SetCompletionInfo (string ID, bool isCompleted)
Parameters
ID The ID of the completion.
isCompleted Whether the completion mark is actually completed.
References _completionInfo, CompletionData.IDToCompletion, and OnCompletionInfoChanged.
SetDataToSave()
void SaveGameManager.SetDataToSave (GameData data, string ID, bool writeImmediate)
Parameters
data The implementation of GameData, which stores the serializable data.
ID The ID of the Saveable, which this data belongs to.
writeImmediate Should the data be serialized immediately? Serializes ALL data.
References _data, _spawnData, and WriteData().
SpawnSaved()
void SaveGameManager.SpawnSaved () private
References _spawnData, _spawnedIDs, PrefabManager.GetPrefabForID(), and IDManager.GetSceneNameOfID().
Referenced by LoadAllIntoScene().
WriteData()
void SaveGameManager.WriteData () private
References _completionDataPath, _completionInfo, _data, _dataPath, _pathToUse, _settings, _spawnData, and _spawnDataPath.
Referenced by OnDestroy(), and SetDataToSave().
Member Data Documentation
_completionDataPath
readonly string SaveGameManager._completionDataPath = "/SaveGameCompletion.dat" private
Referenced by ReadCompletionData(), and WriteData().
_completionInfo
CompletionData SaveGameManager._completionInfo private
Referenced by Awake(), GetCompletionInfo(), ReadCompletionData(), ResetAll(), SetCompletionInfo(), and WriteData().
_data
Dictionary<string,List<GameData> > SaveGameManager._data private
Referenced by Awake(), GetGameDataForID(), LoadSaved(), ReadData(), RemoveDataFromSave(), ResetAll(), SetDataToSave(), and WriteData().
_dataPath
readonly string SaveGameManager._dataPath = "/SaveGameData.dat" private
Referenced by ReadData(), and WriteData().
_pathToUse
string SaveGameManager._pathToUse private
Referenced by Awake(), ReadCompletionData(), ReadData(), ReadSpawnData(), and WriteData().
_settings
JsonSerializerSettings SaveGameManager._settings private
Referenced by Awake(), ReadCompletionData(), ReadData(), ReadSpawnData(), and WriteData().
_spawnData
Dictionary<string, ResourceData> SaveGameManager._spawnData private
Referenced by Awake(), ReadSpawnData(), RemoveDataFromSave(), ResetAll(), SetDataToSave(), SpawnSaved(), and WriteData().
_spawnDataPath
readonly string SaveGameManager._spawnDataPath = "/SaveGameObjects.dat" private
Referenced by ReadSpawnData(), and WriteData().
_spawnedIDs
HashSet<string> SaveGameManager._spawnedIDs private
Referenced by Awake(), Load(), and SpawnSaved().
OnCompletionInfoChanged
Action<string, bool> SaveGameManager.OnCompletionInfoChanged
Referenced by SetCompletionInfo().