UnityToolbox: GamestateGraphView Class Reference
GamestateGraphView Class Reference
The gamestate graph used within a window.
Public Member Functions
GamestateGraphView ()
void AddNode (GamestateNode node)
Adds a new GamestateNode to the graph and draws it.
override List< Port > GetCompatiblePorts (Port startPort, NodeAdapter nodeAdapter)
Properties
HashSet< int > IDS [get]
Private Member Functions
GamestateNode CreateNode (Vector2 position)
void AddGrid ()
void AddStyle ()
void AddManipulators ()
IManipulator CreateNodeManipulator ()
Group CreateGroup (string title, Vector2 localMousePosition)
string GetPathOfStyle ()
Private Attributes
HashSet< int > _ids
Constructor & Destructor Documentation
GamestateGraphView()
GamestateGraphView.GamestateGraphView ()
References _ids, AddGrid(), AddManipulators(), and AddStyle().
Member Function Documentation
AddGrid()
void GamestateGraphView.AddGrid () private
Referenced by GamestateGraphView().
AddManipulators()
void GamestateGraphView.AddManipulators () private
References CreateNodeManipulator().
Referenced by GamestateGraphView().
AddNode()
void GamestateGraphView.AddNode (GamestateNode node)
Parameters
node
References _ids, GamestateNode.Draw(), and GamestateNode.ID.
Referenced by GamestateGraphWindow.UpdateData().
AddStyle()
void GamestateGraphView.AddStyle () private
References GetPathOfStyle().
Referenced by GamestateGraphView().
CreateGroup()
Group GamestateGraphView.CreateGroup (string title, Vector2 localMousePosition) private
CreateNode()
GamestateNode GamestateGraphView.CreateNode (Vector2 position) private
References _ids, and GamestateNode.Draw().
Referenced by CreateNodeManipulator().
CreateNodeManipulator()
IManipulator GamestateGraphView.CreateNodeManipulator () private
References CreateNode().
Referenced by AddManipulators().
GetCompatiblePorts()
override List< Port > GamestateGraphView.GetCompatiblePorts (Port startPort, NodeAdapter nodeAdapter)
GetPathOfStyle()
string GamestateGraphView.GetPathOfStyle () private
References ProjectPrefs.GetString().
Referenced by AddStyle().
Member Data Documentation
_ids
HashSet<int> GamestateGraphView._ids private
Referenced by AddNode(), CreateNode(), and GamestateGraphView().
Property Documentation
IDS
HashSet<int> GamestateGraphView.IDS get