UnityToolbox: UnityToolbox.Item.Management.ItemDefinitionEditWindow Class Reference
UnityToolbox.Item.Management.ItemDefinitionEditWindow Class Reference
Public Member Functions
void OnGUI ()
new void Close ()
Static Public Member Functions
static void Open (ItemDefinition currentItemDefinition)
Properties
ItemDefinition CurrentItemDefinition [set]
Private Member Functions
void Awake ()
void Init (ItemDefinition value)
void DrawLine ()
void DrawCreationFields ()
void DrawAddDefinedItem ()
void ItemDefinitionEdited (ItemDefinition oldItemDefinition, ItemDefinition newItemDefinition)
void ScopeEdited (ItemScope oldScope, ItemScope newScope)
void UpdateStatus (string status)
Private Attributes
ItemDefinition _currentItemDefinition
Vector2 _scrollPosCreation
Type _type
List< bool > _selectionBoolValues
List< string > _selectionStringValues
List< float > _selectionFloatValues
List< int > _selectionIntValues
List< FieldInfo > _selectionFields
string _newItemDefinitionName
int _newSelectedScope
Texture2D _newItemDefinitionIcon
GameObject _newItemDefinitionPrefab
int _newMaxStackCount
string _status
Member Function Documentation
Awake()
void UnityToolbox.Item.Management.ItemDefinitionEditWindow.Awake () private
References UnityToolbox.Item.Management.ItemDefinitionEditWindow.ItemDefinitionEdited(), UnityToolbox.Item.Management.ItemDefinitionEditWindow.ScopeEdited(), and UnityToolbox.Item.Management.ItemDefinitionEditWindow.UpdateStatus().
Close()
new void UnityToolbox.Item.Management.ItemDefinitionEditWindow.Close ()
References UnityToolbox.Item.Management.ItemDefinitionEditWindow.ItemDefinitionEdited(), and UnityToolbox.Item.Management.ItemDefinitionEditWindow.ScopeEdited().
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemDefinitionEditWindow.ItemDefinitionEdited(), and UnityToolbox.Item.Management.ItemDefinitionEditWindow.ScopeEdited().
DrawAddDefinedItem()
void UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem () private
References UnityToolbox.Item.Management.ItemDefinitionEditWindow._currentItemDefinition, UnityToolbox.Item.Management.ItemDefinitionEditWindow._newItemDefinitionIcon, UnityToolbox.Item.Management.ItemDefinitionEditWindow._newItemDefinitionName, UnityToolbox.Item.Management.ItemDefinitionEditWindow._newItemDefinitionPrefab, UnityToolbox.Item.Management.ItemDefinitionEditWindow._newMaxStackCount, UnityToolbox.Item.Management.ItemDefinitionEditWindow._newSelectedScope, UnityToolbox.Item.Management.ItemDefinitionEditWindow._selectionBoolValues, UnityToolbox.Item.Management.ItemDefinitionEditWindow._selectionFields, UnityToolbox.Item.Management.ItemDefinitionEditWindow._selectionFloatValues, UnityToolbox.Item.Management.ItemDefinitionEditWindow._selectionIntValues, UnityToolbox.Item.Management.ItemDefinitionEditWindow._selectionStringValues, UnityToolbox.Item.Management.ItemDefinitionEditWindow._type, UnityToolbox.Item.Management.ItemDefinitionEditWindow.Close(), UnityToolbox.Item.Management.Itemizer.EditItemDefinition(), UnityToolbox.Item.Management.Itemizer.Instance, UnityToolbox.Item.Management.Itemizer.ItemScopes, UnityToolbox.Item.Management.ItemDefinitionEditWindow.UpdateStatus(), and UnityToolbox.Item.Management.Itemizer.WriteData().
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.OnGUI().
DrawCreationFields()
void UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawCreationFields () private
References UnityToolbox.Item.Management.ItemDefinitionEditWindow._newItemDefinitionIcon, UnityToolbox.Item.Management.ItemDefinitionEditWindow._newItemDefinitionName, UnityToolbox.Item.Management.ItemDefinitionEditWindow._newItemDefinitionPrefab, UnityToolbox.Item.Management.ItemDefinitionEditWindow._newMaxStackCount, UnityToolbox.Item.Management.ItemDefinitionEditWindow._newSelectedScope, UnityToolbox.Item.Management.ItemDefinitionEditWindow._scrollPosCreation, UnityToolbox.Item.Management.ItemDefinitionEditWindow._selectionBoolValues, UnityToolbox.Item.Management.ItemDefinitionEditWindow._selectionFields, UnityToolbox.Item.Management.ItemDefinitionEditWindow._selectionFloatValues, UnityToolbox.Item.Management.ItemDefinitionEditWindow._selectionIntValues, UnityToolbox.Item.Management.ItemDefinitionEditWindow._selectionStringValues, UnityToolbox.Item.Management.ItemDefinitionEditWindow._type, UnityToolbox.Item.ItemDefinition.DEVIDER, UnityToolbox.Item.Management.Itemizer.Instance, and UnityToolbox.Item.Management.Itemizer.ItemScopes.
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.OnGUI().
DrawLine()
void UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawLine () private
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.OnGUI().
Init()
void UnityToolbox.Item.Management.ItemDefinitionEditWindow.Init (ItemDefinition value) private
References UnityToolbox.Item.Management.ItemDefinitionEditWindow._currentItemDefinition, UnityToolbox.Item.Management.ItemDefinitionEditWindow._newItemDefinitionIcon, UnityToolbox.Item.Management.ItemDefinitionEditWindow._newItemDefinitionName, UnityToolbox.Item.Management.ItemDefinitionEditWindow._newItemDefinitionPrefab, UnityToolbox.Item.Management.ItemDefinitionEditWindow._newMaxStackCount, UnityToolbox.Item.Management.ItemDefinitionEditWindow._newSelectedScope, UnityToolbox.Item.Management.ItemDefinitionEditWindow._selectionBoolValues, UnityToolbox.Item.Management.ItemDefinitionEditWindow._selectionFields, UnityToolbox.Item.Management.ItemDefinitionEditWindow._selectionFloatValues, UnityToolbox.Item.Management.ItemDefinitionEditWindow._selectionIntValues, UnityToolbox.Item.Management.ItemDefinitionEditWindow._selectionStringValues, UnityToolbox.Item.Management.ItemDefinitionEditWindow._type, UnityToolbox.Item.Management.ItemScope.Equals(), UnityToolbox.Item.ItemDefinition.IconPath, UnityToolbox.Item.Management.Itemizer.Instance, UnityToolbox.Item.Management.Itemizer.ItemScopes, UnityToolbox.Item.ItemDefinition.MaxStackCount, UnityToolbox.Item.ItemDefinition.Name, and UnityToolbox.Item.ItemDefinition.PrefabPath.
ItemDefinitionEdited()
void UnityToolbox.Item.Management.ItemDefinitionEditWindow.ItemDefinitionEdited (ItemDefinition oldItemDefinition, ItemDefinition newItemDefinition) private
References UnityToolbox.Item.Management.ItemDefinitionEditWindow.Close().
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.Awake(), and UnityToolbox.Item.Management.ItemDefinitionEditWindow.Close().
OnGUI()
void UnityToolbox.Item.Management.ItemDefinitionEditWindow.OnGUI ()
References UnityToolbox.Item.Management.ItemDefinitionEditWindow._status, UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawLine().
Open()
static void UnityToolbox.Item.Management.ItemDefinitionEditWindow.Open (ItemDefinition currentItemDefinition) static
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DrawListItems(), UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.DrawListItems(), and UnityToolbox.Item.Management.ItemManagerWindow.DrawListItems().
ScopeEdited()
void UnityToolbox.Item.Management.ItemDefinitionEditWindow.ScopeEdited (ItemScope oldScope, ItemScope newScope) private
References UnityToolbox.Item.Management.ItemDefinitionEditWindow.Close().
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.Awake(), and UnityToolbox.Item.Management.ItemDefinitionEditWindow.Close().
UpdateStatus()
void UnityToolbox.Item.Management.ItemDefinitionEditWindow.UpdateStatus (string status) private
References UnityToolbox.Item.Management.ItemDefinitionEditWindow._status.
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.Awake(), and UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem().
Member Data Documentation
_currentItemDefinition
ItemDefinition UnityToolbox.Item.Management.ItemDefinitionEditWindow._currentItemDefinition private
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), and UnityToolbox.Item.Management.ItemDefinitionEditWindow.Init().
_newItemDefinitionIcon
Texture2D UnityToolbox.Item.Management.ItemDefinitionEditWindow._newItemDefinitionIcon private
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and UnityToolbox.Item.Management.ItemDefinitionEditWindow.Init().
_newItemDefinitionName
string UnityToolbox.Item.Management.ItemDefinitionEditWindow._newItemDefinitionName private
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and UnityToolbox.Item.Management.ItemDefinitionEditWindow.Init().
_newItemDefinitionPrefab
GameObject UnityToolbox.Item.Management.ItemDefinitionEditWindow._newItemDefinitionPrefab private
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and UnityToolbox.Item.Management.ItemDefinitionEditWindow.Init().
_newMaxStackCount
int UnityToolbox.Item.Management.ItemDefinitionEditWindow._newMaxStackCount private
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and UnityToolbox.Item.Management.ItemDefinitionEditWindow.Init().
_newSelectedScope
int UnityToolbox.Item.Management.ItemDefinitionEditWindow._newSelectedScope private
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and UnityToolbox.Item.Management.ItemDefinitionEditWindow.Init().
_scrollPosCreation
Vector2 UnityToolbox.Item.Management.ItemDefinitionEditWindow._scrollPosCreation private
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawCreationFields().
_selectionBoolValues
List<bool> UnityToolbox.Item.Management.ItemDefinitionEditWindow._selectionBoolValues private
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and UnityToolbox.Item.Management.ItemDefinitionEditWindow.Init().
_selectionFields
List<FieldInfo> UnityToolbox.Item.Management.ItemDefinitionEditWindow._selectionFields private
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and UnityToolbox.Item.Management.ItemDefinitionEditWindow.Init().
_selectionFloatValues
List<float> UnityToolbox.Item.Management.ItemDefinitionEditWindow._selectionFloatValues private
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and UnityToolbox.Item.Management.ItemDefinitionEditWindow.Init().
_selectionIntValues
List<int> UnityToolbox.Item.Management.ItemDefinitionEditWindow._selectionIntValues private
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and UnityToolbox.Item.Management.ItemDefinitionEditWindow.Init().
_selectionStringValues
List<string> UnityToolbox.Item.Management.ItemDefinitionEditWindow._selectionStringValues private
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and UnityToolbox.Item.Management.ItemDefinitionEditWindow.Init().
_status
string UnityToolbox.Item.Management.ItemDefinitionEditWindow._status private
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.OnGUI(), and UnityToolbox.Item.Management.ItemDefinitionEditWindow.UpdateStatus().
_type
Type UnityToolbox.Item.Management.ItemDefinitionEditWindow._type private
Referenced by UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and UnityToolbox.Item.Management.ItemDefinitionEditWindow.Init().
Property Documentation
CurrentItemDefinition
ItemDefinition UnityToolbox.Item.Management.ItemDefinitionEditWindow.CurrentItemDefinition set