UnityToolbox: UnityToolbox.Item.Management.ItemManagerWindow Class Reference
UnityToolbox.Item.Management.ItemManagerWindow Class Reference
Public Member Functions
void OnAfterAssemblyReload ()
Static Public Member Functions
static void Open ()
Private Member Functions
void InitializeWindow ()
void Awake ()
void OnGUI ()
void FixFaultyItemsByGUID ()
void DisplaySettingsTab ()
void DisplayScopesTab ()
void DisplayItemsTab ()
void DrawLineHorizontal ()
void UpdateStatus (string status)
void SetupListsForItemType (Type type)
void DrawListScopes ()
void DrawCreationFields ()
void DrawListItems ()
void DrawAddDefinedItem ()
void OnEnable ()
void OnDisable ()
Static Private Member Functions
static void DisplayWindow ()
Private Attributes
int _selectedTab = 0
string _assetPathInProject
Vector2 _scrollPosScope
string _scopeName
Vector2 _scrollPosItemDefinition
string _itemDefinitionName
int _selectedScope
Texture2D _itemDefinitionIcon
GameObject _itemDefinitionPrefab
int _maxStackCount
int _selectedType
List< Type > _itemDefinitionTypes
Vector2 _scrollPosCreation
List< bool > _selectionBoolValues
List< string > _selectionStringValues
List< float > _selectionFloatValues
List< int > _selectionIntValues
List< FieldInfo > _selectionFields
string _searchIDString
int _selectedSearch
bool _foldoutAdd
bool _foldoutSearch
string _status
bool _waitReinitForRepaint
ItemDefinitionErrorWindow _errorWindow
Static Private Attributes
const int IDS = 0
const int SCOPES = 1
const int SETTINGS = 2
Member Function Documentation
Awake()
void UnityToolbox.Item.Management.ItemManagerWindow.Awake () private
References UnityToolbox.Item.Management.ItemManagerWindow.InitializeWindow().
DisplayItemsTab()
void UnityToolbox.Item.Management.ItemManagerWindow.DisplayItemsTab () private
References UnityToolbox.Item.Management.ItemManagerWindow._foldoutAdd, UnityToolbox.Item.Management.ItemManagerWindow._foldoutSearch, UnityToolbox.Item.Management.ItemManagerWindow._itemDefinitionTypes, UnityToolbox.Item.Management.ItemManagerWindow._searchIDString, UnityToolbox.Item.Management.ItemManagerWindow._selectedSearch, UnityToolbox.Item.Management.ItemManagerWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemManagerWindow.DrawCreationFields(), UnityToolbox.Item.Management.ItemManagerWindow.DrawLineHorizontal(), and UnityToolbox.Item.Management.ItemManagerWindow.DrawListItems().
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.OnGUI().
DisplayScopesTab()
void UnityToolbox.Item.Management.ItemManagerWindow.DisplayScopesTab () private
References UnityToolbox.Item.Management.ItemManagerWindow._scopeName, UnityToolbox.Item.Management.Itemizer.AddItemScope(), UnityToolbox.Item.Management.ItemManagerWindow.DrawLineHorizontal(), UnityToolbox.Item.Management.ItemManagerWindow.DrawListScopes(), UnityToolbox.Item.Management.Itemizer.Instance, UnityToolbox.Item.Management.ItemManagerWindow.UpdateStatus(), and UnityToolbox.Item.Management.Itemizer.WriteData().
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.OnGUI().
DisplaySettingsTab()
void UnityToolbox.Item.Management.ItemManagerWindow.DisplaySettingsTab () private
References UnityToolbox.Item.Management.ItemManagerWindow._assetPathInProject, UnityToolbox.Item.Management.ItemManagerWindow._itemDefinitionTypes, UnityToolbox.Item.Management.ItemManagerWindow._selectedType, UnityToolbox.Item.Management.ItemManagerWindow.DrawLineHorizontal(), UnityToolbox.Item.Management.Itemizer.GetAllInheritedItemDefinitionTypes(), UnityToolbox.Item.Management.Itemizer.Initialize(), UnityToolbox.Item.Management.Itemizer.Instance, UnityToolbox.Item.Management.ItemManagerWindow.SetupListsForItemType(), ResourcesUtil.TrySetValidPath(), and UnityToolbox.Item.Management.ItemManagerWindow.UpdateStatus().
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.OnGUI().
DisplayWindow()
static void UnityToolbox.Item.Management.ItemManagerWindow.DisplayWindow () static private
DrawAddDefinedItem()
void UnityToolbox.Item.Management.ItemManagerWindow.DrawAddDefinedItem () private
References UnityToolbox.Item.Management.ItemManagerWindow._itemDefinitionIcon, UnityToolbox.Item.Management.ItemManagerWindow._itemDefinitionName, UnityToolbox.Item.Management.ItemManagerWindow._itemDefinitionPrefab, UnityToolbox.Item.Management.ItemManagerWindow._itemDefinitionTypes, UnityToolbox.Item.Management.ItemManagerWindow._maxStackCount, UnityToolbox.Item.Management.ItemManagerWindow._selectedScope, UnityToolbox.Item.Management.ItemManagerWindow._selectedType, UnityToolbox.Item.Management.ItemManagerWindow._selectionBoolValues, UnityToolbox.Item.Management.ItemManagerWindow._selectionFields, UnityToolbox.Item.Management.ItemManagerWindow._selectionFloatValues, UnityToolbox.Item.Management.ItemManagerWindow._selectionIntValues, UnityToolbox.Item.Management.ItemManagerWindow._selectionStringValues, UnityToolbox.Item.Management.Itemizer.AddItemDefinition(), UnityToolbox.Item.Management.Itemizer.Instance, UnityToolbox.Item.Management.Itemizer.ItemScopes, UnityToolbox.Item.Management.ItemManagerWindow.UpdateStatus(), and UnityToolbox.Item.Management.Itemizer.WriteData().
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DisplayItemsTab().
DrawCreationFields()
void UnityToolbox.Item.Management.ItemManagerWindow.DrawCreationFields () private
References UnityToolbox.Item.Management.ItemManagerWindow._itemDefinitionIcon, UnityToolbox.Item.Management.ItemManagerWindow._itemDefinitionName, UnityToolbox.Item.Management.ItemManagerWindow._itemDefinitionPrefab, UnityToolbox.Item.Management.ItemManagerWindow._itemDefinitionTypes, UnityToolbox.Item.Management.ItemManagerWindow._maxStackCount, UnityToolbox.Item.Management.ItemManagerWindow._scrollPosCreation, UnityToolbox.Item.Management.ItemManagerWindow._selectedScope, UnityToolbox.Item.Management.ItemManagerWindow._selectedType, UnityToolbox.Item.Management.ItemManagerWindow._selectionBoolValues, UnityToolbox.Item.Management.ItemManagerWindow._selectionFields, UnityToolbox.Item.Management.ItemManagerWindow._selectionFloatValues, UnityToolbox.Item.Management.ItemManagerWindow._selectionIntValues, UnityToolbox.Item.Management.ItemManagerWindow._selectionStringValues, UnityToolbox.Item.ItemDefinition.DEVIDER, UnityToolbox.Item.Management.Itemizer.Instance, UnityToolbox.Item.Management.Itemizer.ItemScopes, and UnityToolbox.Item.Management.ItemManagerWindow.SetupListsForItemType().
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DisplayItemsTab().
DrawLineHorizontal()
void UnityToolbox.Item.Management.ItemManagerWindow.DrawLineHorizontal () private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DisplayItemsTab(), UnityToolbox.Item.Management.ItemManagerWindow.DisplayScopesTab(), UnityToolbox.Item.Management.ItemManagerWindow.DisplaySettingsTab(), UnityToolbox.Item.Management.ItemManagerWindow.DrawListItems(), and UnityToolbox.Item.Management.ItemManagerWindow.OnGUI().
DrawListItems()
void UnityToolbox.Item.Management.ItemManagerWindow.DrawListItems () private
References UnityToolbox.Item.Management.ItemManagerWindow._itemDefinitionTypes, UnityToolbox.Item.Management.ItemManagerWindow._scrollPosItemDefinition, UnityToolbox.Item.Management.ItemManagerWindow._searchIDString, UnityToolbox.Item.Management.ItemManagerWindow._selectedSearch, UnityToolbox.Item.Management.ItemManagerWindow.DrawLineHorizontal(), UnityToolbox.Item.ItemDefinition.GetQualifiedName(), UnityToolbox.Item.Management.Itemizer.Instance, UnityToolbox.Item.Management.Itemizer.ItemDefinitions, UnityToolbox.Item.ItemDefinition.Name, UnityToolbox.Item.Management.ItemDefinitionEditWindow.Open(), UnityToolbox.Item.Management.Itemizer.RemoveItemDefinition(), UnityToolbox.Item.Management.ItemManagerWindow.UpdateStatus(), and UnityToolbox.Item.Management.Itemizer.WriteData().
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DisplayItemsTab().
DrawListScopes()
void UnityToolbox.Item.Management.ItemManagerWindow.DrawListScopes () private
References UnityToolbox.Item.Management.ItemManagerWindow._scrollPosScope, UnityToolbox.Item.Management.Itemizer.DefaultScope, UnityToolbox.Item.Management.ItemScope.Equals(), UnityToolbox.Item.Management.Itemizer.Instance, UnityToolbox.Item.Management.Itemizer.ItemScopes, UnityToolbox.Item.Management.ItemScope.Name, UnityToolbox.Item.Management.ItemScopeEditWindow.Open(), UnityToolbox.Item.Management.Itemizer.RemoveItemScope(), UnityToolbox.Item.Management.ItemManagerWindow.UpdateStatus(), and UnityToolbox.Item.Management.Itemizer.WriteData().
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DisplayScopesTab().
FixFaultyItemsByGUID()
void UnityToolbox.Item.Management.ItemManagerWindow.FixFaultyItemsByGUID () private
References UnityToolbox.Item.Management.Itemizer.EditItemDefinition(), UnityToolbox.Item.ItemDefinition.Equals(), UnityToolbox.Item.Management.Itemizer.FaultyItemDefinitions, UnityToolbox.Item.ItemDefinition.Icon, UnityToolbox.Item.ItemDefinition.IconGUID, UnityToolbox.Item.ItemDefinition.IconPath, UnityToolbox.Item.Management.Itemizer.Instance, UnityToolbox.Item.ItemDefinition.MaxStackCount, UnityToolbox.Item.ItemDefinition.Name, UnityToolbox.Item.ItemDefinition.Prefab, UnityToolbox.Item.ItemDefinition.PrefabGUID, UnityToolbox.Item.ItemDefinition.PrefabPath, UnityToolbox.Item.ItemDefinition.Scope, UnityToolbox.Item.Management.ItemManagerWindow.UpdateStatus(), and UnityToolbox.Item.Management.Itemizer.WriteData().
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.InitializeWindow().
InitializeWindow()
void UnityToolbox.Item.Management.ItemManagerWindow.InitializeWindow () private
References UnityToolbox.Item.Management.ItemManagerWindow._assetPathInProject, UnityToolbox.Item.Management.ItemManagerWindow._itemDefinitionTypes, UnityToolbox.Item.Management.ItemManagerWindow._searchIDString, UnityToolbox.Item.Management.ItemManagerWindow._selectedType, UnityToolbox.Item.Management.ItemManagerWindow.FixFaultyItemsByGUID(), UnityToolbox.Item.Management.Itemizer.GetAllInheritedItemDefinitionTypes(), ResourcesUtil.GetProjectPath(), UnityToolbox.Item.Management.Itemizer.Initialize(), UnityToolbox.Item.Management.Itemizer.Initialized, UnityToolbox.Item.Management.Itemizer.Instance, UnityToolbox.Item.Management.ItemManagerWindow.SetupListsForItemType(), and UnityToolbox.Item.Management.ItemManagerWindow.UpdateStatus().
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.Awake(), and UnityToolbox.Item.Management.ItemManagerWindow.OnAfterAssemblyReload().
OnAfterAssemblyReload()
void UnityToolbox.Item.Management.ItemManagerWindow.OnAfterAssemblyReload ()
References UnityToolbox.Item.Management.ItemManagerWindow.InitializeWindow().
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.OnDisable(), and UnityToolbox.Item.Management.ItemManagerWindow.OnEnable().
OnDisable()
void UnityToolbox.Item.Management.ItemManagerWindow.OnDisable () private
References UnityToolbox.Item.Management.ItemManagerWindow.OnAfterAssemblyReload().
OnEnable()
void UnityToolbox.Item.Management.ItemManagerWindow.OnEnable () private
References UnityToolbox.Item.Management.ItemManagerWindow.OnAfterAssemblyReload().
OnGUI()
void UnityToolbox.Item.Management.ItemManagerWindow.OnGUI () private
References UnityToolbox.Item.Management.ItemManagerWindow._errorWindow, UnityToolbox.Item.Management.ItemManagerWindow._selectedTab, UnityToolbox.Item.Management.ItemManagerWindow._status, UnityToolbox.Item.Management.ItemManagerWindow.DisplayItemsTab(), UnityToolbox.Item.Management.ItemManagerWindow.DisplayScopesTab(), UnityToolbox.Item.Management.ItemManagerWindow.DisplaySettingsTab(), UnityToolbox.Item.Management.ItemManagerWindow.DrawLineHorizontal(), UnityToolbox.Item.Management.Itemizer.FaultyItemDefinitions, UnityToolbox.Item.Management.ItemManagerWindow.IDS, UnityToolbox.Item.Management.Itemizer.Initialized, UnityToolbox.Item.Management.Itemizer.Instance, UnityToolbox.Item.Management.ItemDefinitionErrorWindow.Open(), UnityToolbox.Item.Management.ItemManagerWindow.SCOPES, UnityToolbox.Item.Management.ItemManagerWindow.SETTINGS, and UnityToolbox.Item.Management.ItemManagerWindow.UpdateStatus().
Open()
static void UnityToolbox.Item.Management.ItemManagerWindow.Open () static
SetupListsForItemType()
void UnityToolbox.Item.Management.ItemManagerWindow.SetupListsForItemType (Type type) private
References UnityToolbox.Item.Management.ItemManagerWindow._selectionBoolValues, UnityToolbox.Item.Management.ItemManagerWindow._selectionFields, UnityToolbox.Item.Management.ItemManagerWindow._selectionFloatValues, UnityToolbox.Item.Management.ItemManagerWindow._selectionIntValues, and UnityToolbox.Item.Management.ItemManagerWindow._selectionStringValues.
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DisplaySettingsTab(), UnityToolbox.Item.Management.ItemManagerWindow.DrawCreationFields(), and UnityToolbox.Item.Management.ItemManagerWindow.InitializeWindow().
UpdateStatus()
void UnityToolbox.Item.Management.ItemManagerWindow.UpdateStatus (string status) private
References UnityToolbox.Item.Management.ItemManagerWindow._status.
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DisplayScopesTab(), UnityToolbox.Item.Management.ItemManagerWindow.DisplaySettingsTab(), UnityToolbox.Item.Management.ItemManagerWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemManagerWindow.DrawListItems(), UnityToolbox.Item.Management.ItemManagerWindow.DrawListScopes(), UnityToolbox.Item.Management.ItemManagerWindow.FixFaultyItemsByGUID(), UnityToolbox.Item.Management.ItemManagerWindow.InitializeWindow(), and UnityToolbox.Item.Management.ItemManagerWindow.OnGUI().
Member Data Documentation
_assetPathInProject
string UnityToolbox.Item.Management.ItemManagerWindow._assetPathInProject private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DisplaySettingsTab(), and UnityToolbox.Item.Management.ItemManagerWindow.InitializeWindow().
_errorWindow
ItemDefinitionErrorWindow UnityToolbox.Item.Management.ItemManagerWindow._errorWindow private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.OnGUI().
_foldoutAdd
bool UnityToolbox.Item.Management.ItemManagerWindow._foldoutAdd private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DisplayItemsTab().
_foldoutSearch
bool UnityToolbox.Item.Management.ItemManagerWindow._foldoutSearch private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DisplayItemsTab().
_itemDefinitionIcon
Texture2D UnityToolbox.Item.Management.ItemManagerWindow._itemDefinitionIcon private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DrawAddDefinedItem(), and UnityToolbox.Item.Management.ItemManagerWindow.DrawCreationFields().
_itemDefinitionName
string UnityToolbox.Item.Management.ItemManagerWindow._itemDefinitionName private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DrawAddDefinedItem(), and UnityToolbox.Item.Management.ItemManagerWindow.DrawCreationFields().
_itemDefinitionPrefab
GameObject UnityToolbox.Item.Management.ItemManagerWindow._itemDefinitionPrefab private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DrawAddDefinedItem(), and UnityToolbox.Item.Management.ItemManagerWindow.DrawCreationFields().
_itemDefinitionTypes
List<Type> UnityToolbox.Item.Management.ItemManagerWindow._itemDefinitionTypes private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DisplayItemsTab(), UnityToolbox.Item.Management.ItemManagerWindow.DisplaySettingsTab(), UnityToolbox.Item.Management.ItemManagerWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemManagerWindow.DrawCreationFields(), UnityToolbox.Item.Management.ItemManagerWindow.DrawListItems(), and UnityToolbox.Item.Management.ItemManagerWindow.InitializeWindow().
_maxStackCount
int UnityToolbox.Item.Management.ItemManagerWindow._maxStackCount private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DrawAddDefinedItem(), and UnityToolbox.Item.Management.ItemManagerWindow.DrawCreationFields().
_scopeName
string UnityToolbox.Item.Management.ItemManagerWindow._scopeName private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DisplayScopesTab().
_scrollPosCreation
Vector2 UnityToolbox.Item.Management.ItemManagerWindow._scrollPosCreation private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DrawCreationFields().
_scrollPosItemDefinition
Vector2 UnityToolbox.Item.Management.ItemManagerWindow._scrollPosItemDefinition private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DrawListItems().
_scrollPosScope
Vector2 UnityToolbox.Item.Management.ItemManagerWindow._scrollPosScope private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DrawListScopes().
_searchIDString
string UnityToolbox.Item.Management.ItemManagerWindow._searchIDString private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DisplayItemsTab(), UnityToolbox.Item.Management.ItemManagerWindow.DrawListItems(), and UnityToolbox.Item.Management.ItemManagerWindow.InitializeWindow().
_selectedScope
int UnityToolbox.Item.Management.ItemManagerWindow._selectedScope private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DrawAddDefinedItem(), and UnityToolbox.Item.Management.ItemManagerWindow.DrawCreationFields().
_selectedSearch
int UnityToolbox.Item.Management.ItemManagerWindow._selectedSearch private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DisplayItemsTab(), and UnityToolbox.Item.Management.ItemManagerWindow.DrawListItems().
_selectedTab
int UnityToolbox.Item.Management.ItemManagerWindow._selectedTab = 0 private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.OnGUI().
_selectedType
int UnityToolbox.Item.Management.ItemManagerWindow._selectedType private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DisplaySettingsTab(), UnityToolbox.Item.Management.ItemManagerWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemManagerWindow.DrawCreationFields(), and UnityToolbox.Item.Management.ItemManagerWindow.InitializeWindow().
_selectionBoolValues
List<bool> UnityToolbox.Item.Management.ItemManagerWindow._selectionBoolValues private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemManagerWindow.DrawCreationFields(), and UnityToolbox.Item.Management.ItemManagerWindow.SetupListsForItemType().
_selectionFields
List<FieldInfo> UnityToolbox.Item.Management.ItemManagerWindow._selectionFields private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemManagerWindow.DrawCreationFields(), and UnityToolbox.Item.Management.ItemManagerWindow.SetupListsForItemType().
_selectionFloatValues
List<float> UnityToolbox.Item.Management.ItemManagerWindow._selectionFloatValues private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemManagerWindow.DrawCreationFields(), and UnityToolbox.Item.Management.ItemManagerWindow.SetupListsForItemType().
_selectionIntValues
List<int> UnityToolbox.Item.Management.ItemManagerWindow._selectionIntValues private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemManagerWindow.DrawCreationFields(), and UnityToolbox.Item.Management.ItemManagerWindow.SetupListsForItemType().
_selectionStringValues
List<string> UnityToolbox.Item.Management.ItemManagerWindow._selectionStringValues private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.DrawAddDefinedItem(), UnityToolbox.Item.Management.ItemManagerWindow.DrawCreationFields(), and UnityToolbox.Item.Management.ItemManagerWindow.SetupListsForItemType().
_status
string UnityToolbox.Item.Management.ItemManagerWindow._status private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.OnGUI(), and UnityToolbox.Item.Management.ItemManagerWindow.UpdateStatus().
_waitReinitForRepaint
bool UnityToolbox.Item.Management.ItemManagerWindow._waitReinitForRepaint private
IDS
const int UnityToolbox.Item.Management.ItemManagerWindow.IDS = 0 static private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.OnGUI().
SCOPES
const int UnityToolbox.Item.Management.ItemManagerWindow.SCOPES = 1 static private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.OnGUI().
SETTINGS
const int UnityToolbox.Item.Management.ItemManagerWindow.SETTINGS = 2 static private
Referenced by UnityToolbox.Item.Management.ItemManagerWindow.OnGUI().