UnityToolbox: Item.Management.ItemDefinitionSelectionWindow Class Reference
Item.Management.ItemDefinitionSelectionWindow Class Reference
Static Public Member Functions
static ItemDefinitionSelectionWindow Open ()
Events
Action< ItemDefinition > OnItemDefinitionSelected
Private Member Functions
void Awake ()
void OnGUI ()
void DrawLineHorizontal ()
void UpdateStatus (string status)
Private Attributes
Vector2 _scrollPos
string _searchString
bool _foldoutSearch
string _status
Member Function Documentation
Awake()
void Item.Management.ItemDefinitionSelectionWindow.Awake () private
References Item.Management.ItemDefinitionSelectionWindow._searchString, Item.Management.Itemizer.Initialize(), Item.Management.Itemizer.Instance, and Item.Management.ItemDefinitionSelectionWindow.UpdateStatus().
DrawLineHorizontal()
void Item.Management.ItemDefinitionSelectionWindow.DrawLineHorizontal () private
Referenced by Item.Management.ItemDefinitionSelectionWindow.OnGUI().
OnGUI()
void Item.Management.ItemDefinitionSelectionWindow.OnGUI () private
References Item.Management.ItemDefinitionSelectionWindow._foldoutSearch, Item.Management.ItemDefinitionSelectionWindow._scrollPos, Item.Management.ItemDefinitionSelectionWindow._searchString, Item.Management.ItemDefinitionSelectionWindow._status, Item.Management.ItemDefinitionSelectionWindow.DrawLineHorizontal(), Item.ItemDefinition.GetQualifiedName(), Item.Management.Itemizer.Instance, Item.Management.Itemizer.ItemDefinitions, Item.Management.ItemDefinitionSelectionWindow.OnItemDefinitionSelected, Item.Management.ItemDefinitionEditWindow.Open(), Item.Management.Itemizer.RemoveItemDefinition(), Item.Management.ItemDefinitionSelectionWindow.UpdateStatus(), and Item.Management.Itemizer.WriteData().
Open()
static ItemDefinitionSelectionWindow Item.Management.ItemDefinitionSelectionWindow.Open () static
Referenced by Item.Management.ItemDefinitionDrawer.OnGUI().
UpdateStatus()
void Item.Management.ItemDefinitionSelectionWindow.UpdateStatus (string status) private
References Item.Management.ItemDefinitionSelectionWindow._status.
Referenced by Item.Management.ItemDefinitionSelectionWindow.Awake(), and Item.Management.ItemDefinitionSelectionWindow.OnGUI().
Member Data Documentation
_foldoutSearch
bool Item.Management.ItemDefinitionSelectionWindow._foldoutSearch private
Referenced by Item.Management.ItemDefinitionSelectionWindow.OnGUI().
_scrollPos
Vector2 Item.Management.ItemDefinitionSelectionWindow._scrollPos private
Referenced by Item.Management.ItemDefinitionSelectionWindow.OnGUI().
_searchString
string Item.Management.ItemDefinitionSelectionWindow._searchString private
Referenced by Item.Management.ItemDefinitionSelectionWindow.Awake(), and Item.Management.ItemDefinitionSelectionWindow.OnGUI().
_status
string Item.Management.ItemDefinitionSelectionWindow._status private
Referenced by Item.Management.ItemDefinitionSelectionWindow.OnGUI(), and Item.Management.ItemDefinitionSelectionWindow.UpdateStatus().
Event Documentation
OnItemDefinitionSelected
Action<ItemDefinition> Item.Management.ItemDefinitionSelectionWindow.OnItemDefinitionSelected
Referenced by Item.Management.ItemDefinitionSelectionWindow.OnGUI().