UnityToolbox: Movement2DSide Class Reference
Movement2DSide Class Reference
An implementation of MovementBase which works for a side scroller.
Public Member Functions
override void Move (Vector3 direction)
Updates the player movement with the direction data.
override void MoveWithStrength (Vector3 direction, Vector3 strength)
Updates the player movement with the direction data and defined strength .
override Vector3 GetCurrentVelocity ()
override void Jump ()
Updates the player movement to execute a jump.
Public Member Functions inherited from MovementBase
void UpdateMovementState ()
Updates the current state of movement. MovementState.Moving does not mean that the current velocity is > 0!
abstract void Move (Vector3 direction)
Updates the player movement with the direction data.
abstract void Jump ()
Updates the player movement to execute a jump.
abstract void MoveWithStrength (Vector3 direction, Vector3 strength)
Updates the player movement with the direction data and defined strength .
abstract Vector3 GetCurrentVelocity ()
Properties
Transform GroundedTransformTwo [get]
Properties inherited from MovementBase
Transform GroundedTransform [get]
bool IsMovementLocked [get, set]
bool IsClimbingLocked [get, set]
bool IsJumpingLocked [get, set]
MovementState CurrentMovementState [get]
bool Grounded [get]
bool AnimationGrounded [get]
bool Climbing [get]
bool IsToggledMoving [get]
Private Member Functions
void Start ()
void FixedUpdate ()
IEnumerator DelayGrounded ()
IEnumerator DelayUngrounded ()
IEnumerator PauseJumping ()
void OnTriggerEnter2D (Collider2D other)
void OnTriggerExit2D (Collider2D other)
Private Attributes
Transform _groundedTransformTwo
RaycastHit2D _groundedHit
Rigidbody2D _rb
float _oldGravityScale
bool _mayJump
LayerMask _layerMasksToIgnore
Additional Inherited Members
Protected Attributes inherited from MovementBase
float _speed
Defines the speed of the player.
float _toggledSpeed
Defines the toggledSpeed of the player.
float _jumpForce
Defines the amount of force (speed) for a jump.
float _climbingForce
Defines the amount of force (speed) for climbing.
string _movementActionName
The action name for the movement controls. Needs to be defined as a Vector2D.
string _toggleSpeedActionName
The action name for the changing the players speed.
string _jumpActionName
The action name for the jump control.
string _attackActionName
The action name for the attack control.
Transform _groundedTransform
The transform defines the position where to define if the player is grounded or not.
PlayerInput _input
The player input.
bool _isMovementLocked
Defines whether the movement should be locked or not. The PlayerEventManager also has events for this.
bool _isClimbingLocked
Defines whether the climbing should be locked or not.
bool _isJumpingLocked
Defines whether the jumping should be locked or not.
MovementState _currentMovementState
The current movement state. (MovementState.Climbing, MovementState.Moving, MovementState.Jumping) MovementState.Moving does not mean that the current velocity is > 0.
LayerMask _climbingMask
The climbing layer mask, which defines which objects should be read as climbable.
LayerMask _jumpingMask
The jumping layer mask, which defines which objects should be read as jumpable.
bool _grounded
Defines whether the player is grounded.
bool _animationGrounded
Defines whether the animation should be counted as grounded. A usecase would be a delay between the actual MovementBase.Grounded.
bool _climbing
Defines whether the player is climbing.
bool _isToggledMoving
Member Function Documentation
DelayGrounded()
IEnumerator Movement2DSide.DelayGrounded () private
Referenced by FixedUpdate().
DelayUngrounded()
IEnumerator Movement2DSide.DelayUngrounded () private
References MovementBase._grounded, MovementBase._groundedTransform, _groundedTransformTwo, _layerMasksToIgnore, and _oldGravityScale.
Referenced by FixedUpdate().
FixedUpdate()
void Movement2DSide.FixedUpdate () private
References MovementBase._animationGrounded, MovementBase._currentMovementState, _groundedHit, MovementBase._groundedTransform, _groundedTransformTwo, MovementBase._input, MovementBase._isMovementLocked, _layerMasksToIgnore, MovementBase._movementActionName, _rb, DelayGrounded(), DelayUngrounded(), Move(), and MovementBase.UpdateMovementState().
GetCurrentVelocity()
override Vector3 Movement2DSide.GetCurrentVelocity () virtual
Returns
Returns the current velocity of the player.
Implements MovementBase.
References _rb.
Jump()
override void Movement2DSide.Jump () virtual
Implements MovementBase.
Move()
override void Movement2DSide.Move (Vector3 direction) virtual
Parameters
direction
Implements MovementBase.
References MovementBase._climbingForce, MovementBase._currentMovementState, MovementBase._jumpForce, _mayJump, _rb, MovementBase._speed, and PauseJumping().
Referenced by FixedUpdate().
MoveWithStrength()
override void Movement2DSide.MoveWithStrength (Vector3 direction, Vector3 strength) virtual
Parameters
direction
strength
Implements MovementBase.
References MovementBase._climbingForce, MovementBase._currentMovementState, MovementBase._jumpForce, _mayJump, _rb, MovementBase._speed, and PauseJumping().
OnTriggerEnter2D()
void Movement2DSide.OnTriggerEnter2D (Collider2D other) private
References MovementBase._climbing, and MovementBase._climbingMask.
OnTriggerExit2D()
void Movement2DSide.OnTriggerExit2D (Collider2D other) private
References MovementBase._climbing, MovementBase._climbingMask, and _oldGravityScale.
PauseJumping()
IEnumerator Movement2DSide.PauseJumping () private
References _mayJump.
Referenced by Move(), and MoveWithStrength().
Start()
void Movement2DSide.Start () private
References _mayJump, _oldGravityScale, and _rb.
Member Data Documentation
_groundedHit
RaycastHit2D Movement2DSide._groundedHit private
Referenced by FixedUpdate().
_groundedTransformTwo
Transform Movement2DSide._groundedTransformTwo private
Referenced by DelayUngrounded(), and FixedUpdate().
_layerMasksToIgnore
LayerMask Movement2DSide._layerMasksToIgnore private
Referenced by DelayUngrounded(), and FixedUpdate().
_mayJump
bool Movement2DSide._mayJump private
Referenced by Move(), MoveWithStrength(), PauseJumping(), and Start().
_oldGravityScale
float Movement2DSide._oldGravityScale private
Referenced by DelayUngrounded(), OnTriggerExit2D(), and Start().
_rb
Rigidbody2D Movement2DSide._rb private
Referenced by FixedUpdate(), GetCurrentVelocity(), Move(), MoveWithStrength(), and Start().
Property Documentation
GroundedTransformTwo
Transform Movement2DSide.GroundedTransformTwo get