UnityToolbox Documentation: LocalisationEditScopeWindow Class Reference
LocalisationEditScopeWindow Class Reference
Public Member Functions
void OnGUI ()
Static Public Member Functions
static void Open (LocalisationScope scope)
Properties
LocalisationScope Scope [set]
Private Member Functions
void Awake ()
void ScopeEdited (LocalisationScope scope)
Private Attributes
LocalisationScope _scope
string _newScopeName
string _status
Member Function Documentation
Awake()
void LocalisationEditScopeWindow.Awake () private
References ScopeEdited().
OnGUI()
void LocalisationEditScopeWindow.OnGUI ()
References _newScopeName, _scope, _status, Localizer.EditScope(), Localizer.Instance, ScopeEdited(), and Localizer.WriteData().
Open()
static void LocalisationEditScopeWindow.Open (LocalisationScope scope) static
Referenced by LocalisationManagerWindow.DisplayScopesTab().
ScopeEdited()
void LocalisationEditScopeWindow.ScopeEdited (LocalisationScope scope) private
References _scope, LocalisationScope.Equals(), and ScopeEdited().
Referenced by Awake(), OnGUI(), and ScopeEdited().
Member Data Documentation
_newScopeName
string LocalisationEditScopeWindow._newScopeName private
Referenced by OnGUI().
_scope
LocalisationScope LocalisationEditScopeWindow._scope private
Referenced by OnGUI(), and ScopeEdited().
_status
string LocalisationEditScopeWindow._status private
Referenced by OnGUI().
Property Documentation
Scope
LocalisationScope LocalisationEditScopeWindow.Scope set