UnityToolbox: MenuManager Class Reference
MenuManager Class Reference
This manager takes care of all menu related tasks. That is, sorting within a hierarchy and switching between visible canvases. The menus are called with types also defined here. Requires the UIEventManager.
Public Member Functions
void SetActiveMenu (Menu menu)
Sets the active menu with a given <see cref="Menu". Disables the current if there is one. Null will disable any active menu and enable the overlay if there is one set.
void ToggleMenu (int type, int menuIndex)
Toggles a menu by the given ID which references to a type. See MenuManager.MenuTypesForEditor. A menu can only be activated if there is no current already active.
void ToggleMenuManager ()
Toogles the MenuManager. Useful if UI interaction should be locked.
void ToggleMenuManager (bool isEnabled)
Toogles the MenuManager. Useful if UI interaction should be locked.
void OnBeforeSerialize ()
void OnAfterDeserialize ()
Public Member Functions inherited from Module
virtual void Awake ()
Static Public Member Functions
static List< string > GetAllMenusOfType (int type)
Public Attributes
int OverlayType
Static Public Attributes
static List< MenuType > MenuTypesForEditor = new List<MenuType>()
All menu types defined by the manager.
static List< string > MenuTypeNamesForEditor = new List<string>()
Properties
bool IsEnabled [get]
MenuType CurrentActiveMenuType [get]
Member Function Documentation
GetAllMenusOfType()
static List< string > MenuManager.GetAllMenusOfType (int type) static
References MenuType.Menus, MenuType.MenuTypeID, and MenuTypesForEditor.
OnAfterDeserialize()
void MenuManager.OnAfterDeserialize ()
References MenuTypeNamesForEditor, and MenuTypesForEditor.
OnBeforeSerialize()
void MenuManager.OnBeforeSerialize ()
References MenuTypeNamesForEditor, and MenuTypesForEditor.
SetActiveMenu()
void MenuManager.SetActiveMenu (Menu menu)
Parameters
menu
References MenuType.Menus.
Referenced by ToggleMenu().
ToggleMenu()
void MenuManager.ToggleMenu (int type, int menuIndex)
Parameters
type The ID which references to a type.
References MenuType.Menus, MenuType.MenuTypeID, and SetActiveMenu().
ToggleMenuManager() [1/2]
void MenuManager.ToggleMenuManager ()
ToggleMenuManager() [2/2]
void MenuManager.ToggleMenuManager (bool isEnabled)
Parameters
isEnabled
Member Data Documentation
MenuTypeNamesForEditor
List<string> MenuManager.MenuTypeNamesForEditor = new List<string>() static
Referenced by OnAfterDeserialize(), and OnBeforeSerialize().
MenuTypesForEditor
List<MenuType> MenuManager.MenuTypesForEditor = new List<MenuType>() static
Referenced by GetAllMenusOfType(), OnAfterDeserialize(), and OnBeforeSerialize().
OverlayType
int MenuManager.OverlayType
Property Documentation
CurrentActiveMenuType
MenuType MenuManager.CurrentActiveMenuType get
Referenced by DisplayDialog.UpdateDialog().
IsEnabled
bool MenuManager.IsEnabled get