UnityToolbox: ImageSliderSetting Class Reference
ImageSliderSetting Class Reference
An alternative to the Unity Slider. The fill area of this is a cropped instead of scaled image.
Public Types
enum SliderOption { Effects , Music , Ambience , Mouse_Sensitivity }
Public Member Functions
void Awake ()
void UpdateValues (float value)
Updates the values set with the slider to the preferences and manager. To set up the slider, set a EventTrigger to execute this on end drag.
Member Enumeration Documentation
SliderOption
enum ImageSliderSetting.SliderOption
Enumerator
Effects
Music
Ambience
Mouse_Sensitivity
Member Function Documentation
Awake()
void ImageSliderSetting.Awake ()
References UpdateValues().
UpdateValues()
void ImageSliderSetting.UpdateValues (float value)
References AudioMixer.PlayRandomSource().
Referenced by Awake().