UnityToolbox Documentation: LocalisationSelectionWindow Class Reference
LocalisationSelectionWindow Class Reference
Static Public Member Functions
static LocalisationSelectionWindow Open ()
Events
Action< LocalisationID > OnIDSelected
Private Member Functions
void InitializeWindow ()
void Awake ()
void OnGUI ()
void DrawLineHorizontal ()
Private Attributes
Vector2 _scrollPos
int _selectedSearch
int _selectedLanguage
string _searchIDString
bool _foldoutSearch
Member Function Documentation
Awake()
void LocalisationSelectionWindow.Awake () private
References InitializeWindow().
DrawLineHorizontal()
void LocalisationSelectionWindow.DrawLineHorizontal () private
Referenced by OnGUI().
InitializeWindow()
void LocalisationSelectionWindow.InitializeWindow () private
References _searchIDString, ProjectPrefs.GetString(), Localizer.Initialize(), and Localizer.Instance.
Referenced by Awake().
OnGUI()
void LocalisationSelectionWindow.OnGUI () private
References _foldoutSearch, _scrollPos, _searchIDString, _selectedLanguage, _selectedSearch, LocalisationID.DEVIDER, DrawLineHorizontal(), Localizer.Instance, Localizer.LocalisationData, Localizer.LocalisationLanguages, OnIDSelected, LocalisationEditIDWindow.Open(), Localizer.RemoveLocalisation(), and Localizer.WriteData().
Open()
static LocalisationSelectionWindow LocalisationSelectionWindow.Open () static
Referenced by LocalisationDrawer.OnGUI().
Member Data Documentation
_foldoutSearch
bool LocalisationSelectionWindow._foldoutSearch private
Referenced by OnGUI().
_scrollPos
Vector2 LocalisationSelectionWindow._scrollPos private
Referenced by OnGUI().
_searchIDString
string LocalisationSelectionWindow._searchIDString private
Referenced by InitializeWindow(), and OnGUI().
_selectedLanguage
int LocalisationSelectionWindow._selectedLanguage private
Referenced by OnGUI().
_selectedSearch
int LocalisationSelectionWindow._selectedSearch private
Referenced by OnGUI().
Event Documentation
OnIDSelected
Action<LocalisationID> LocalisationSelectionWindow.OnIDSelected
Referenced by OnGUI().