UnityToolbox: ItemDefinitionSelectionWindow Class Reference
ItemDefinitionSelectionWindow Class Reference
Static Public Member Functions
static ItemDefinitionSelectionWindow Open ()
Events
Action< ItemDefinition > OnItemDefinitionSelected
Private Member Functions
void Awake ()
void OnGUI ()
void DrawLineHorizontal ()
void UpdateStatus (string status)
Private Attributes
Vector2 _scrollPos
string _searchString
bool _foldoutSearch
string _status
Member Function Documentation
Awake()
void ItemDefinitionSelectionWindow.Awake () private
References _searchString, Itemizer.Initialize(), Itemizer.Instance, and UpdateStatus().
DrawLineHorizontal()
void ItemDefinitionSelectionWindow.DrawLineHorizontal () private
Referenced by OnGUI().
OnGUI()
void ItemDefinitionSelectionWindow.OnGUI () private
References _foldoutSearch, _scrollPos, _searchString, _status, DrawLineHorizontal(), ItemDefinition.GetQualifiedName(), Itemizer.Instance, Itemizer.ItemDefinitions, OnItemDefinitionSelected, ItemDefinitionEditWindow.Open(), Itemizer.RemoveItemDefinition(), UpdateStatus(), and Itemizer.WriteData().
Open()
static ItemDefinitionSelectionWindow ItemDefinitionSelectionWindow.Open () static
Referenced by ItemDefinitionDrawer.OnGUI().
UpdateStatus()
void ItemDefinitionSelectionWindow.UpdateStatus (string status) private
References _status.
Referenced by Awake(), and OnGUI().
Member Data Documentation
_foldoutSearch
bool ItemDefinitionSelectionWindow._foldoutSearch private
Referenced by OnGUI().
_scrollPos
Vector2 ItemDefinitionSelectionWindow._scrollPos private
Referenced by OnGUI().
_searchString
string ItemDefinitionSelectionWindow._searchString private
Referenced by Awake(), and OnGUI().
_status
string ItemDefinitionSelectionWindow._status private
Referenced by OnGUI(), and UpdateStatus().
Event Documentation
OnItemDefinitionSelected
Action<ItemDefinition> ItemDefinitionSelectionWindow.OnItemDefinitionSelected
Referenced by OnGUI().