UnityToolbox Documentation: IDManager Class Reference
IDManager Class Reference
A manager which can generate unique IDs. Works in editor and runtime.
Public Member Functions
override void Awake ()
virtual void Awake ()
Static Public Member Functions
static void SceneChanged (Scene newScene)
Is called when the scene changes. See IDInitializer.
static string GetUniqueID ()
Generates a new unique ID.
static void RemoveID (string ID)
Removes an ID from the existing.
static void RegisterID (string ID)
Registeres a given ID. Throws an error if the ID is already known.
static string GetSceneNameOfID (string ID)
Extracts the scene name of the ID.
Static Private Member Functions
static void logIDs ()
Static Private Attributes
static HashSet< string > _usedIds
static string _currentSceneName
static char _separator = '/'
Member Function Documentation
Awake()
override void IDManager.Awake () virtual
Reimplemented from Module.
References SceneChanged().
GetSceneNameOfID()
static string IDManager.GetSceneNameOfID (string ID) static
Parameters
ID The ID to read its scene from.
Returns
A scene name.
References _separator.
Referenced by SaveGameManager.Load(), SaveGameManager.LoadSaved(), and SaveGameManager.SpawnSaved().
GetUniqueID()
static string IDManager.GetUniqueID () static
Returns
A unique ID.
References _currentSceneName, _separator, and _usedIds.
Referenced by Saveable.Awake(), InventoryBase.OnValidate(), ParentIdentifier.OnValidate(), and Saveable.OnValidate().
logIDs()
static void IDManager.logIDs () static private
References _usedIds.
RegisterID()
static void IDManager.RegisterID (string ID) static
Parameters
ID The ID to register.
Exceptions
Exception
References _usedIds.
RemoveID()
static void IDManager.RemoveID (string ID) static
Parameters
ID An existing ID.
References _usedIds.
SceneChanged()
static void IDManager.SceneChanged (Scene newScene) static
Parameters
newScene The new scene.
References _currentSceneName, _usedIds, and Saveable.ID.
Referenced by Awake(), and IDInitializer.IDInitializer().
Member Data Documentation
_currentSceneName
string IDManager._currentSceneName static private
Referenced by GetUniqueID(), and SceneChanged().
_separator
char IDManager._separator = '/' static private
Referenced by GetSceneNameOfID(), and GetUniqueID().
_usedIds
HashSet<string> IDManager._usedIds static private
Referenced by GetUniqueID(), logIDs(), RegisterID(), RemoveID(), and SceneChanged().