UnityToolbox Documentation: LocalisationEditIDWindow Class Reference
LocalisationEditIDWindow Class Reference
Public Member Functions
void OnGUI ()
new void Close ()
Static Public Member Functions
static void Open (LocalisationID localisationID)
Properties
LocalisationID LocalisationID [set]
Private Member Functions
void Awake ()
void DrawLine ()
void LanguageEdited (LocalisationLanguage language)
void ScopeEdited (LocalisationScope scope)
void LocalisationIDEdited (LocalisationID ID)
Private Attributes
LocalisationID _localisationID
Dictionary< LocalisationLanguage, string > _newLocalisations
string _newIDName
int _newSelectedScope
string _status
Member Function Documentation
Awake()
void LocalisationEditIDWindow.Awake () private
References LanguageEdited(), LocalisationIDEdited(), and ScopeEdited().
Close()
new void LocalisationEditIDWindow.Close ()
References LanguageEdited(), LocalisationIDEdited(), and ScopeEdited().
Referenced by LanguageEdited(), LocalisationIDEdited(), OnGUI(), and ScopeEdited().
DrawLine()
void LocalisationEditIDWindow.DrawLine () private
LanguageEdited()
void LocalisationEditIDWindow.LanguageEdited (LocalisationLanguage language) private
References Close().
Referenced by Awake(), and Close().
LocalisationIDEdited()
void LocalisationEditIDWindow.LocalisationIDEdited (LocalisationID ID) private
References Close().
Referenced by Awake(), and Close().
OnGUI()
void LocalisationEditIDWindow.OnGUI ()
References _localisationID, _newIDName, _newLocalisations, _newSelectedScope, _status, Close(), LocalisationID.DEVIDER, Localizer.EditLocalisation(), Localizer.EditLocalisationID(), LocalisationID.Equals(), Localizer.Instance, LocalisationID, Localizer.LocalisationLanguages, Localizer.LocalisationScopes, LocalisationLanguage.Name, and Localizer.WriteData().
Open()
static void LocalisationEditIDWindow.Open (LocalisationID localisationID) static
Referenced by LocalisationManagerWindow.DisplayIDsTab(), and LocalisationSelectionWindow.OnGUI().
ScopeEdited()
void LocalisationEditIDWindow.ScopeEdited (LocalisationScope scope) private
References Close().
Referenced by Awake(), and Close().
Member Data Documentation
_localisationID
LocalisationID LocalisationEditIDWindow._localisationID private
Referenced by OnGUI().
_newIDName
string LocalisationEditIDWindow._newIDName private
Referenced by OnGUI().
_newLocalisations
Dictionary<LocalisationLanguage, string> LocalisationEditIDWindow._newLocalisations private
Referenced by OnGUI().
_newSelectedScope
int LocalisationEditIDWindow._newSelectedScope private
Referenced by OnGUI().
_status
string LocalisationEditIDWindow._status private
Referenced by OnGUI().
Property Documentation
LocalisationID
LocalisationID LocalisationEditIDWindow.LocalisationID set
Referenced by OnGUI().