UnityToolbox Documentation: Movement3D Class Reference
Movement3D Class Reference
A MovementBase implementation for 3D movment. Requires the PlayerEventManager.
Public Member Functions
override void Jump ()
Updates the player movement to execute a jump.
override void Move (Vector3 direction)
Updates the player movement with the direction data.
override Vector3 GetCurrentVelocity ()
override void MoveWithStrength (Vector3 direction, Vector3 strength)
Updates the player movement with the direction data and defined strength .
Public Member Functions inherited from MovementBase
void UpdateMovementState ()
Updates the current state of movement. MovementState.Moving does not mean that the current velocity is > 0!
abstract void Move (Vector3 direction)
Updates the player movement with the direction data.
abstract void Jump ()
Updates the player movement to execute a jump.
abstract void MoveWithStrength (Vector3 direction, Vector3 strength)
Updates the player movement with the direction data and defined strength .
abstract Vector3 GetCurrentVelocity ()
Private Member Functions
void Start ()
void FixedUpdate ()
void Update ()
bool OnSlope ()
Vector3 GetSlopeDirection (Vector3 direction)
void OnCollisionEnter (Collision collision)
void OnCollisionExit (Collision collision)
Private Attributes
Rigidbody _rb
float _jumpTimer
float _maxSlopeAngle
RaycastHit _onSlope
bool _firstPerson
Additional Inherited Members
Protected Attributes inherited from MovementBase
float _speed
Defines the speed of the player.
float _jumpForce
Defines the amount of force (speed) for a jump.
float _climbingForce
Defines the amount of force (speed) for climbing.
string _movementActionName
The action name for the movement controls. Needs to be defined as a Vector2D.
string _jumpActionName
The action name for the jump control.
string _attackActionName
The action name for the attack control.
Transform _groundedTransform
The transform defines the position where to define if the player is grounded or not.
PlayerInput _input
The player input.
bool _isMovementLocked
Defines whether the movement should be locked or not. The PlayerEventManager also has events for this.
bool _isClimbingLocked
Defines whether the climbing should be locked or not.
bool _isJumpingLocked
Defines whether the jumping should be locked or not.
MovementState _currentMovementState
The current movement state. (MovementState.Climbing, MovementState.Moving, MovementState.Jumping) MovementState.Moving does not mean that the current velocity is > 0.
LayerMask _climbingMask
The climbing layer mask, which defines which objects should be read as climbable.
LayerMask _jumpingMask
The jumping layer mask, which defines which objects should be read as jumpable.
bool _grounded
Defines whether the player is grounded.
bool _animationGrounded
Defines whether the animation should be counted as grounded. A usecase would be a delay between the actual MovementBase.Grounded.
bool _climbing
Defines whether the player is climbing.
Properties inherited from MovementBase
Transform GroundedTransform [get]
bool IsMovementLocked [get, set]
bool IsClimbingLocked [get, set]
bool IsJumpingLocked [get, set]
MovementState CurrentMovementState [get]
bool Grounded [get]
bool AnimationGrounded [get]
bool Climbing [get]
Member Function Documentation
FixedUpdate()
void Movement3D.FixedUpdate () private
References MovementBase._currentMovementState, MovementBase._input, MovementBase._isMovementLocked, MovementBase._movementActionName, GetCurrentVelocity(), and Move().
GetCurrentVelocity()
override Vector3 Movement3D.GetCurrentVelocity () virtual
Returns
Returns the current velocity of the player.
Implements MovementBase.
References _rb.
Referenced by FixedUpdate().
GetSlopeDirection()
Vector3 Movement3D.GetSlopeDirection (Vector3 direction) private
References _onSlope.
Referenced by Move().
Jump()
override void Movement3D.Jump () virtual
Implements MovementBase.
References MovementBase._jumpForce, _rb, and MovementBase.IsJumpingLocked.
Referenced by Update().
Move()
override void Movement3D.Move (Vector3 direction) virtual
Parameters
direction
Implements MovementBase.
References MovementBase._climbing, _firstPerson, MovementBase._isMovementLocked, _rb, MovementBase._speed, GetSlopeDirection(), MovementBase.IsClimbingLocked, and OnSlope().
Referenced by FixedUpdate().
MoveWithStrength()
override void Movement3D.MoveWithStrength (Vector3 direction, Vector3 strength) virtual
Parameters
direction
strength
Implements MovementBase.
OnCollisionEnter()
void Movement3D.OnCollisionEnter (Collision collision) private
References MovementBase._climbing, and MovementBase._climbingMask.
OnCollisionExit()
void Movement3D.OnCollisionExit (Collision collision) private
References MovementBase._climbing, and MovementBase._climbingMask.
OnSlope()
bool Movement3D.OnSlope () private
References MovementBase._groundedTransform, _maxSlopeAngle, and _onSlope.
Referenced by Move().
Start()
void Movement3D.Start () private
References _rb.
Update()
void Movement3D.Update () private
References MovementBase._attackActionName, MovementBase._grounded, MovementBase._groundedTransform, MovementBase._input, MovementBase._jumpActionName, MovementBase._jumpingMask, _jumpTimer, and Jump().
Member Data Documentation
_firstPerson
bool Movement3D._firstPerson private
Referenced by Move().
_jumpTimer
float Movement3D._jumpTimer private
Referenced by Update().
_maxSlopeAngle
float Movement3D._maxSlopeAngle private
Referenced by OnSlope().
_onSlope
RaycastHit Movement3D._onSlope private
Referenced by GetSlopeDirection(), and OnSlope().
_rb
Rigidbody Movement3D._rb private
Referenced by GetCurrentVelocity(), Jump(), Move(), and Start().