UnityToolbox: UnityToolbox.Item.Management.ItemDefinitionErrorWindow Class Reference
UnityToolbox.Item.Management.ItemDefinitionErrorWindow Class Reference
Public Member Functions
new void Close ()
Static Public Member Functions
static ItemDefinitionErrorWindow Open ()
Events
Action OnClose
Private Member Functions
void Awake ()
void OnGUI ()
void DisplayItemsTab ()
void DrawListItems ()
void SetupListsForItemType (Type type)
void DrawLineHorizontal ()
void UpdateStatus (string status)
Private Attributes
Vector2 _scrollPos
string _searchString
bool _foldoutSearch
string _status
int _selectedSearch
List< Type > _itemDefinitionTypes
List< bool > _selectionBoolValues
List< float > _selectionFloatValues
List< int > _selectionIntValues
List< string > _selectionStringValues
List< FieldInfo > _selectionFields
Member Function Documentation
Awake()
void UnityToolbox.Item.Management.ItemDefinitionErrorWindow.Awake () private
References UnityToolbox.Item.Management.ItemDefinitionErrorWindow._itemDefinitionTypes, UnityToolbox.Item.Management.ItemDefinitionErrorWindow._searchString, UnityToolbox.Item.Management.ItemDefinitionErrorWindow._selectedSearch, UnityToolbox.Item.Management.Itemizer.GetAllInheritedItemDefinitionTypes(), UnityToolbox.Item.Management.Itemizer.Initialize(), UnityToolbox.Item.Management.Itemizer.Initialized, UnityToolbox.Item.Management.Itemizer.Instance, UnityToolbox.Item.Management.ItemDefinitionErrorWindow.SetupListsForItemType(), and UnityToolbox.Item.Management.ItemDefinitionErrorWindow.UpdateStatus().
Close()
new void UnityToolbox.Item.Management.ItemDefinitionErrorWindow.Close ()
References UnityToolbox.Item.Management.ItemDefinitionErrorWindow.OnClose.
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.OnGUI().
DisplayItemsTab()
void UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DisplayItemsTab () private
References UnityToolbox.Item.Management.ItemDefinitionErrorWindow._foldoutSearch, UnityToolbox.Item.Management.ItemDefinitionErrorWindow._itemDefinitionTypes, UnityToolbox.Item.Management.ItemDefinitionErrorWindow._searchString, UnityToolbox.Item.Management.ItemDefinitionErrorWindow._selectedSearch, UnityToolbox.Item.Management.ItemDefinitionErrorWindow._status, UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DrawLineHorizontal(), and UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DrawListItems().
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.OnGUI().
DrawLineHorizontal()
void UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DrawLineHorizontal () private
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DisplayItemsTab(), and UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DrawListItems().
DrawListItems()
void UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DrawListItems () private
References UnityToolbox.Item.Management.ItemDefinitionErrorWindow._itemDefinitionTypes, UnityToolbox.Item.Management.ItemDefinitionErrorWindow._scrollPos, UnityToolbox.Item.Management.ItemDefinitionErrorWindow._searchString, UnityToolbox.Item.Management.ItemDefinitionErrorWindow._selectedSearch, UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DrawLineHorizontal(), UnityToolbox.Item.Management.Itemizer.FaultyItemDefinitions, UnityToolbox.Item.ItemDefinition.GetQualifiedName(), UnityToolbox.Item.Management.Itemizer.Instance, UnityToolbox.Item.ItemDefinition.Name, UnityToolbox.Item.Management.ItemDefinitionEditWindow.Open(), UnityToolbox.Item.Management.Itemizer.RemoveItemDefinition(), UnityToolbox.Item.Management.ItemDefinitionErrorWindow.UpdateStatus(), and UnityToolbox.Item.Management.Itemizer.WriteData().
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DisplayItemsTab().
OnGUI()
void UnityToolbox.Item.Management.ItemDefinitionErrorWindow.OnGUI () private
References UnityToolbox.Item.Management.ItemDefinitionErrorWindow.Close(), UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DisplayItemsTab(), UnityToolbox.Item.Management.Itemizer.FaultyItemDefinitions, and UnityToolbox.Item.Management.Itemizer.Instance.
Open()
static ItemDefinitionErrorWindow UnityToolbox.Item.Management.ItemDefinitionErrorWindow.Open () static
Referenced by UnityToolbox.Item.Management.ItemDefinitionSelectionWindow.OnGUI(), and UnityToolbox.Item.Management.ItemManagerWindow.OnGUI().
SetupListsForItemType()
void UnityToolbox.Item.Management.ItemDefinitionErrorWindow.SetupListsForItemType (Type type) private
References UnityToolbox.Item.Management.ItemDefinitionErrorWindow._selectionBoolValues, UnityToolbox.Item.Management.ItemDefinitionErrorWindow._selectionFields, UnityToolbox.Item.Management.ItemDefinitionErrorWindow._selectionFloatValues, UnityToolbox.Item.Management.ItemDefinitionErrorWindow._selectionIntValues, and UnityToolbox.Item.Management.ItemDefinitionErrorWindow._selectionStringValues.
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.Awake().
UpdateStatus()
void UnityToolbox.Item.Management.ItemDefinitionErrorWindow.UpdateStatus (string status) private
References UnityToolbox.Item.Management.ItemDefinitionErrorWindow._status.
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.Awake(), and UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DrawListItems().
Member Data Documentation
_foldoutSearch
bool UnityToolbox.Item.Management.ItemDefinitionErrorWindow._foldoutSearch private
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DisplayItemsTab().
_itemDefinitionTypes
List<Type> UnityToolbox.Item.Management.ItemDefinitionErrorWindow._itemDefinitionTypes private
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.Awake(), UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DisplayItemsTab(), and UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DrawListItems().
_scrollPos
Vector2 UnityToolbox.Item.Management.ItemDefinitionErrorWindow._scrollPos private
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DrawListItems().
_searchString
string UnityToolbox.Item.Management.ItemDefinitionErrorWindow._searchString private
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.Awake(), UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DisplayItemsTab(), and UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DrawListItems().
_selectedSearch
int UnityToolbox.Item.Management.ItemDefinitionErrorWindow._selectedSearch private
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.Awake(), UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DisplayItemsTab(), and UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DrawListItems().
_selectionBoolValues
List<bool> UnityToolbox.Item.Management.ItemDefinitionErrorWindow._selectionBoolValues private
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.SetupListsForItemType().
_selectionFields
List<FieldInfo> UnityToolbox.Item.Management.ItemDefinitionErrorWindow._selectionFields private
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.SetupListsForItemType().
_selectionFloatValues
List<float> UnityToolbox.Item.Management.ItemDefinitionErrorWindow._selectionFloatValues private
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.SetupListsForItemType().
_selectionIntValues
List<int> UnityToolbox.Item.Management.ItemDefinitionErrorWindow._selectionIntValues private
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.SetupListsForItemType().
_selectionStringValues
List<string> UnityToolbox.Item.Management.ItemDefinitionErrorWindow._selectionStringValues private
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.SetupListsForItemType().
_status
string UnityToolbox.Item.Management.ItemDefinitionErrorWindow._status private
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.DisplayItemsTab(), and UnityToolbox.Item.Management.ItemDefinitionErrorWindow.UpdateStatus().
Event Documentation
OnClose
Action UnityToolbox.Item.Management.ItemDefinitionErrorWindow.OnClose
Referenced by UnityToolbox.Item.Management.ItemDefinitionErrorWindow.Close().