UnityToolbox Documentation: AudioVolumeSetter Class Reference
AudioVolumeSetter Class Reference
This script sets the volume of a AudioSource and reads the data from the settings. For more information on volume settings see SettingsManager and SliderSetting. Requires PlayerPrefKeys and PlayerPrefKeys.
Private Member Functions
void Start ()
void OnDestroy ()
void OnSoundChanged (AudioType type, float newValue)
Private Attributes
AudioType _type
List< AudioSource > _audioSources
Member Function Documentation
OnDestroy()
void AudioVolumeSetter.OnDestroy () private
References OnSoundChanged().
OnSoundChanged()
void AudioVolumeSetter.OnSoundChanged (AudioType type, float newValue) private
References _audioSources, and _type.
Referenced by OnDestroy(), and Start().
Start()
void AudioVolumeSetter.Start () private
References _audioSources, _type, PlayerPrefKeys.EFFECTS_VOLUME, PlayerPrefKeys.MUSIC_VOLUME, and OnSoundChanged().
Member Data Documentation
_audioSources
List<AudioSource> AudioVolumeSetter._audioSources private
Referenced by OnSoundChanged(), and Start().
_type
AudioType AudioVolumeSetter._type private
Referenced by OnSoundChanged(), and Start().