UnityToolbox: Item Class Reference
Item Class Reference
Public Member Functions
override bool Equals (object other)
override int GetHashCode ()
void Click ()
Public Member Functions inherited from Saveable
void Save ()
Defines all data to be serialized by the SaveGameManager.
void Load ()
Loads all data, deserialized by the SaveGameManager.
void OnValidate ()
Public Attributes
bool Stackable
Public Attributes inherited from Saveable
int PrefabID = -1
Protected Member Functions
override void LoadData (GameData data)
Is called after the base data is loaded in Load. Allows additional data to be deserialized.
override List< GameData > SaveData ()
Is called on Save. Allows the definition of all additional GameData to be serialized.
override void OnObjectDeleted ()
A method called on deletion, that is that the object is removed from the save game and destroyed. It is not called when destroyed but saved.
abstract void LoadData (GameData data)
Is called after the base data is loaded in Load. Allows additional data to be deserialized.
abstract List< GameData > SaveData ()
Is called on Save. Allows the definition of all additional GameData to be serialized.
abstract void OnObjectDeleted ()
A method called on deletion, that is that the object is removed from the save game and destroyed. It is not called when destroyed but saved.
Protected Attributes
string _itemName
Sprite _icon
Protected Attributes inherited from Saveable
bool _removeFromSaveOnDelete
Properties
InventoryBase Inventory [get, set]
string ItemName [get, set]
Sprite Icon [get, set]
string Indentifier [get, set]
Properties inherited from Saveable
string ID [get, set]
A unique ID.
bool InEditor [get]
Whether the gameobject is found in the scene initally. Or created dynamically.
Private Attributes
InventoryBase _inventoryOfItem
string _indentifier
Member Function Documentation
Click()
void Item.Click ()
References HeldInventoryManager.EnablePlacement, and HeldInventoryManager.ManageInventorys().
Equals()
override bool Item.Equals (object other)
References _indentifier, _itemName, and ItemName.
Referenced by HeldInventory.AddItem(), HeldInventoryManager.ManageInventorys(), HeldInventory.RemoveItem(), and HeldInventory.UpdateItem().
GetHashCode()
override int Item.GetHashCode ()
LoadData()
override void Item.LoadData (GameData data) protected virtual
Parameters
data A GameData implementation, which holds data to load.
Implements Saveable.
References _itemName, ItemData.InventoryID, and ItemData.ItemName.
OnObjectDeleted()
override void Item.OnObjectDeleted () protected virtual
Implements Saveable.
References _inventoryOfItem, and InventoryBase.RemoveItem().
SaveData()
override List< GameData > Item.SaveData () protected virtual
Returns
Implements Saveable.
References _inventoryOfItem, _itemName, HeldInventoryManager.BackUpInventory, HeldInventoryManager.HInventory, and InventoryBase.ID.
Member Data Documentation
_icon
Sprite Item._icon protected
_indentifier
string Item._indentifier private
Referenced by Equals().
_inventoryOfItem
InventoryBase Item._inventoryOfItem private
Referenced by OnObjectDeleted(), and SaveData().
_itemName
string Item._itemName protected
Referenced by Equals(), LoadData(), and SaveData().
Stackable
bool Item.Stackable
Referenced by BoundInventory.AddItem().
Property Documentation
Icon
Sprite Item.Icon get set
Referenced by InventoryUISlot.UpdateItem().
Indentifier
string Item.Indentifier get set
Inventory
InventoryBase Item.Inventory get set
Referenced by BoundInventory.RemoveItem(), and HeldInventory.RemoveItem().
ItemName
string Item.ItemName get set
Referenced by Equals(), and InventoryUISlot.UpdateItem().