UnityToolbox Documentation: BoundInventory Class Reference
BoundInventory Class Reference
Public Member Functions
override bool AddItem (Item item, int count)
override void RemoveItem (Item item, int count)
override void UpdateItem (Item old, Item updated)
override void RemoveItem (Item item)
abstract bool AddItem (Item item, int count)
abstract void RemoveItem (Item item, int count)
abstract void RemoveItem (Item item)
abstract void UpdateItem (Item old, Item updated)
Public Attributes
Action OnInventoryChanged
int MaxSlotCount
Properties
Dictionary< Item, int > Items [get, set]
Properties inherited from InventoryBase
string ID [get]
Private Member Functions
void Awake ()
Private Attributes
Transform _placeToHideObjects
Dictionary< Item, int > _items
Member Function Documentation
AddItem()
override bool BoundInventory.AddItem (Item item, int count) virtual
Implements InventoryBase.
References _items, _placeToHideObjects, MaxSlotCount, OnInventoryChanged, and Item.Stackable.
Referenced by HeldInventoryManager.ManageInventorys(), and UpdateItem().
Awake()
void BoundInventory.Awake () private
References _items.
RemoveItem() [1/2]
override void BoundInventory.RemoveItem (Item item) virtual
Implements InventoryBase.
References _items, and OnInventoryChanged.
RemoveItem() [2/2]
override void BoundInventory.RemoveItem (Item item, int count) virtual
Implements InventoryBase.
References _items, Item.Inventory, and OnInventoryChanged.
Referenced by HeldInventoryManager.ManageInventorys(), and UpdateItem().
UpdateItem()
override void BoundInventory.UpdateItem (Item old, Item updated) virtual
Implements InventoryBase.
References _items, AddItem(), OnInventoryChanged, and RemoveItem().
Member Data Documentation
_items
Dictionary<Item, int> BoundInventory._items private
Referenced by AddItem(), Awake(), RemoveItem(), and UpdateItem().
_placeToHideObjects
Transform BoundInventory._placeToHideObjects private
Referenced by AddItem().
MaxSlotCount
int BoundInventory.MaxSlotCount
Referenced by AddItem().
OnInventoryChanged
Action BoundInventory.OnInventoryChanged
Referenced by AddItem(), RemoveItem(), and UpdateItem().
Property Documentation
Items
Dictionary<Item, int> BoundInventory.Items get set
Referenced by HeldInventoryManager.ManageInventorys(), and InventoryUI.UpdateSlots().