UnityToolbox: Item.Management.ItemManagerWindow Class Reference
Item.Management.ItemManagerWindow Class Reference
Public Member Functions
void OnAfterAssemblyReload ()
Static Public Member Functions
static void Open ()
Private Member Functions
void InitializeWindow ()
void Awake ()
void OnGUI ()
void DisplaySettingsTab ()
void DisplayScopesTab ()
void DisplayItemsTab ()
void DrawLineHorizontal ()
void UpdateStatus (string status)
void SetupListsForItemType (Type type)
void DrawListScopes ()
void DrawCreationFields ()
void DrawListItems ()
void DrawAddDefinedItem ()
void OnEnable ()
void OnDisable ()
Static Private Member Functions
static void DisplayWindow ()
Private Attributes
int _selectedTab = 0
string _assetPathInProject
Vector2 _scrollPosScope
string _scopeName
Vector2 _scrollPosItemDefinition
string _itemDefinitionName
int _selectedScope
Texture2D _itemDefinitionIcon
GameObject _itemDefinitionPrefab
int _maxStackCount
int _selectedType
List< Type > _itemDefinitionTypes
Vector2 _scrollPosCreation
List< bool > _selectionBoolValues
List< string > _selectionStringValues
List< float > _selectionFloatValues
List< int > _selectionIntValues
List< FieldInfo > _selectionFields
string _searchIDString
int _selectedSearch
bool _foldoutAdd
bool _foldoutSearch
string _status
Static Private Attributes
const int IDS = 0
const int SCOPES = 1
const int SETTINGS = 2
Member Function Documentation
Awake()
void Item.Management.ItemManagerWindow.Awake () private
References Item.Management.ItemManagerWindow.InitializeWindow().
DisplayItemsTab()
void Item.Management.ItemManagerWindow.DisplayItemsTab () private
References Item.Management.ItemManagerWindow._foldoutAdd, Item.Management.ItemManagerWindow._foldoutSearch, Item.Management.ItemManagerWindow._itemDefinitionTypes, Item.Management.ItemManagerWindow._searchIDString, Item.Management.ItemManagerWindow._selectedSearch, Item.Management.ItemManagerWindow.DrawAddDefinedItem(), Item.Management.ItemManagerWindow.DrawCreationFields(), Item.Management.ItemManagerWindow.DrawLineHorizontal(), and Item.Management.ItemManagerWindow.DrawListItems().
Referenced by Item.Management.ItemManagerWindow.OnGUI().
DisplayScopesTab()
void Item.Management.ItemManagerWindow.DisplayScopesTab () private
References Item.Management.ItemManagerWindow._scopeName, Item.Management.Itemizer.AddItemScope(), Item.Management.ItemManagerWindow.DrawLineHorizontal(), Item.Management.ItemManagerWindow.DrawListScopes(), Item.Management.Itemizer.Instance, Item.Management.ItemManagerWindow.UpdateStatus(), and Item.Management.Itemizer.WriteData().
Referenced by Item.Management.ItemManagerWindow.OnGUI().
DisplaySettingsTab()
void Item.Management.ItemManagerWindow.DisplaySettingsTab () private
References Item.Management.ItemManagerWindow._assetPathInProject, Item.Management.ItemManagerWindow._itemDefinitionTypes, Item.Management.ItemManagerWindow._selectedType, Item.Management.ItemManagerWindow.DrawLineHorizontal(), Item.Management.Itemizer.GetAllInheritedItemDefinitionTypes(), Item.Management.Itemizer.Initialize(), Item.Management.Itemizer.Instance, Item.Management.ItemManagerWindow.SetupListsForItemType(), ResourcesUtil.TrySetValidPath(), and Item.Management.ItemManagerWindow.UpdateStatus().
Referenced by Item.Management.ItemManagerWindow.OnGUI().
DisplayWindow()
static void Item.Management.ItemManagerWindow.DisplayWindow () static private
DrawAddDefinedItem()
void Item.Management.ItemManagerWindow.DrawAddDefinedItem () private
References Item.Management.ItemManagerWindow._itemDefinitionIcon, Item.Management.ItemManagerWindow._itemDefinitionName, Item.Management.ItemManagerWindow._itemDefinitionPrefab, Item.Management.ItemManagerWindow._itemDefinitionTypes, Item.Management.ItemManagerWindow._maxStackCount, Item.Management.ItemManagerWindow._selectedScope, Item.Management.ItemManagerWindow._selectedType, Item.Management.ItemManagerWindow._selectionBoolValues, Item.Management.ItemManagerWindow._selectionFields, Item.Management.ItemManagerWindow._selectionFloatValues, Item.Management.ItemManagerWindow._selectionIntValues, Item.Management.ItemManagerWindow._selectionStringValues, Item.Management.Itemizer.AddItemDefinition(), Item.Management.Itemizer.Instance, Item.Management.Itemizer.ItemScopes, Item.Management.ItemManagerWindow.UpdateStatus(), and Item.Management.Itemizer.WriteData().
Referenced by Item.Management.ItemManagerWindow.DisplayItemsTab().
DrawCreationFields()
void Item.Management.ItemManagerWindow.DrawCreationFields () private
References Item.Management.ItemManagerWindow._itemDefinitionIcon, Item.Management.ItemManagerWindow._itemDefinitionName, Item.Management.ItemManagerWindow._itemDefinitionPrefab, Item.Management.ItemManagerWindow._itemDefinitionTypes, Item.Management.ItemManagerWindow._maxStackCount, Item.Management.ItemManagerWindow._scrollPosCreation, Item.Management.ItemManagerWindow._selectedScope, Item.Management.ItemManagerWindow._selectedType, Item.Management.ItemManagerWindow._selectionBoolValues, Item.Management.ItemManagerWindow._selectionFields, Item.Management.ItemManagerWindow._selectionFloatValues, Item.Management.ItemManagerWindow._selectionIntValues, Item.Management.ItemManagerWindow._selectionStringValues, Item.ItemDefinition.DEVIDER, Item.Management.Itemizer.Instance, Item.Management.Itemizer.ItemScopes, and Item.Management.ItemManagerWindow.SetupListsForItemType().
Referenced by Item.Management.ItemManagerWindow.DisplayItemsTab().
DrawLineHorizontal()
void Item.Management.ItemManagerWindow.DrawLineHorizontal () private
Referenced by Item.Management.ItemManagerWindow.DisplayItemsTab(), Item.Management.ItemManagerWindow.DisplayScopesTab(), Item.Management.ItemManagerWindow.DisplaySettingsTab(), Item.Management.ItemManagerWindow.DrawListItems(), and Item.Management.ItemManagerWindow.OnGUI().
DrawListItems()
void Item.Management.ItemManagerWindow.DrawListItems () private
References Item.Management.ItemManagerWindow._itemDefinitionTypes, Item.Management.ItemManagerWindow._scrollPosItemDefinition, Item.Management.ItemManagerWindow._searchIDString, Item.Management.ItemManagerWindow._selectedSearch, Item.Management.ItemManagerWindow.DrawLineHorizontal(), Item.ItemDefinition.GetQualifiedName(), Item.Management.Itemizer.Instance, Item.Management.Itemizer.ItemDefinitions, Item.ItemDefinition.Name, Item.Management.ItemDefinitionEditWindow.Open(), Item.Management.Itemizer.RemoveItemDefinition(), Item.Management.ItemManagerWindow.UpdateStatus(), and Item.Management.Itemizer.WriteData().
Referenced by Item.Management.ItemManagerWindow.DisplayItemsTab().
DrawListScopes()
void Item.Management.ItemManagerWindow.DrawListScopes () private
References Item.Management.ItemManagerWindow._scrollPosScope, Item.Management.Itemizer.DefaultScope, Item.Management.ItemScope.Equals(), Item.Management.Itemizer.Instance, Item.Management.Itemizer.ItemScopes, Item.Management.ItemScope.Name, Item.Management.ItemScopeEditWindow.Open(), Item.Management.Itemizer.RemoveItemScope(), Item.Management.ItemManagerWindow.UpdateStatus(), and Item.Management.Itemizer.WriteData().
Referenced by Item.Management.ItemManagerWindow.DisplayScopesTab().
InitializeWindow()
void Item.Management.ItemManagerWindow.InitializeWindow () private
References Item.Management.ItemManagerWindow._assetPathInProject, Item.Management.ItemManagerWindow._itemDefinitionTypes, Item.Management.ItemManagerWindow._searchIDString, Item.Management.ItemManagerWindow._selectedType, Item.Management.Itemizer.GetAllInheritedItemDefinitionTypes(), ResourcesUtil.GetProjectPath(), Item.Management.Itemizer.Initialized, Item.Management.Itemizer.Instance, Item.Management.ItemManagerWindow.SetupListsForItemType(), and Item.Management.ItemManagerWindow.UpdateStatus().
Referenced by Item.Management.ItemManagerWindow.Awake(), and Item.Management.ItemManagerWindow.OnAfterAssemblyReload().
OnAfterAssemblyReload()
void Item.Management.ItemManagerWindow.OnAfterAssemblyReload ()
References Item.Management.ItemManagerWindow.InitializeWindow().
Referenced by Item.Management.ItemManagerWindow.OnDisable(), and Item.Management.ItemManagerWindow.OnEnable().
OnDisable()
void Item.Management.ItemManagerWindow.OnDisable () private
References Item.Management.ItemManagerWindow.OnAfterAssemblyReload().
OnEnable()
void Item.Management.ItemManagerWindow.OnEnable () private
References Item.Management.ItemManagerWindow.OnAfterAssemblyReload().
OnGUI()
void Item.Management.ItemManagerWindow.OnGUI () private
References Item.Management.ItemManagerWindow._selectedTab, Item.Management.ItemManagerWindow._status, Item.Management.ItemManagerWindow.DisplayItemsTab(), Item.Management.ItemManagerWindow.DisplayScopesTab(), Item.Management.ItemManagerWindow.DisplaySettingsTab(), Item.Management.ItemManagerWindow.DrawLineHorizontal(), Item.Management.ItemManagerWindow.IDS, Item.Management.Itemizer.Initialized, Item.Management.Itemizer.Instance, Item.Management.ItemManagerWindow.SCOPES, and Item.Management.ItemManagerWindow.SETTINGS.
Open()
static void Item.Management.ItemManagerWindow.Open () static
SetupListsForItemType()
void Item.Management.ItemManagerWindow.SetupListsForItemType (Type type) private
References Item.Management.ItemManagerWindow._selectionBoolValues, Item.Management.ItemManagerWindow._selectionFields, Item.Management.ItemManagerWindow._selectionFloatValues, Item.Management.ItemManagerWindow._selectionIntValues, and Item.Management.ItemManagerWindow._selectionStringValues.
Referenced by Item.Management.ItemManagerWindow.DisplaySettingsTab(), Item.Management.ItemManagerWindow.DrawCreationFields(), and Item.Management.ItemManagerWindow.InitializeWindow().
UpdateStatus()
void Item.Management.ItemManagerWindow.UpdateStatus (string status) private
References Item.Management.ItemManagerWindow._status.
Referenced by Item.Management.ItemManagerWindow.DisplayScopesTab(), Item.Management.ItemManagerWindow.DisplaySettingsTab(), Item.Management.ItemManagerWindow.DrawAddDefinedItem(), Item.Management.ItemManagerWindow.DrawListItems(), Item.Management.ItemManagerWindow.DrawListScopes(), and Item.Management.ItemManagerWindow.InitializeWindow().
Member Data Documentation
_assetPathInProject
string Item.Management.ItemManagerWindow._assetPathInProject private
Referenced by Item.Management.ItemManagerWindow.DisplaySettingsTab(), and Item.Management.ItemManagerWindow.InitializeWindow().
_foldoutAdd
bool Item.Management.ItemManagerWindow._foldoutAdd private
Referenced by Item.Management.ItemManagerWindow.DisplayItemsTab().
_foldoutSearch
bool Item.Management.ItemManagerWindow._foldoutSearch private
Referenced by Item.Management.ItemManagerWindow.DisplayItemsTab().
_itemDefinitionIcon
Texture2D Item.Management.ItemManagerWindow._itemDefinitionIcon private
Referenced by Item.Management.ItemManagerWindow.DrawAddDefinedItem(), and Item.Management.ItemManagerWindow.DrawCreationFields().
_itemDefinitionName
string Item.Management.ItemManagerWindow._itemDefinitionName private
Referenced by Item.Management.ItemManagerWindow.DrawAddDefinedItem(), and Item.Management.ItemManagerWindow.DrawCreationFields().
_itemDefinitionPrefab
GameObject Item.Management.ItemManagerWindow._itemDefinitionPrefab private
Referenced by Item.Management.ItemManagerWindow.DrawAddDefinedItem(), and Item.Management.ItemManagerWindow.DrawCreationFields().
_itemDefinitionTypes
List<Type> Item.Management.ItemManagerWindow._itemDefinitionTypes private
Referenced by Item.Management.ItemManagerWindow.DisplayItemsTab(), Item.Management.ItemManagerWindow.DisplaySettingsTab(), Item.Management.ItemManagerWindow.DrawAddDefinedItem(), Item.Management.ItemManagerWindow.DrawCreationFields(), Item.Management.ItemManagerWindow.DrawListItems(), and Item.Management.ItemManagerWindow.InitializeWindow().
_maxStackCount
int Item.Management.ItemManagerWindow._maxStackCount private
Referenced by Item.Management.ItemManagerWindow.DrawAddDefinedItem(), and Item.Management.ItemManagerWindow.DrawCreationFields().
_scopeName
string Item.Management.ItemManagerWindow._scopeName private
Referenced by Item.Management.ItemManagerWindow.DisplayScopesTab().
_scrollPosCreation
Vector2 Item.Management.ItemManagerWindow._scrollPosCreation private
Referenced by Item.Management.ItemManagerWindow.DrawCreationFields().
_scrollPosItemDefinition
Vector2 Item.Management.ItemManagerWindow._scrollPosItemDefinition private
Referenced by Item.Management.ItemManagerWindow.DrawListItems().
_scrollPosScope
Vector2 Item.Management.ItemManagerWindow._scrollPosScope private
Referenced by Item.Management.ItemManagerWindow.DrawListScopes().
_searchIDString
string Item.Management.ItemManagerWindow._searchIDString private
Referenced by Item.Management.ItemManagerWindow.DisplayItemsTab(), Item.Management.ItemManagerWindow.DrawListItems(), and Item.Management.ItemManagerWindow.InitializeWindow().
_selectedScope
int Item.Management.ItemManagerWindow._selectedScope private
Referenced by Item.Management.ItemManagerWindow.DrawAddDefinedItem(), and Item.Management.ItemManagerWindow.DrawCreationFields().
_selectedSearch
int Item.Management.ItemManagerWindow._selectedSearch private
Referenced by Item.Management.ItemManagerWindow.DisplayItemsTab(), and Item.Management.ItemManagerWindow.DrawListItems().
_selectedTab
int Item.Management.ItemManagerWindow._selectedTab = 0 private
Referenced by Item.Management.ItemManagerWindow.OnGUI().
_selectedType
int Item.Management.ItemManagerWindow._selectedType private
Referenced by Item.Management.ItemManagerWindow.DisplaySettingsTab(), Item.Management.ItemManagerWindow.DrawAddDefinedItem(), Item.Management.ItemManagerWindow.DrawCreationFields(), and Item.Management.ItemManagerWindow.InitializeWindow().
_selectionBoolValues
List<bool> Item.Management.ItemManagerWindow._selectionBoolValues private
Referenced by Item.Management.ItemManagerWindow.DrawAddDefinedItem(), Item.Management.ItemManagerWindow.DrawCreationFields(), and Item.Management.ItemManagerWindow.SetupListsForItemType().
_selectionFields
List<FieldInfo> Item.Management.ItemManagerWindow._selectionFields private
Referenced by Item.Management.ItemManagerWindow.DrawAddDefinedItem(), Item.Management.ItemManagerWindow.DrawCreationFields(), and Item.Management.ItemManagerWindow.SetupListsForItemType().
_selectionFloatValues
List<float> Item.Management.ItemManagerWindow._selectionFloatValues private
Referenced by Item.Management.ItemManagerWindow.DrawAddDefinedItem(), Item.Management.ItemManagerWindow.DrawCreationFields(), and Item.Management.ItemManagerWindow.SetupListsForItemType().
_selectionIntValues
List<int> Item.Management.ItemManagerWindow._selectionIntValues private
Referenced by Item.Management.ItemManagerWindow.DrawAddDefinedItem(), Item.Management.ItemManagerWindow.DrawCreationFields(), and Item.Management.ItemManagerWindow.SetupListsForItemType().
_selectionStringValues
List<string> Item.Management.ItemManagerWindow._selectionStringValues private
Referenced by Item.Management.ItemManagerWindow.DrawAddDefinedItem(), Item.Management.ItemManagerWindow.DrawCreationFields(), and Item.Management.ItemManagerWindow.SetupListsForItemType().
_status
string Item.Management.ItemManagerWindow._status private
Referenced by Item.Management.ItemManagerWindow.OnGUI(), and Item.Management.ItemManagerWindow.UpdateStatus().
IDS
const int Item.Management.ItemManagerWindow.IDS = 0 static private
Referenced by Item.Management.ItemManagerWindow.OnGUI().
SCOPES
const int Item.Management.ItemManagerWindow.SCOPES = 1 static private
Referenced by Item.Management.ItemManagerWindow.OnGUI().
SETTINGS
const int Item.Management.ItemManagerWindow.SETTINGS = 2 static private
Referenced by Item.Management.ItemManagerWindow.OnGUI().