UnityToolbox: TerrainGenerator Class Reference
TerrainGenerator Class Reference
The main componant of the terrain generation. It can generate one mesh, with defined settings using CellularAutomata.
Classes
struct PlacementInformation
Public Member Functions
void GenerateViaCellularAutomata ()
Starts the generation with cellular automata.
void GenerateWithAnchorPoints ()
Starts the generation with anchor points. These are carved out in the terrain.
Protected Member Functions
Texture2DArray GenerateTextureArray (Texture2D[] textures)
void GenerateMesh ()
void FillGridWithFillerValues (int[,] grid)
void UpdateMaterial ()
Properties
int[,] GeneratedGrid [get]
Mesh GeneratedMesh [get]
Private Member Functions
void OnValidate ()
void GenerateAnchorSpace (int[,] cAGrid)
Vector2 GetNewPosition (Bounds bounds, int[,] cAGrid)
void PlaceObjects ()
List< Vector2 > Bezier (Vector2 p1, Vector2 p2)
void RotationPlacementForChildren (GameObject parent, float heightOffset, bool widthPlacement)
void RotationPlacementForChildrenRecursiv (GameObject parent, float heightOffset, bool widthPlacement)
Private Attributes
int[,] _grid
Mesh _mesh
int _length
int _iterationCount
float _fillPct
int _edgeSize
float _height
float _noiseHeightTop
float _noiseHeightBottom
float _sizeBetweenNodes
Material _material
bool _autoUpdate
TextureSizes _textureSize
TextureFormat _textureFormat
List< HeightColorTypes > _heightDefinitions
List< GameObject > _toPlace
LayerMask _groundMask
List< GameObject > _spawnedObjects
List< PlacementInformation > _toPlacePositions
Texture2DArray texture2DArray
Member Function Documentation
Bezier()
List< Vector2 > TerrainGenerator.Bezier (Vector2 p1, Vector2 p2) private
Referenced by GenerateAnchorSpace().
FillGridWithFillerValues()
void TerrainGenerator.FillGridWithFillerValues (int grid[,]) protected
References _grid, and _length.
Referenced by GenerateViaCellularAutomata(), and GenerateWithAnchorPoints().
GenerateAnchorSpace()
void TerrainGenerator.GenerateAnchorSpace (int cAGrid[,]) private
References _sizeBetweenNodes, _spawnedObjects, _toPlace, _toPlacePositions, Bezier(), and GetNewPosition().
Referenced by GenerateWithAnchorPoints().
GenerateMesh()
void TerrainGenerator.GenerateMesh () protected
References _grid, _height, _length, _mesh, _noiseHeightBottom, _noiseHeightTop, and _sizeBetweenNodes.
Referenced by GenerateViaCellularAutomata(), and GenerateWithAnchorPoints().
GenerateTextureArray()
Texture2DArray TerrainGenerator.GenerateTextureArray (Texture2D[] textures) protected
References _textureFormat, _textureSize, and texture2DArray.
Referenced by UpdateMaterial().
GenerateViaCellularAutomata()
void TerrainGenerator.GenerateViaCellularAutomata ()
References _edgeSize, _fillPct, _heightDefinitions, _iterationCount, _length, FillGridWithFillerValues(), CellularAutomata.Generate(), GenerateMesh(), and UpdateMaterial().
Referenced by TerrainGenerateAll.GenerateAll(), and TerrainGeneratorEditor.OnInspectorGUI().
GenerateWithAnchorPoints()
void TerrainGenerator.GenerateWithAnchorPoints ()
References _edgeSize, _fillPct, _heightDefinitions, _iterationCount, _length, _toPlacePositions, FillGridWithFillerValues(), CellularAutomata.Generate(), GenerateAnchorSpace(), GenerateMesh(), PlaceObjects(), and UpdateMaterial().
Referenced by TerrainGenerateAll.GenerateAllWithAnchors().
GetNewPosition()
Vector2 TerrainGenerator.GetNewPosition (Bounds bounds, int cAGrid[,]) private
References _toPlacePositions, TerrainGenerator.PlacementInformation.Position, and TerrainGenerator.PlacementInformation.WholeBounds.
Referenced by GenerateAnchorSpace().
OnValidate()
void TerrainGenerator.OnValidate () private
References _autoUpdate, _sizeBetweenNodes, and UpdateMaterial().
PlaceObjects()
void TerrainGenerator.PlaceObjects () private
References _height, _noiseHeightTop, _sizeBetweenNodes, _spawnedObjects, _toPlacePositions, TerrainGenerator.PlacementInformation.Position, TerrainDecorationChildInfo.RelativeToParent, RotationPlacementForChildren(), and TerrainGenerator.PlacementInformation.ToSpawn.
Referenced by GenerateWithAnchorPoints().
RotationPlacementForChildren()
void TerrainGenerator.RotationPlacementForChildren (GameObject parent, float heightOffset, bool widthPlacement) private
References _groundMask, and RotationPlacementForChildrenRecursiv().
Referenced by PlaceObjects().
RotationPlacementForChildrenRecursiv()
void TerrainGenerator.RotationPlacementForChildrenRecursiv (GameObject parent, float heightOffset, bool widthPlacement) private
References _groundMask, _spawnedObjects, TerrainDecorationChildInfo.RelativeToParent, and RotationPlacementForChildrenRecursiv().
Referenced by RotationPlacementForChildren(), and RotationPlacementForChildrenRecursiv().
UpdateMaterial()
void TerrainGenerator.UpdateMaterial () protected
References _height, _heightDefinitions, _material, _noiseHeightBottom, HeightColorTypes.BlendAmount, GenerateTextureArray(), HeightColorTypes.HeightStart, HeightColorTypes.TerrainColor, HeightColorTypes.TerrainColorStrength, HeightColorTypes.TerrainTexture, and HeightColorTypes.TerrainTextureScale.
Referenced by GenerateViaCellularAutomata(), GenerateWithAnchorPoints(), and OnValidate().
Member Data Documentation
_autoUpdate
bool TerrainGenerator._autoUpdate private
Referenced by OnValidate().
_edgeSize
int TerrainGenerator._edgeSize private
Referenced by GenerateViaCellularAutomata(), and GenerateWithAnchorPoints().
_fillPct
float TerrainGenerator._fillPct private
Referenced by GenerateViaCellularAutomata(), and GenerateWithAnchorPoints().
_grid
int [,] TerrainGenerator._grid private
Referenced by FillGridWithFillerValues(), and GenerateMesh().
_groundMask
LayerMask TerrainGenerator._groundMask private
Referenced by RotationPlacementForChildren(), and RotationPlacementForChildrenRecursiv().
_height
float TerrainGenerator._height private
Referenced by GenerateMesh(), PlaceObjects(), and UpdateMaterial().
_heightDefinitions
List<HeightColorTypes> TerrainGenerator._heightDefinitions private
Referenced by GenerateViaCellularAutomata(), GenerateWithAnchorPoints(), and UpdateMaterial().
_iterationCount
int TerrainGenerator._iterationCount private
Referenced by GenerateViaCellularAutomata(), and GenerateWithAnchorPoints().
_length
int TerrainGenerator._length private
Referenced by FillGridWithFillerValues(), GenerateMesh(), GenerateViaCellularAutomata(), and GenerateWithAnchorPoints().
_material
Material TerrainGenerator._material private
Referenced by UpdateMaterial().
_mesh
Mesh TerrainGenerator._mesh private
Referenced by GenerateMesh().
_noiseHeightBottom
float TerrainGenerator._noiseHeightBottom private
Referenced by GenerateMesh(), and UpdateMaterial().
_noiseHeightTop
float TerrainGenerator._noiseHeightTop private
Referenced by GenerateMesh(), and PlaceObjects().
_sizeBetweenNodes
float TerrainGenerator._sizeBetweenNodes private
Referenced by GenerateAnchorSpace(), GenerateMesh(), OnValidate(), and PlaceObjects().
_spawnedObjects
List<GameObject> TerrainGenerator._spawnedObjects private
Referenced by GenerateAnchorSpace(), PlaceObjects(), and RotationPlacementForChildrenRecursiv().
_textureFormat
TextureFormat TerrainGenerator._textureFormat private
Referenced by GenerateTextureArray().
_textureSize
TextureSizes TerrainGenerator._textureSize private
Referenced by GenerateTextureArray().
_toPlace
List<GameObject> TerrainGenerator._toPlace private
Referenced by GenerateAnchorSpace().
_toPlacePositions
List<PlacementInformation> TerrainGenerator._toPlacePositions private
Referenced by GenerateAnchorSpace(), GenerateWithAnchorPoints(), GetNewPosition(), and PlaceObjects().
texture2DArray
Texture2DArray TerrainGenerator.texture2DArray private
Referenced by GenerateTextureArray().
Property Documentation
GeneratedGrid
int [,] TerrainGenerator.GeneratedGrid get
Referenced by TerrainDecoration.CheckPositionType(), and TerrainDecoration.PlaceObjects().
GeneratedMesh
Mesh TerrainGenerator.GeneratedMesh get
Referenced by TerrainDecoration.PlaceObjects().