UnityToolbox: Item.Management.ItemDefinitionEditWindow Class Reference
Item.Management.ItemDefinitionEditWindow Class Reference
Public Member Functions
void OnGUI ()
new void Close ()
Static Public Member Functions
static void Open (ItemDefinition currentItemDefinition)
Properties
ItemDefinition CurrentItemDefinition [set]
Private Member Functions
void Awake ()
void Init (ItemDefinition value)
void DrawLine ()
void DrawCreationFields ()
void DrawAddDefinedItem ()
void ItemDefinitionEdited (ItemDefinition oldItemDefinition, ItemDefinition newItemDefinition)
void ScopeEdited (ItemScope oldScope, ItemScope newScope)
void UpdateStatus (string status)
Private Attributes
ItemDefinition _currentItemDefinition
Vector2 _scrollPosCreation
Type _type
List< bool > _selectionBoolValues
List< string > _selectionStringValues
List< float > _selectionFloatValues
List< int > _selectionIntValues
List< FieldInfo > _selectionFields
string _newItemDefinitionName
int _newSelectedScope
Texture2D _newItemDefinitionIcon
GameObject _newItemDefinitionPrefab
int _newMaxStackCount
string _status
Member Function Documentation
Awake()
void Item.Management.ItemDefinitionEditWindow.Awake () private
References Item.Management.ItemDefinitionEditWindow.ItemDefinitionEdited(), Item.Management.ItemDefinitionEditWindow.ScopeEdited(), and Item.Management.ItemDefinitionEditWindow.UpdateStatus().
Close()
new void Item.Management.ItemDefinitionEditWindow.Close ()
References Item.Management.ItemDefinitionEditWindow.ItemDefinitionEdited(), and Item.Management.ItemDefinitionEditWindow.ScopeEdited().
Referenced by Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), Item.Management.ItemDefinitionEditWindow.ItemDefinitionEdited(), and Item.Management.ItemDefinitionEditWindow.ScopeEdited().
DrawAddDefinedItem()
void Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem () private
References Item.Management.ItemDefinitionEditWindow._currentItemDefinition, Item.Management.ItemDefinitionEditWindow._newItemDefinitionIcon, Item.Management.ItemDefinitionEditWindow._newItemDefinitionName, Item.Management.ItemDefinitionEditWindow._newItemDefinitionPrefab, Item.Management.ItemDefinitionEditWindow._newMaxStackCount, Item.Management.ItemDefinitionEditWindow._newSelectedScope, Item.Management.ItemDefinitionEditWindow._selectionBoolValues, Item.Management.ItemDefinitionEditWindow._selectionFields, Item.Management.ItemDefinitionEditWindow._selectionFloatValues, Item.Management.ItemDefinitionEditWindow._selectionIntValues, Item.Management.ItemDefinitionEditWindow._selectionStringValues, Item.Management.ItemDefinitionEditWindow._type, Item.Management.ItemDefinitionEditWindow.Close(), Item.Management.Itemizer.EditItemDefinition(), Item.Management.Itemizer.Instance, Item.Management.Itemizer.ItemScopes, Item.Management.ItemDefinitionEditWindow.UpdateStatus(), and Item.Management.Itemizer.WriteData().
Referenced by Item.Management.ItemDefinitionEditWindow.OnGUI().
DrawCreationFields()
void Item.Management.ItemDefinitionEditWindow.DrawCreationFields () private
References Item.Management.ItemDefinitionEditWindow._newItemDefinitionIcon, Item.Management.ItemDefinitionEditWindow._newItemDefinitionName, Item.Management.ItemDefinitionEditWindow._newItemDefinitionPrefab, Item.Management.ItemDefinitionEditWindow._newMaxStackCount, Item.Management.ItemDefinitionEditWindow._newSelectedScope, Item.Management.ItemDefinitionEditWindow._scrollPosCreation, Item.Management.ItemDefinitionEditWindow._selectionBoolValues, Item.Management.ItemDefinitionEditWindow._selectionFields, Item.Management.ItemDefinitionEditWindow._selectionFloatValues, Item.Management.ItemDefinitionEditWindow._selectionIntValues, Item.Management.ItemDefinitionEditWindow._selectionStringValues, Item.Management.ItemDefinitionEditWindow._type, Item.ItemDefinition.DEVIDER, Item.Management.Itemizer.Instance, and Item.Management.Itemizer.ItemScopes.
Referenced by Item.Management.ItemDefinitionEditWindow.OnGUI().
DrawLine()
void Item.Management.ItemDefinitionEditWindow.DrawLine () private
Referenced by Item.Management.ItemDefinitionEditWindow.OnGUI().
Init()
void Item.Management.ItemDefinitionEditWindow.Init (ItemDefinition value) private
References Item.Management.ItemDefinitionEditWindow._currentItemDefinition, Item.Management.ItemDefinitionEditWindow._newItemDefinitionIcon, Item.Management.ItemDefinitionEditWindow._newItemDefinitionName, Item.Management.ItemDefinitionEditWindow._newItemDefinitionPrefab, Item.Management.ItemDefinitionEditWindow._newMaxStackCount, Item.Management.ItemDefinitionEditWindow._newSelectedScope, Item.Management.ItemDefinitionEditWindow._selectionBoolValues, Item.Management.ItemDefinitionEditWindow._selectionFields, Item.Management.ItemDefinitionEditWindow._selectionFloatValues, Item.Management.ItemDefinitionEditWindow._selectionIntValues, Item.Management.ItemDefinitionEditWindow._selectionStringValues, Item.Management.ItemDefinitionEditWindow._type, Item.Management.ItemScope.Equals(), Item.ItemDefinition.IconPath, Item.Management.Itemizer.Instance, Item.Management.Itemizer.ItemScopes, Item.ItemDefinition.MaxStackCount, Item.ItemDefinition.Name, and Item.ItemDefinition.PrefabPath.
ItemDefinitionEdited()
void Item.Management.ItemDefinitionEditWindow.ItemDefinitionEdited (ItemDefinition oldItemDefinition, ItemDefinition newItemDefinition) private
References Item.Management.ItemDefinitionEditWindow.Close().
Referenced by Item.Management.ItemDefinitionEditWindow.Awake(), and Item.Management.ItemDefinitionEditWindow.Close().
OnGUI()
void Item.Management.ItemDefinitionEditWindow.OnGUI ()
References Item.Management.ItemDefinitionEditWindow._status, Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and Item.Management.ItemDefinitionEditWindow.DrawLine().
Open()
static void Item.Management.ItemDefinitionEditWindow.Open (ItemDefinition currentItemDefinition) static
Referenced by Item.Management.ItemManagerWindow.DrawListItems(), and Item.Management.ItemDefinitionSelectionWindow.OnGUI().
ScopeEdited()
void Item.Management.ItemDefinitionEditWindow.ScopeEdited (ItemScope oldScope, ItemScope newScope) private
References Item.Management.ItemDefinitionEditWindow.Close().
Referenced by Item.Management.ItemDefinitionEditWindow.Awake(), and Item.Management.ItemDefinitionEditWindow.Close().
UpdateStatus()
void Item.Management.ItemDefinitionEditWindow.UpdateStatus (string status) private
References Item.Management.ItemDefinitionEditWindow._status.
Referenced by Item.Management.ItemDefinitionEditWindow.Awake(), and Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem().
Member Data Documentation
_currentItemDefinition
ItemDefinition Item.Management.ItemDefinitionEditWindow._currentItemDefinition private
Referenced by Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), and Item.Management.ItemDefinitionEditWindow.Init().
_newItemDefinitionIcon
Texture2D Item.Management.ItemDefinitionEditWindow._newItemDefinitionIcon private
Referenced by Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and Item.Management.ItemDefinitionEditWindow.Init().
_newItemDefinitionName
string Item.Management.ItemDefinitionEditWindow._newItemDefinitionName private
Referenced by Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and Item.Management.ItemDefinitionEditWindow.Init().
_newItemDefinitionPrefab
GameObject Item.Management.ItemDefinitionEditWindow._newItemDefinitionPrefab private
Referenced by Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and Item.Management.ItemDefinitionEditWindow.Init().
_newMaxStackCount
int Item.Management.ItemDefinitionEditWindow._newMaxStackCount private
Referenced by Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and Item.Management.ItemDefinitionEditWindow.Init().
_newSelectedScope
int Item.Management.ItemDefinitionEditWindow._newSelectedScope private
Referenced by Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and Item.Management.ItemDefinitionEditWindow.Init().
_scrollPosCreation
Vector2 Item.Management.ItemDefinitionEditWindow._scrollPosCreation private
Referenced by Item.Management.ItemDefinitionEditWindow.DrawCreationFields().
_selectionBoolValues
List<bool> Item.Management.ItemDefinitionEditWindow._selectionBoolValues private
Referenced by Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and Item.Management.ItemDefinitionEditWindow.Init().
_selectionFields
List<FieldInfo> Item.Management.ItemDefinitionEditWindow._selectionFields private
Referenced by Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and Item.Management.ItemDefinitionEditWindow.Init().
_selectionFloatValues
List<float> Item.Management.ItemDefinitionEditWindow._selectionFloatValues private
Referenced by Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and Item.Management.ItemDefinitionEditWindow.Init().
_selectionIntValues
List<int> Item.Management.ItemDefinitionEditWindow._selectionIntValues private
Referenced by Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and Item.Management.ItemDefinitionEditWindow.Init().
_selectionStringValues
List<string> Item.Management.ItemDefinitionEditWindow._selectionStringValues private
Referenced by Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and Item.Management.ItemDefinitionEditWindow.Init().
_status
string Item.Management.ItemDefinitionEditWindow._status private
Referenced by Item.Management.ItemDefinitionEditWindow.OnGUI(), and Item.Management.ItemDefinitionEditWindow.UpdateStatus().
_type
Type Item.Management.ItemDefinitionEditWindow._type private
Referenced by Item.Management.ItemDefinitionEditWindow.DrawAddDefinedItem(), Item.Management.ItemDefinitionEditWindow.DrawCreationFields(), and Item.Management.ItemDefinitionEditWindow.Init().
Property Documentation
CurrentItemDefinition
ItemDefinition Item.Management.ItemDefinitionEditWindow.CurrentItemDefinition set