UnityToolbox: HeldInventoryManager Class Reference
HeldInventoryManager Class Reference
Public Member Functions
void Update ()
void ManageInventorys (BoundInventory other, ItemInstance otherItem)
Public Member Functions inherited from Module
virtual void Awake ()
Public Attributes
HeldInventory HInventory
bool EnablePlacement
Properties
InventoryBase BackUpInventory [get]
bool IsEnabled [get, set]
Private Member Functions
IEnumerator WaitTillNextAction ()
Private Attributes
Camera _camera
string _mouseClickAction
PlayerInput _input
LayerMask _placementMask
GameObject _placementParent
InventoryBase _backUpInventory
bool _mayAct = true
bool _isEnabled
Member Function Documentation
ManageInventorys()
void HeldInventoryManager.ManageInventorys (BoundInventory other, ItemInstance otherItem)
References _isEnabled, _mayAct, BoundInventory.AddItem(), HeldInventory.AddItem(), HeldInventory.Count, UnityToolbox.Item.ItemInstance.Equals(), HInventory, HeldInventory.ItemHeld, BoundInventory.Items, BoundInventory.RemoveItem(), and HeldInventory.RemoveItem().
Referenced by UnityToolbox.Item.ItemInstance.Click().
Update()
void HeldInventoryManager.Update ()
References _camera, _input, _isEnabled, _mayAct, _mouseClickAction, _placementMask, _placementParent, HeldInventory.Count, EnablePlacement, ColliderInfo.GetAllCollisions(), HInventory, HeldInventory.ItemHeld, HeldInventory.RemoveItem(), and WaitTillNextAction().
WaitTillNextAction()
IEnumerator HeldInventoryManager.WaitTillNextAction () private
References _mayAct.
Referenced by Update().
Member Data Documentation
_backUpInventory
InventoryBase HeldInventoryManager._backUpInventory private
_camera
Camera HeldInventoryManager._camera private
Referenced by Update().
_input
PlayerInput HeldInventoryManager._input private
Referenced by Update().
_isEnabled
bool HeldInventoryManager._isEnabled private
Referenced by ManageInventorys(), and Update().
_mayAct
bool HeldInventoryManager._mayAct = true private
Referenced by ManageInventorys(), Update(), and WaitTillNextAction().
_mouseClickAction
string HeldInventoryManager._mouseClickAction private
Referenced by Update().
_placementMask
LayerMask HeldInventoryManager._placementMask private
Referenced by Update().
_placementParent
GameObject HeldInventoryManager._placementParent private
Referenced by Update().
EnablePlacement
bool HeldInventoryManager.EnablePlacement
Referenced by UnityToolbox.Item.ItemInstance.Click(), and Update().
HInventory
HeldInventory HeldInventoryManager.HInventory
Referenced by ManageInventorys(), UnityToolbox.Item.ItemInstance.SaveData(), and Update().
Property Documentation
BackUpInventory
InventoryBase HeldInventoryManager.BackUpInventory get
Referenced by UnityToolbox.Item.ItemInstance.SaveData().
IsEnabled
bool HeldInventoryManager.IsEnabled get set