UnityToolbox Documentation: DialogGraphWindow Class Reference
DialogGraphWindow Class Reference
Public Member Functions
void UpdateData ()
void WriteData ()
void OnAfterAssemblyReload ()
Static Public Member Functions
static void Open ()
Private Member Functions
void AddGraphView ()
void OnDestroy ()
void OnEnable ()
void OnDisable ()
Private Attributes
string _fullPath
JsonSerializerSettings _settings
DialogGraphView _graphView
Static Private Attributes
const string FILENAME = "/DialogData.dat"
Member Function Documentation
AddGraphView()
void DialogGraphWindow.AddGraphView () private
References _graphView.
Referenced by OnEnable().
OnAfterAssemblyReload()
void DialogGraphWindow.OnAfterAssemblyReload ()
References UpdateData().
Referenced by OnDisable(), and OnEnable().
OnDestroy()
void DialogGraphWindow.OnDestroy () private
References WriteData().
OnDisable()
void DialogGraphWindow.OnDisable () private
References OnAfterAssemblyReload().
OnEnable()
void DialogGraphWindow.OnEnable () private
References _fullPath, _settings, AddGraphView(), ProjectPrefs.GetString(), and OnAfterAssemblyReload().
Open()
static void DialogGraphWindow.Open () static
References FILENAME, ProjectPrefs.GetString(), DialogGraphPathSelectionWindow.Open(), and UpdateData().
UpdateData()
void DialogGraphWindow.UpdateData ()
References _fullPath, _graphView, _settings, DialogGraphView.AddNode(), FILENAME, ProjectPrefs.GetString(), DialogNode.InputPort, and DialogNode.UpdateInputConnectionLabel().
Referenced by DialogGraphPathSelectionWindow.DisplaySetting(), OnAfterAssemblyReload(), and Open().
WriteData()
void DialogGraphWindow.WriteData ()
References _fullPath, _graphView, _settings, DialogNode.Avatar, DialogNode.CompletionToSet, DialogNode.DialogIndentifier, DialogNode.DialogText, DialogNode.DialogTitle, FILENAME, DialogNode.ID, DialogNode.InputIDs, DialogNode.Options, DialogNode.OutputIDs, and DialogNode.UpdateValues().
Referenced by OnDestroy().
Member Data Documentation
_fullPath
string DialogGraphWindow._fullPath private
Referenced by OnEnable(), UpdateData(), and WriteData().
_graphView
DialogGraphView DialogGraphWindow._graphView private
Referenced by AddGraphView(), UpdateData(), and WriteData().
_settings
JsonSerializerSettings DialogGraphWindow._settings private
Referenced by OnEnable(), UpdateData(), and WriteData().
FILENAME
const string DialogGraphWindow.FILENAME = "/DialogData.dat" static private
Referenced by Open(), UpdateData(), and WriteData().