UnityToolbox: ItemDefinitionDrawer Class Reference
ItemDefinitionDrawer Class Reference
Public Member Functions
override float GetPropertyHeight (SerializedProperty property, GUIContent label)
override void OnGUI (Rect position, SerializedProperty property, GUIContent label)
void ItemDefinitionSelected (ItemDefinition itemDefinition)
Private Attributes
ItemDefinitionSelectionWindow _window
SerializedProperty _property
Member Function Documentation
GetPropertyHeight()
override float ItemDefinitionDrawer.GetPropertyHeight (SerializedProperty property, GUIContent label)
ItemDefinitionSelected()
void ItemDefinitionDrawer.ItemDefinitionSelected (ItemDefinition itemDefinition)
References _property, _window, and ItemDefinitionSelected().
Referenced by ItemDefinitionSelected(), and OnGUI().
OnGUI()
override void ItemDefinitionDrawer.OnGUI (Rect position, SerializedProperty property, GUIContent label)
References _property, _window, ItemDefinition.DEVIDER, ItemDefinitionSelected(), ItemDefinition.Name, ItemScope.Name, ItemDefinitionSelectionWindow.Open(), and ItemDefinition.Scope.
Member Data Documentation
_property
SerializedProperty ItemDefinitionDrawer._property private
Referenced by ItemDefinitionSelected(), and OnGUI().
_window
ItemDefinitionSelectionWindow ItemDefinitionDrawer._window private
Referenced by ItemDefinitionSelected(), and OnGUI().