UnityToolbox: ItemScopeEditWindow Class Reference
ItemScopeEditWindow Class Reference
Public Member Functions
void OnGUI ()
Static Public Member Functions
static void Open (ItemScope scope)
Properties
ItemScope Scope [set]
Private Member Functions
void Awake ()
void ScopeEdited (ItemScope scope, ItemScope newScope)
void DrawLineHorizontal ()
void UpdateStatus (string status)
Private Attributes
ItemScope _scope
string _newScopeName
string _status
Member Function Documentation
Awake()
void ItemScopeEditWindow.Awake () private
References ScopeEdited(), and UpdateStatus().
DrawLineHorizontal()
void ItemScopeEditWindow.DrawLineHorizontal () private
Referenced by OnGUI().
OnGUI()
void ItemScopeEditWindow.OnGUI ()
References _newScopeName, _scope, _status, DrawLineHorizontal(), Itemizer.EditItemScope(), Itemizer.Instance, ScopeEdited(), UpdateStatus(), and Itemizer.WriteData().
Open()
static void ItemScopeEditWindow.Open (ItemScope scope) static
Referenced by ItemManagerWindow.DrawListScopes().
ScopeEdited()
void ItemScopeEditWindow.ScopeEdited (ItemScope scope, ItemScope newScope) private
References _scope, ItemScope.Equals(), and ScopeEdited().
Referenced by Awake(), OnGUI(), and ScopeEdited().
UpdateStatus()
void ItemScopeEditWindow.UpdateStatus (string status) private
References _status.
Referenced by Awake(), and OnGUI().
Member Data Documentation
_newScopeName
string ItemScopeEditWindow._newScopeName private
Referenced by OnGUI().
_scope
ItemScope ItemScopeEditWindow._scope private
Referenced by OnGUI(), and ScopeEdited().
_status
string ItemScopeEditWindow._status private
Referenced by OnGUI(), and UpdateStatus().
Property Documentation
Scope
ItemScope ItemScopeEditWindow.Scope set