UnityToolbox: ItemManagerWindow Class Reference
ItemManagerWindow Class Reference
Public Member Functions
void OnAfterAssemblyReload ()
Static Public Member Functions
static void Open ()
Private Member Functions
void InitializeWindow ()
void Awake ()
void OnGUI ()
void DisplaySettingsTab ()
void DisplayScopesTab ()
void DisplayItemsTab ()
void DrawLineHorizontal ()
void UpdateStatus (string status)
void SetupListsForItemType (Type type)
void DrawListScopes ()
void DrawCreationFields ()
void DrawListItems ()
void DrawAddDefinedItem ()
void OnEnable ()
void OnDisable ()
Static Private Member Functions
static void DisplayWindow ()
Private Attributes
int _selectedTab = 0
string _assetPathInProject
Vector2 _scrollPosScope
string _scopeName
Vector2 _scrollPosItemDefinition
string _itemDefinitionName
int _selectedScope
Texture2D _itemDefinitionIcon
GameObject _itemDefinitionPrefab
int _maxStackCount
int _selectedType
List< Type > _itemDefinitionTypes
Vector2 _scrollPosCreation
List< bool > _selectionBoolValues
List< string > _selectionStringValues
List< float > _selectionFloatValues
List< int > _selectionIntValues
List< FieldInfo > _selectionFields
string _searchIDString
int _selectedSearch
bool _foldoutAdd
bool _foldoutSearch
string _status
Static Private Attributes
const int IDS = 0
const int SCOPES = 1
const int SETTINGS = 2
Member Function Documentation
Awake()
void ItemManagerWindow.Awake () private
References InitializeWindow().
DisplayItemsTab()
void ItemManagerWindow.DisplayItemsTab () private
References _foldoutAdd, _foldoutSearch, _itemDefinitionTypes, _searchIDString, _selectedSearch, DrawAddDefinedItem(), DrawCreationFields(), DrawLineHorizontal(), and DrawListItems().
Referenced by OnGUI().
DisplayScopesTab()
void ItemManagerWindow.DisplayScopesTab () private
References _scopeName, Itemizer.AddItemScope(), DrawLineHorizontal(), DrawListScopes(), Itemizer.Instance, UpdateStatus(), and Itemizer.WriteData().
Referenced by OnGUI().
DisplaySettingsTab()
void ItemManagerWindow.DisplaySettingsTab () private
References _assetPathInProject, _itemDefinitionTypes, _selectedType, DrawLineHorizontal(), Itemizer.GetAllInheritedItemDefinitionTypes(), Itemizer.Initialize(), Itemizer.Instance, SetupListsForItemType(), ResourcesUtil.TrySetValidPath(), and UpdateStatus().
Referenced by OnGUI().
DisplayWindow()
static void ItemManagerWindow.DisplayWindow () static private
DrawAddDefinedItem()
void ItemManagerWindow.DrawAddDefinedItem () private
References _itemDefinitionIcon, _itemDefinitionName, _itemDefinitionPrefab, _itemDefinitionTypes, _maxStackCount, _selectedScope, _selectedType, _selectionBoolValues, _selectionFields, _selectionFloatValues, _selectionIntValues, _selectionStringValues, Itemizer.AddItemDefinition(), Itemizer.Instance, Itemizer.ItemScopes, UpdateStatus(), and Itemizer.WriteData().
Referenced by DisplayItemsTab().
DrawCreationFields()
void ItemManagerWindow.DrawCreationFields () private
References _itemDefinitionIcon, _itemDefinitionName, _itemDefinitionPrefab, _itemDefinitionTypes, _maxStackCount, _scrollPosCreation, _selectedScope, _selectedType, _selectionBoolValues, _selectionFields, _selectionFloatValues, _selectionIntValues, _selectionStringValues, ItemDefinition.DEVIDER, Itemizer.Instance, Itemizer.ItemScopes, and SetupListsForItemType().
Referenced by DisplayItemsTab().
DrawLineHorizontal()
void ItemManagerWindow.DrawLineHorizontal () private
Referenced by DisplayItemsTab(), DisplayScopesTab(), DisplaySettingsTab(), DrawListItems(), and OnGUI().
DrawListItems()
void ItemManagerWindow.DrawListItems () private
References _itemDefinitionTypes, _scrollPosItemDefinition, _searchIDString, _selectedSearch, DrawLineHorizontal(), ItemDefinition.GetQualifiedName(), Itemizer.Instance, Itemizer.ItemDefinitions, ItemDefinition.Name, ItemDefinitionEditWindow.Open(), Itemizer.RemoveItemDefinition(), UpdateStatus(), and Itemizer.WriteData().
Referenced by DisplayItemsTab().
DrawListScopes()
void ItemManagerWindow.DrawListScopes () private
References _scrollPosScope, Itemizer.DefaultScope, ItemScope.Equals(), Itemizer.Instance, Itemizer.ItemScopes, ItemScope.Name, ItemScopeEditWindow.Open(), Itemizer.RemoveItemScope(), UpdateStatus(), and Itemizer.WriteData().
Referenced by DisplayScopesTab().
InitializeWindow()
void ItemManagerWindow.InitializeWindow () private
References _assetPathInProject, _itemDefinitionTypes, _searchIDString, _selectedType, Itemizer.GetAllInheritedItemDefinitionTypes(), ResourcesUtil.GetProjectPath(), Itemizer.Initialized, Itemizer.Instance, SetupListsForItemType(), and UpdateStatus().
Referenced by Awake(), and OnAfterAssemblyReload().
OnAfterAssemblyReload()
void ItemManagerWindow.OnAfterAssemblyReload ()
References InitializeWindow().
Referenced by OnDisable(), and OnEnable().
OnDisable()
void ItemManagerWindow.OnDisable () private
References OnAfterAssemblyReload().
OnEnable()
void ItemManagerWindow.OnEnable () private
References OnAfterAssemblyReload().
OnGUI()
void ItemManagerWindow.OnGUI () private
References _selectedTab, _status, DisplayItemsTab(), DisplayScopesTab(), DisplaySettingsTab(), DrawLineHorizontal(), IDS, Itemizer.Initialized, Itemizer.Instance, SCOPES, and SETTINGS.
Open()
static void ItemManagerWindow.Open () static
SetupListsForItemType()
void ItemManagerWindow.SetupListsForItemType (Type type) private
References _selectionBoolValues, _selectionFields, _selectionFloatValues, _selectionIntValues, and _selectionStringValues.
Referenced by DisplaySettingsTab(), DrawCreationFields(), and InitializeWindow().
UpdateStatus()
void ItemManagerWindow.UpdateStatus (string status) private
References _status.
Referenced by DisplayScopesTab(), DisplaySettingsTab(), DrawAddDefinedItem(), DrawListItems(), DrawListScopes(), and InitializeWindow().
Member Data Documentation
_assetPathInProject
string ItemManagerWindow._assetPathInProject private
Referenced by DisplaySettingsTab(), and InitializeWindow().
_foldoutAdd
bool ItemManagerWindow._foldoutAdd private
Referenced by DisplayItemsTab().
_foldoutSearch
bool ItemManagerWindow._foldoutSearch private
Referenced by DisplayItemsTab().
_itemDefinitionIcon
Texture2D ItemManagerWindow._itemDefinitionIcon private
Referenced by DrawAddDefinedItem(), and DrawCreationFields().
_itemDefinitionName
string ItemManagerWindow._itemDefinitionName private
Referenced by DrawAddDefinedItem(), and DrawCreationFields().
_itemDefinitionPrefab
GameObject ItemManagerWindow._itemDefinitionPrefab private
Referenced by DrawAddDefinedItem(), and DrawCreationFields().
_itemDefinitionTypes
List<Type> ItemManagerWindow._itemDefinitionTypes private
Referenced by DisplayItemsTab(), DisplaySettingsTab(), DrawAddDefinedItem(), DrawCreationFields(), DrawListItems(), and InitializeWindow().
_maxStackCount
int ItemManagerWindow._maxStackCount private
Referenced by DrawAddDefinedItem(), and DrawCreationFields().
_scopeName
string ItemManagerWindow._scopeName private
Referenced by DisplayScopesTab().
_scrollPosCreation
Vector2 ItemManagerWindow._scrollPosCreation private
Referenced by DrawCreationFields().
_scrollPosItemDefinition
Vector2 ItemManagerWindow._scrollPosItemDefinition private
Referenced by DrawListItems().
_scrollPosScope
Vector2 ItemManagerWindow._scrollPosScope private
Referenced by DrawListScopes().
_searchIDString
string ItemManagerWindow._searchIDString private
Referenced by DisplayItemsTab(), DrawListItems(), and InitializeWindow().
_selectedScope
int ItemManagerWindow._selectedScope private
Referenced by DrawAddDefinedItem(), and DrawCreationFields().
_selectedSearch
int ItemManagerWindow._selectedSearch private
Referenced by DisplayItemsTab(), and DrawListItems().
_selectedTab
int ItemManagerWindow._selectedTab = 0 private
Referenced by OnGUI().
_selectedType
int ItemManagerWindow._selectedType private
Referenced by DisplaySettingsTab(), DrawAddDefinedItem(), DrawCreationFields(), and InitializeWindow().
_selectionBoolValues
List<bool> ItemManagerWindow._selectionBoolValues private
Referenced by DrawAddDefinedItem(), DrawCreationFields(), and SetupListsForItemType().
_selectionFields
List<FieldInfo> ItemManagerWindow._selectionFields private
Referenced by DrawAddDefinedItem(), DrawCreationFields(), and SetupListsForItemType().
_selectionFloatValues
List<float> ItemManagerWindow._selectionFloatValues private
Referenced by DrawAddDefinedItem(), DrawCreationFields(), and SetupListsForItemType().
_selectionIntValues
List<int> ItemManagerWindow._selectionIntValues private
Referenced by DrawAddDefinedItem(), DrawCreationFields(), and SetupListsForItemType().
_selectionStringValues
List<string> ItemManagerWindow._selectionStringValues private
Referenced by DrawAddDefinedItem(), DrawCreationFields(), and SetupListsForItemType().
_status
string ItemManagerWindow._status private
Referenced by OnGUI(), and UpdateStatus().
IDS
const int ItemManagerWindow.IDS = 0 static private
Referenced by OnGUI().
SCOPES
const int ItemManagerWindow.SCOPES = 1 static private
Referenced by OnGUI().
SETTINGS
const int ItemManagerWindow.SETTINGS = 2 static private
Referenced by OnGUI().