UnityToolbox: ItemManager Class Reference
ItemManager Class Reference
Public Member Functions
override void Awake ()
ItemInstance SpawnItemInstance (Vector3 position, Quaternion rotation, Vector3 scale, string itemDefKey)
Creates a new ItemInstance into the scene.
virtual void Awake ()
Static Public Member Functions
static Dictionary< string, ItemDefinition > ReadItemData ()
Reads all data from the set resources folder.
static HashSet< string > ReadItemScopes ()
Reads all scopes from the set resources folder.
static void WriteData (Dictionary< string, ItemDefinition > allItems, HashSet< string > scopes)
Writes all data to the set resources folder.
static void ScopeEdited (ItemScope scope)
Properties
Dictionary< string, ItemDefinition > AllItems [get]
All defined items.
HashSet< string > ItemScopes [get]
Events
static Action< ItemScope > OnScopeEdited
Private Member Functions
void ReadDataLocally ()
Private Attributes
Dictionary< string, ItemDefinition > _allItems
HashSet< string > _itemScopes
Static Private Attributes
static readonly JsonSerializerSettings _settings = new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.All }
static string FILENAMEITEMS = "ItemData.txt"
static string FILENAMESCOPES = "ItemScopeData.txt"
Member Function Documentation
Awake()
override void ItemManager.Awake () virtual
Reimplemented from Module.
References ReadDataLocally().
ReadDataLocally()
void ItemManager.ReadDataLocally () private
References _allItems, _itemScopes, ReadItemData(), and ReadItemScopes().
Referenced by Awake().
ReadItemData()
static Dictionary< string, ItemDefinition > ItemManager.ReadItemData () static
Returns
Returns all defined items, with the key being the item name
References _settings, ItemDefinition.Deserialize(), FILENAMEITEMS, and ProjectPrefs.GetString().
Referenced by ReadDataLocally().
ReadItemScopes()
static HashSet< string > ItemManager.ReadItemScopes () static
Returns
Returns all defined items, with the key being the item name
References _settings, FILENAMESCOPES, and ProjectPrefs.GetString().
Referenced by ReadDataLocally().
ScopeEdited()
static void ItemManager.ScopeEdited (ItemScope scope) static
References OnScopeEdited.
SpawnItemInstance()
ItemInstance ItemManager.SpawnItemInstance (Vector3 position, Quaternion rotation, Vector3 scale, string itemDefKey)
Parameters
position The position of the new object.
rotation The rotation of the new object.
scale The scale of the new object.
itemDefKey The key which indentifies the ItemDefinition.
Returns
A new ItemInstance.
References _allItems.
WriteData()
static void ItemManager.WriteData (Dictionary< string, ItemDefinition > allItems, HashSet< string > scopes) static
Parameters
allItems All items to serialize.
References _settings, FILENAMEITEMS, FILENAMESCOPES, and ProjectPrefs.GetString().
Member Data Documentation
_allItems
Dictionary<string, ItemDefinition> ItemManager._allItems private
Referenced by ReadDataLocally(), and SpawnItemInstance().
_itemScopes
HashSet<string> ItemManager._itemScopes private
Referenced by ReadDataLocally().
_settings
readonly JsonSerializerSettings ItemManager._settings = new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.All } static private
Referenced by ReadItemData(), ReadItemScopes(), and WriteData().
FILENAMEITEMS
string ItemManager.FILENAMEITEMS = "ItemData.txt" static private
Referenced by ReadItemData(), and WriteData().
FILENAMESCOPES
string ItemManager.FILENAMESCOPES = "ItemScopeData.txt" static private
Referenced by ReadItemScopes(), and WriteData().
Property Documentation
AllItems
Dictionary<string, ItemDefinition> ItemManager.AllItems get
ItemScopes
HashSet<string> ItemManager.ItemScopes get
Event Documentation
OnScopeEdited
Action<ItemScope> ItemManager.OnScopeEdited static
Referenced by ScopeEdited().