UnityToolbox: DialogGraphPathSelectionWindow Class Reference
DialogGraphPathSelectionWindow Class Reference
Static Public Member Functions
static void Open (DialogGraphWindow graph)
Properties
DialogGraphWindow Graph [set]
Private Member Functions
void OnEnable ()
void OnGUI ()
void DisplaySetting ()
Private Attributes
string _assetPathInProject
string _status
DialogGraphWindow _graph
Member Function Documentation
DisplaySetting()
void DialogGraphPathSelectionWindow.DisplaySetting () private
References _assetPathInProject, _graph, _status, ProjectPrefs.SetString(), and DialogGraphWindow.UpdateData().
Referenced by OnGUI().
OnEnable()
void DialogGraphPathSelectionWindow.OnEnable () private
References _assetPathInProject, and ProjectPrefs.GetString().
OnGUI()
void DialogGraphPathSelectionWindow.OnGUI () private
References DisplaySetting().
Open()
static void DialogGraphPathSelectionWindow.Open (DialogGraphWindow graph) static
Referenced by DialogGraphWindow.Open().
Member Data Documentation
_assetPathInProject
string DialogGraphPathSelectionWindow._assetPathInProject private
Referenced by DisplaySetting(), and OnEnable().
_graph
DialogGraphWindow DialogGraphPathSelectionWindow._graph private
Referenced by DisplaySetting().
_status
string DialogGraphPathSelectionWindow._status private
Referenced by DisplaySetting().
Property Documentation
Graph
DialogGraphWindow DialogGraphPathSelectionWindow.Graph set