UnityToolbox: LocalisationScope Struct Reference
LocalisationScope Struct Reference
The scope which is used to indentify and serialize localisation data.
Public Member Functions
override bool Equals (object obj)
override int GetHashCode ()
Public Attributes
string Name
Member Function Documentation
Equals()
override bool LocalisationScope.Equals (object obj)
References Name.
Referenced by Localizer.AddScope(), Localizer.EditScope(), and Localizer.RemoveScope().
GetHashCode()
override int LocalisationScope.GetHashCode ()
Member Data Documentation
Name
string LocalisationScope.Name
Referenced by Localizer.EditScope(), Equals(), LocalisationDrawer.OnGUI(), and Localizer.RemoveScope().