var _item_definition_drawer_8cs =
[
    [ "UnityToolbox.GameplayFeatures.Items.Management.Editor.ItemDefinitionDrawer", "class_unity_toolbox_1_1_gameplay_features_1_1_items_1_1_management_1_1_editor_1_1_item_definition_drawer.html", "class_unity_toolbox_1_1_gameplay_features_1_1_items_1_1_management_1_1_editor_1_1_item_definition_drawer" ]
];