var _localization_edit_language_window_8cs =
[
    [ "UnityToolbox.UI.Localization.Editor.LocalizationEditLanguageWindow", "class_unity_toolbox_1_1_u_i_1_1_localization_1_1_editor_1_1_localization_edit_language_window.html", "class_unity_toolbox_1_1_u_i_1_1_localization_1_1_editor_1_1_localization_edit_language_window" ]
];