var _localisation_edit_language_window_8cs =
[
    [ "UnityToolbox.UI.Localisation.Editor.LocalisationEditLanguageWindow", "class_unity_toolbox_1_1_u_i_1_1_localisation_1_1_editor_1_1_localisation_edit_language_window.html", "class_unity_toolbox_1_1_u_i_1_1_localisation_1_1_editor_1_1_localisation_edit_language_window" ]
];