var _serialized_data_error_details_8cs =
[
    [ "UnityToolbox.GameplayFeatures.SerializationData.SerializedDataErrorDetails", "class_unity_toolbox_1_1_gameplay_features_1_1_serialization_data_1_1_serialized_data_error_details.html", "class_unity_toolbox_1_1_gameplay_features_1_1_serialization_data_1_1_serialized_data_error_details" ]
];