var _terrain_decoration_child_info_8cs =
[
    [ "UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainDecorationChildInfo", "class_unity_toolbox_1_1_gameplay_features_1_1_procedural_generation_1_1_terrain_1_1_terrain_decoration_child_info.html", "class_unity_toolbox_1_1_gameplay_features_1_1_procedural_generation_1_1_terrain_1_1_terrain_decoration_child_info" ]
];