var _terrain_decoration_information_8cs =
[
    [ "UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainDecorationInformation", "class_unity_toolbox_1_1_gameplay_features_1_1_procedural_generation_1_1_terrain_1_1_terrain_decoration_information.html", "class_unity_toolbox_1_1_gameplay_features_1_1_procedural_generation_1_1_terrain_1_1_terrain_decoration_information" ]
];