UnityToolbox: UnityToolbox.General.Preferences.ProjectPrefs Class Reference
UnityToolbox.General.Preferences.ProjectPrefs Class Reference
Project preferences. Just like the PlayerPrefs but within the editor. These are stored within a created resource folder.
Static Public Member Functions
static void SetString (string key, string value)
Saves a string value to the project prefs.
static string GetString (string key)
Reads a string value from the project prefs.
Member Function Documentation
GetString()
static string UnityToolbox.General.Preferences.ProjectPrefs.GetString (string key) static
Parameters
key The key, which indentifies the value. See ProjectPrefKeys for UnityToolbox internal use.
Returns
The read value.
Exceptions
ArgumentException
Referenced by UnityToolbox.General.Management.ResourcesUtil.GetLocalPath(), UnityToolbox.General.Management.ResourcesUtil.GetProjectPath(), UnityToolbox.General.Management.ResourcesUtil.GetResourcesPath(), UnityToolbox.GameplayFeatures.Items.Management.Itemizer.Initialize(), UnityToolbox.UI.Localization.Localizzer.Initialize(), and UnityToolbox.General.Management.ResourcesUtil.WriteFile().
SetString()
static void UnityToolbox.General.Preferences.ProjectPrefs.SetString (string key, string value) static
Parameters
key The key, which indentifies the value. See ProjectPrefKeys for UnityToolbox internal use.
value The value to save.
Exceptions
ArgumentException
Referenced by UnityToolbox.General.Management.ResourcesUtil.TrySetValidPath().