UnityToolbox: UnityToolbox.General.Management.ResourcesUtil Class Reference
UnityToolbox.General.Management.ResourcesUtil Class Reference
A utility which writes and reads data with correctly formatted paths.
Static Public Member Functions
static bool IsFullPathValid (string path)
Checks whether the path is valid and defined with a "Resources" folder.
static bool TrySetValidPath (string fullPath, string key)
Tries to define a path within the ProjectPrefs. The Application.dataPath will be removed from it.
static string GetLocalPath (string key)
Builds the local path from the stored path within the ProjectPrefs.
static string GetResourcesPath (string key)
Builds the "Resources" path from the stored path within the ProjectPrefs.
static string GetProjectPath (string key)
Builds the project path from the stored path within the ProjectPrefs.
static T GetFileData< T > (string key, string filename)
Reads a TextAsset with a key for the ProjectPrefs and the filename.
static void WriteFile (string key, string filename, object fileData)
Writes an object to a file and refreshes the AssetDatabase.
Member Function Documentation
GetFileData< T >()
static T UnityToolbox.General.Management.ResourcesUtil.GetFileData< T > (string key, string filename) static
Parameters
key The key for the ProjectPrefs.
filename The filename.
Returns
The cast values of the file.
References UnityToolbox.General.Management.ResourcesUtil.GetLocalPath(), and UnityToolbox.General.Management.ResourcesUtil.GetResourcesPath().
GetLocalPath()
static string UnityToolbox.General.Management.ResourcesUtil.GetLocalPath (string key) static
Parameters
key The key for the ProjectPrefs.
Returns
The local path.
References UnityToolbox.General.Preferences.ProjectPrefs.GetString().
Referenced by UnityToolbox.General.Management.ResourcesUtil.GetFileData< T >(), and UnityToolbox.General.Management.ResourcesUtil.WriteFile().
GetProjectPath()
static string UnityToolbox.General.Management.ResourcesUtil.GetProjectPath (string key) static
Parameters
key The key for the ProjectPrefs.
Returns
A project directory.
References UnityToolbox.General.Preferences.ProjectPrefs.GetString().
GetResourcesPath()
static string UnityToolbox.General.Management.ResourcesUtil.GetResourcesPath (string key) static
Parameters
key The key for the ProjectPrefs.
Returns
The resources path.
References UnityToolbox.General.Preferences.ProjectPrefs.GetString().
Referenced by UnityToolbox.General.Management.ResourcesUtil.GetFileData< T >().
IsFullPathValid()
static bool UnityToolbox.General.Management.ResourcesUtil.IsFullPathValid (string path) static
Parameters
path The local path.
Returns
Whether a path is a valid resources path.
Referenced by UnityToolbox.GameplayFeatures.Items.Management.Itemizer.Initialize(), UnityToolbox.UI.Localization.Localizzer.Initialize(), and UnityToolbox.General.Management.ResourcesUtil.TrySetValidPath().
TrySetValidPath()
static bool UnityToolbox.General.Management.ResourcesUtil.TrySetValidPath (string fullPath, string key) static
Parameters
path The local path.
key The key for the ProjectPrefs.
Returns
Whether the path could be set.
References UnityToolbox.General.Management.ResourcesUtil.IsFullPathValid(), and UnityToolbox.General.Preferences.ProjectPrefs.SetString().
WriteFile()
static void UnityToolbox.General.Management.ResourcesUtil.WriteFile (string key, string filename, object fileData) static
Parameters
key The key for the ProjectPrefs.
filename The filename with extension.
fileData The object to write.
References UnityToolbox.General.Management.ResourcesUtil.GetLocalPath(), and UnityToolbox.General.Preferences.ProjectPrefs.GetString().
Referenced by UnityToolbox.GameplayFeatures.Items.Management.Itemizer.WriteData(), and UnityToolbox.UI.Localization.Localizzer.WriteData().