UnityToolbox: RaycastDetection Class Reference
RaycastDetection Class Reference abstract
This script is used for interactions with objects with optional tooltips.
Public Member Functions
void Start ()
void Update ()
abstract void OnInteraction (RaycastHit raycastHit)
Execute whatever should happen when the raycast found a valid object to interact with.
abstract void OnInteraction (RaycastHit2D raycastHit)
Execute whatever should happen when the raycast found a valid object to interact with.
abstract void OnHit (RaycastHit raycastHit)
Execute whatever should happen when the raycast found a valid object.
abstract void OnHit (RaycastHit2D raycastHit)
Execute whatever should happen when the raycast found a valid object.
Protected Attributes
string _tooltip
string _appendedTooltip
string _interactActionName
Transform _raycastLocation
PlayerInput _input
bool _tooltipEnabled
Whether the tooltip module should be used to display text.
bool _isBinding
Member Function Documentation
OnHit() [1/2]
abstract void RaycastDetection.OnHit (RaycastHit raycastHit) pure virtual
Parameters
raycastHit The raycast data.
Implemented in StartDialogInteraction, and ToggleMenuInteraction.
Referenced by Update().
OnHit() [2/2]
abstract void RaycastDetection.OnHit (RaycastHit2D raycastHit) pure virtual
Parameters
raycastHit The raycast data.
Implemented in StartDialogInteraction, and ToggleMenuInteraction.
OnInteraction() [1/2]
abstract void RaycastDetection.OnInteraction (RaycastHit raycastHit) pure virtual
Parameters
raycastHit The raycast data.
Implemented in StartDialogInteraction, and ToggleMenuInteraction.
Referenced by Update().
OnInteraction() [2/2]
abstract void RaycastDetection.OnInteraction (RaycastHit2D raycastHit) pure virtual
Parameters
raycastHit The raycast data.
Implemented in StartDialogInteraction, and ToggleMenuInteraction.
Start()
void RaycastDetection.Start ()
References _isBinding, and _tooltipEnabled.
Update()
void RaycastDetection.Update ()
References _appendedTooltip, _input, _interactActionName, _isBinding, _raycastLocation, _tooltip, _tooltipEnabled, UnityToolbox.UI.Settings.SettingsManager.CurrentValueOfControl(), OnHit(), and OnInteraction().
Member Data Documentation
_appendedTooltip
string RaycastDetection._appendedTooltip protected
Referenced by Update().
_input
PlayerInput RaycastDetection._input protected
Referenced by Update().
_interactActionName
string RaycastDetection._interactActionName protected
Referenced by Update().
_isBinding
bool RaycastDetection._isBinding protected
Referenced by Start(), and Update().
_raycastLocation
Transform RaycastDetection._raycastLocation protected
Referenced by Update().
_tooltip
string RaycastDetection._tooltip protected
Referenced by Update().
_tooltipEnabled
bool RaycastDetection._tooltipEnabled protected
Referenced by Start(), and Update().