UnityToolbox: UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow Class Reference
UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow Class Reference
Public Member Functions
void InitializeWindow ()
void OnGUI ()
void DefineSettings (bool enableOcclusion, bool enableNormal, bool enableMetallic, bool enableEmission, bool enableRoughness)
void DeleteLayer (int currentPos)
bool MoveLayer (TerrainGenerationHeightColorLayer terrainGenerationHeightColorLayer, int prev, int currentPos)
SerializedDataErrorDetails Deserialize (List< TerrainGenerationHeightColorData > data)
List< TerrainGenerationHeightColorData > Serialize ()
Public Member Functions inherited from UnityToolbox.GameplayFeatures.SerializationData.ISerializedDataContainer< List< TerrainGenerationHeightColorData > >
abstract SerializedDataErrorDetails Deserialize (T obj)
abstract T Serialize ()
Static Public Member Functions
static TerrainGenerationHeightColorsWindow Open (bool enableSettings)
static SerializedDataErrorDetails DummyDeserialize (List< TerrainGenerationHeightColorData > data)
Public Attributes
Action< StatusException > OnUpdateStatus
Action< List< TerrainGenerationHeightColorData > > OnClose
bool EnableSettings
Member Function Documentation
DefineSettings()
void UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.DefineSettings (bool enableOcclusion, bool enableNormal, bool enableMetallic, bool enableEmission, bool enableRoughness)
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorLayer.Data.
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.DrawDetailsRest().
DeleteLayer()
void UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.DeleteLayer (int currentPos)
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.CurrentPos, UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorLayer.Data, UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.Instance, and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.UpdateStatus().
Deserialize()
SerializedDataErrorDetails UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.Deserialize (List< TerrainGenerationHeightColorData > data)
References UnityToolbox.GameplayFeatures.SerializationData.SerializedDataErrorDetails.HasErrors, UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.InitializeWindow(), and UnityToolbox.GameplayFeatures.SerializationData.SerializedDataErrorDetails.Traced.
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.DrawDetailsRest().
DummyDeserialize()
static SerializedDataErrorDetails UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.DummyDeserialize (List< TerrainGenerationHeightColorData > data) static
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorLayer.Deserialize(), UnityToolbox.GameplayFeatures.SerializationData.SerializedDataErrorDetails.HasErrors, and UnityToolbox.GameplayFeatures.SerializationData.SerializedDataErrorDetails.Traced.
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.DeserializeRest().
InitializeWindow()
void UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.InitializeWindow ()
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.Deserialize().
MoveLayer()
bool UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.MoveLayer (TerrainGenerationHeightColorLayer terrainGenerationHeightColorLayer, int prev, int currentPos)
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.Instance, and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.UpdateStatus().
OnGUI()
void UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.OnGUI ()
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorLayer.Data, UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorLayer.DrawDetails(), and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.EnableSettings.
Open()
static TerrainGenerationHeightColorsWindow UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.Open (bool enableSettings) static
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.DrawDetailsRest().
Serialize()
List< TerrainGenerationHeightColorData > UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.Serialize () virtual
Implements UnityToolbox.GameplayFeatures.SerializationData.ISerializedDataContainer< List< TerrainGenerationHeightColorData > >.
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorLayer.Serialize().
Member Data Documentation
EnableSettings
bool UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.EnableSettings
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.OnGUI().
OnClose
Action<List<TerrainGenerationHeightColorData> > UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.OnClose
OnUpdateStatus
Action<StatusException> UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.OnUpdateStatus