UnityToolbox: UnityToolbox.GameplayFeatures.ProceduralGeneration.TerrainGenerationIO Class Reference
UnityToolbox.GameplayFeatures.ProceduralGeneration.TerrainGenerationIO Class Reference
A singleton which reads and writes all data for the terrain generation.
Public Member Functions
void WriteData (Dictionary< string, TerrainGenerationData > data)
Writes the procedural generation data.
Dictionary< string, TerrainGenerationData > ReadData ()
Reads the procedural generation data.
bool Initialize ()
Initializes the singleton to check if a valid path is set.
Properties
static TerrainGenerationIO Instance [get]
The singleton instance.
Member Function Documentation
Initialize()
bool UnityToolbox.GameplayFeatures.ProceduralGeneration.TerrainGenerationIO.Initialize ()
Returns
References UnityToolbox.General.Preferences.ProjectPrefs.GetString(), and UnityToolbox.General.Management.ResourcesUtil.IsFullPathValid().
ReadData()
Dictionary< string, TerrainGenerationData > UnityToolbox.GameplayFeatures.ProceduralGeneration.TerrainGenerationIO.ReadData ()
Returns
A dictionary with the names of each generator as keys.
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration.GenerateTerrain(), and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditor.OnInspectorGUI().
WriteData()
void UnityToolbox.GameplayFeatures.ProceduralGeneration.TerrainGenerationIO.WriteData (Dictionary< string, TerrainGenerationData > data)
Parameters
data A dictionary with the names of each generator as keys.
References UnityToolbox.General.Management.ResourcesUtil.WriteFile().
Property Documentation
Instance
TerrainGenerationIO UnityToolbox.GameplayFeatures.ProceduralGeneration.TerrainGenerationIO.Instance static get
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration.GenerateTerrain(), and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditor.OnInspectorGUI().