UnityToolbox: UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainDecoration Class Reference
UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainDecoration Class Reference
A script which places decoration on a generated terrain.
Public Member Functions
void DeleteObjects ()
Deletes all spawned objects.
void PlaceObjects ()
Places all defined objects.
Member Function Documentation
DeleteObjects()
void UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainDecoration.DeleteObjects ()
Referenced by UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerateAll.DeleteAllDecoration(), and UnityToolbox.GameplayFeatures.ProzedualGeneration.Editor.TerrainDecorationEditor.OnInspectorGUI().
PlaceObjects()
void UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainDecoration.PlaceObjects ()
References UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainDecorationInformation.Clone(), UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.GeneratedGrid, UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.GeneratedMesh, UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainDecorationInformation.HeightOffset, UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainDecorationInformation.Object, UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainDecorationChildInfo.RelativeToParent, UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainDecorationInformation.Weight, and UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainDecorationInformation.WidthPlacement.
Referenced by UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerateAll.GenerateAll(), and UnityToolbox.GameplayFeatures.ProzedualGeneration.Editor.TerrainDecorationEditor.OnInspectorGUI().