UnityToolbox: UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayered Class Reference
UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayered Class Reference
Public Member Functions
TerrainMeshTypeLayered ()
override void DrawDetails ()
bool MoveLayer (TerrainMeshTypeLayeredLayer layer, int currentPos, int goalPos)
bool DeleteLayer (int currentPos)
override SerializedDataErrorDetails Deserialize (TerrainMeshTypeBaseData obj)
override TerrainMeshTypeBaseData Serialize ()
abstract void DrawDetails ()
abstract SerializedDataErrorDetails Deserialize (TerrainMeshTypeBaseData obj)
abstract TerrainMeshTypeBaseData Serialize ()
Public Member Functions inherited from UnityToolbox.GameplayFeatures.SerializationData.ISerializedDataContainer< TerrainMeshTypeBaseData >
abstract SerializedDataErrorDetails Deserialize (T obj)
abstract T Serialize ()
Additional Inherited Members
Protected Member Functions inherited from UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.TerrainMeshType
void DrawLineHorizontal ()
Constructor & Destructor Documentation
TerrainMeshTypeLayered()
UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayered.TerrainMeshTypeLayered ()
Member Function Documentation
DeleteLayer()
bool UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayered.DeleteLayer (int currentPos)
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.Instance, and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.UpdateStatus().
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.DrawDetails().
Deserialize()
override SerializedDataErrorDetails UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayered.Deserialize (TerrainMeshTypeBaseData obj) virtual
Implements UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.TerrainMeshType.
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredLayerBaseData.CurrentPos, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredData.EnabledEmission, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredData.EnabledMetallic, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredData.EnabledNormal, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredData.EnabledOcclusion, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredData.EnabledRoughness, UnityToolbox.GameplayFeatures.SerializationData.SerializedDataErrorDetails.HasErrors, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredData.Layers, and UnityToolbox.GameplayFeatures.SerializationData.SerializedDataErrorDetails.Traced.
DrawDetails()
override void UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayered.DrawDetails () virtual
Implements UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.TerrainMeshType.
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredData.AssetPositionNoise, UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.DrawDetails(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.TerrainMeshType.DrawLineHorizontal(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainMeshTypeBaseData.EnabledAssets, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredData.EnabledEmission, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredData.EnabledMetallic, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredData.EnabledNormal, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredData.EnabledOcclusion, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredData.EnabledRoughness, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredData.SizeBetweenVertices, and UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredData.VertexMultiplier.
MoveLayer()
bool UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayered.MoveLayer (TerrainMeshTypeLayeredLayer layer, int currentPos, int goalPos)
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.Instance, and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.UpdateStatus().
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.DrawDetails().
Serialize()
override TerrainMeshTypeBaseData UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayered.Serialize () virtual
Implements UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.TerrainMeshType.
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.CurrentPos, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredData.Layers, and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.Serialize().