UnityToolbox: SettingsManager Class Reference
SettingsManager Class Reference
This manager controls all relevant information about settings, that is key, volume and sensitivity controls. Requires the UIEventManager and PlayerPrefKeys.
Public Member Functions
bool SetKey (string control, string path, string actionName)
Sets the setting for a key control.
void ResetKey (string control, string actionName)
Resets the setting for a key control to the last known setting.
void ResetAllKeys ()
Resets the settings of all controls to its last known setting.
string CurrentValueOfControl (string control, string actionName)
Reads the current value of a given key control.
void SoundValueChanged (AudioType type, float newValue)
Executes the SettingsManager.OnSoundValueChanged event.
void SenseValueChanged (float newValue)
Executes the SettingsManager.OnSenseValueChanged event.
Public Member Functions inherited from Module
virtual void Awake ()
Public Attributes
Action< AudioType, float > OnSoundValueChanged
The event which is executed as soon as volumes are changed.
Action< float > OnSenseValueChanged
The event which is executed as soon as the mouse sensitivity is changed.
Member Function Documentation
CurrentValueOfControl()
string SettingsManager.CurrentValueOfControl (string control, string actionName)
Parameters
control The control name, which specifies more information about the action. (e.g "left" or "up")
actionName The action name (e.g. "Character Jump")
Returns
Returns the string path of the current setting.
Referenced by RebindButton.OnGUI(), RaycastDetection.Update(), and TriggerDetection.Update().
ResetAllKeys()
void SettingsManager.ResetAllKeys ()
Referenced by ResetButton.OnPointerClick().
ResetKey()
void SettingsManager.ResetKey (string control, string actionName)
Parameters
control The control name, which specifies more information about the action. (e.g "left" or "up")
actionName The action name (e.g. "Character Jump")
Referenced by ResetButton.OnPointerClick().
SenseValueChanged()
void SettingsManager.SenseValueChanged (float newValue)
Parameters
newValue The new value for the mouse sensitivity, must be between 0-1.
References OnSenseValueChanged.
SetKey()
bool SettingsManager.SetKey (string control, string path, string actionName)
Parameters
control The control name, which specifies more information about the action. (e.g "left" or "up")
path The path to the new key (e.g."<Keyboard>/W" or "<Mouse>/LeftClick)"
actionName The action name (e.g. "Character Jump")
Returns
Returns false if the given key path is already taken.
SoundValueChanged()
void SettingsManager.SoundValueChanged (AudioType type, float newValue)
Parameters
type The sound type. (e.g. AudioType.Music or AudioType.Effects)
newValue The new value for the volume, must be between 0-1.
References OnSoundValueChanged.
Member Data Documentation
OnSenseValueChanged
Action<float> SettingsManager.OnSenseValueChanged
Referenced by SenseValueChanged().
OnSoundValueChanged
Action<AudioType, float> SettingsManager.OnSoundValueChanged
Referenced by SoundValueChanged().