UnityToolbox: UnityToolbox.UI.Localisation.Localizer Class Reference
UnityToolbox.UI.Localisation.Localizer Class Reference
The heart of the localisation system. Every localisation, its serialisation and editing is managed here.
Public Member Functions
void AddLocalisation (LocalisationID localisationID, Dictionary< LocalisationLanguage, string > localisations)
Adds a new localisation to the system.
void AddScope (string scopeName)
Adds a new LocalisationScope to the system.
void AddLanguage (string languageName, string languageShortName)
Adds a new LocalisationLanguage to the system.
void RemoveLanguage (LocalisationLanguage language)
Removes a LocalisationLanguage from the system.
void RemoveScope (LocalisationScope scope)
Removes a LocalisationScope from the system.
void RemoveLocalisation (LocalisationID localisationID)
Removes a localisation, that is a LocalisationID with all its content, from the system.
void EditLocalisationID (LocalisationID oldID, LocalisationID newID)
Edits an existing LocalisationID by replacing the IDs, but keeping its content.
void EditScope (LocalisationScope oldScope, string newScopeName)
Replaces a LocalisationScope with a new one for all available data.
void EditLanguage (LocalisationLanguage oldLanguage, string newLanguageName, string newLanguageShortName)
Replaces a LocalisationLanguage with a new one for all available data.
void EditLocalisation (LocalisationID localisationID, Dictionary< LocalisationLanguage, string > localisations)
Edits a given localisation found by the LocalisationID by replacing the current content with localisations .
void WriteData ()
Writes the data to disk. For this to work, a valid path within the project must be setup.
void Initialize ()
Initializes the Localizer. This is required due to its dependency on a valid path.
Properties
static Localizer Instance [get]
Dictionary< LocalisationID, Dictionary< LocalisationLanguage, string > > LocalisationData [get]
HashSet< LocalisationLanguage > LocalisationLanguages [get]
HashSet< LocalisationScope > LocalisationScopes [get]
LocalisationScope DefaultScope [get]
bool IsInitialized [get]
Events
Action< LocalisationScope > ScopeEdited
Action< LocalisationLanguage > LanguageEdited
Action< LocalisationID > LocalisationIDEdited
Member Function Documentation
AddLanguage()
void UnityToolbox.UI.Localisation.Localizer.AddLanguage (string languageName, string languageShortName)
Parameters
languageName
languageShortName
Exceptions
LocalisationException
References UnityToolbox.UI.Localisation.Localizer.Initialize().
AddLocalisation()
void UnityToolbox.UI.Localisation.Localizer.AddLocalisation (LocalisationID localisationID, Dictionary< LocalisationLanguage, string > localisations)
Parameters
localisationID
localisations
Exceptions
LocalisationException
References UnityToolbox.UI.Localisation.Localizer.Initialize(), and UnityToolbox.UI.Localisation.LocalisationLanguage.Name.
AddScope()
void UnityToolbox.UI.Localisation.Localizer.AddScope (string scopeName)
Parameters
scopeName
Exceptions
LocalisationException
References UnityToolbox.UI.Localisation.LocalisationScope.Equals(), and UnityToolbox.UI.Localisation.Localizer.Initialize().
EditLanguage()
void UnityToolbox.UI.Localisation.Localizer.EditLanguage (LocalisationLanguage oldLanguage, string newLanguageName, string newLanguageShortName)
Parameters
oldLanguage
newLanguageName
newLanguageShortName
Exceptions
LocalisationException
References UnityToolbox.UI.Localisation.Localizer.Initialize().
Referenced by UnityToolbox.UI.Localisation.Editor.LocalisationEditLanguageWindow.OnGUI().
EditLocalisation()
void UnityToolbox.UI.Localisation.Localizer.EditLocalisation (LocalisationID localisationID, Dictionary< LocalisationLanguage, string > localisations)
Parameters
localisationID
localisations
Exceptions
LocalisationException
References UnityToolbox.UI.Localisation.Localizer.Initialize(), and UnityToolbox.UI.Localisation.LocalisationLanguage.Name.
Referenced by UnityToolbox.UI.Localisation.Editor.LocalisationEditIDWindow.OnGUI().
EditLocalisationID()
void UnityToolbox.UI.Localisation.Localizer.EditLocalisationID (LocalisationID oldID, LocalisationID newID)
Parameters
oldID
newID
Exceptions
LocalisationException
References UnityToolbox.UI.Localisation.Localizer.Initialize().
Referenced by UnityToolbox.UI.Localisation.Editor.LocalisationEditIDWindow.OnGUI().
EditScope()
void UnityToolbox.UI.Localisation.Localizer.EditScope (LocalisationScope oldScope, string newScopeName)
Parameters
oldScope
newScopeName
Exceptions
LocalisationException
References UnityToolbox.UI.Localisation.LocalisationScope.Equals(), UnityToolbox.UI.Localisation.Localizer.Initialize(), and UnityToolbox.UI.Localisation.LocalisationScope.Name.
Referenced by UnityToolbox.UI.Localisation.Editor.LocalisationEditScopeWindow.OnGUI().
Initialize()
void UnityToolbox.UI.Localisation.Localizer.Initialize ()
References UnityToolbox.General.Preferences.ProjectPrefs.GetString(), and UnityToolbox.General.Management.ResourcesUtil.IsFullPathValid().
Referenced by UnityToolbox.UI.Localisation.Localizer.AddLanguage(), UnityToolbox.UI.Localisation.Localizer.AddLocalisation(), UnityToolbox.UI.Localisation.Localizer.AddScope(), UnityToolbox.UI.Localisation.Localizer.EditLanguage(), UnityToolbox.UI.Localisation.Localizer.EditLocalisation(), UnityToolbox.UI.Localisation.Localizer.EditLocalisationID(), UnityToolbox.UI.Localisation.Localizer.EditScope(), UnityToolbox.UI.Localisation.LocalizedText.OnValidate(), UnityToolbox.UI.Localisation.Localizer.RemoveLanguage(), UnityToolbox.UI.Localisation.Localizer.RemoveLocalisation(), UnityToolbox.UI.Localisation.Localizer.RemoveScope(), and UnityToolbox.UI.Localisation.Localizer.WriteData().
RemoveLanguage()
void UnityToolbox.UI.Localisation.Localizer.RemoveLanguage (LocalisationLanguage language)
Parameters
language
Exceptions
LocalisationException
References UnityToolbox.UI.Localisation.Localizer.Initialize().
RemoveLocalisation()
void UnityToolbox.UI.Localisation.Localizer.RemoveLocalisation (LocalisationID localisationID)
Parameters
localisationID
References UnityToolbox.UI.Localisation.Localizer.Initialize().
RemoveScope()
void UnityToolbox.UI.Localisation.Localizer.RemoveScope (LocalisationScope scope)
Parameters
scope
Exceptions
LocalisationException
References UnityToolbox.UI.Localisation.LocalisationScope.Equals(), UnityToolbox.UI.Localisation.Localizer.Initialize(), and UnityToolbox.UI.Localisation.LocalisationScope.Name.
WriteData()
void UnityToolbox.UI.Localisation.Localizer.WriteData ()
References UnityToolbox.UI.Localisation.Localizer.Initialize(), and UnityToolbox.General.Management.ResourcesUtil.WriteFile().
Referenced by UnityToolbox.UI.Localisation.Editor.LocalisationEditIDWindow.OnGUI(), UnityToolbox.UI.Localisation.Editor.LocalisationEditLanguageWindow.OnGUI(), and UnityToolbox.UI.Localisation.Editor.LocalisationEditScopeWindow.OnGUI().
Property Documentation
DefaultScope
LocalisationScope UnityToolbox.UI.Localisation.Localizer.DefaultScope get
Instance
Localizer UnityToolbox.UI.Localisation.Localizer.Instance static get
Referenced by UnityToolbox.UI.Localisation.Editor.LocalisationEditIDWindow.OnGUI(), UnityToolbox.UI.Localisation.Editor.LocalisationEditLanguageWindow.OnGUI(), UnityToolbox.UI.Localisation.Editor.LocalisationEditScopeWindow.OnGUI(), and UnityToolbox.UI.Localisation.LocalizedText.OnValidate().
IsInitialized
bool UnityToolbox.UI.Localisation.Localizer.IsInitialized get
Referenced by UnityToolbox.UI.Localisation.LocalizedText.OnValidate().
LocalisationData
Dictionary<LocalisationID, Dictionary<LocalisationLanguage, string> > UnityToolbox.UI.Localisation.Localizer.LocalisationData get
LocalisationLanguages
HashSet<LocalisationLanguage> UnityToolbox.UI.Localisation.Localizer.LocalisationLanguages get
Referenced by UnityToolbox.UI.Localisation.Editor.LocalisationEditIDWindow.OnGUI(), and UnityToolbox.UI.Localisation.LocalizedText.OnValidate().
LocalisationScopes
HashSet<LocalisationScope> UnityToolbox.UI.Localisation.Localizer.LocalisationScopes get
Referenced by UnityToolbox.UI.Localisation.Editor.LocalisationEditIDWindow.OnGUI().
Event Documentation
LanguageEdited
Action<LocalisationLanguage> UnityToolbox.UI.Localisation.Localizer.LanguageEdited
LocalisationIDEdited
Action<LocalisationID> UnityToolbox.UI.Localisation.Localizer.LocalisationIDEdited
ScopeEdited
Action<LocalisationScope> UnityToolbox.UI.Localisation.Localizer.ScopeEdited