UnityToolbox: UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration Class Reference
UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration Class Reference
The main terrain generation component within a scene.
Public Member Functions
void GenerateTerrain ()
Generates the terrain with selected settings.
Public Member Functions inherited from UnityToolbox.General.Management.Module
virtual void Awake ()
Public Attributes
Material TerrainMaterial
Dictionary< string, TerrainGenerationData > Data
int SelectedData
List< Texture2DArray > Texture2DArrays
List< Texture2D > Texture2Ds
Protected Attributes
TextureSizes _textureSize
TextureFormat _textureFormat
List< TerrainGenerationHeightColorData > _allHeightData
Member Function Documentation
GenerateTerrain()
void UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration.GenerateTerrain ()
Exceptions
DataException Thrown either no data can be found or the terrain generation has encountered errors with its data.
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration.Data, UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGenerationGenerator.Generate(), UnityToolbox.GameplayFeatures.ProceduralGeneration.TerrainGenerationIO.Instance, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationData.MeshData, UnityToolbox.GameplayFeatures.ProceduralGeneration.TerrainGenerationIO.ReadData(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration.SelectedData, UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGenerationGenerator.SetData(), and UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration.TerrainMaterial.
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditor.OnInspectorGUI().
Member Data Documentation
_allHeightData
List<TerrainGenerationHeightColorData> UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration._allHeightData protected
_textureFormat
TextureFormat UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration._textureFormat protected
_textureSize
TextureSizes UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration._textureSize protected
Data
Dictionary<string, TerrainGenerationData> UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration.Data
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration.GenerateTerrain(), and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditor.OnInspectorGUI().
SelectedData
int UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration.SelectedData
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration.GenerateTerrain(), and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditor.OnInspectorGUI().
TerrainMaterial
Material UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration.TerrainMaterial
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration.GenerateTerrain(), and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditor.OnInspectorGUI().
Texture2DArrays
List<Texture2DArray> UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration.Texture2DArrays
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditor.OnInspectorGUI().
Texture2Ds
List<Texture2D> UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration.Texture2Ds
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditor.OnInspectorGUI().