UnityToolbox: UnityToolbox.Audio.AudioMixer Class Reference
UnityToolbox.Audio.AudioMixer Class Reference
A audio mixer which plays audio clips and with optional defined volume settings. See AudioVolumeSetter.
Public Member Functions
void PlayRandomSource ()
Plays a random sound from the defined list.
void FadePause ()
void FadeResume ()
Properties
bool IsPassive [get, set]
bool IsPlaying [get]
Member Function Documentation
FadePause()
void UnityToolbox.Audio.AudioMixer.FadePause ()
FadeResume()
void UnityToolbox.Audio.AudioMixer.FadeResume ()
Referenced by UnityToolbox.Audio.AudioMixer.PlayRandomSource().
PlayRandomSource()
void UnityToolbox.Audio.AudioMixer.PlayRandomSource ()
References UnityToolbox.Audio.AudioMixer.FadeResume(), and UnityToolbox.Audio.AudioMixerItem.Source.
Referenced by UnityToolbox.UI.Menus.FlatMenu.GotoMenuButton.OnPointerClick(), UnityToolbox.UI.Menus.FlatMenu.ToggleMenuButton.OnPointerClick(), UnityToolbox.UI.Menus.MenuWheel.MenuWheelNavButton.OnPointerClick(), UnityToolbox.UI.Settings.Controls.RebindButton.OnPointerClick(), UnityToolbox.UI.Settings.Controls.ResetButton.OnPointerClick(), UnityToolbox.UI.Dialog.UI.NextDialogButton.OnPointerDown(), UnityToolbox.UI.Dialog.UI.NextDialogOptionButton.OnPointerDown(), UnityToolbox.UI.Menus.FlatMenu.GotoSceneButton.OnPointerDown(), UnityToolbox.UI.Menus.FlatMenu.QuitButton.OnPointerDown(), UnityToolbox.UI.Menus.FlatMenu.ResetSavegameButton.OnPointerDown(), UnityToolbox.UI.Menus.FlatMenu.OnHover.ShowOnHover.OnPointerEnter(), UnityToolbox.UI.Menus.FlatMenu.OnHover.SwapOnHover.OnPointerEnter(), UnityToolbox.UI.Menus.FlatMenu.OnHover.TintImageOnHover.OnPointerEnter(), UnityToolbox.UI.Menus.FlatMenu.OnHover.TintTextOnHover.OnPointerEnter(), UnityToolbox.UI.Settings.Sliders.UnitySliderSetting.UpdateValues(), and UnityToolbox.UI.Settings.Sliders.ImageSliderSetting.UpdateValues().
Property Documentation
IsPassive
bool UnityToolbox.Audio.AudioMixer.IsPassive get set
IsPlaying
bool UnityToolbox.Audio.AudioMixer.IsPlaying get