UnityToolbox: UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditor Class Reference
UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditor Class Reference
Public Member Functions
override void OnInspectorGUI ()
Member Function Documentation
OnInspectorGUI()
override void UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditor.OnInspectorGUI ()
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration.Data, UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration.GenerateTerrain(), UnityToolbox.General.Management.ResourcesUtil.GetResourcesPath(), UnityToolbox.GameplayFeatures.ProceduralGeneration.TerrainGenerationIO.Instance, UnityToolbox.GameplayFeatures.ProceduralGeneration.TerrainGenerationIO.ReadData(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration.SelectedData, UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration.TerrainMaterial, UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration.Texture2DArrays, and UnityToolbox.GameplayFeatures.ProceduralGeneration.Terrain.TerrainGeneration.Texture2Ds.