UnityToolbox: UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerateAll Class Reference
UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerateAll Class Reference
A helping script which references all terrain generation algorithms as buttons.
Public Member Functions
void GenerateAll ()
Generates the terrain and all decoration excluding anchors.
void GenerateAllWithAnchors ()
Generates the terrain and all decoration.
void DeleteAllDecoration ()
Deletes all genereated objects.
Member Function Documentation
DeleteAllDecoration()
void UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerateAll.DeleteAllDecoration ()
References UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainDecoration.DeleteObjects().
Referenced by UnityToolbox.GameplayFeatures.ProzedualGeneration.Editor.TerrainGenerateAllEditor.OnInspectorGUI().
GenerateAll()
void UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerateAll.GenerateAll ()
References UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.GenerateViaCellularAutomata(), and UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainDecoration.PlaceObjects().
Referenced by UnityToolbox.GameplayFeatures.ProzedualGeneration.Editor.TerrainGenerateAllEditor.OnInspectorGUI().
GenerateAllWithAnchors()
void UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerateAll.GenerateAllWithAnchors ()
References UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.GenerateWithAnchorPoints().
Referenced by UnityToolbox.GameplayFeatures.ProzedualGeneration.Editor.TerrainGenerateAllEditor.OnInspectorGUI().