UnityToolbox: UnityToolbox.PlayerControls.TriggerDetection Class Reference
UnityToolbox.PlayerControls.TriggerDetection Class Reference abstract
This script is used for interactions with objects with optional tooltips.
Public Member Functions
void Start ()
void Update ()
abstract void OnInteraction (GameObject foundObject)
Execute whatever should happen when the trigger found a valid object to interact with.
Protected Attributes
string _tooltip
string _appendedTooltip
string _interactActionName
PlayerInput _input
bool _tooltipEnabled
Whether the tooltip module should be used to display text.
bool _isBinding
Member Function Documentation
OnInteraction()
abstract void UnityToolbox.PlayerControls.TriggerDetection.OnInteraction (GameObject foundObject) pure virtual
Parameters
foundObject The trigger data.
Referenced by UnityToolbox.PlayerControls.TriggerDetection.Update().
Start()
void UnityToolbox.PlayerControls.TriggerDetection.Start ()
References UnityToolbox.PlayerControls.TriggerDetection._isBinding, and UnityToolbox.PlayerControls.TriggerDetection._tooltipEnabled.
Update()
void UnityToolbox.PlayerControls.TriggerDetection.Update ()
References UnityToolbox.PlayerControls.TriggerDetection._appendedTooltip, UnityToolbox.PlayerControls.TriggerDetection._input, UnityToolbox.PlayerControls.TriggerDetection._interactActionName, UnityToolbox.PlayerControls.TriggerDetection._isBinding, UnityToolbox.PlayerControls.TriggerDetection._tooltip, UnityToolbox.PlayerControls.TriggerDetection._tooltipEnabled, UnityToolbox.UI.Settings.SettingsManager.CurrentValueOfControl(), UnityToolbox.General.ColliderInfo.GetAllCollisions2D(), and UnityToolbox.PlayerControls.TriggerDetection.OnInteraction().
Member Data Documentation
_appendedTooltip
string UnityToolbox.PlayerControls.TriggerDetection._appendedTooltip protected
Referenced by UnityToolbox.PlayerControls.TriggerDetection.Update().
_input
PlayerInput UnityToolbox.PlayerControls.TriggerDetection._input protected
Referenced by UnityToolbox.PlayerControls.TriggerDetection.Update().
_interactActionName
string UnityToolbox.PlayerControls.TriggerDetection._interactActionName protected
Referenced by UnityToolbox.PlayerControls.TriggerDetection.Update().
_isBinding
bool UnityToolbox.PlayerControls.TriggerDetection._isBinding protected
Referenced by UnityToolbox.PlayerControls.TriggerDetection.Start(), and UnityToolbox.PlayerControls.TriggerDetection.Update().
_tooltip
string UnityToolbox.PlayerControls.TriggerDetection._tooltip protected
Referenced by UnityToolbox.PlayerControls.TriggerDetection.Update().
_tooltipEnabled
bool UnityToolbox.PlayerControls.TriggerDetection._tooltipEnabled protected
Referenced by UnityToolbox.PlayerControls.TriggerDetection.Start(), and UnityToolbox.PlayerControls.TriggerDetection.Update().