UnityToolbox: UnityToolbox.PlayerControls.RaycastDetection Class Reference
UnityToolbox.PlayerControls.RaycastDetection Class Reference abstract
This script is used for interactions with objects with optional tooltips.
Public Member Functions
void Start ()
void Update ()
abstract void OnInteraction (RaycastHit raycastHit)
Execute whatever should happen when the raycast found a valid object to interact with.
abstract void OnInteraction (RaycastHit2D raycastHit)
Execute whatever should happen when the raycast found a valid object to interact with.
abstract void OnHit (RaycastHit raycastHit)
Execute whatever should happen when the raycast found a valid object.
abstract void OnHit (RaycastHit2D raycastHit)
Execute whatever should happen when the raycast found a valid object.
Protected Attributes
string _tooltip
string _appendedTooltip
string _interactActionName
Transform _raycastLocation
PlayerInput _input
bool _tooltipEnabled
Whether the tooltip module should be used to display text.
bool _isBinding
Member Function Documentation
OnHit() [1/2]
abstract void UnityToolbox.PlayerControls.RaycastDetection.OnHit (RaycastHit raycastHit) pure virtual
Parameters
raycastHit The raycast data.
Implemented in UnityToolbox.PlayerControls.UI.StartDialogInteraction, and UnityToolbox.PlayerControls.UI.ToggleMenuInteraction.
Referenced by UnityToolbox.PlayerControls.RaycastDetection.Update().
OnHit() [2/2]
abstract void UnityToolbox.PlayerControls.RaycastDetection.OnHit (RaycastHit2D raycastHit) pure virtual
Parameters
raycastHit The raycast data.
Implemented in UnityToolbox.PlayerControls.UI.StartDialogInteraction, and UnityToolbox.PlayerControls.UI.ToggleMenuInteraction.
OnInteraction() [1/2]
abstract void UnityToolbox.PlayerControls.RaycastDetection.OnInteraction (RaycastHit raycastHit) pure virtual
Parameters
raycastHit The raycast data.
Implemented in UnityToolbox.PlayerControls.UI.StartDialogInteraction, and UnityToolbox.PlayerControls.UI.ToggleMenuInteraction.
Referenced by UnityToolbox.PlayerControls.RaycastDetection.Update().
OnInteraction() [2/2]
abstract void UnityToolbox.PlayerControls.RaycastDetection.OnInteraction (RaycastHit2D raycastHit) pure virtual
Parameters
raycastHit The raycast data.
Implemented in UnityToolbox.PlayerControls.UI.StartDialogInteraction, and UnityToolbox.PlayerControls.UI.ToggleMenuInteraction.
Start()
void UnityToolbox.PlayerControls.RaycastDetection.Start ()
References UnityToolbox.PlayerControls.RaycastDetection._isBinding, and UnityToolbox.PlayerControls.RaycastDetection._tooltipEnabled.
Update()
void UnityToolbox.PlayerControls.RaycastDetection.Update ()
References UnityToolbox.PlayerControls.RaycastDetection._appendedTooltip, UnityToolbox.PlayerControls.RaycastDetection._input, UnityToolbox.PlayerControls.RaycastDetection._interactActionName, UnityToolbox.PlayerControls.RaycastDetection._isBinding, UnityToolbox.PlayerControls.RaycastDetection._raycastLocation, UnityToolbox.PlayerControls.RaycastDetection._tooltip, UnityToolbox.PlayerControls.RaycastDetection._tooltipEnabled, UnityToolbox.UI.Settings.SettingsManager.CurrentValueOfControl(), UnityToolbox.PlayerControls.RaycastDetection.OnHit(), and UnityToolbox.PlayerControls.RaycastDetection.OnInteraction().
Member Data Documentation
_appendedTooltip
string UnityToolbox.PlayerControls.RaycastDetection._appendedTooltip protected
Referenced by UnityToolbox.PlayerControls.RaycastDetection.Update().
_input
PlayerInput UnityToolbox.PlayerControls.RaycastDetection._input protected
Referenced by UnityToolbox.PlayerControls.RaycastDetection.Update().
_interactActionName
string UnityToolbox.PlayerControls.RaycastDetection._interactActionName protected
Referenced by UnityToolbox.PlayerControls.RaycastDetection.Update().
_isBinding
bool UnityToolbox.PlayerControls.RaycastDetection._isBinding protected
Referenced by UnityToolbox.PlayerControls.RaycastDetection.Start(), and UnityToolbox.PlayerControls.RaycastDetection.Update().
_raycastLocation
Transform UnityToolbox.PlayerControls.RaycastDetection._raycastLocation protected
Referenced by UnityToolbox.PlayerControls.RaycastDetection.Update().
_tooltip
string UnityToolbox.PlayerControls.RaycastDetection._tooltip protected
Referenced by UnityToolbox.PlayerControls.RaycastDetection.Update().
_tooltipEnabled
bool UnityToolbox.PlayerControls.RaycastDetection._tooltipEnabled protected
Referenced by UnityToolbox.PlayerControls.RaycastDetection.Start(), and UnityToolbox.PlayerControls.RaycastDetection.Update().