UnityToolbox: UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator Class Reference
UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator Class Reference
The main component of the terrain generation. It can generate one mesh, with defined settings using CellularAutomata.
Public Member Functions
void GenerateViaCellularAutomata ()
Starts the generation with cellular automata.
void GenerateWithAnchorPoints ()
Starts the generation with anchor points. These are carved out in the terrain.
Protected Member Functions
Texture2DArray GenerateTextureArray (Texture2D[] textures)
void GenerateMesh ()
void FillGridWithFillerValues (int[,] grid)
void UpdateMaterial ()
Properties
int[,] GeneratedGrid [get]
Mesh GeneratedMesh [get]
Member Function Documentation
FillGridWithFillerValues()
void UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.FillGridWithFillerValues (int grid[,]) protected
Referenced by UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.GenerateViaCellularAutomata(), and UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.GenerateWithAnchorPoints().
GenerateMesh()
void UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.GenerateMesh () protected
Referenced by UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.GenerateViaCellularAutomata(), and UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.GenerateWithAnchorPoints().
GenerateTextureArray()
Texture2DArray UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.GenerateTextureArray (Texture2D[] textures) protected
Referenced by UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.UpdateMaterial().
GenerateViaCellularAutomata()
void UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.GenerateViaCellularAutomata ()
References UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.FillGridWithFillerValues(), UnityToolbox.General.Algorithms.CellularAutomata.Generate(), UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.GenerateMesh(), and UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.UpdateMaterial().
Referenced by UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerateAll.GenerateAll(), and UnityToolbox.GameplayFeatures.ProzedualGeneration.Editor.TerrainGeneratorEditor.OnInspectorGUI().
GenerateWithAnchorPoints()
void UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.GenerateWithAnchorPoints ()
References UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.FillGridWithFillerValues(), UnityToolbox.General.Algorithms.CellularAutomata.Generate(), UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.GenerateMesh(), and UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.UpdateMaterial().
Referenced by UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerateAll.GenerateAllWithAnchors().
UpdateMaterial()
void UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.UpdateMaterial () protected
References UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.HeightColorTypes.BlendAmount, UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.GenerateTextureArray(), UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.HeightColorTypes.HeightStart, UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.HeightColorTypes.TerrainColor, UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.HeightColorTypes.TerrainColorStrength, UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.HeightColorTypes.TerrainTexture, and UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.HeightColorTypes.TerrainTextureScale.
Referenced by UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.GenerateViaCellularAutomata(), and UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.GenerateWithAnchorPoints().
Property Documentation
GeneratedGrid
int [,] UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.GeneratedGrid get
Referenced by UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainDecoration.PlaceObjects().
GeneratedMesh
Mesh UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainGenerator.GeneratedMesh get
Referenced by UnityToolbox.GameplayFeatures.ProzedualGeneration.Terrain.TerrainDecoration.PlaceObjects().