UnityToolbox: UnityToolbox.UI.Settings.ResetButton Class Reference
UnityToolbox.UI.Settings.ResetButton Class Reference
A script which is placed on a UI element and acts as a button. It will reset key controls to the last know setting. It requires a SettingsManager, as well information about the ActionName and the Control (e.g. "Character Move" & "left"). The control can be left empty if no information is necessary. (e.g. "Character Jump" & "")
Public Member Functions
void Awake ()
void OnPointerClick (PointerEventData eventData)
Member Function Documentation
Awake()
void UnityToolbox.UI.Settings.ResetButton.Awake ()
OnPointerClick()
void UnityToolbox.UI.Settings.ResetButton.OnPointerClick (PointerEventData eventData)
References AudioMixer.PlayRandomSource(), UnityToolbox.UI.Settings.SettingsManager.ResetAllKeys(), and UnityToolbox.UI.Settings.SettingsManager.ResetKey().