UnityToolbox: UnityToolbox.UI.Menus.MenuManager Class Reference
UnityToolbox.UI.Menus.MenuManager Class Reference
This manager takes care of all menu related tasks. That is, sorting within a hierarchy and switching between visible canvases. The menus are called with types also defined here. Requires the UIEventManager.
Public Member Functions
void SetActiveMenu (Menu menu)
Sets the active menu with a given <see cref="Menu". Disables the current if there is one. Null will disable any active menu and enable the overlay if there is one set.
void ToggleMenu (int type, int menuIndex)
Toggles a menu by the given ID which references to a type. See MenuManager.MenuTypesForEditor. A menu can only be activated if there is no current already active.
void ToggleMenuManager ()
Toogles the MenuManager. Useful if UI interaction should be locked.
void ToggleMenuManager (bool isEnabled)
Toogles the MenuManager. Useful if UI interaction should be locked.
void OnBeforeSerialize ()
void OnAfterDeserialize ()
Public Member Functions inherited from UnityToolbox.General.Management.Module
virtual void Awake ()
Static Public Member Functions
static List< string > GetAllMenusOfType (int type)
Public Attributes
int OverlayType
Static Public Attributes
static List< MenuType > MenuTypesForEditor = new List<MenuType>()
All menu types defined by the manager.
static List< string > MenuTypeNamesForEditor = new List<string>()
Properties
bool IsEnabled [get]
MenuType CurrentActiveMenuType [get]
Member Function Documentation
GetAllMenusOfType()
static List< string > UnityToolbox.UI.Menus.MenuManager.GetAllMenusOfType (int type) static
References UnityToolbox.UI.Menus.MenuType.Menus, UnityToolbox.UI.Menus.MenuType.MenuTypeID, and UnityToolbox.UI.Menus.MenuManager.MenuTypesForEditor.
OnAfterDeserialize()
void UnityToolbox.UI.Menus.MenuManager.OnAfterDeserialize ()
References UnityToolbox.UI.Menus.MenuManager.MenuTypeNamesForEditor, and UnityToolbox.UI.Menus.MenuManager.MenuTypesForEditor.
OnBeforeSerialize()
void UnityToolbox.UI.Menus.MenuManager.OnBeforeSerialize ()
References UnityToolbox.UI.Menus.MenuManager.MenuTypeNamesForEditor, and UnityToolbox.UI.Menus.MenuManager.MenuTypesForEditor.
SetActiveMenu()
void UnityToolbox.UI.Menus.MenuManager.SetActiveMenu (Menu menu)
Parameters
menu
References UnityToolbox.UI.Menus.MenuType.Menus.
Referenced by UnityToolbox.UI.Menus.MenuManager.ToggleMenu().
ToggleMenu()
void UnityToolbox.UI.Menus.MenuManager.ToggleMenu (int type, int menuIndex)
Parameters
type The ID which references to a type.
References UnityToolbox.UI.Menus.MenuType.Menus, UnityToolbox.UI.Menus.MenuType.MenuTypeID, and UnityToolbox.UI.Menus.MenuManager.SetActiveMenu().
ToggleMenuManager() [1/2]
void UnityToolbox.UI.Menus.MenuManager.ToggleMenuManager ()
ToggleMenuManager() [2/2]
void UnityToolbox.UI.Menus.MenuManager.ToggleMenuManager (bool isEnabled)
Parameters
isEnabled
Member Data Documentation
MenuTypeNamesForEditor
List<string> UnityToolbox.UI.Menus.MenuManager.MenuTypeNamesForEditor = new List<string>() static
Referenced by UnityToolbox.UI.Menus.MenuManager.OnAfterDeserialize(), and UnityToolbox.UI.Menus.MenuManager.OnBeforeSerialize().
MenuTypesForEditor
List<MenuType> UnityToolbox.UI.Menus.MenuManager.MenuTypesForEditor = new List<MenuType>() static
Referenced by UnityToolbox.UI.Menus.MenuManager.GetAllMenusOfType(), UnityToolbox.UI.Menus.MenuManager.OnAfterDeserialize(), and UnityToolbox.UI.Menus.MenuManager.OnBeforeSerialize().
OverlayType
int UnityToolbox.UI.Menus.MenuManager.OverlayType
Property Documentation
CurrentActiveMenuType
MenuType UnityToolbox.UI.Menus.MenuManager.CurrentActiveMenuType get
Referenced by UnityToolbox.UI.Dialog.UI.DisplayDialog.UpdateDialog().
IsEnabled
bool UnityToolbox.UI.Menus.MenuManager.IsEnabled get