UnityToolbox: UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorLayer Class Reference
UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorLayer Class Reference
Public Member Functions
TerrainGenerationHeightColorLayer (TerrainGenerationHeightColorsWindow parent, int currentPos)
TerrainGenerationHeightColorLayer (TerrainGenerationHeightColorsWindow parent, int currentPos, bool isBaseLayer, string baseLayerName)
SerializedDataErrorDetails Deserialize (TerrainGenerationHeightColorData obj)
TerrainGenerationHeightColorData Serialize ()
void DrawDetails ()
Public Member Functions inherited from UnityToolbox.GameplayFeatures.SerializationData.ISerializedDataContainer< TerrainGenerationHeightColorData >
abstract SerializedDataErrorDetails Deserialize (T obj)
abstract T Serialize ()
Properties
TerrainGenerationHeightColorData Data [get, set]
Constructor & Destructor Documentation
TerrainGenerationHeightColorLayer() [1/2]
UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorLayer.TerrainGenerationHeightColorLayer (TerrainGenerationHeightColorsWindow parent, int currentPos)
TerrainGenerationHeightColorLayer() [2/2]
UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorLayer.TerrainGenerationHeightColorLayer (TerrainGenerationHeightColorsWindow parent, int currentPos, bool isBaseLayer, string baseLayerName)
Member Function Documentation
Deserialize()
SerializedDataErrorDetails UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorLayer.Deserialize (TerrainGenerationHeightColorData obj)
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.EmissionTexture, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.EmissionTextureGUID, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.EmissionTexturePath, UnityToolbox.GameplayFeatures.SerializationData.ColorData.GetColor(), UnityToolbox.GameplayFeatures.SerializationData.SerializedDataErrorDetails.HasErrors, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.MetallicTexture, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.MetallicTextureGUID, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.MetallicTexturePath, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.NormalTexture, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.NormalTextureGUID, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.NormalTexturePath, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.OcclusionTexture, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.OcclusionTextureGUID, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.OcclusionTexturePath, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.RoughnessTexture, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.RoughnessTextureGUID, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.RoughnessTexturePath, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.TerrainColorData, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.TerrainTexture, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.TerrainTextureGUID, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.TerrainTexturePath, and UnityToolbox.GameplayFeatures.SerializationData.SerializedDataErrorDetails.Traced.
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.DummyDeserialize().
DrawDetails()
void UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorLayer.DrawDetails ()
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.OnGUI().
Serialize()
TerrainGenerationHeightColorData UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorLayer.Serialize () virtual
Implements UnityToolbox.GameplayFeatures.SerializationData.ISerializedDataContainer< TerrainGenerationHeightColorData >.
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.EmissionTexture, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.MetallicTexture, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.NormalTexture, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.OcclusionTexture, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.RoughnessTexture, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.TerrainColor, and UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.TerrainGenerationHeightColorData.TerrainTexture.
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.Serialize().
Property Documentation
Data
TerrainGenerationHeightColorData UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorLayer.Data get set
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.DefineSettings(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.DeleteLayer(), and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.OnGUI().