UnityToolbox: UnityToolbox.UI.Localization.Editor.LocalizationEditIDWindow Class Reference
UnityToolbox.UI.Localization.Editor.LocalizationEditIDWindow Class Reference
Public Member Functions
void OnGUI ()
new void Close ()
Static Public Member Functions
static void Open (LocalizationID LocalizationID)
Properties
LocalizationID LocalizationID [set]
Member Function Documentation
Close()
new void UnityToolbox.UI.Localization.Editor.LocalizationEditIDWindow.Close ()
Referenced by UnityToolbox.UI.Localization.Editor.LocalizationEditIDWindow.OnGUI().
OnGUI()
void UnityToolbox.UI.Localization.Editor.LocalizationEditIDWindow.OnGUI ()
References UnityToolbox.UI.Localization.Editor.LocalizationEditIDWindow.Close(), UnityToolbox.UI.Localization.LocalizationID.DEVIDER, UnityToolbox.UI.Localization.Localizer.EditLocalization(), UnityToolbox.UI.Localization.Localizer.EditLocalizationID(), UnityToolbox.UI.Localization.LocalizationID.Equals(), UnityToolbox.UI.Localization.Localizer.Instance, UnityToolbox.UI.Localization.Editor.LocalizationEditIDWindow.LocalizationID, UnityToolbox.UI.Localization.Localizer.LocalizationLanguages, UnityToolbox.UI.Localization.Localizer.LocalizationScopes, UnityToolbox.UI.Localization.LocalizationLanguage.Name, and UnityToolbox.UI.Localization.Localizer.WriteData().
Open()
static void UnityToolbox.UI.Localization.Editor.LocalizationEditIDWindow.Open (LocalizationID LocalizationID) static
References UnityToolbox.UI.Localization.Editor.LocalizationEditIDWindow.LocalizationID.
Property Documentation
LocalizationID
LocalizationID UnityToolbox.UI.Localization.Editor.LocalizationEditIDWindow.LocalizationID set
Referenced by UnityToolbox.UI.Localization.Editor.LocalizationEditIDWindow.OnGUI(), and UnityToolbox.UI.Localization.Editor.LocalizationEditIDWindow.Open().