UnityToolbox: UnityToolbox.Item.ItemInstance Class Reference
UnityToolbox.Item.ItemInstance Class Reference
An instanciated item, created from an ItemDefinition.
Public Member Functions
object GetValueForField (string fieldName)
override bool Equals (object other)
override int GetHashCode ()
void Click ()
Public Member Functions inherited from Saveable
void Save ()
Defines all data to be serialized by the SaveGameManager.
void Load ()
Loads all data, deserialized by the SaveGameManager.
void OnValidate ()
Public Attributes
string IconPath
int MaxStackCount
Public Attributes inherited from Saveable
ResourceData PrefabData
The date which is used to serialize a reference to the Prefab.
Protected Member Functions
override void LoadData (GameData data)
Is called after the base data is loaded in Load. Allows additional data to be deserialized.
override List< GameData > SaveData ()
Is called on Save. Allows the definition of all additional GameData to be serialized.
override void OnObjectDeleted ()
A method called on deletion, that is that the object is removed from the save game and destroyed. It is not called when destroyed but saved.
abstract void LoadData (GameData data)
Is called after the base data is loaded in Load. Allows additional data to be deserialized.
abstract List< GameData > SaveData ()
Is called on Save. Allows the definition of all additional GameData to be serialized.
abstract void OnObjectDeleted ()
A method called on deletion, that is that the object is removed from the save game and destroyed. It is not called when destroyed but saved.
Protected Attributes
string _itemName
Sprite _icon
Protected Attributes inherited from Saveable
bool _removeFromSaveOnDelete
Properties
InventoryBase Inventory [get, set]
string ItemName [get, set]
Sprite Icon [get, set]
string Indentifier [get, set]
Type ItemType [get, set]
HashSet< ItemField > ItemFields [get, set]
Properties inherited from Saveable
string ID [get, set]
A unique ID.
bool InEditor [get]
Whether the gameobject is found in the scene initally. Or created dynamically.
Member Function Documentation
Click()
void UnityToolbox.Item.ItemInstance.Click ()
References HeldInventoryManager.EnablePlacement, and HeldInventoryManager.ManageInventorys().
Equals()
override bool UnityToolbox.Item.ItemInstance.Equals (object other)
References UnityToolbox.Item.ItemInstance._itemName.
Referenced by HeldInventory.AddItem(), HeldInventoryManager.ManageInventorys(), HeldInventory.RemoveItem(), and HeldInventory.UpdateItem().
GetHashCode()
override int UnityToolbox.Item.ItemInstance.GetHashCode ()
GetValueForField()
object UnityToolbox.Item.ItemInstance.GetValueForField (string fieldName)
LoadData()
override void UnityToolbox.Item.ItemInstance.LoadData (GameData data) protected virtual
Parameters
data A GameData implementation, which holds data to load.
Implements Saveable.
References UnityToolbox.Item.ItemInstance._icon, UnityToolbox.Item.ItemInstance._itemName, ItemData.Fields, ItemData.IconPath, ItemData.InventoryID, ItemData.ItemName, and ItemData.ItemType.
OnObjectDeleted()
override void UnityToolbox.Item.ItemInstance.OnObjectDeleted () protected virtual
Implements Saveable.
References InventoryBase.RemoveItem().
SaveData()
override List< GameData > UnityToolbox.Item.ItemInstance.SaveData () protected virtual
Returns
Implements Saveable.
References UnityToolbox.Item.ItemInstance._itemName, HeldInventoryManager.BackUpInventory, HeldInventoryManager.HInventory, UnityToolbox.Item.ItemInstance.IconPath, and InventoryBase.ID.
Member Data Documentation
_icon
Sprite UnityToolbox.Item.ItemInstance._icon protected
Referenced by UnityToolbox.Item.ItemInstance.LoadData().
_itemName
string UnityToolbox.Item.ItemInstance._itemName protected
Referenced by UnityToolbox.Item.ItemInstance.Equals(), UnityToolbox.Item.ItemInstance.LoadData(), and UnityToolbox.Item.ItemInstance.SaveData().
IconPath
string UnityToolbox.Item.ItemInstance.IconPath
Referenced by UnityToolbox.Item.ItemInstance.SaveData().
MaxStackCount
int UnityToolbox.Item.ItemInstance.MaxStackCount
Referenced by BoundInventory.AddItem().
Property Documentation
Icon
Sprite UnityToolbox.Item.ItemInstance.Icon get set
Referenced by InventoryUISlot.UpdateItem().
Indentifier
string UnityToolbox.Item.ItemInstance.Indentifier get set
Inventory
InventoryBase UnityToolbox.Item.ItemInstance.Inventory get set
Referenced by BoundInventory.RemoveItem(), and HeldInventory.RemoveItem().
ItemFields
HashSet<ItemField> UnityToolbox.Item.ItemInstance.ItemFields get set
ItemName
string UnityToolbox.Item.ItemInstance.ItemName get set
Referenced by InventoryUISlot.UpdateItem().
ItemType
Type UnityToolbox.Item.ItemInstance.ItemType get set