UnityToolbox: UnityToolbox.UI.Localisation.Editor.LocalisationDrawer Class Reference
UnityToolbox.UI.Localisation.Editor.LocalisationDrawer Class Reference
Public Member Functions
override float GetPropertyHeight (SerializedProperty property, GUIContent label)
override void OnGUI (Rect position, SerializedProperty property, GUIContent label)
void IDSelected (LocalisationID ID)
Member Function Documentation
GetPropertyHeight()
override float UnityToolbox.UI.Localisation.Editor.LocalisationDrawer.GetPropertyHeight (SerializedProperty property, GUIContent label)
IDSelected()
void UnityToolbox.UI.Localisation.Editor.LocalisationDrawer.IDSelected (LocalisationID ID)
References UnityToolbox.UI.Localisation.Editor.LocalisationDrawer.IDSelected().
Referenced by UnityToolbox.UI.Localisation.Editor.LocalisationDrawer.IDSelected(), and UnityToolbox.UI.Localisation.Editor.LocalisationDrawer.OnGUI().
OnGUI()
override void UnityToolbox.UI.Localisation.Editor.LocalisationDrawer.OnGUI (Rect position, SerializedProperty property, GUIContent label)
References UnityToolbox.UI.Localisation.LocalisationID.DEVIDER, UnityToolbox.UI.Localisation.Editor.LocalisationDrawer.IDSelected(), UnityToolbox.UI.Localisation.LocalisationID.Name, UnityToolbox.UI.Localisation.LocalisationScope.Name, UnityToolbox.UI.Localisation.Editor.LocalisationSelectionWindow.Open(), and UnityToolbox.UI.Localisation.LocalisationID.Scope.