UnityToolbox: UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround Class Reference
UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround Class Reference
Public Member Functions
TerrainMeshTypeLayeredLayerGround (TerrainMeshTypeLayered parent, int currentPos)
TerrainMeshTypeLayeredLayerGround (TerrainMeshTypeLayered parent, int currentPos, bool isBaseLayer, string baseLayerName)
Public Member Functions inherited from UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer
void DrawDetails ()
void DeleteAssetPlacement (TerrainGenerationLayeredAssetLayer current)
SerializedDataErrorDetails Deserialize (TerrainMeshTypeLayeredLayerBaseData obj)
TerrainMeshTypeLayeredLayerBaseData Serialize ()
Public Member Functions inherited from UnityToolbox.GameplayFeatures.SerializationData.ISerializedDataContainer< TerrainMeshTypeLayeredLayerBaseData >
abstract SerializedDataErrorDetails Deserialize (T obj)
abstract T Serialize ()
Protected Member Functions
override void DrawDetailsRest ()
override SerializedDataErrorDetails DeserializeRest (TerrainMeshTypeLayeredLayerBaseData obj, SerializedDataErrorDetails err)
override TerrainMeshTypeLayeredLayerBaseData SerializeRest ()
Protected Member Functions inherited from UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer
TerrainMeshTypeLayeredLayer (TerrainMeshTypeLayered parent, int currentPos, TerrainMeshTypeLayeredLayerBaseData dataType)
TerrainMeshTypeLayeredLayer (TerrainMeshTypeLayered parent, int currentPos, bool isBaseLayer, string baseLayerName, TerrainMeshTypeLayeredLayerBaseData dataType)
abstract void DrawDetailsRest ()
void DrawLineHorizontal ()
void DrawAssetPlacement ()
abstract SerializedDataErrorDetails DeserializeRest (TerrainMeshTypeLayeredLayerBaseData obj, SerializedDataErrorDetails err)
abstract TerrainMeshTypeLayeredLayerBaseData SerializeRest ()
Properties
bool EnabledNormal [get, set]
bool EnabledEmission [get, set]
bool EnabledMetallic [get, set]
bool EnabledOcclusion [get, set]
bool EnabledRoughness [get, set]
Properties inherited from UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer
bool IsBaseLayer [get]
int CurrentPos [get, set]
Additional Inherited Members
Public Attributes inherited from UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer
string GeneratorName
Protected Attributes inherited from UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer
TerrainMeshTypeLayeredLayerBaseData _data
Constructor & Destructor Documentation
TerrainMeshTypeLayeredLayerGround() [1/2]
UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.TerrainMeshTypeLayeredLayerGround (TerrainMeshTypeLayered parent, int currentPos)
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer._data.
TerrainMeshTypeLayeredLayerGround() [2/2]
UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.TerrainMeshTypeLayeredLayerGround (TerrainMeshTypeLayered parent, int currentPos, bool isBaseLayer, string baseLayerName)
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer._data.
Member Function Documentation
DeserializeRest()
override SerializedDataErrorDetails UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.DeserializeRest (TerrainMeshTypeLayeredLayerBaseData obj, SerializedDataErrorDetails err) protected virtual
Implements UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer._data, UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.DummyDeserialize(), UnityToolbox.GameplayFeatures.SerializationData.SerializedDataErrorDetails.HasErrors, and UnityToolbox.GameplayFeatures.SerializationData.SerializedDataErrorDetails.Traced.
DrawDetailsRest()
override void UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.DrawDetailsRest () protected virtual
Implements UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer._data, UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.DefineSettings(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.Deserialize(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.DrawAssetPlacement(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.DrawLineHorizontal(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.EnabledEmission, UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.EnabledMetallic, UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.EnabledNormal, UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.EnabledOcclusion, UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.EnabledRoughness, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredLayerGroundData.Height, UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.HeightColorsOpen(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredLayerGroundData.HeightData, UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.Instance, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredLayerBaseData.IsBaseLayer, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredLayerGroundData.NoiseGround, and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.Open().
SerializeRest()
override TerrainMeshTypeLayeredLayerBaseData UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.SerializeRest () protected virtual
Implements UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer._data.
Property Documentation
EnabledEmission
bool UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.EnabledEmission get set
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.DrawDetailsRest().
EnabledMetallic
bool UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.EnabledMetallic get set
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.DrawDetailsRest().
EnabledNormal
bool UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.EnabledNormal get set
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.DrawDetailsRest().
EnabledOcclusion
bool UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.EnabledOcclusion get set
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.DrawDetailsRest().
EnabledRoughness
bool UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.EnabledRoughness get set
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.DrawDetailsRest().