UnityToolbox: UnityToolbox.UI.Settings.Sliders.ImageSliderSetting Class Reference
UnityToolbox.UI.Settings.Sliders.ImageSliderSetting Class Reference
An alternative to the Unity Slider. The fill area of this is a cropped instead of scaled image.
Public Types
enum SliderOption { Effects , Music , Ambience , Mouse_Sensitivity }
Public Member Functions
void Awake ()
void UpdateValues (float value)
Updates the values set with the slider to the preferences and manager. To set up the slider, set a EventTrigger to execute this on end drag.
Member Enumeration Documentation
SliderOption
enum UnityToolbox.UI.Settings.Sliders.ImageSliderSetting.SliderOption
Enumerator
Effects
Music
Ambience
Mouse_Sensitivity
Member Function Documentation
Awake()
void UnityToolbox.UI.Settings.Sliders.ImageSliderSetting.Awake ()
References UnityToolbox.UI.Settings.Sliders.ImageSliderSetting.UpdateValues().
UpdateValues()
void UnityToolbox.UI.Settings.Sliders.ImageSliderSetting.UpdateValues (float value)
References UnityToolbox.Audio.AudioMixer.PlayRandomSource().
Referenced by UnityToolbox.UI.Settings.Sliders.ImageSliderSetting.Awake().