UnityToolbox: UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory Class Reference
UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory Class Reference
Public Member Functions
override bool AddItem (ItemInstance item, int count)
override void RemoveItem (ItemInstance item, int count)
override void UpdateItem (ItemInstance old, ItemInstance updated)
override void RemoveItem (ItemInstance item)
abstract bool AddItem (ItemInstance item, int count)
abstract void RemoveItem (ItemInstance item, int count)
abstract void RemoveItem (ItemInstance item)
abstract void UpdateItem (ItemInstance old, ItemInstance updated)
Public Attributes
Action OnInventoryChanged
int MaxSlotCount
Properties
Dictionary< ItemInstance, int > Items [get, set]
Properties inherited from UnityToolbox.GameplayFeatures.Items.Inventory.Types.InventoryBase
string ID [get]
Member Function Documentation
AddItem()
override bool UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.AddItem (ItemInstance item, int count) virtual
Implements UnityToolbox.GameplayFeatures.Items.Inventory.Types.InventoryBase.
References UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.MaxSlotCount, UnityToolbox.GameplayFeatures.Items.ItemInstance.MaxStackCount, and UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.OnInventoryChanged.
Referenced by UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager.ManageInventorys(), and UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.UpdateItem().
RemoveItem() [1/2]
override void UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.RemoveItem (ItemInstance item) virtual
Implements UnityToolbox.GameplayFeatures.Items.Inventory.Types.InventoryBase.
References UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.OnInventoryChanged.
RemoveItem() [2/2]
override void UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.RemoveItem (ItemInstance item, int count) virtual
Implements UnityToolbox.GameplayFeatures.Items.Inventory.Types.InventoryBase.
References UnityToolbox.GameplayFeatures.Items.ItemInstance.Inventory, and UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.OnInventoryChanged.
Referenced by UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager.ManageInventorys(), and UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.UpdateItem().
UpdateItem()
override void UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.UpdateItem (ItemInstance old, ItemInstance updated) virtual
Implements UnityToolbox.GameplayFeatures.Items.Inventory.Types.InventoryBase.
References UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.AddItem(), UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.OnInventoryChanged, and UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.RemoveItem().
Member Data Documentation
MaxSlotCount
int UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.MaxSlotCount
Referenced by UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.AddItem().
OnInventoryChanged
Action UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.OnInventoryChanged
Referenced by UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.AddItem(), UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.RemoveItem(), UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.RemoveItem(), and UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.UpdateItem().
Property Documentation
Items
Dictionary<ItemInstance, int> UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.Items get set
Referenced by UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager.ManageInventorys().