UnityToolbox: UnityToolbox.UI.Localization.Editor.LocalizationDrawer Class Reference
UnityToolbox.UI.Localization.Editor.LocalizationDrawer Class Reference
Public Member Functions
override float GetPropertyHeight (SerializedProperty property, GUIContent label)
override void OnGUI (Rect position, SerializedProperty property, GUIContent label)
void IDSelectedInspector (LocalizationID ID)
void IDSelectedUIElement (LocalizationID ID)
VisualElement CreateVisualElement (LocalizationID id)
Properties
LocalizationID DrawerId [get]
Member Function Documentation
CreateVisualElement()
VisualElement UnityToolbox.UI.Localization.Editor.LocalizationDrawer.CreateVisualElement (LocalizationID id)
References UnityToolbox.UI.Localization.Editor.LocalizationDrawer.IDSelectedUIElement(), UnityToolbox.UI.Localization.LocalizationID.Name, UnityToolbox.UI.Localization.Editor.LocalizationSelectionWindow.Open(), and UnityToolbox.UI.Localization.LocalizationID.Scope.
Referenced by UnityToolbox.UI.Dialog.Editor.DialogNodeLocalizzed.Draw().
GetPropertyHeight()
override float UnityToolbox.UI.Localization.Editor.LocalizationDrawer.GetPropertyHeight (SerializedProperty property, GUIContent label)
IDSelectedInspector()
void UnityToolbox.UI.Localization.Editor.LocalizationDrawer.IDSelectedInspector (LocalizationID ID)
References UnityToolbox.UI.Localization.Editor.LocalizationDrawer.IDSelectedInspector().
Referenced by UnityToolbox.UI.Localization.Editor.LocalizationDrawer.IDSelectedInspector(), and UnityToolbox.UI.Localization.Editor.LocalizationDrawer.OnGUI().
IDSelectedUIElement()
void UnityToolbox.UI.Localization.Editor.LocalizationDrawer.IDSelectedUIElement (LocalizationID ID)
References UnityToolbox.UI.Localization.LocalizationID.GetQualifiedName(), and UnityToolbox.UI.Localization.Editor.LocalizationDrawer.IDSelectedUIElement().
Referenced by UnityToolbox.UI.Localization.Editor.LocalizationDrawer.CreateVisualElement(), and UnityToolbox.UI.Localization.Editor.LocalizationDrawer.IDSelectedUIElement().
OnGUI()
override void UnityToolbox.UI.Localization.Editor.LocalizationDrawer.OnGUI (Rect position, SerializedProperty property, GUIContent label)
References UnityToolbox.UI.Localization.LocalizationID.DEVIDER, UnityToolbox.UI.Localization.Editor.LocalizationDrawer.IDSelectedInspector(), UnityToolbox.UI.Localization.LocalizationID.Name, UnityToolbox.UI.Localization.LocalizationScope.Name, UnityToolbox.UI.Localization.Editor.LocalizationSelectionWindow.Open(), and UnityToolbox.UI.Localization.LocalizationID.Scope.
Property Documentation
DrawerId
LocalizationID UnityToolbox.UI.Localization.Editor.LocalizationDrawer.DrawerId get
Referenced by UnityToolbox.UI.Dialog.Editor.DialogNodeLocalizzed.UpdateValues().