UnityToolbox: UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainGenerationLayeredAssetClusterData Class Reference
UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainGenerationLayeredAssetClusterData Class Reference
The data for clustered asset placement.
Public Member Functions
override object Clone ()
virtual object Clone ()
Public Attributes
int MinVerticesBetweenPrefabs
float SpawnDecay
List< TerrainGenerationLayeredAssetData > Assets
Public Attributes inherited from UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainGenerationLayeredAssetBaseData
float HeightOffset
bool PreIterate
float OddsForSpawn
TerrainGenerationAssetPosition Position
Member Function Documentation
Clone()
override object UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainGenerationLayeredAssetClusterData.Clone () virtual
Reimplemented from UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainGenerationLayeredAssetBaseData.
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainGenerationLayeredAssetClusterData.Assets, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainGenerationLayeredAssetBaseData.Clone(), and UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainGenerationLayeredAssetClusterData.Clone().
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainGenerationLayeredAssetClusterData.Clone().
Member Data Documentation
Assets
List<TerrainGenerationLayeredAssetData> UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainGenerationLayeredAssetClusterData.Assets
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainGenerationLayeredAssetClusterData.Clone(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainGenerationLayeredAssetLayerClustered.Deserialize(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainGenerationLayeredAssetLayerClustered.DrawAssets(), and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainGenerationLayeredAssetLayerClustered.Serialize().
MinVerticesBetweenPrefabs
int UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainGenerationLayeredAssetClusterData.MinVerticesBetweenPrefabs
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainGenerationLayeredAssetLayerClustered.DrawAssets().
SpawnDecay
float UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainGenerationLayeredAssetClusterData.SpawnDecay
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainGenerationLayeredAssetLayerClustered.DrawAssets().