UnityToolbox: ResourcesUtil Class Reference
ResourcesUtil Class Reference
A utility which writes and reads data with correctly formatted paths.
Static Public Member Functions
static bool IsFullPathValid (string path)
Checks whether the path is valid and defined with a "Resources" folder.
static bool TrySetValidPath (string fullPath, string key)
Tries to define a path within the ProjectPrefs. The Application.dataPath will be removed from it.
static string GetLocalPath (string key)
Builds the local path from the stored path within the ProjectPrefs.
static string GetResourcesPath (string key)
Builds the "Resources" path from the stored path within the ProjectPrefs.
static string GetProjectPath (string key)
Builds the project path from the stored path within the ProjectPrefs.
static T GetFileData< T > (string key, string filename)
Reads a TextAsset with a key for the ProjectPrefs and the filename.
static void WriteFile (string key, string filename, object fileData)
Writes an object to a file and refreshes the AssetDatabase.
Member Function Documentation
GetFileData< T >()
static T ResourcesUtil.GetFileData< T > (string key, string filename) static
Parameters
key The key for the ProjectPrefs.
filename The filename.
Returns
The cast values of the file.
References GetLocalPath(), and GetResourcesPath().
GetLocalPath()
static string ResourcesUtil.GetLocalPath (string key) static
Parameters
key The key for the ProjectPrefs.
Returns
The local path.
References ProjectPrefs.GetString().
Referenced by GetFileData< T >(), and WriteFile().
GetProjectPath()
static string ResourcesUtil.GetProjectPath (string key) static
Parameters
key The key for the ProjectPrefs.
Returns
A project directory.
References ProjectPrefs.GetString().
GetResourcesPath()
static string ResourcesUtil.GetResourcesPath (string key) static
Parameters
key The key for the ProjectPrefs.
Returns
The resources path.
References ProjectPrefs.GetString().
Referenced by GetFileData< T >().
IsFullPathValid()
static bool ResourcesUtil.IsFullPathValid (string path) static
Parameters
path The local path.
Returns
Whether a path is a valid resources path.
Referenced by UnityToolbox.Item.Management.Itemizer.Initialize(), UnityToolbox.UI.Localisation.Localizer.Initialize(), and TrySetValidPath().
TrySetValidPath()
static bool ResourcesUtil.TrySetValidPath (string fullPath, string key) static
Parameters
path The local path.
key The key for the ProjectPrefs.
Returns
Whether the path could be set.
References IsFullPathValid(), and ProjectPrefs.SetString().
WriteFile()
static void ResourcesUtil.WriteFile (string key, string filename, object fileData) static
Parameters
key The key for the ProjectPrefs.
filename The filename with extension.
fileData The object to write.
References GetLocalPath(), and ProjectPrefs.GetString().
Referenced by UnityToolbox.Item.Management.Itemizer.WriteData(), and UnityToolbox.UI.Localisation.Localizer.WriteData().