UnityToolbox: UnityToolbox.GameplayFeatures.SaveGame.IDManager Class Reference
UnityToolbox.GameplayFeatures.SaveGame.IDManager Class Reference
A manager which can generate unique IDs. Works in editor and runtime.
Public Member Functions
override void Awake ()
virtual void Awake ()
Static Public Member Functions
static void SceneChanged (Scene newScene)
Is called when the scene changes. See IDInitializer.
static string GetUniqueID ()
Generates a new unique ID.
static void RemoveID (string ID)
Removes an ID from the existing.
static void RegisterID (string ID)
Registeres a given ID. Throws an error if the ID is already known.
static string GetSceneNameOfID (string ID)
Extracts the scene name of the ID.
Member Function Documentation
Awake()
override void UnityToolbox.GameplayFeatures.SaveGame.IDManager.Awake () virtual
Reimplemented from UnityToolbox.General.Management.Module.
References UnityToolbox.GameplayFeatures.SaveGame.IDManager.SceneChanged().
GetSceneNameOfID()
static string UnityToolbox.GameplayFeatures.SaveGame.IDManager.GetSceneNameOfID (string ID) static
Parameters
ID The ID to read its scene from.
Returns
A scene name.
GetUniqueID()
static string UnityToolbox.GameplayFeatures.SaveGame.IDManager.GetUniqueID () static
Returns
A unique ID.
Referenced by UnityToolbox.GameplayFeatures.SaveGame.Saveable.OnValidate().
RegisterID()
static void UnityToolbox.GameplayFeatures.SaveGame.IDManager.RegisterID (string ID) static
Parameters
ID The ID to register.
Exceptions
Exception
RemoveID()
static void UnityToolbox.GameplayFeatures.SaveGame.IDManager.RemoveID (string ID) static
Parameters
ID An existing ID.
SceneChanged()
static void UnityToolbox.GameplayFeatures.SaveGame.IDManager.SceneChanged (Scene newScene) static
Parameters
newScene The new scene.
References UnityToolbox.GameplayFeatures.SaveGame.Saveable.ID.
Referenced by UnityToolbox.GameplayFeatures.SaveGame.IDManager.Awake().