UnityToolbox: UnityToolbox.UI.Settings.SettingsManager Class Reference
UnityToolbox.UI.Settings.SettingsManager Class Reference
This manager controls all relevant information about settings, that is key, volume and sensitivity controls. Requires the UIEventManager and PlayerPrefKeys.
Public Member Functions
bool SetKey (string control, string path, string actionName)
Sets the setting for a key control.
void ResetKey (string control, string actionName)
Resets the setting for a key control to the last known setting.
void ResetAllKeys ()
Resets the settings of all controls to its last known setting.
string CurrentValueOfControl (string control, string actionName)
Reads the current value of a given key control.
void SoundValueChanged (Audio.AudioType type, float newValue)
Executes the SettingsManager.OnSoundValueChanged event.
void SenseValueChanged (float newValue)
Executes the SettingsManager.OnSenseValueChanged event.
Public Member Functions inherited from UnityToolbox.General.Management.Module
virtual void Awake ()
Public Attributes
Action< Audio.AudioType, float > OnSoundValueChanged
The event which is executed as soon as volumes are changed.
Action< float > OnSenseValueChanged
The event which is executed as soon as the mouse sensitivity is changed.
Member Function Documentation
CurrentValueOfControl()
string UnityToolbox.UI.Settings.SettingsManager.CurrentValueOfControl (string control, string actionName)
Parameters
control The control name, which specifies more information about the action. (e.g "left" or "up")
actionName The action name (e.g. "Character Jump")
Returns
Returns the string path of the current setting.
Referenced by UnityToolbox.UI.Settings.Controls.RebindButton.OnGUI(), UnityToolbox.PlayerControls.RaycastDetection.Update(), and UnityToolbox.PlayerControls.TriggerDetection.Update().
ResetAllKeys()
void UnityToolbox.UI.Settings.SettingsManager.ResetAllKeys ()
Referenced by UnityToolbox.UI.Settings.Controls.ResetButton.OnPointerClick().
ResetKey()
void UnityToolbox.UI.Settings.SettingsManager.ResetKey (string control, string actionName)
Parameters
control The control name, which specifies more information about the action. (e.g "left" or "up")
actionName The action name (e.g. "Character Jump")
Referenced by UnityToolbox.UI.Settings.Controls.ResetButton.OnPointerClick().
SenseValueChanged()
void UnityToolbox.UI.Settings.SettingsManager.SenseValueChanged (float newValue)
Parameters
newValue The new value for the mouse sensitivity, must be between 0-1.
References UnityToolbox.UI.Settings.SettingsManager.OnSenseValueChanged.
SetKey()
bool UnityToolbox.UI.Settings.SettingsManager.SetKey (string control, string path, string actionName)
Parameters
control The control name, which specifies more information about the action. (e.g "left" or "up")
path The path to the new key (e.g."<Keyboard>/W" or "<Mouse>/LeftClick)"
actionName The action name (e.g. "Character Jump")
Returns
Returns false if the given key path is already taken.
SoundValueChanged()
void UnityToolbox.UI.Settings.SettingsManager.SoundValueChanged (Audio::AudioType type, float newValue)
Parameters
type The sound type. (e.g. Audio.AudioType.Music or Audio.AudioType.Effects)
newValue The new value for the volume, must be between 0-1.
References UnityToolbox.UI.Settings.SettingsManager.OnSoundValueChanged.
Member Data Documentation
OnSenseValueChanged
Action<float> UnityToolbox.UI.Settings.SettingsManager.OnSenseValueChanged
Referenced by UnityToolbox.UI.Settings.SettingsManager.SenseValueChanged().
OnSoundValueChanged
Action<Audio.AudioType, float> UnityToolbox.UI.Settings.SettingsManager.OnSoundValueChanged
Referenced by UnityToolbox.UI.Settings.SettingsManager.SoundValueChanged().