UnityToolbox: UnityToolbox.GameplayFeatures.SaveGame.Saveable Class Reference
UnityToolbox.GameplayFeatures.SaveGame.Saveable Class Reference abstract
The base implementation for all gameobjects that should be saved. It is able to serialize the transform and parent data with the SaveGameManager. Requires a PrefabManager and aIDManager, if the objects are not initially found in the scene.
Public Member Functions
void Save ()
Defines all data to be serialized by the SaveGameManager.
void Load ()
Loads all data, deserialized by the SaveGameManager.
void OnValidate ()
Public Attributes
ResourceData PrefabData
The date which is used to serialize a reference to the Prefab.
Protected Member Functions
abstract void LoadData (GameData data)
Is called after the base data is loaded in Load. Allows additional data to be deserialized.
abstract List< GameData > SaveData ()
Is called on Save. Allows the definition of all additional GameData to be serialized.
abstract void OnObjectDeleted ()
A method called on deletion, that is that the object is removed from the save game and destroyed. It is not called when destroyed but saved.
Protected Attributes
bool _removeFromSaveOnDelete
Properties
string ID [get, set]
A unique ID.
bool InEditor [get]
Whether the gameobject is found in the scene initally. Or created dynamically.
Member Function Documentation
Load()
void UnityToolbox.GameplayFeatures.SaveGame.Saveable.Load ()
References UnityToolbox.GameplayFeatures.SaveGame.Saveable.ID, UnityToolbox.GameplayFeatures.SaveGame.Saveable.LoadData(), UnityToolbox.GameplayFeatures.SerializationData.ParentData.ParentID, UnityToolbox.GameplayFeatures.SerializationData.TransformData.Position, UnityToolbox.GameplayFeatures.SerializationData.TransformData.Rotation, UnityToolbox.GameplayFeatures.SerializationData.TransformData.Scale, UnityToolbox.GameplayFeatures.SerializationData.VectorData.x, UnityToolbox.GameplayFeatures.SerializationData.VectorData.y, and UnityToolbox.GameplayFeatures.SerializationData.VectorData.z.
LoadData()
abstract void UnityToolbox.GameplayFeatures.SaveGame.Saveable.LoadData (GameData data) protected pure virtual
Parameters
data A GameData implementation, which holds data to load.
Implemented in UnityToolbox.GameplayFeatures.Items.ItemInstance.
Referenced by UnityToolbox.GameplayFeatures.SaveGame.Saveable.Load().
OnObjectDeleted()
abstract void UnityToolbox.GameplayFeatures.SaveGame.Saveable.OnObjectDeleted () protected pure virtual
Implemented in UnityToolbox.GameplayFeatures.Items.ItemInstance.
OnValidate()
void UnityToolbox.GameplayFeatures.SaveGame.Saveable.OnValidate ()
References UnityToolbox.GameplayFeatures.SaveGame.IDManager.GetUniqueID().
Save()
void UnityToolbox.GameplayFeatures.SaveGame.Saveable.Save ()
References UnityToolbox.GameplayFeatures.SaveGame.Saveable.ID, UnityToolbox.GameplayFeatures.SaveGame.Saveable.InEditor, UnityToolbox.GameplayFeatures.SaveGame.Saveable.PrefabData, and UnityToolbox.GameplayFeatures.SaveGame.Saveable.SaveData().
SaveData()
abstract List< GameData > UnityToolbox.GameplayFeatures.SaveGame.Saveable.SaveData () protected pure virtual
Returns
Implemented in UnityToolbox.GameplayFeatures.Items.ItemInstance.
Referenced by UnityToolbox.GameplayFeatures.SaveGame.Saveable.Save().
Member Data Documentation
_removeFromSaveOnDelete
bool UnityToolbox.GameplayFeatures.SaveGame.Saveable._removeFromSaveOnDelete protected
PrefabData
ResourceData UnityToolbox.GameplayFeatures.SaveGame.Saveable.PrefabData
Referenced by UnityToolbox.GameplayFeatures.SaveGame.Saveable.Save().
Property Documentation
ID
string UnityToolbox.GameplayFeatures.SaveGame.Saveable.ID get set
Referenced by UnityToolbox.GameplayFeatures.SaveGame.Saveable.Load(), UnityToolbox.GameplayFeatures.SaveGame.Saveable.Save(), and UnityToolbox.GameplayFeatures.SaveGame.IDManager.SceneChanged().
InEditor
bool UnityToolbox.GameplayFeatures.SaveGame.Saveable.InEditor get
Referenced by UnityToolbox.GameplayFeatures.SaveGame.Saveable.Save().