UnityToolbox: UnityToolbox.GameplayFeatures.Items.Management.Itemizer Class Reference
UnityToolbox.GameplayFeatures.Items.Management.Itemizer Class Reference
The core of the item managment system. It takes care of the (de)serialization and changes to all data.
Public Member Functions
bool Initialize ()
Tries to initialize the Itemizer.
ItemDefinition AddItemDefinition (ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, string iconGUID, string prefabGUID)
Creates a new item definition and adds it to the mangement.
T AddInheritedItemDefinition< T > (ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, string iconGUID, string prefabGUID, HashSet< ItemField > itemFields)
Creates a new item inheriting ItemDefinition and adds it to the mangement.
void RemoveItemDefinition (ItemDefinition itemDefinition)
Removes an ItemDefinition from the mangement.
void EditInheritedItemDefinition< T > (ItemDefinition itemDefinition, ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, string iconGUID, string prefabGUID, HashSet< ItemField > itemFields)
Edits a given item inheriting ItemDefinition and replaces the old within the mangement.
void EditItemDefinition (ItemDefinition itemDefinition, ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, string iconGUID, string prefabGUID)
Edits a given ItemDefinition and replaces the old within the mangement.
ItemScope AddItemScope (string name)
Adds a new ItemScope by a given unique name.
void RemoveItemScope (ItemScope scope)
Removes a given ItemScope. Replaces the given scope used for the ItemDefinition with the DefaultScope.
void EditItemScope (ItemScope scope, string name)
Edits a given ItemScope and replaces the old.
List< Type > GetAllInheritedItemDefinitionTypes ()
Checks the assembly for all classes inheriting ItemDefinition.
void WriteData ()
Writes all data to the set resources folder.
void ItemScopeEdited (ItemScope oldScope, ItemScope newScope)
Invokes the OnItemScopeEdited action.
void ItemDefinitionEdited (ItemDefinition oldItemDefinition, ItemDefinition newItemDefinition)
Invokes the OnItemDefinitionEdited action.
Properties
static Itemizer Instance [get]
The singleton instance of the Itemizer.
bool Initialized [get]
Is the itemizer initialized? If not, it cannot be used.
HashSet< ItemDefinition > ItemDefinitions [get]
All defined items.
HashSet< ItemDefinition > FaultyItemDefinitions [get]
All defined items which are faulty.
HashSet< ItemScope > ItemScopes [get]
All defined item scopes.
ItemScope DefaultScope [get]
The defaulte scope, set by default and is the replacement for deleted scopes.
Events
Action< ItemScope, ItemScope > OnItemScopeEdited
Action< ItemDefinition, ItemDefinition > OnItemDefinitionEdited
Member Function Documentation
AddInheritedItemDefinition< T >()
T UnityToolbox.GameplayFeatures.Items.Management.Itemizer.AddInheritedItemDefinition< T > (ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, string iconGUID, string prefabGUID, HashSet< ItemField > itemFields)
Template Parameters
T A type which inherits ItemDefinition.
Parameters
scope The scope of the definition."/></param> <param name="name">The name of the definition. Has to be unique in combination with the scope.</param> <param name="maxStackCount">How high this item can be stacked.</param> <param name="resourceIconPath">The path to where the icon can be found. Has to be a resources path.</param> <param name="resourcePrefabPath">The path to where the prefab can be found. Has to be a resources path.</param> <param name="itemFields">All additional field values defined for type <typeparamref name="T"/>.</param> <returns>The created <see cref="ItemDefinition"/>.</returns> <exception cref="ItemDefinitionException">
Type Constraints
T : ItemDefinition
References UnityToolbox.GameplayFeatures.Items.Management.ItemField.FieldName, UnityToolbox.GameplayFeatures.Items.Management.ItemField.FieldType, and UnityToolbox.GameplayFeatures.Items.Management.ItemField.GetValue().
Referenced by UnityToolbox.GameplayFeatures.Items.Management.Itemizer.EditInheritedItemDefinition< T >().
AddItemDefinition()
ItemDefinition UnityToolbox.GameplayFeatures.Items.Management.Itemizer.AddItemDefinition (ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, string iconGUID, string prefabGUID)
Parameters
scope The scope of the definition."/></param> <param name="name">The name of the definition. Has to be unique in combination with the scope.</param> <param name="maxStackCount">How high this item can be stacked.</param> <param name="resourceIconPath">The path to where the icon can be found. Has to be a resources path.</param> <param name="resourcePrefabPath">The path to where the prefab can be found. Has to be a resources path.</param> <returns>The created <see cref="ItemDefinition"/>.</returns> <exception cref="ItemDefinitionException">
References UnityToolbox.GameplayFeatures.Items.ItemDefinition.GetQualifiedName().
Referenced by UnityToolbox.GameplayFeatures.Items.Management.Itemizer.EditItemDefinition(), UnityToolbox.GameplayFeatures.Items.Management.Itemizer.EditItemScope(), and UnityToolbox.GameplayFeatures.Items.Management.Itemizer.RemoveItemScope().
AddItemScope()
ItemScope UnityToolbox.GameplayFeatures.Items.Management.Itemizer.AddItemScope (string name)
Parameters
name The unique name of the scope to create.
Returns
The created ItemScope.
Exceptions
ItemDefinitionException
Referenced by UnityToolbox.GameplayFeatures.Items.Management.Itemizer.EditItemScope().
EditInheritedItemDefinition< T >()
void UnityToolbox.GameplayFeatures.Items.Management.Itemizer.EditInheritedItemDefinition< T > (ItemDefinition itemDefinition, ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, string iconGUID, string prefabGUID, HashSet< ItemField > itemFields)
Template Parameters
T A type which inherits ItemDefinition.
Parameters
itemDefinition The ItemDefinition to be edited.
scope The new scope of the definition."/></param> <param name="name">The new name of the definition. Has to be unique in combination with the scope.</param> <param name="maxStackCount">How high this item can be stacked.</param> <param name="resourceIconPath">The new path to where the icon can be found. Has to be a resources path.</param> <param name="resourcePrefabPath">The new path to where the prefab can be found. Has to be a resources path.</param> <param name="itemFields">All additional new field values defined for type <typeparamref name="T"/>.</param> <returns>The created <see cref="ItemDefinition"/>.</returns> <exception cref="ItemDefinitionException">
Type Constraints
T : ItemDefinition
References UnityToolbox.GameplayFeatures.Items.Management.Itemizer.AddInheritedItemDefinition< T >(), and UnityToolbox.GameplayFeatures.Items.Management.Itemizer.ItemDefinitionEdited().
EditItemDefinition()
void UnityToolbox.GameplayFeatures.Items.Management.Itemizer.EditItemDefinition (ItemDefinition itemDefinition, ItemScope scope, string name, int maxStackCount, string resourceIconPath, string resourcePrefabPath, string iconGUID, string prefabGUID)
Parameters
itemDefinition The ItemDefinition to be edited.
scope The new scope of the definition."/></param> <param name="name">The new name of the definition. Has to be unique in combination with the scope.</param> <param name="maxStackCount">How high this item can be stacked.</param> <param name="resourceIconPath">The new path to where the icon can be found. Has to be a resources path.</param> <param name="resourcePrefabPath">The new path to where the prefab can be found. Has to be a resources path.</param> <returns>The created <see cref="ItemDefinition"/>.</returns> <exception cref="ItemDefinitionException">
References UnityToolbox.GameplayFeatures.Items.Management.Itemizer.AddItemDefinition(), and UnityToolbox.GameplayFeatures.Items.Management.Itemizer.ItemDefinitionEdited().
EditItemScope()
void UnityToolbox.GameplayFeatures.Items.Management.Itemizer.EditItemScope (ItemScope scope, string name)
Parameters
scope The ItemScope to edit.
name The new unique name of the scope.
Exceptions
ItemDefinitionException
References UnityToolbox.GameplayFeatures.Items.Management.Itemizer.AddItemDefinition(), UnityToolbox.GameplayFeatures.Items.Management.Itemizer.AddItemScope(), UnityToolbox.GameplayFeatures.Items.Management.ItemScope.Equals(), UnityToolbox.GameplayFeatures.Items.ItemDefinition.IconGUID, UnityToolbox.GameplayFeatures.Items.ItemDefinition.IconPath, UnityToolbox.GameplayFeatures.Items.Management.Itemizer.ItemScopeEdited(), UnityToolbox.GameplayFeatures.Items.ItemDefinition.MaxStackCount, UnityToolbox.GameplayFeatures.Items.ItemDefinition.Name, UnityToolbox.GameplayFeatures.Items.Management.ItemScope.Name, UnityToolbox.GameplayFeatures.Items.ItemDefinition.PrefabGUID, and UnityToolbox.GameplayFeatures.Items.ItemDefinition.PrefabPath.
Referenced by UnityToolbox.GameplayFeatures.Items.Management.Editor.ItemScopeEditWindow.OnGUI().
GetAllInheritedItemDefinitionTypes()
List< Type > UnityToolbox.GameplayFeatures.Items.Management.Itemizer.GetAllInheritedItemDefinitionTypes ()
Returns
Initialize()
bool UnityToolbox.GameplayFeatures.Items.Management.Itemizer.Initialize ()
Returns
Whether initializing was successful.
References UnityToolbox.General.Preferences.ProjectPrefs.GetString(), and UnityToolbox.General.Management.ResourcesUtil.IsFullPathValid().
Referenced by UnityToolbox.GameplayFeatures.Items.ItemManager.Awake().
ItemDefinitionEdited()
void UnityToolbox.GameplayFeatures.Items.Management.Itemizer.ItemDefinitionEdited (ItemDefinition oldItemDefinition, ItemDefinition newItemDefinition)
Parameters
oldItemDefinition
newItemDefinition
References UnityToolbox.GameplayFeatures.Items.Management.Itemizer.OnItemDefinitionEdited.
Referenced by UnityToolbox.GameplayFeatures.Items.Management.Itemizer.EditInheritedItemDefinition< T >(), UnityToolbox.GameplayFeatures.Items.Management.Itemizer.EditItemDefinition(), and UnityToolbox.GameplayFeatures.Items.Management.Itemizer.RemoveItemDefinition().
ItemScopeEdited()
void UnityToolbox.GameplayFeatures.Items.Management.Itemizer.ItemScopeEdited (ItemScope oldScope, ItemScope newScope)
Parameters
oldScope
newScope
References UnityToolbox.GameplayFeatures.Items.Management.Itemizer.OnItemScopeEdited.
Referenced by UnityToolbox.GameplayFeatures.Items.Management.Itemizer.EditItemScope(), and UnityToolbox.GameplayFeatures.Items.Management.Itemizer.RemoveItemScope().
RemoveItemDefinition()
void UnityToolbox.GameplayFeatures.Items.Management.Itemizer.RemoveItemDefinition (ItemDefinition itemDefinition)
Parameters
itemDefinition The ItemDefinition to be removed.
Exceptions
ItemDefinitionException
References UnityToolbox.GameplayFeatures.Items.ItemDefinition.GetQualifiedName(), and UnityToolbox.GameplayFeatures.Items.Management.Itemizer.ItemDefinitionEdited().
RemoveItemScope()
void UnityToolbox.GameplayFeatures.Items.Management.Itemizer.RemoveItemScope (ItemScope scope)
Parameters
scope The ItemScope to remove.
Exceptions
ItemDefinitionException
References UnityToolbox.GameplayFeatures.Items.Management.Itemizer.AddItemDefinition(), UnityToolbox.GameplayFeatures.Items.Management.ItemScope.Equals(), UnityToolbox.GameplayFeatures.Items.ItemDefinition.IconGUID, UnityToolbox.GameplayFeatures.Items.ItemDefinition.IconPath, UnityToolbox.GameplayFeatures.Items.Management.Itemizer.ItemScopeEdited(), UnityToolbox.GameplayFeatures.Items.ItemDefinition.MaxStackCount, UnityToolbox.GameplayFeatures.Items.ItemDefinition.Name, UnityToolbox.GameplayFeatures.Items.Management.ItemScope.Name, UnityToolbox.GameplayFeatures.Items.ItemDefinition.PrefabGUID, and UnityToolbox.GameplayFeatures.Items.ItemDefinition.PrefabPath.
WriteData()
void UnityToolbox.GameplayFeatures.Items.Management.Itemizer.WriteData ()
References UnityToolbox.General.Management.ResourcesUtil.WriteFile().
Referenced by UnityToolbox.GameplayFeatures.Items.Management.Editor.ItemScopeEditWindow.OnGUI().
Property Documentation
DefaultScope
ItemScope UnityToolbox.GameplayFeatures.Items.Management.Itemizer.DefaultScope get
FaultyItemDefinitions
HashSet<ItemDefinition> UnityToolbox.GameplayFeatures.Items.Management.Itemizer.FaultyItemDefinitions get
Initialized
bool UnityToolbox.GameplayFeatures.Items.Management.Itemizer.Initialized get
Referenced by UnityToolbox.GameplayFeatures.Items.ItemManager.SpawnItemInstance().
Instance
Itemizer UnityToolbox.GameplayFeatures.Items.Management.Itemizer.Instance static get
Referenced by UnityToolbox.GameplayFeatures.Items.ItemManager.Awake(), UnityToolbox.GameplayFeatures.Items.Management.Editor.ItemScopeEditWindow.OnGUI(), and UnityToolbox.GameplayFeatures.Items.ItemManager.SpawnItemInstance().
ItemDefinitions
HashSet<ItemDefinition> UnityToolbox.GameplayFeatures.Items.Management.Itemizer.ItemDefinitions get
Referenced by UnityToolbox.GameplayFeatures.Items.ItemManager.SpawnItemInstance().
ItemScopes
HashSet<ItemScope> UnityToolbox.GameplayFeatures.Items.Management.Itemizer.ItemScopes get
Event Documentation
OnItemDefinitionEdited
Action<ItemDefinition, ItemDefinition> UnityToolbox.GameplayFeatures.Items.Management.Itemizer.OnItemDefinitionEdited
Referenced by UnityToolbox.GameplayFeatures.Items.Management.Itemizer.ItemDefinitionEdited().
OnItemScopeEdited
Action<ItemScope, ItemScope> UnityToolbox.GameplayFeatures.Items.Management.Itemizer.OnItemScopeEdited
Referenced by UnityToolbox.GameplayFeatures.Items.Management.Itemizer.ItemScopeEdited().