UnityToolbox: UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents Class Reference
UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents Class Reference
Public Member Functions
void UpdateStatus (string status)
void Close ()
void HeightColorsOpen ()
Public Attributes
Action OnClose
Action OnHeightColorsOpen
Action< string > OnUpdateStatus
Properties
static TerrainGenerationEditorEvents Instance [get]
Member Function Documentation
Close()
void UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.Close ()
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.OnClose.
HeightColorsOpen()
void UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.HeightColorsOpen ()
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.OnHeightColorsOpen.
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.DrawDetailsRest().
UpdateStatus()
void UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.UpdateStatus (string status)
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.OnUpdateStatus.
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayered.DeleteLayer(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.DeleteLayer(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainGenerationLayeredAssetLayerClustered.DrawAssets(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainGenerationLayeredAssetLayerSingle.DrawAssets(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.MoveLayer(), and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayered.MoveLayer().
Member Data Documentation
OnClose
Action UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.OnClose
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.Close().
OnHeightColorsOpen
Action UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.OnHeightColorsOpen
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.HeightColorsOpen().
OnUpdateStatus
Action<string> UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.OnUpdateStatus
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.UpdateStatus().
Property Documentation
Instance
TerrainGenerationEditorEvents UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationEditorEvents.Instance static get
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayered.DeleteLayer(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.DeleteLayer(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainGenerationLayeredAssetLayerClustered.DrawAssets(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainGenerationLayeredAssetLayerSingle.DrawAssets(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.DrawDetailsRest(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.MoveLayer(), and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayered.MoveLayer().