UnityToolbox: UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager Class Reference
UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager Class Reference
Public Member Functions
void Update ()
void ManageInventorys (BoundInventory other, ItemInstance otherItem)
Public Member Functions inherited from UnityToolbox.General.Management.Module
virtual void Awake ()
Public Attributes
HeldInventory HInventory
bool EnablePlacement
Properties
InventoryBase BackUpInventory [get]
bool IsEnabled [get, set]
Member Function Documentation
ManageInventorys()
void UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager.ManageInventorys (BoundInventory other, ItemInstance otherItem)
References UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.AddItem(), UnityToolbox.GameplayFeatures.Items.Inventory.Types.HeldInventory.AddItem(), UnityToolbox.GameplayFeatures.Items.Inventory.Types.HeldInventory.Count, UnityToolbox.GameplayFeatures.Items.ItemInstance.Equals(), UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager.HInventory, UnityToolbox.GameplayFeatures.Items.Inventory.Types.HeldInventory.ItemHeld, UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.Items, UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.RemoveItem(), and UnityToolbox.GameplayFeatures.Items.Inventory.Types.HeldInventory.RemoveItem().
Referenced by UnityToolbox.GameplayFeatures.Items.ItemInstance.Click().
Update()
void UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager.Update ()
References UnityToolbox.GameplayFeatures.Items.Inventory.Types.HeldInventory.Count, UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager.EnablePlacement, UnityToolbox.General.ColliderInfo.GetAllCollisions(), UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager.HInventory, UnityToolbox.GameplayFeatures.Items.Inventory.Types.HeldInventory.ItemHeld, and UnityToolbox.GameplayFeatures.Items.Inventory.Types.HeldInventory.RemoveItem().
Member Data Documentation
EnablePlacement
bool UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager.EnablePlacement
Referenced by UnityToolbox.GameplayFeatures.Items.ItemInstance.Click(), and UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager.Update().
HInventory
HeldInventory UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager.HInventory
Referenced by UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager.ManageInventorys(), UnityToolbox.GameplayFeatures.Items.ItemInstance.SaveData(), and UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager.Update().
Property Documentation
BackUpInventory
InventoryBase UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager.BackUpInventory get
Referenced by UnityToolbox.GameplayFeatures.Items.ItemInstance.SaveData().
IsEnabled
bool UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager.IsEnabled get set