UnityToolbox: UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer Class Reference
UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer Class Reference abstract
Public Member Functions
void DrawDetails ()
void DeleteAssetPlacement (TerrainGenerationLayeredAssetLayer current)
SerializedDataErrorDetails Deserialize (TerrainMeshTypeLayeredLayerBaseData obj)
TerrainMeshTypeLayeredLayerBaseData Serialize ()
Public Member Functions inherited from UnityToolbox.GameplayFeatures.SerializationData.ISerializedDataContainer< TerrainMeshTypeLayeredLayerBaseData >
abstract SerializedDataErrorDetails Deserialize (T obj)
abstract T Serialize ()
Public Attributes
string GeneratorName
Protected Member Functions
TerrainMeshTypeLayeredLayer (TerrainMeshTypeLayered parent, int currentPos, TerrainMeshTypeLayeredLayerBaseData dataType)
TerrainMeshTypeLayeredLayer (TerrainMeshTypeLayered parent, int currentPos, bool isBaseLayer, string baseLayerName, TerrainMeshTypeLayeredLayerBaseData dataType)
abstract void DrawDetailsRest ()
void DrawLineHorizontal ()
void DrawAssetPlacement ()
abstract SerializedDataErrorDetails DeserializeRest (TerrainMeshTypeLayeredLayerBaseData obj, SerializedDataErrorDetails err)
abstract TerrainMeshTypeLayeredLayerBaseData SerializeRest ()
Protected Attributes
TerrainMeshTypeLayeredLayerBaseData _data
Properties
bool IsBaseLayer [get]
int CurrentPos [get, set]
Constructor & Destructor Documentation
TerrainMeshTypeLayeredLayer() [1/2]
UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.TerrainMeshTypeLayeredLayer (TerrainMeshTypeLayered parent, int currentPos, TerrainMeshTypeLayeredLayerBaseData dataType) protected
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer._data.
TerrainMeshTypeLayeredLayer() [2/2]
UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.TerrainMeshTypeLayeredLayer (TerrainMeshTypeLayered parent, int currentPos, bool isBaseLayer, string baseLayerName, TerrainMeshTypeLayeredLayerBaseData dataType) protected
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer._data.
Member Function Documentation
DeleteAssetPlacement()
void UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.DeleteAssetPlacement (TerrainGenerationLayeredAssetLayer current)
Deserialize()
SerializedDataErrorDetails UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.Deserialize (TerrainMeshTypeLayeredLayerBaseData obj)
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredLayerBaseData.AssetPlacements, UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.DeserializeRest(), UnityToolbox.GameplayFeatures.SerializationData.SerializedDataErrorDetails.HasErrors, and UnityToolbox.GameplayFeatures.SerializationData.SerializedDataErrorDetails.Traced.
DeserializeRest()
abstract SerializedDataErrorDetails UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.DeserializeRest (TerrainMeshTypeLayeredLayerBaseData obj, SerializedDataErrorDetails err) protected pure virtual
Implemented in UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.Deserialize().
DrawAssetPlacement()
void UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.DrawAssetPlacement () protected
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer._data, UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainGenerationLayeredAssetLayer.DrawDetails(), and UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredLayerBaseData.PctForNoAsset.
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.DrawDetailsRest().
DrawDetails()
void UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.DrawDetails ()
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer._data, UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredLayerBaseData.CurrentPos, UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayered.DeleteLayer(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.DrawDetailsRest(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.DrawLineHorizontal(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredLayerBaseData.IsBaseLayer, UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayered.MoveLayer(), and UnityToolbox.GameplayFeatures.ProceduralGeneration.Data.Layered.TerrainMeshTypeLayeredLayerBaseData.Name.
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayered.DrawDetails().
DrawDetailsRest()
abstract void UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.DrawDetailsRest () protected pure virtual
Implemented in UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.DrawDetails().
DrawLineHorizontal()
void UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.DrawLineHorizontal () protected
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.DrawDetails(), and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.DrawDetailsRest().
Serialize()
TerrainMeshTypeLayeredLayerBaseData UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.Serialize () virtual
Implements UnityToolbox.GameplayFeatures.SerializationData.ISerializedDataContainer< TerrainMeshTypeLayeredLayerBaseData >.
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainGenerationLayeredAssetLayer.Serialize(), and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.SerializeRest().
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayered.Serialize().
SerializeRest()
abstract TerrainMeshTypeLayeredLayerBaseData UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.SerializeRest () protected pure virtual
Implemented in UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.Serialize().
Member Data Documentation
_data
TerrainMeshTypeLayeredLayerBaseData UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer._data protected
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.DeserializeRest(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.DrawAssetPlacement(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.DrawDetails(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.DrawDetailsRest(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.SerializeRest(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.TerrainMeshTypeLayeredLayer(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.TerrainMeshTypeLayeredLayer(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.TerrainMeshTypeLayeredLayerGround(), and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.TerrainMeshTypeLayeredLayerGround().
GeneratorName
string UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.GeneratorName
Property Documentation
CurrentPos
int UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.CurrentPos get set
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayered.Serialize().
IsBaseLayer
bool UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.IsBaseLayer get