UnityToolbox: UnityToolbox.GameplayFeatures.Items.Management.Editor.ItemDefinitionDrawer Class Reference
UnityToolbox.GameplayFeatures.Items.Management.Editor.ItemDefinitionDrawer Class Reference
This class enables a selection field for the ItemDefinition within the inspector.
Public Member Functions
override float GetPropertyHeight (SerializedProperty property, GUIContent label)
override void OnGUI (Rect position, SerializedProperty property, GUIContent label)
void ItemDefinitionSelected (ItemDefinition itemDefinition)
Member Function Documentation
GetPropertyHeight()
override float UnityToolbox.GameplayFeatures.Items.Management.Editor.ItemDefinitionDrawer.GetPropertyHeight (SerializedProperty property, GUIContent label)
ItemDefinitionSelected()
void UnityToolbox.GameplayFeatures.Items.Management.Editor.ItemDefinitionDrawer.ItemDefinitionSelected (ItemDefinition itemDefinition)
References UnityToolbox.GameplayFeatures.Items.Management.Editor.ItemDefinitionDrawer.ItemDefinitionSelected().
Referenced by UnityToolbox.GameplayFeatures.Items.Management.Editor.ItemDefinitionDrawer.ItemDefinitionSelected(), and UnityToolbox.GameplayFeatures.Items.Management.Editor.ItemDefinitionDrawer.OnGUI().
OnGUI()
override void UnityToolbox.GameplayFeatures.Items.Management.Editor.ItemDefinitionDrawer.OnGUI (Rect position, SerializedProperty property, GUIContent label)
References UnityToolbox.GameplayFeatures.Items.ItemDefinition.DEVIDER, UnityToolbox.GameplayFeatures.Items.Management.Editor.ItemDefinitionDrawer.ItemDefinitionSelected(), UnityToolbox.GameplayFeatures.Items.ItemDefinition.Name, UnityToolbox.GameplayFeatures.Items.Management.ItemScope.Name, UnityToolbox.GameplayFeatures.Items.Management.Editor.ItemDefinitionSelectionWindow.Open(), and UnityToolbox.GameplayFeatures.Items.ItemDefinition.Scope.