UnityToolbox: UnityToolbox.GameplayFeatures.Items.ItemInstance Class Reference
UnityToolbox.GameplayFeatures.Items.ItemInstance Class Reference
An instanciated item, created from an ItemDefinition.
Public Member Functions
object GetValueForField (string fieldName)
override bool Equals (object other)
override int GetHashCode ()
void Click ()
Public Member Functions inherited from UnityToolbox.GameplayFeatures.SaveGame.Saveable
void Save ()
Defines all data to be serialized by the SaveGameManager.
void Load ()
Loads all data, deserialized by the SaveGameManager.
void OnValidate ()
Public Attributes
string IconPath
int MaxStackCount
Public Attributes inherited from UnityToolbox.GameplayFeatures.SaveGame.Saveable
ResourceData PrefabData
The date which is used to serialize a reference to the Prefab.
Protected Member Functions
override void LoadData (GameData data)
Is called after the base data is loaded in Load. Allows additional data to be deserialized.
override List< GameData > SaveData ()
Is called on Save. Allows the definition of all additional GameData to be serialized.
override void OnObjectDeleted ()
A method called on deletion, that is that the object is removed from the save game and destroyed. It is not called when destroyed but saved.
abstract void LoadData (GameData data)
Is called after the base data is loaded in Load. Allows additional data to be deserialized.
abstract List< GameData > SaveData ()
Is called on Save. Allows the definition of all additional GameData to be serialized.
abstract void OnObjectDeleted ()
A method called on deletion, that is that the object is removed from the save game and destroyed. It is not called when destroyed but saved.
Protected Attributes
string _itemName
Sprite _icon
Protected Attributes inherited from UnityToolbox.GameplayFeatures.SaveGame.Saveable
bool _removeFromSaveOnDelete
Properties
InventoryBase Inventory [get, set]
string ItemName [get, set]
Sprite Icon [get, set]
string Indentifier [get, set]
Type ItemType [get, set]
HashSet< ItemField > ItemFields [get, set]
Properties inherited from UnityToolbox.GameplayFeatures.SaveGame.Saveable
string ID [get, set]
A unique ID.
bool InEditor [get]
Whether the gameobject is found in the scene initally. Or created dynamically.
Member Function Documentation
Click()
void UnityToolbox.GameplayFeatures.Items.ItemInstance.Click ()
References UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager.EnablePlacement, and UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager.ManageInventorys().
Equals()
override bool UnityToolbox.GameplayFeatures.Items.ItemInstance.Equals (object other)
References UnityToolbox.GameplayFeatures.Items.ItemInstance._itemName.
Referenced by UnityToolbox.GameplayFeatures.Items.Inventory.Types.HeldInventory.AddItem(), UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager.ManageInventorys(), UnityToolbox.GameplayFeatures.Items.Inventory.Types.HeldInventory.RemoveItem(), and UnityToolbox.GameplayFeatures.Items.Inventory.Types.HeldInventory.UpdateItem().
GetHashCode()
override int UnityToolbox.GameplayFeatures.Items.ItemInstance.GetHashCode ()
GetValueForField()
object UnityToolbox.GameplayFeatures.Items.ItemInstance.GetValueForField (string fieldName)
LoadData()
override void UnityToolbox.GameplayFeatures.Items.ItemInstance.LoadData (GameData data) protected virtual
Parameters
data A GameData implementation, which holds data to load.
Implements UnityToolbox.GameplayFeatures.SaveGame.Saveable.
References UnityToolbox.GameplayFeatures.Items.ItemInstance._icon, UnityToolbox.GameplayFeatures.Items.ItemInstance._itemName, UnityToolbox.GameplayFeatures.SerializationData.ItemData.Fields, UnityToolbox.GameplayFeatures.SerializationData.ItemData.IconPath, UnityToolbox.GameplayFeatures.SerializationData.ItemData.InventoryID, UnityToolbox.GameplayFeatures.SerializationData.ItemData.ItemName, and UnityToolbox.GameplayFeatures.SerializationData.ItemData.ItemType.
OnObjectDeleted()
override void UnityToolbox.GameplayFeatures.Items.ItemInstance.OnObjectDeleted () protected virtual
Implements UnityToolbox.GameplayFeatures.SaveGame.Saveable.
References UnityToolbox.GameplayFeatures.Items.Inventory.Types.InventoryBase.RemoveItem().
SaveData()
override List< GameData > UnityToolbox.GameplayFeatures.Items.ItemInstance.SaveData () protected virtual
Returns
Implements UnityToolbox.GameplayFeatures.SaveGame.Saveable.
References UnityToolbox.GameplayFeatures.Items.ItemInstance._itemName, UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager.BackUpInventory, UnityToolbox.GameplayFeatures.Items.Inventory.Managers.HeldInventoryManager.HInventory, UnityToolbox.GameplayFeatures.Items.ItemInstance.IconPath, and UnityToolbox.GameplayFeatures.Items.Inventory.Types.InventoryBase.ID.
Member Data Documentation
_icon
Sprite UnityToolbox.GameplayFeatures.Items.ItemInstance._icon protected
Referenced by UnityToolbox.GameplayFeatures.Items.ItemInstance.LoadData().
_itemName
string UnityToolbox.GameplayFeatures.Items.ItemInstance._itemName protected
Referenced by UnityToolbox.GameplayFeatures.Items.ItemInstance.Equals(), UnityToolbox.GameplayFeatures.Items.ItemInstance.LoadData(), and UnityToolbox.GameplayFeatures.Items.ItemInstance.SaveData().
IconPath
string UnityToolbox.GameplayFeatures.Items.ItemInstance.IconPath
Referenced by UnityToolbox.GameplayFeatures.Items.ItemInstance.SaveData().
MaxStackCount
int UnityToolbox.GameplayFeatures.Items.ItemInstance.MaxStackCount
Referenced by UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.AddItem().
Property Documentation
Icon
Sprite UnityToolbox.GameplayFeatures.Items.ItemInstance.Icon get set
Referenced by UnityToolbox.GameplayFeatures.Items.Inventory.UI.InventoryUISlot.UpdateItem().
Indentifier
string UnityToolbox.GameplayFeatures.Items.ItemInstance.Indentifier get set
Inventory
InventoryBase UnityToolbox.GameplayFeatures.Items.ItemInstance.Inventory get set
Referenced by UnityToolbox.GameplayFeatures.Items.Inventory.Types.BoundInventory.RemoveItem(), and UnityToolbox.GameplayFeatures.Items.Inventory.Types.HeldInventory.RemoveItem().
ItemFields
HashSet<ItemField> UnityToolbox.GameplayFeatures.Items.ItemInstance.ItemFields get set
ItemName
string UnityToolbox.GameplayFeatures.Items.ItemInstance.ItemName get set
Referenced by UnityToolbox.GameplayFeatures.Items.Inventory.UI.InventoryUISlot.UpdateItem().
ItemType
Type UnityToolbox.GameplayFeatures.Items.ItemInstance.ItemType get set