UnityToolbox: UnityToolbox.GameplayFeatures.SerializationData.SerializedDataErrorDetails Class Reference
UnityToolbox.GameplayFeatures.SerializationData.SerializedDataErrorDetails Class Reference
Non serialized data, rather data to be used on serialization errors. See ISerializedDataContainer<T> for the usage.
Public Attributes
bool HasErrors
string ErrorDescription
List< SerializedDataErrorDetails > Traced = new()
Member Data Documentation
ErrorDescription
string UnityToolbox.GameplayFeatures.SerializationData.SerializedDataErrorDetails.ErrorDescription
HasErrors
bool UnityToolbox.GameplayFeatures.SerializationData.SerializedDataErrorDetails.HasErrors
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.Deserialize(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorLayer.Deserialize(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainGenerationLayeredAssetLayerClustered.Deserialize(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainGenerationLayeredAssetLayerSingle.Deserialize(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayered.Deserialize(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.Deserialize(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.DeserializeRest(), and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.DummyDeserialize().
Traced
List<SerializedDataErrorDetails> UnityToolbox.GameplayFeatures.SerializationData.SerializedDataErrorDetails.Traced = new()
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.Deserialize(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorLayer.Deserialize(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainGenerationLayeredAssetLayerClustered.Deserialize(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayered.Deserialize(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayer.Deserialize(), UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.GenerationTypes.Layered.TerrainMeshTypeLayeredLayerGround.DeserializeRest(), and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationHeightColorsWindow.DummyDeserialize().