UnityToolbox: UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationErrorWindow Class Reference
UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationErrorWindow Class Reference
Public Member Functions
void InitializeWindow (SerializedDataErrorDetails errors)
void OnGUI ()
void OnAfterAssemblyReload ()
Static Public Member Functions
static TerrainGenerationErrorWindow Open (SerializedDataErrorDetails errors)
Member Function Documentation
InitializeWindow()
void UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationErrorWindow.InitializeWindow (SerializedDataErrorDetails errors)
Referenced by UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationErrorWindow.OnAfterAssemblyReload(), and UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationErrorWindow.Open().
OnAfterAssemblyReload()
void UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationErrorWindow.OnAfterAssemblyReload ()
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationErrorWindow.InitializeWindow().
OnGUI()
void UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationErrorWindow.OnGUI ()
Open()
static TerrainGenerationErrorWindow UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationErrorWindow.Open (SerializedDataErrorDetails errors) static
References UnityToolbox.GameplayFeatures.ProceduralGeneration.Editor.TerrainGenerationErrorWindow.InitializeWindow().