var namespace_unity_toolbox_1_1_gameplay_features_1_1_items_1_1_inventory_1_1_managers =
[
    [ "HeldInventoryManager", "class_unity_toolbox_1_1_gameplay_features_1_1_items_1_1_inventory_1_1_managers_1_1_held_inventory_manager.html", "class_unity_toolbox_1_1_gameplay_features_1_1_items_1_1_inventory_1_1_managers_1_1_held_inventory_manager" ],
    [ "InventoryManager", "class_unity_toolbox_1_1_gameplay_features_1_1_items_1_1_inventory_1_1_managers_1_1_inventory_manager.html", "class_unity_toolbox_1_1_gameplay_features_1_1_items_1_1_inventory_1_1_managers_1_1_inventory_manager" ]
];