var namespace_unity_toolbox_1_1_gameplay_features_1_1_items_1_1_inventory_1_1_types =
[
    [ "BoundInventory", "class_unity_toolbox_1_1_gameplay_features_1_1_items_1_1_inventory_1_1_types_1_1_bound_inventory.html", "class_unity_toolbox_1_1_gameplay_features_1_1_items_1_1_inventory_1_1_types_1_1_bound_inventory" ],
    [ "HeldInventory", "class_unity_toolbox_1_1_gameplay_features_1_1_items_1_1_inventory_1_1_types_1_1_held_inventory.html", "class_unity_toolbox_1_1_gameplay_features_1_1_items_1_1_inventory_1_1_types_1_1_held_inventory" ],
    [ "InventoryBase", "class_unity_toolbox_1_1_gameplay_features_1_1_items_1_1_inventory_1_1_types_1_1_inventory_base.html", "class_unity_toolbox_1_1_gameplay_features_1_1_items_1_1_inventory_1_1_types_1_1_inventory_base" ]
];