UnityToolbox: UnityToolbox.UI.Localisation.LocalisationID Struct Reference
UnityToolbox.UI.Localisation.LocalisationID Struct Reference
An ID which is used to indentify and serialize localisation data.
Public Member Functions
string GetQualifiedName ()
Creates and returns the name in syntax of LocalisationScope.Name + DEVIDER + Name
override bool Equals (object obj)
override int GetHashCode ()
Public Attributes
LocalisationScope Scope
string Name
Static Public Attributes
static char DEVIDER = '_'
Member Function Documentation
Equals()
override bool UnityToolbox.UI.Localisation.LocalisationID.Equals (object obj)
References UnityToolbox.UI.Localisation.LocalisationID.GetQualifiedName().
Referenced by UnityToolbox.UI.Localisation.Editor.LocalisationEditIDWindow.OnGUI().
GetHashCode()
override int UnityToolbox.UI.Localisation.LocalisationID.GetHashCode ()
References UnityToolbox.UI.Localisation.LocalisationID.GetQualifiedName().
GetQualifiedName()
string UnityToolbox.UI.Localisation.LocalisationID.GetQualifiedName ()
Returns
A qualified name.
References UnityToolbox.UI.Localisation.LocalisationID.DEVIDER, and UnityToolbox.UI.Localisation.LocalisationID.Name.
Referenced by UnityToolbox.UI.Localisation.LocalisationID.Equals(), and UnityToolbox.UI.Localisation.LocalisationID.GetHashCode().
Member Data Documentation
DEVIDER
char UnityToolbox.UI.Localisation.LocalisationID.DEVIDER = '_' static
Referenced by UnityToolbox.UI.Localisation.LocalisationID.GetQualifiedName(), UnityToolbox.UI.Localisation.Editor.LocalisationEditIDWindow.OnGUI(), and UnityToolbox.UI.Localisation.Editor.LocalisationDrawer.OnGUI().
Name
string UnityToolbox.UI.Localisation.LocalisationID.Name
Referenced by UnityToolbox.UI.Localisation.LocalisationID.GetQualifiedName(), and UnityToolbox.UI.Localisation.Editor.LocalisationDrawer.OnGUI().
Scope
LocalisationScope UnityToolbox.UI.Localisation.LocalisationID.Scope
Referenced by UnityToolbox.UI.Localisation.Editor.LocalisationDrawer.OnGUI().