UnityToolbox: UnityToolbox.UI.Localization.LocalizationID Struct Reference
UnityToolbox.UI.Localization.LocalizationID Struct Reference
An ID which is used to indentify and serialize Localization data.
Public Member Functions
string GetQualifiedName ()
Creates and returns the name in syntax of LocalizationScope.Name + DEVIDER + Name
override bool Equals (object obj)
override int GetHashCode ()
Public Attributes
LocalizationScope Scope
string Name
Static Public Attributes
static char DEVIDER = '_'
Member Function Documentation
Equals()
override bool UnityToolbox.UI.Localization.LocalizationID.Equals (object obj)
References UnityToolbox.UI.Localization.LocalizationID.GetQualifiedName().
Referenced by UnityToolbox.UI.Localization.Editor.LocalizationEditIDWindow.OnGUI().
GetHashCode()
override int UnityToolbox.UI.Localization.LocalizationID.GetHashCode ()
References UnityToolbox.UI.Localization.LocalizationID.GetQualifiedName().
GetQualifiedName()
string UnityToolbox.UI.Localization.LocalizationID.GetQualifiedName ()
Returns
A qualified name.
References UnityToolbox.UI.Localization.LocalizationID.DEVIDER, and UnityToolbox.UI.Localization.LocalizationID.Name.
Referenced by UnityToolbox.UI.Localization.LocalizationID.Equals(), UnityToolbox.UI.Localization.LocalizationID.GetHashCode(), and UnityToolbox.UI.Localization.Editor.LocalizationDrawer.IDSelectedUIElement().
Member Data Documentation
DEVIDER
char UnityToolbox.UI.Localization.LocalizationID.DEVIDER = '_' static
Referenced by UnityToolbox.UI.Localization.LocalizationID.GetQualifiedName(), UnityToolbox.UI.Localization.Editor.LocalizationEditIDWindow.OnGUI(), and UnityToolbox.UI.Localization.Editor.LocalizationDrawer.OnGUI().
Name
string UnityToolbox.UI.Localization.LocalizationID.Name
Referenced by UnityToolbox.UI.Localization.Editor.LocalizationDrawer.CreateVisualElement(), UnityToolbox.UI.Localization.LocalizationID.GetQualifiedName(), and UnityToolbox.UI.Localization.Editor.LocalizationDrawer.OnGUI().
Scope
LocalizationScope UnityToolbox.UI.Localization.LocalizationID.Scope
Referenced by UnityToolbox.UI.Localization.Editor.LocalizationDrawer.CreateVisualElement(), and UnityToolbox.UI.Localization.Editor.LocalizationDrawer.OnGUI().