UnityToolbox: UnityToolbox.UI.Localization.LocalizationScope Struct Reference
UnityToolbox.UI.Localization.LocalizationScope Struct Reference
The scope which is used to indentify and serialize Localization data.
Public Member Functions
override bool Equals (object obj)
override int GetHashCode ()
Public Attributes
string Name
Member Function Documentation
Equals()
override bool UnityToolbox.UI.Localization.LocalizationScope.Equals (object obj)
References UnityToolbox.UI.Localization.LocalizationScope.Name.
Referenced by UnityToolbox.UI.Localization.Localizer.AddScope(), UnityToolbox.UI.Localization.Localizer.EditScope(), and UnityToolbox.UI.Localization.Localizer.RemoveScope().
GetHashCode()
override int UnityToolbox.UI.Localization.LocalizationScope.GetHashCode ()
Member Data Documentation
Name
string UnityToolbox.UI.Localization.LocalizationScope.Name
Referenced by UnityToolbox.UI.Localization.Localizer.EditScope(), UnityToolbox.UI.Localization.LocalizationScope.Equals(), UnityToolbox.UI.Localization.Editor.LocalizationDrawer.OnGUI(), and UnityToolbox.UI.Localization.Localizer.RemoveScope().