UnityToolbox: LocalisationID Struct Reference
LocalisationID Struct Reference
An ID which is used to indentify and serialize localisation data.
Public Member Functions
string GetQualifiedName ()
Creates and returns the name in syntax of LocalisationScope.Name + DEVIDER + Name
override bool Equals (object obj)
override int GetHashCode ()
Public Attributes
LocalisationScope Scope
string Name
Static Public Attributes
static char DEVIDER = '_'
Member Function Documentation
Equals()
override bool LocalisationID.Equals (object obj)
References GetQualifiedName().
Referenced by LocalisationEditIDWindow.OnGUI().
GetHashCode()
override int LocalisationID.GetHashCode ()
References GetQualifiedName().
GetQualifiedName()
string LocalisationID.GetQualifiedName ()
Returns
A qualified name.
References DEVIDER, and Name.
Referenced by Equals(), and GetHashCode().
Member Data Documentation
DEVIDER
char LocalisationID.DEVIDER = '_' static
Referenced by GetQualifiedName(), LocalisationEditIDWindow.OnGUI(), and LocalisationDrawer.OnGUI().
Name
string LocalisationID.Name
Referenced by GetQualifiedName(), and LocalisationDrawer.OnGUI().
Scope
LocalisationScope LocalisationID.Scope
Referenced by LocalisationDrawer.OnGUI().